### ISSUE TITLE
Problems with Apex

### ISSUE THREAD

**Issue by thegallier** [ThilinaRajapakse/simpletransformers#1]
getting error whern training

utils line 196, in <module>
    "binary": BinaryProcessor
NameError: name 'BinaryProcessor' is not defined

**Comment by ThilinaRajapakse** [comment]
It should be fixed now. Please update to the latest version (0.2.0).

**Comment by thegallier** [comment]
Yes indeed.  Thank you.  I would add

Pip install tensorboardX

For completeness.

Peter

On Oct 5, 2019, at 11:10 AM, Thilina Rajapakse <notifications@github.com<mailto:notifications@github.com>> wrote:


It should be fixed now. Please update to the latest version (0.2.0).

**Comment by thegallier** [comment]
Actually, there is another issue.  Will check it out and file.  Model.py line 245 no model_name in arts

Peter

On Oct 5, 2019, at 11:10 AM, Thilina Rajapakse <notifications@github.com<mailto:notifications@github.com>> wrote:


It should be fixed now. Please update to the latest version (0.2.0).

**Comment by ThilinaRajapakse** [comment]
Found a few more bugs. I think that's all of them though. Do let me know if there are other issues.

**Comment by thegallier** [comment]
Not sure your problem but need to install apex from repository.  Pip one had issue (on 2 different machines/os)

Peter

On Oct 5, 2019, at 12:11 PM, Thilina Rajapakse <notifications@github.com<mailto:notifications@github.com>> wrote:


Found a few more bugs. I think that's all of them though. Do let me know if there are other issues.

**Comment by ThilinaRajapakse** [comment]
That's on their end. I think the recommended way to install Apex is from the repo.

**Comment by samarthsarin** [comment]
Can you please add the note to installation of apex.

**Comment by ThilinaRajapakse** [comment]
Ok, I'll add it then.

**Comment by thegallier** [comment]
Are you good or you want me to do it tonight?

Peter

On Oct 7, 2019, at 10:03 AM, Thilina Rajapakse <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, I'll add it then.

**Comment by samarthsarin** [comment]
Would be helpful if you can add it tonight.
Else you can do it tomorrow if you are busy today

**Comment by ThilinaRajapakse** [comment]
![image](https://user-images.githubusercontent.com/17320131/66321747-af4fd680-e93e-11e9-944d-52ce14e177a0.png)

Added this line to the setup instructions.

**Comment by samarthsarin** [comment]
Thank you

**Comment by RabbitJackTrade** [comment]
Just to add a note on Apex here. The default setting is `'fp16': True,`. If you don't install it and try to train a model, an error message will result. So I would suggest changing this line in the example to:
`model = TransformerModel('roberta', 'roberta-base', args=({'fp16': False})`
for those who don't install Apex.

**Comment by ThilinaRajapakse** [comment]
Well, it does give a pretty clear error message if Apex is not installed. I think it makes more sense to leave Apex on by default because there's no indicator to show that it is off.

**Comment by RabbitJackTrade** [comment]
Hey, you're the boss! :)

**Comment by ThilinaRajapakse** [comment]
Ideas are always welcome!
