### ISSUE TITLE
Issue in continue pre-training

### ISSUE THREAD

**Issue by akshay4malik** [ThilinaRajapakse/simpletransformers#1001]
I am having issue while starting the training. When I start the pre-training from scratch, the progress doesn't start at all.
It get stuck on 0 %. 
Epoch: 0%   0/3 [00:00<?, ?it/s].
For some reasons, I am not able to upload the screenshot. 

And When I use pre-trained models for fine tuning or for continue pre-training, I am getting the following errors:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte`

I think there are issues with the file. I tried downloading the pre-trained models from here:
https://github.com/google-research/electra
[](https://github.com/google-research/electra)

But this doesn't contain separate generator and discriminator, So I explicitly downloaded generator and discriminators from https://huggingface.co/models
But in both the cases, the error remains the same.

**Comment by ThilinaRajapakse** [comment]
It sounds like the model files are corrupted somehow. Try initializing your `LanguageModel` with `force_download=True`.

**Comment by akshay4malik** [comment]
Hi, Thanks for prompt reply. 

I have limitation for internet connection. I can only upload the pre-trained models.
