### ISSUE TITLE
Error about sliding window

### ISSUE THREAD

**Issue by QAQOAO** [ThilinaRajapakse/simpletransformers#102]
It was no problem yesterday, so I guess it was because of the latest update.

----> 6 model.train_model(train_df)

/usr/local/lib/python3.6/dist-packages/simpletransformers/classification/classification_model.py in load_and_cache_examples(self, examples, evaluate, no_cache, multi_label)
    494                 silent=args['silent'],
    495                 use_multiprocessing=args['use_multiprocessing'],
--> 496                 sliding_window=args['sliding_window'],
    497                 flatten=not evaluate,
    498                 stride=args['stride']

KeyError: 'sliding_window'

**Comment by ThilinaRajapakse** [comment]
Yeah, this was from the last update. Should be fixed now.

**Comment by QAQOAO** [comment]
I can train now. However similar things happened when I tried to load my model.


----> 1 model = MultiLabelClassificationModel('roberta',  'drive/My Drive/roberta')
      2 #model

/usr/local/lib/python3.6/dist-packages/simpletransformers/classification/multi_label_classification_model.py in __init__(self, model_type, model_name, num_labels, pos_weight, args, use_cuda)
    102         }
    103 
--> 104         args['sliding_window'] = False
    105         args['stride'] = False
    106 

TypeError: 'NoneType' object does not support item assignment

**Comment by ThilinaRajapakse** [comment]
I didn't get this issue but try it now and see if it is still happening.
