### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'cache_dir/cached_dev_xlnet_128_2_1'

### ISSUE THREAD

**Issue by BenF99** [ThilinaRajapakse/simpletransformers#1024]
**Description**

I have fine-tuned XLNet to classify text using Google Colab. I downloaded the outputs onto my local machine and am attempting to make predictions. When version 0.60.9 is installed I receive the following bug:

`FileNotFoundError: [Errno 2] No such file or directory: 'cache_dir/cached_dev_xlnet_128_2_1'`

However, version 0.51.1 doesn't cause the above bug.

**To Reproduce**

Python 3.8 | PyCharm

```
class xlclf:
    def __init__(self, txt, model_dir="D:/Language Models/XLNET-LARGE/"):
        self.txt = txt
        self.model = ClassificationModel("xlnet", model_dir, use_cuda=False)

    def d(self):
        a, b = self.model.predict([self.txt])
        return a, b
    
x = xlclf("Hello World")
print(x.d())
```

Output (0.51.1 - As Expected):

`(['machine'], array([[ 2.8955102 , -3.05609155]]))`

Output (0.60.9 - Erroneous):

`FileNotFoundError: [Errno 2] No such file or directory: 'cache_dir/cached_dev_xlnet_128_2_1'`

**Screenshots**

![Model Directory (Fine-tuned)](https://user-images.githubusercontent.com/55698282/110162166-434cf880-7de6-11eb-87fc-7f087cffd6b4.png)

**Desktop:**
 - Windows 10

**Comment by vijumane** [comment]
Hello, has this issue been resolved? I am getting similar error with 0.60.9 version.

(st) C:\Users\Q15166\Anaconda3\condabin>python.exe C:\Vijay\src\PythonScript\predict_emails.py "some test text"
Traceback (most recent call last):
  File "C:\Vijay\src\PythonScript\predict_emails.py", line 147, in <module>
    print(get_prediction(sys.argv[1]))
  File "C:\Vijay\src\PythonScript\predict_emails.py", line 137, in get_prediction
    category_predictions, category_raw_outputs = category_model.predict(cleaned_text_list)
  File "C:\Users\Q15166\Anaconda3\envs\st\lib\site-packages\simpletransformers\classification\classification_model.py", line 1441, in predict
    eval_dataset = self.load_and_cache_examples(
  File "C:\Users\Q15166\Anaconda3\envs\st\lib\site-packages\simpletransformers\classification\classification_model.py", line 1284, in load_and_cache_examples
    dataset = ClassificationDataset(
  File "C:\Users\Q15166\Anaconda3\envs\st\lib\site-packages\simpletransformers\classification\classification_utils.py", line 215, in __init__
    self.examples, self.labels = build_classification_dataset(
  File "C:\Users\Q15166\Anaconda3\envs\st\lib\site-packages\simpletransformers\classification\classification_utils.py", line 208, in build_classification_dataset
    torch.save(data, cached_features_file)
  File "C:\Users\Q15166\Anaconda3\envs\st\lib\site-packages\torch\serialization.py", line 369, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "C:\Users\Q15166\Anaconda3\envs\st\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\Q15166\Anaconda3\envs\st\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'cache_dir/cached_dev_roberta_128_5_1'

**Comment by BenF99** [comment]
> Hello, has this issue been resolved? I am getting similar error with 0.60.9 version.
> 
> (st) C:\Users\Q15166\Anaconda3\condabin>python.exe C:\Vijay\src\PythonScript\predict_emails.py "some test text"
> Traceback (most recent call last):
> File "C:\Vijay\src\PythonScript\predict_emails.py", line 147, in
> print(get_prediction(sys.argv[1]))
> File "C:\Vijay\src\PythonScript\predict_emails.py", line 137, in get_prediction
> category_predictions, category_raw_outputs = category_model.predict(cleaned_text_list)
> File "C:\Users\Q15166\Anaconda3\envs\st\lib\site-packages\simpletransformers\classification\classification_model.py", line 1441, in predict
> eval_dataset = self.load_and_cache_examples(
> File "C:\Users\Q15166\Anaconda3\envs\st\lib\site-packages\simpletransformers\classification\classification_model.py", line 1284, in load_and_cache_examples
> dataset = ClassificationDataset(
> File "C:\Users\Q15166\Anaconda3\envs\st\lib\site-packages\simpletransformers\classification\classification_utils.py", line 215, in **init**
> self.examples, self.labels = build_classification_dataset(
> File "C:\Users\Q15166\Anaconda3\envs\st\lib\site-packages\simpletransformers\classification\classification_utils.py", line 208, in build_classification_dataset
> torch.save(data, cached_features_file)
> File "C:\Users\Q15166\Anaconda3\envs\st\lib\site-packages\torch\serialization.py", line 369, in save
> with _open_file_like(f, 'wb') as opened_file:
> File "C:\Users\Q15166\Anaconda3\envs\st\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
> return _open_file(name_or_buffer, mode)
> File "C:\Users\Q15166\Anaconda3\envs\st\lib\site-packages\torch\serialization.py", line 211, in **init**
> super(_open_file, self).**init**(open(name, mode))
> FileNotFoundError: [Errno 2] No such file or directory: 'cache_dir/cached_dev_roberta_128_5_1'

@vijumane I evaluated the model once and that seemed to generate and store the cached file required

**Comment by vijumane** [comment]
issue was of relative path of "cache_dir" in model_args.json file, which was set to "cache_dir": "cache_dir/",

I changed it to absolute path on windows

**Comment by BenF99** [comment]
@vijumane Would you be able to show me what you meant exactly (How did you specify the abs path)?
