### ISSUE TITLE
Can I train the model without save all the checkpoints?

### ISSUE THREAD

**Issue by moh-yani** [ThilinaRajapakse/simpletransformers#1025]
Dear,

I trained a huge data using SimpleTransformers for multi-class classification task. Unfortunately, it is stopped due to no space left on device. I checked the size of the folder 'outputs', I got 80GB only for 20% training process. I assume that I need 400GB to 100% training process. It is impossible to try in our device for now.

My question, can I train that without save all the checkpoints? (only the last check point I save) If so, how to do that?

Regards,

YANI

**Comment by Shivanandroy** [comment]
Add these arguments in addition to your existing model parameters, and it will not save the checkpoints after every epochs. Your best model will be saved under `best_model` directory
```python
model_args = {
    "save_eval_checkpoints": False,
    "save_model_every_epoch": False
    "best_model_dir": "best_model",
    "save_steps": -1
}
```

**Comment by moh-yani** [comment]
Thank you @Shivanandroy.
