### ISSUE TITLE
Support for Longformer seq-seq models

### ISSUE THREAD

**Issue by Hellisotherpeople** [ThilinaRajapakse/simpletransformers#1026]
**Is your feature request related to a problem? Please describe.**
The last time I tried to make longformer models work with the built in seq-seq model here, it didn't work. I seem to remember finding an issue about it at one point but I could not locate it when I searched for it right before posting here. 

Looks like there are folks who are uploading models to huggingface which show that longformer seq-seq is possible. 
This is extremely important to the NLP community because most people (e.g. folks with a 3090 at home) are realistically constrained to no more than a 1024 sequence length on most sequence to sequence tasks due to GPU memory limitations. 

**Describe the solution you'd like**
Support longformer-longformer sequence to sequence models without crashing. Give documentation minimal start example of it. 

**Describe alternatives you've considered**
Yeah, I could try to run it using the notebooks that other people have built in pure pytorch or with regular transformers - but screw that! I'm not spending all my time on boilerplate! That's why I use this wonderful library!

**Comment by ThilinaRajapakse** [comment]
You should be able to use a longformer model as the encoder. Huggingface used to be constrained to BERT as the decoder but I don't think it is anymore. I'll take a look and see what I can do.

**Comment by rajgar114** [comment]
I have a Sequence2Sequence task in which input length of sequences are close to 1024 and output lengths are below 512.
I am using the Longformer model (for fine-tuning) in the following way:

```
from simpletransformers.seq2seq import Seq2SeqModel
from simpletransformers.seq2seq import Seq2SeqArgs

modelArgs = Seq2SeqArgs()
modelArgs.num_train_epochs = 10
modelArgs.best_model_dir = path
modelArgs.output_dir  = path2
modelArgs.evaluate_generated_text = True
modelArgs.evaluate_during_training = True
modelArgs.evaluate_during_training_verbose = True
modelArgs.early_stopping_consider_epochs = True
modelArgs.evaluate_during_training_steps = 500
modelArgs.manual_seed = 4
modelArgs.max_seq_length = 4096
modelArgs.use_early_stopping = True
modelArgs.early_stopping_patience = 3

model = Seq2SeqModel(
    encoder_type = "longformer",
    encoder_name = "allenai/longformer-base-4096",
    decoder_name = "bert-base-cased",
    args = modelArgs,
    use_cuda = False,   
)
```

Is it a correct way of using Longformer for a Seq2Seq task ?
