### ISSUE TITLE
Multiple GPU connected for training, but average utilization per GPU is lower than using single GPU

### ISSUE THREAD

**Issue by leungi** [ThilinaRajapakse/simpletransformers#1027]
**Describe the bug**
Trained classification model with a single GPU, and saw average GPU utilization of ~40%.

I assumed using more GPU by increasing `n_gpu` in `args` can speed it up in proportional to the number of GPUs supplied.

In reality, the _total_ GPU utilization remains the same at ~40%, but the average GPU utilization is ~7%.

**Screenshots**
#### Single GPU
![image](https://user-images.githubusercontent.com/30273868/110253828-fab24e00-7f51-11eb-9527-ad94ac074d7d.png)

#### Multiple GPUs
![image](https://user-images.githubusercontent.com/30273868/110253781-c179de00-7f51-11eb-910f-461b09919209.png)

**Desktop (please complete the following information):**
-OS
`4.15.0-124-generic #127-Ubuntu SMP Fri Nov 6 10:54:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by leungi** [comment]
Jupyter output:

#### Single GPU
![image](https://user-images.githubusercontent.com/30273868/110254010-d9059680-7f52-11eb-9830-a1686e06e3f0.png)

<hr>

#### Multiple GPU
![image](https://user-images.githubusercontent.com/30273868/110254017-e7ec4900-7f52-11eb-821c-7fc64d10aecf.png)

**Comment by ThilinaRajapakse** [comment]
Your GPU utilization should go up if you increase the batch size. Right now, your GPUs are getting data starved.

**Comment by leungi** [comment]
Appreciate the layman's explanation!

Updated the training with higher `train_batch_size` and the GPU utilization increases as you suggested; however, the _it/s_ is still suffering (~2-3 vs. 7-8).

I don't see memory being an issue; any more tips @ThilinaRajapakse? 🙏

![image](https://user-images.githubusercontent.com/30273868/111042282-43f71780-8402-11eb-8022-37c4f3aadaff.png)

**Comment by ThilinaRajapakse** [comment]
Sadly, this is probably because of issues with DataParallel from PyTorch. I am planning to upgrade to DistributedDataParallel, which should help. There's no timeframe as of yet though.

**Comment by leungi** [comment]
Appreciate your guidance @ThilinaRajapakse!
