### ISSUE TITLE
ClassificationModel Architecture: which part of the all_embedding_outputs is actually used for classification? 

### ISSUE THREAD

**Issue by shinthor** [ThilinaRajapakse/simpletransformers#1031]
I'm trying to understand the architecture of the [ClassificationModel](https://github.com/ThilinaRajapakse/simpletransformers/blob/master/simpletransformers/classification/classification_model.py).

I've been going through the code and I can't find where the embedding output gets used for  classification. I know it is common to use only the embedding for the first token - the [CLS] token - for classification - is that what is done in SimpleTransformers?

Also, what is the architecture used for classification on the BERT embeddings? Is it a simple feedforward neural network? Does it have hidden layers and activation layers?

Thank you for your help

**Comment by ThilinaRajapakse** [comment]
Simple Transformers uses the Huggingface models under the hood, which in turn implements whatever was used in the original source. You can see the BERT implementation [here](https://github.com/ThilinaRajapakse/simpletransformers/blob/master/simpletransformers/classification/transformer_models/bert_model.py) for example. This is almost identical to the Huggingface implementation except this also supports class weights.
