### ISSUE TITLE
Include Dropout rate

### ISSUE THREAD

**Issue by ChrisChross** [ThilinaRajapakse/simpletransformers#1032]
Wanted to train a seq2seq model with a dropout. 
However, I could not find any parameter in the  Seq2seqArgs nor the`ModelArgs`. 
Is there already a dropout parameter? Otherwise, I'd like to request to include the dropout rate.

**Comment by ThilinaRajapakse** [comment]
You can pass a `config` dictionary with the dropout value you want. You can also pass any other parameter that works with a Huggingface config file.

**Comment by ChrisChross** [comment]
Great, can you give a code snippet how to do it? Would be nice @ThilinaRajapakse

**Comment by ThilinaRajapakse** [comment]
```python
model_args = Seq2SeqArgs()

model_args.config = {"dropout": 0.3}
```

_Not tested_
