### ISSUE TITLE
TPU Support

### ISSUE THREAD

**Issue by nickcoch** [ThilinaRajapakse/simpletransformers#1038]
This library is amazing and thank you very much!  To do any state of the art models now days it seems a TPU is the only way to do it, is there any plans to add TPU pytorch/XLA etc., to the library in the future as that would be incredible to train larger models like T5's larger models, etc.  Thank you!

**Comment by ykzj** [comment]
+1
TPU provides more power and cost efficiency

**Comment by flaviussn** [comment]
It should be easy to integrate with the new huggigface Accelearte

https://github.com/huggingface/accelerate
