### ISSUE TITLE
Onnx with quantized example for prediction needed.

### ISSUE THREAD

**Issue by vimal-quilt** [ThilinaRajapakse/simpletransformers#1039]
Dear Developers,
Will u pl share a working example of converting the onnx model to opitimzed and quantized one and export. also example for prediction of the output. currently i am facing the error 
Error no file named ['pytorch_model.bin', 'tf_model.h5', 'model.ckpt.index'] found in directory onnx_outputs or `from_tf` set to False

**Comment by prrao87** [comment]
@vimal-quilt This is [shown in the documentation here](https://simpletransformers.ai/docs/tips-and-tricks/#code-example).

I believe the issue you're facing is related to the way you load the ONNX classification model (don't pass in the original PyTorch model arguments when loading the ONNX model). Consider you trained a PyTorch DistilBERT model, which you convert to ONNX to make optimized inferences. This sequence of steps worked for me.

### Convert PyTorch model to ONNX

```py
onnx_output = "./model_onnx"   # Specify output path here
onnx_convert(onnx_output, model)
```

### Load ONNX model with dynamic quantization
Note that you can load the ONNX model on CPU by disabling `use_cuda`.
```py
model = ClassificationModel(
    "distilbert",
    onnx_output,
    overwrite_output_dir=True,
    dynamic_quantize=True,
    use_cuda=False,
)
```

### Make inferences (sentiment analysis example)
```py
sentences = ["I am happy", "I am sad"] * 10
pytorch_onnx_result = [model_onnx.predict(sent) for sent in sentences]
```
I observed ~30x inference speedup on CPU compared to the the PyTorch model in my case. Hope that helps!

**Comment by vimal-quilt** [comment]
@prrao87 thanks for your support. I tried this works perfect. But my requirement is want to save the optimized and quantized model to the disk and load the model from that checkpoint for inference. i reduced the model size to about one third of the original size using transformer convert_graph_to_onnx function. when i am using this model as described here, it is throwing me error could not broadcast  input array from shape (5,1024) into shape(44) (mine is a multiclass classification model with 44 labels) will u pl support on this.

**Comment by vimal-quilt** [comment]
Thanks. I found out the issue. I have quantized the model with inbuilt feature extraction parameter. I changed the parameter to sentiment-analysis. Now it is working superb.

**Comment by prrao87** [comment]
Hi @vimal-quilt do you mind sharing the code snippet for how you reduced model size to a third of the original? I don't see a model size reduction in my case. Did you entirely switch over to the transformers `convert_graph_to_onnx` for this portion, or did you still use the `convert_to_onnx` from simpletransformers to get it to work?

**Comment by vimal-quilt** [comment]
Hi @prrao87 i used the transformers function to build my model
python3 -m transformers.convert_graph_to_onnx --framework pt --model <path to model> --tokenizer <path to tokenizer> --quantize <output_path> --pipeline sentiment-analysis

**Comment by prrao87** [comment]
Perfect, thanks! I'm not sure why simpletransformers' doesn't reduce model size when saving the ONNX model, so I might just switch my workflow to using transformers instead.

**Comment by vimal-quilt** [comment]
yes, option for quantization is not available in the method of simple transformers.

**Comment by prrao87** [comment]
It's odd, the `dynamic_quantize` method implemented in simpletransformers does call the exact `transformers.convert_graph_to_onnx` method as required ([see code here](https://github.com/ThilinaRajapakse/simpletransformers/blob/76f1df524c046760fd2938839f014e88678b2a27/simpletransformers/classification/classification_model.py#L275)). So we should be able to pass a `dynamkc_quantize` argument when converting the `ClassificationModel` to ONNX just as we would do via the transformers command line.

But the way the API is defined currently, it only allows the `dynamic_quantize` *after* the ONNX model is loaded. I suppose this is still an experimental feature in simpletransformers.

All the more reason to dig deeper into the transformers library documentation. Thanks for the pointers!
