### ISSUE TITLE
Multi GPU error

### ISSUE THREAD

**Issue by ChrisChross** [ThilinaRajapakse/simpletransformers#1042]
Hey guys,

I am currently trying to train a model on multiple GPUs. 
For this reason, I set the number of n_gpu=2.
If I do so, I get the following error: 
```RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cuda:1```

the other parameters I used are pretty much default like:

```
    # Configure the model
    model_args = Seq2SeqArgs()
    model_args.num_train_epochs = 10
    model_args.train_batch_size = 4
    model_args.evaluate_generated_text = True
    model_args.overwrite_output_dir = True
    model_args.save_optimizer_and_scheduler = True
    model_args.max_length = 128
    model_args.process_count = 8
```
I found this issue:
https://discuss.pytorch.org/t/multiple-gpu-model-getting-runtimeerror-caught-runtimeerror-in-replica-0-on-device-0/78025 
but not sure how I could activate DistributedDataParallel, is there any parameter for that?

**Comment by ChrisChross** [comment]
Anyone can help, please?

**Comment by Liujingxiu23** [comment]
@ChrisDelClea  have you sovle the problem? some problem meet
