### ISSUE TITLE
T5 Load model Query

### ISSUE THREAD

**Issue by Threepointone4** [ThilinaRajapakse/simpletransformers#1046]
Issue : Decoder goes into some kind of infinite loop or stuck looks like  

How to reproduce : 
Given custom model in your local load it using T5Model(), now once its loaded based on my assumption , that is self sufficient for predict.But after load done if i delete or move the model folder somewhere  during predict time it throws this error. 

Am I missing something or this is a bug ?

**Comment by Threepointone4** [comment]
In predict there is a code: self._move_model_to_device() , is it because of that ?

**Comment by ThilinaRajapakse** [comment]
I'm not sure but it doesn't seem like a good idea to delete the model folder even if it is loaded.

**Comment by Threepointone4** [comment]
Yes But what I was doing was downloading model in tmp directory using **with**, and storing the variable as global. So when we come out of **with** it deletes. Right now i am doing  without deleting but wanted to understand.
