### ISSUE TITLE
QuestionAnswering Model shows error when evaluate_during_training parameter is set to True.

### ISSUE THREAD

**Issue by Tahsin-Mayeesha** [ThilinaRajapakse/simpletransformers#105]
**Describe the bug**
A clear and concise description of what the bug is. Please specify the class causing the issue.

https://github.com/ThilinaRajapakse/simpletransformers/blob/b6e057369aa3fe797ab01b3259efaa69a826e9fe/simpletransformers/question_answering/question_answering_model.py#L340

This line has this implementation where the self.eval_model() is returning 3 results. But in reality it returns two dictionaries, one containing the number of correct,incorrect and similar results and the other the actual results. So it gives a too many values to unpack error. 

![image](https://user-images.githubusercontent.com/17886829/71309477-41418880-2432-11ea-82ea-17abcfc4c5e7.png)

Fix would be to write : 

results, _ = self.eval_model(eval_data, verbose=True) instead of the above line.

Screenshots :

![image](https://user-images.githubusercontent.com/17886829/71309502-8665ba80-2432-11ea-903b-e2c046c6305e.png)

**Comment by ThilinaRajapakse** [comment]
It should be fixed now. As always, thank you for the detailed bug report!

**Comment by Tahsin-Mayeesha** [comment]
It works now, thanks. @ThilinaRajapakse .
