### ISSUE TITLE
Training Issue

### ISSUE THREAD

**Issue by deeps1210** [ThilinaRajapakse/simpletransformers#1053]
**Describe the bug**
During custom training the 'seq2seq'  'bart-large' model for paraphrasing the model throws error for deadlock
"Reason: 'OSError(24, 'Too many open files')"
![image](https://user-images.githubusercontent.com/43183554/111881030-adfc5780-89d4-11eb-8ed6-3ee60d7059d2.png)

**Comment by philipperemy** [comment]
Same here.

**Comment by philipperemy** [comment]
@deeps1210 try to remove multiprocessing everywhere.

```
model_args.use_multiprocessing = False
model_args.use_multiprocessing_for_evaluation = False
model_args.thread_count = 1
```

**Comment by ThilinaRajapakse** [comment]
Yeah, disabling multiprocessing should solve the issue.
