### ISSUE TITLE
Multi Gpu training

### ISSUE THREAD

**Issue by deeps1210** [ThilinaRajapakse/simpletransformers#1054]
**Is your feature request related to a problem? Please describe.**
The code has torch.nn.DataParallel

![image](https://user-images.githubusercontent.com/43183554/111881072-ef8d0280-89d4-11eb-928d-ea43f7d94918.png)

but as per pytorch documentation DistributedDataParallel should be used for multigpu processing. Kindly review
![image](https://user-images.githubusercontent.com/43183554/111881137-2c58f980-89d5-11eb-8ac2-5dc9dd2bea1c.png)

**Describe the solution you'd like**
torch.nn.DistributedDataParallel should be used

![image](https://user-images.githubusercontent.com/43183554/111881144-37138e80-89d5-11eb-9b56-f1dc3f0be807.png)

**Comment by ThilinaRajapakse** [comment]
DistributedDataParallel wasn't stable when Simple Transformers was released. I'm planning to upgrade but it will likely take a few weeks.

**Comment by anaivebird** [comment]
Any progress on DistributedDataParallel?
