### ISSUE TITLE
Resume or Pause Model Training & Model Prediction

### ISSUE THREAD

**Issue by sourangshupal** [ThilinaRajapakse/simpletransformers#1055]
I am following your medium blog [Bart for Paraphrasing](https://towardsdatascience.com/bart-for-paraphrasing-with-simple-transformers-7c9ea3dfdd8c) to train the model. I have done it successfully. I got the best model folder also.

1. Please help how to pause or resume model training for Sequence to Sequence Model ( used pretrained model facebook/bart-large) .

2. How to load the best model separately and do predictions on sentences?

**Comment by tiru1930** [comment]
@sourangshupal  .. u can try something like below, specify ur best model paths

```
model = Seq2SeqModel("bert", "./seq2seq_large/encoder", "./seq2seq_large/decoder", args=model_args,use_cuda=True,cuda_device="1")
```
