### ISSUE TITLE
How to extract vector representations generataed by a ClassificationModel with multiple classes?

### ISSUE THREAD

**Issue by letsGoBharat** [ThilinaRajapakse/simpletransformers#1059]
I am using a ClassificationModel to perform a classification task for multiple classes and would like to graphically represent and analyze the word embeddings produced by the model of the training data. I am unable to find a way to do so at the moment. There is a TextRepresentationModel that does this but I want to analyze the embeddings while using the classification model. Is that possible? If yes, how?

**Comment by karthik19967829** [comment]
Hey @letsGoBharat the CLS embedding of the model is what you are looking for.

**Comment by letsGoBharat** [comment]
Hey @karthik19967829, Thanks for your response.
For simple transformers, is there a way I can extract the CLS embedding from the ClassificationModel? I am using xlnet-base-cased as the transformer model inside the ClassificationModel. I looked at the source code of the classification model and it doesn't return CLS embedding. Maybe I missed something obvious. Thanks again :)

**Comment by letsGoBharat** [comment]
Hey @ThilinaRajapakse, Thanks for your response. 
I reviewed the attached issue and the ClassificationModel source code. The embeddings are produced by the model.predict() function. Does that mean that only embeddings for the eval dataset could be fetched? My use case is to compare embeddings produced by the model on the training dataset for various deep learning models. Would the predict() method give me embeddings for training data correctly if I pass the train_df in the predict() method?

**Comment by letsGoBharat** [comment]
@ThilinaRajapakse To be more precise, usually, the model takes the training text data and converts the data in word embeddings, and then trains the model on those emeddings. I am trying to access these training data word embeddings that were used to train the model. Is there by way to access those in the simple transformers classification model?

**Comment by ThilinaRajapakse** [comment]
Yes, as long as the input to the `predict()` function is in the correct format, it doesn't matter whether it's test or train.

**Comment by letsGoBharat** [comment]
Trying the mode. predict() gives an error for longer sequences. I have opened a new issue for the same [#1120](https://github.com/ThilinaRajapakse/simpletransformers/issues/1120).

**Comment by JINHXu** [comment]
I think with the `RepresentationModel` available, it is now possible to get the CLS embedding of a sentence through the following code:

```python
from simpletransformers.language_representation import RepresentationModel
        
sentences = ["Example sentence 1", "Example sentence 2"]
model = RepresentationModel(
        model_type="bert",
        model_name="bert-base-uncased",
        use_cuda=False
    )
word_vectors = model.encode_sentences(sentences, combine_strategy=None)
cls_embedings = word_vectors[:,0,:]
```
