### ISSUE TITLE
'do_lower_case' option is not available?

### ISSUE THREAD

**Issue by yliu2018** [ThilinaRajapakse/simpletransformers#106]
For initializing a new classification model, I don't see an option to specific 'do_lower_case'. How do you set to True/False depending on the uncased/cased pretrained LMs? Please clarify and thanks!

**Comment by ThilinaRajapakse** [comment]
This functionality was missing but I've added it now. You can set it along with the other training arguments.

Embarrassingly, I never noticed it was missing as I don't generally use uncased models (and this library was initially developed for personal use).
