### ISSUE TITLE
model.predict() throws error multilabel classification

### ISSUE THREAD

**Issue by akshay6238** [ThilinaRajapakse/simpletransformers#1061]
![image](https://user-images.githubusercontent.com/34939791/112289795-9f53c000-8cb4-11eb-89fe-dece2f64bc38.png)
Working on multilabel classification which has 22 different classes and for some reason the model.predict throws an error. Help ASAP!

**Comment by Lolologist** [comment]
I'm having the same issue.

**Comment by vtrokhymenko** [comment]
unfortunately, via `.py` don't work
<img width="1062" alt="imag@Lolologist " src="https://user-images.githubusercontent.com/8581044/122550541-7ab17f00-d03c-11eb-9ea9-89ba898c3106.png">

@Lolologist mb u know how to fix more this error?

ps
#1170
