### ISSUE TITLE
Masked word completion

### ISSUE THREAD

**Issue by moh-yani** [ThilinaRajapakse/simpletransformers#1064]
Dear,

Is there a task of masked word completion with simpletransformers?

For example:
unmasker("Hello I'm a [MASK] model.")
will output:

[{'sequence': "[CLS] hello i'm a fashion model. [SEP]",
  'score': 0.1073106899857521,
  'token': 4827,
  'token_str': 'fashion'},

etc

Thank you

Regards,

M. Yani

**Comment by ThilinaRajapakse** [comment]
No, but it should be possible to do that quite easily with Huggingface Transformers. You can use a Simple Transformers trained model, of course.

**Comment by moh-yani** [comment]
I see. Okay, thank you for the response. Have a nice day.

Pada tanggal Jum, 2 Apr 2021 pukul 02.52 Thilina Rajapakse <
***@***.***> menulis:
