### ISSUE TITLE
T5 for Multi-Label Classification

### ISSUE THREAD

**Issue by jonsaadfalcon** [ThilinaRajapakse/simpletransformers#1071]
**Description**
I currently am trying to use the T5 model for multi-label classification on 8 labels. However, when I try to train the model on the my train data, it only seems to allow that I include two labels for the classification training. If I add more than two, I get the following error:

`ValueError('too many values to unpack (expected 2)')`

**To Reproduce**

Create a simple dataset with the multi-label classification prefix:

`                          prefix  ... target_text
0     multi-label classification  ...   [0, 0, 0]
1     multi-label classification  ...   [0, 0, 0]
2     multi-label classification  ...   [1, 0, 0]`

Make normal call to train model: `model.train_model(train_df, eval_data=first_eval_df)`

**Expected behavior**
I expected the model to train with 8 labels, since it worked for 2 labels. 

**Screenshots**
![image](https://user-images.githubusercontent.com/41205309/112738342-75aacb00-8f38-11eb-97f8-6c627047dabd.png)

![image](https://user-images.githubusercontent.com/41205309/112738345-7d6a6f80-8f38-11eb-8a0d-0dc9aa9ccd33.png)

**Desktop (please complete the following information):**
 - MacOS

**Comment by ThilinaRajapakse** [comment]
T5 is a sequence-to-sequence model. Your target_text should be a single string no matter what task you are doing. You could use a comma-separated string of labels as the target.
