### ISSUE TITLE
multi-label multi-class

### ISSUE THREAD

**Issue by enpassanty** [ThilinaRajapakse/simpletransformers#1072]
from what I can tell, the MultiLabelClassificationModel allows multiple binary labels.  is there a way to do multiple labels with multiple classes in each label?  e.g.

label A = { 5 classes, 0:4 }
label B = {10 classes, 0:9}

another related question:  for my actual problem I need to predict on a some combination of classes. so say 

label A = {classes: 'house', 'dog' , 'tree' , 'cloud' , 'sun'}

My output could have any combination of label A classes.  e.g.

{'house'} or {'house', 'dog'} or {'house', 'dog' , 'tree' , 'cloud' , 'sun'},   etc...

thanks

**Comment by ThilinaRajapakse** [comment]
Multi-class, multi-label classification is not currently supported in Simple Transformers.

**Comment by enpassanty** [comment]
thanks for taking the time to reply.
