### ISSUE TITLE
When to use model.reprocess_input_data, model.use_cached_eval_features?

### ISSUE THREAD

**Issue by roshan-k-patel** [ThilinaRajapakse/simpletransformers#1073]
Hi i'm running a Bayesian parameter search on a text classification model. Should i be using my cached_eval_features or not in this circumstance? Likewise should i set reprocess_input_data to false? using cache and not reprocessing input data saves a lot of time, but will it lead to my model parameter search not executing properly or is it fine to do this as long as my input data is the same?

**Comment by ThilinaRajapakse** [comment]
Both these parameters control whether the feature preprocessing is done again. So, you should reprocess the inputs if you change a parameter that will change the generated features (e.g. maximum sequence length).
