### ISSUE TITLE
Even T5 example is not running

### ISSUE THREAD

**Issue by Lalit-01** [ThilinaRajapakse/simpletransformers#1074]
When I'm copying and paste the t5 example from [documentation](https://simpletransformers.ai/docs/t5-specifics/)

first, it raises the eval_df error then is raising this error

`AssertionError: text input must of type "str" (single example), "List[str]" (batch or single pretokenized example) or "List[List[str]]" (batch of pretokenized examples).`

Any suggestion on how to solve this?

**Comment by overlookcurl** [comment]
Yeah, I am facing the same issue

**Comment by overlookcurl** [comment]
Is there any update on this issue?

**Comment by matjazmav** [comment]
Anything?

**Comment by ThilinaRajapakse** [comment]
The issue is that the examples have ints as the `target_text`. It works if you use strings instead, i.e., `"1"` instead of `1`. I'll update the docs to fix it (and will also just add a line to make sure numbers are converted to strings automatically).
