### ISSUE TITLE
How classification works on MASK tokens 

### ISSUE THREAD

**Issue by BaoshengHeTR** [ThilinaRajapakse/simpletransformers#1075]
I have a question. In default, for text classification the hidden state of `<s>` (e.g., roberta) token is fed into classification. However, since bert-like models are pretrained as masked language models, so if we insert `<mask>` somewhere in the text, will the hidden states of the mask token be used for classification purpose? If so, is this a routine in `transformers` library?

**Comment by ThilinaRajapakse** [comment]
Yeah, it should be used. But, I'm not sure why you'd want to do that.

**Comment by BaoshengHeTR** [comment]
> Yeah, it should be used. But, I'm not sure why you'd want to do that.

Here is what I am trying to solve. I got two numbers 5 and 10 in a text, e.g.,:
` I got $5 for eating and $10 for drinking`
I want to make classfication on what `$5` and `$10` represent, by masking them individually, I got two samples with labels `eat` and `drink` respectively. NER does not work well on my case.

**Comment by ThilinaRajapakse** [comment]
The classification layer only gets the representation for the first (CLS) token as its input. It won't directly see the masked tokens. However, masking some tokens will change the representation for the CLS token due to the attention mechanisms of the model.

**Comment by BaoshengHeTR** [comment]
> The classification layer only gets the representation for the first (CLS) token as its input. It won't directly see the masked tokens. However, masking some tokens will change the representation for the CLS token due to the attention mechanisms of the model.

Curious about this. Since `mask_token` is only used as an arg in Tokenizer object, I would like to know if `<mask>` tokens in classification models will be ignored in attention?

**Comment by ThilinaRajapakse** [comment]
I think so, but I don't know for sure.
