### ISSUE TITLE
DebertaV2ForSequenceClassification?

### ISSUE THREAD

**Issue by roshan-k-patel** [ThilinaRajapakse/simpletransformers#1078]
Hi @ThilinaRajapakse, when trying to initialise DeBERTAv2 i get this run time error

```
RuntimeError: Error(s) in loading state_dict for DebertaForSequenceClassification:
        size mismatch for deberta.encoder.rel_embeddings.weight: copying a param with shape torch.Size([512, 1536]) from checkpoint, the shape in current model is torch.Size([1024, 1536]).
```

Is there anyway i can override it to use DebertaV2ForSequenceClassification instead of DebertaForSequenceClassification.

Or does this need to be added in a future update?

Thanks

**Comment by ThilinaRajapakse** [comment]
This still needs to be added.
