### ISSUE TITLE
Reducing Dimension of BERT Embeddings

### ISSUE THREAD

**Issue by QAQOAO** [ThilinaRajapakse/simpletransformers#1085]
Hi, what a wonderful repo!

I know one can use a pretrained model in RepresentationModel to get sentnce embeddings easily.

However, the dimension of output embedding (768) is too large for me.

If I just want the output dimension to be set like 256 without retraining the model or other dimension reduction technique, is this possible now?

I have an idea of adding a Dense Layer after loading a RepresentationModel like below, and then use the concatenated model to encode sentences.

model = RepresentationModel(
    "roberta",
    "roberta-base",
    args=model_args,
)

?? adding a Dense layer ??

emb = model.encode_sentences(text_list, combine_strategy="mean")

But I am not sure how to implement that, or there might be a better way of doing that. What's your take on that?

Thanks a lot!

**Comment by ThilinaRajapakse** [comment]
You can technically add an additional layer to reduce the output dimension but it's non-trivial. You will likely have to change the model implementation itself (after which you might run into issues with loading pretrained weights).
