### ISSUE TITLE
Get negative eval_loss?

### ISSUE THREAD

**Issue by hxxxxh** [ThilinaRajapakse/simpletransformers#1086]
**Describe the bug**
I am using the simpletransformers framework for question answering. When I use the "Question Answering Minimal Start" in the document, I get a negative eval_loss in the "training_progress_scores.csv" file. This confuses me.
Script from link: [https://simpletransformers.ai/docs/qa-minimal-start/](https://simpletransformers.ai/docs/qa-minimal-start/)  
Can anyone explain to me why this happens?

**To Reproduce**
I just change some model args in the script. It looks like:
```python
model_args = QuestionAnsweringArgs(
    output_dir="./output",
    overwrite_output_dir=True,
    use_multiprocessing=False,
    use_multiprocessing_for_evaluation=False,
    fp16=False,
    save_best_model=False
)
```  
Then after the program finished, I check `training_progress_scores.csv` in the output dir:  
```csv
global_step,correct,similar,incorrect,train_loss,eval_loss
1,0,1,2,4.807735443115234,-0.30414509773254395
```

I found that it show an **nagetive loss value** on column "eval_loss".  

**Desktop (please complete the following information):**
 - OS: Windows 10
 - using Anaconda3
 - simpletransformers == 0.60.9
 - transformers == 4.4.2
 - python == 3.7.10

**Comment by ThilinaRajapakse** [comment]
The minimal start is just to show how the model can be used. You won't get realistic results from it as it only has 2 or 3 training samples.
