### ISSUE TITLE
Does early stopping work in LanguageModelingModel?

### ISSUE THREAD

**Issue by higopires** [ThilinaRajapakse/simpletransformers#1088]
I'm training a `LanguageModelingModel` now, with the following early stopping configs:

```
model_args.evaluate_during_training = True
model_args.evaluate_during_training_verbose = True

model_args.use_early_stopping = True
model_args.early_stopping_delta = 0.01
model_args.early_stopping_metric = "eval_loss"
model_args.early_stopping_metric_minimize = True
```

(patience with default value = 3)

Over the course of several epochs, my `eval_loss` is getting higher, but the problem I noticed is that early stopping is not being triggered. What can be done?

**Comment by ThilinaRajapakse** [comment]
It should work with Language Modeling. Do you get the log messages like "No improvement in metric"?

**Comment by higopires** [comment]
There's no log messages about the early stopping, only about the training itself.

**Comment by ThilinaRajapakse** [comment]
That's weird. Can you try setting up a debugger or just some print statements to see whether the code is actually going into the early stopping logic?
