### ISSUE TITLE
how to make predictions on test.csv file with more than one line of text?

### ISSUE THREAD

**Issue by azamatolegen** [ThilinaRajapakse/simpletransformers#109]
In your article you showed how to make prediction on a single sentence, by feeding that sentence to model.predict() method. How to make predictions on test.csv file which is a file with more that one line of text (few hundred sentences)? Thanks!

**Comment by azamatolegen** [comment]
and got kind of "submission" file with output result?

**Comment by ThilinaRajapakse** [comment]
Going to need a little more detail. Which model are you referring to?

**Comment by kinoute** [comment]
What don't you use the `model.eval_model()` method to check how your model is doing on your `test.csv`  dataset?

If I wanted to use `model.predict()` on a `.csv` file, I will basically read the CSV with pandas and transform it to a list.

Like:

```py
mails = []

for _, row in test_dataset.iterrows():
    mails.append(row['text'])
        
predictions, raw_outputs = model.predict(mails)
```

Or even simpler with `mails = test_dataset['text'].tolist()`
