### ISSUE TITLE
What is the best way to perform text duplicate detection?

### ISSUE THREAD

**Issue by Moradnejad** [ThilinaRajapakse/simpletransformers#1090]
Hi everyone,
Thank you for this great library.

I wanted to perform duplicate detection on Quora question pairs: https://paperswithcode.com/dataset/quora-1

Basically, we have three columns: text1, text2, is_duplicate

I checked the examples on binary text classification, but they take only one text input. I can build my own NN and use sentence embedding, but I wanted to see if there is a way to do it using `simpletransformers`.

**Comment by kongyurui** [comment]
The library also has an option for sentence pair classification that could apply here: https://simpletransformers.ai/docs/sentence-pair-classification/

**Comment by Moradnejad** [comment]
Wow. Thank you. Exactly what I was looking for.
