### ISSUE TITLE
How to solve overfitting in multi class classification?

### ISSUE THREAD

**Issue by moh-yani** [ThilinaRajapakse/simpletransformers#1098]
Dear,

I performed the simple transformers model for multi class classification task. However, I got overfitting. Is there approach to prevent the problem (overfitting) for this case?

Thank you.

Regards,
M Yani

**Comment by higopires** [comment]
You can use early stopping.

**Comment by moh-yani** [comment]
@higopires 

Thank you for the response. I will try it.


Regards,
MY

**Comment by higopires** [comment]
You're welcome.

It's very easy to use early stopping. Documentation [here](https://simpletransformers.ai/docs/tips-and-tricks/#using-early-stopping).
