### ISSUE TITLE
Model being slow

### ISSUE THREAD

**Issue by Bams2011** [ThilinaRajapakse/simpletransformers#1099]
**Describe the bug**
I have an existing classification model(with 7 classes) that's running on production(deployed on a cortex cluster on AWS)! I was developping a new version of the model (with 37 classes) and when i deployed it to dev section for testing the api was very slow and i noticed that the predict function of the model was taking so much time (about 100 seconds). I have tested the same script on the notebook but it was working properly with reasonable time (about 400 ms)!
The actual live deployment have an aveage response time of 600 ms.

I have also tried to test the deployment building a simple api using fastapi but the model predict function was still slow!

**To Reproduce**
from simpletransformers.classification import ClassificationModel

def __init__(self,logger):
        self.CONFIG_FILE="./ml/wakanda_conf.ini"
        self.conf = configparser.ConfigParser()
        self.conf.read(self.CONFIG_FILE)
        self.logger = logger
        self.logger.info("Loading classifier model....")
        self.model = ClassificationModel('roberta', self.conf['WAKANDA']['classifier_path'], use_cuda=False,args= 
                         {"use_multiprocessing":False})

 def predict(self,payload):
        description = payload["description_text"]
        subject = payload["subject"]
        ticket_content = subject + "  " + description
        sample = pd.DataFrame(data = [ticket_content],columns=['ticket_full_content'] )
        pred,preprocessed_input = self.make_prediction(sample)
        return pred,preprocessed_input

**Expected behavior**
Normallly we would get predictions in a reansonable time( about 500 ms)

**Environnements:**
 - Python 3.7
 - transformers 4.2.2
 - simpletransformers 0.51.15
 - cortex cli 0.20

**Comment by Bams2011** [comment]
The slowness was due some errors on using the predict function!

**Comment by askintution** [comment]
@Bams2011 did you find solution for this problem?
