### ISSUE TITLE
What do these model parameters mean?

### ISSUE THREAD

**Issue by roshan-k-patel** [ThilinaRajapakse/simpletransformers#1107]
"params_classifier.dense.weight"
        "params_classifier.dense.bias"
        "params_classifier.out_proj.weight"
        "params_classifier.out_proj.bias"

Could someone please briefly explain these parameters to me? Using the DeBERTa model

**Comment by ThilinaRajapakse** [comment]
Those are the parameters associated with the fully-connected classification layer.

**Comment by roshan-k-patel** [comment]
Thanks @ThilinaRajapakse, but could you explain what they specifically are? I'm following you hyperparameter optimisation guide on medium.
