### ISSUE TITLE
Can I add seqeval.metrics.classification_report as metric while train and eval the NER model?

### ISSUE THREAD

**Issue by Jefffish09** [ThilinaRajapakse/simpletransformers#1111]
My code of training model part:
![image](https://user-images.githubusercontent.com/44800122/115965090-0eddf900-a55a-11eb-8680-8da3557bc632.png)

but it showed this TypeError after several epochs:

![image](https://user-images.githubusercontent.com/44800122/115965170-56648500-a55a-11eb-90fc-3c457e2ba301.png)

![image](https://user-images.githubusercontent.com/44800122/115965199-89a71400-a55a-11eb-8b1d-a40a73fdd654.png)

**Comment by ThilinaRajapakse** [comment]
Your metric needs to return a numerical value. It won't work with a classification report.

**Comment by Jefffish09** [comment]
> Your metric needs to return a numerical value. It won't work with a classification report.

thanks!
