### ISSUE TITLE
AttributeError: 'MMBTConfig' object has no attribute 'use_return_dict' in MultiModalClassificationModel

### ISSUE THREAD

**Issue by usmanmalik57** [ThilinaRajapakse/simpletransformers#1115]
**Describe the bug**
 
I receive the exception:
AttributeError: 'MMBTConfig' object has no attribute 'use_return_dict' while training the following model:

```
model = MultiModalClassificationModel(
     "bert", "bert-base-multilingual-cased", num_labels = 47, args=({'fp16': False,
                                                       'reprocess_input_data': True, 
                                                       'overwrite_output_dir' : True, 
                                                       'num_train_epochs': 5,
                                                       'max_seq_length':128,
                                                       'batch_size':2
                                                       #'evaluate_during_training': True,
                                                       #'logging_steps': 50,

                                                       })
)
```

**Comment by simepy** [comment]
Hi @usmanmalik57 !

I fix this problem by adding `model.config.use_return_dict = False`
I find this in the issue #774 

I'm now facing to another issue:

``` python
Traceback (most recent call last):
  File "/file.py", line 84, in <module>
    model.train_model(train_sample, image_path=image_dir)
  File "pyEnv/lib/python3.9/site-packages/simpletransformers/classification/multi_modal_classification_model.py", line 319, in train_model
    global_step, training_details = self.train(
  File "/pyEnv/lib/python3.9/site-packages/simpletransformers/classification/multi_modal_classification_model.py", line 555, in train
    current_loss = loss.item()
ValueError: only one element tensors can be converted to Python scalars
```

I launch like this:
``` python
arg = MultiModalClassificationArgs()
model = MultiModalClassificationModel(
    'bert',
    'bert-base-multilingual-cased',
    args=arg,
    use_cuda=cuda_available,
    label_list=my_label_list
)

model.config.use_return_dict = False

# Train the model
model.train_model(train_sample, image_path=image_dir)
```

@ThilinaRajapakse Do you have some clue ?

Thanks in advance

**Comment by simepy** [comment]
After a while of tinkering, it's working if you turn `fp16` to `False`

``` python
arg = MultiModalClassificationArgs(fp16=False)
```
Unfortunately, I don't have enough knowledge if he has any consequence, 
fell free to give some explain :+1:

**Comment by usmanmalik57** [comment]
> After a while of tinkering, it's working if you turn `fp16` to `False`
> 
> ```python
> arg = MultiModalClassificationArgs(fp16=False)
> ```
> 
> Unfortunately, I don't have enough knowledge for know if he has any consequence,
> fell free to give some explain 👍

Thank you for your reply.
I have made the changes you recommend. The model is training successfully, however while making predictions, I get the following error:

   if isinstance(data, tuple):
UnboundLocalError: local variable 'data' referenced before assignment

**Comment by whalekeykeeper** [comment]
> assignment

I have the same error messages.

**Comment by whalekeykeeper** [comment]
> Thank you for your reply. I have made the changes you recommend. The model is training successfully, however while making predictions, I get the following error:
> 
> if isinstance(data, tuple): UnboundLocalError: local variable 'data' referenced before assignment

I have been through the same earlier errors that I fixed them by reading this issue.
And now I have the same error message `local variable 'data' referenced before assignment`

**Comment by Tdrinker** [comment]
> > Thank you for your reply. I have made the changes you recommend. The model is training successfully, however while making predictions, I get the following error:
> > if isinstance(data, tuple): UnboundLocalError: local variable 'data' referenced before assignment
> 
> I have been through the same earlier errors that I fixed them by reading this issue. And now I have the same error message `local variable 'data' referenced before assignment`

Hello I am facing the same issue. Do you have a solution for this?
