### ISSUE TITLE
XLM-RoBERTa is not supported

### ISSUE THREAD

**Issue by hammad26** [ThilinaRajapakse/simpletransformers#112]
Hi
Thanks a lot for your hard work. Can you add support `XLM-RoBERTa` too? Thanks

**Comment by kinoute** [comment]
Any news from this one? It seem really good but maybe it needs a lot of work to add it here.

Flair is about to add it. Here's the PR, you can see some code that could help you to add it: https://github.com/flairNLP/flair/pull/1333

**Comment by ThilinaRajapakse** [comment]
Shouldn't be too hard I think. I should be able to add this soon.

**Comment by ThilinaRajapakse** [comment]
Added in 0.17.0. Let me know if you run into any issues! :wink:

**Comment by kinoute** [comment]
Tested the model quickly this morning. Seems good so far.

**Comment by alejandrojcastaneira** [comment]
Hi I'm initializing the model class like this;

model = MultiLabelClassificationModel('xlm-roberta', 'xlm-roberta-base')

however I get this error:

line 69, in __init__  config_class, model_class, tokenizer_class = MODEL_CLASSES[model_type] KeyError: 'xlm-roberta'

**Comment by kinoute** [comment]
Try `xmlroberta`.

**Comment by alejandrojcastaneira** [comment]
I tried, it gives the same error.

**Comment by ThilinaRajapakse** [comment]
It's not added for multi-label classification at the moment.

**Comment by alejandrojcastaneira** [comment]
hello @ThilinaRajapakse just to be sure,  it's XLM_Roberta already available in the model's list for multiple label classification? We had good results with other models and we are looking forward to try this one, we are very excited!

**Comment by ThilinaRajapakse** [comment]
It's just been added in 0.22.1.

**Comment by alejandrojcastaneira** [comment]
thanks @ThilinaRajapakse so much, for your support!

**Comment by freeIsa** [comment]
Is there a reason why xml-roberta is not supported for language modeling fine-tuning?
