### ISSUE TITLE
Will LanguageGenerationModel ever support GPT Neo?

### ISSUE THREAD

**Issue by Shane-Neeley** [ThilinaRajapakse/simpletransformers#1124]
It is in the transformers library now: https://huggingface.co/transformers/master/model_doc/gpt_neo.html

Just wondering! Thanks.

**Comment by GenTxt** [comment]
Managed to get gpt-neo models working by editing 'language_generation_model.py' as follows:

See # add

from transformers import (
    CTRLConfig,
    CTRLLMHeadModel,
    CTRLTokenizer,
    GPT2Config,
    GPT2LMHeadModel,
    GPT2Tokenizer,
    GPTNeoConfig, # add
    AutoModelForCausalLM, #add
    etc.

MODEL_CLASSES = {
            "gpt2": (GPT2Config, GPT2LMHeadModel, GPT2Tokenizer),
            "gpt_neo": (GPTNeoConfig, AutoModelForCausalLM, GPT2Tokenizer), # add here for both models - AutoTokenizer (fast) = error

Example line to add model for generation 'generate.py'

model = LanguageGenerationModel("gpt_neo", "models/gpt-neo-1.3B", args={"max_length": 1500, "top_p": 0.9, "repetition_penalty": 1.2, "num_return_sequences": 1})

Outputs for both 1.3 and 2.7B including finetuned checkpoints. "repetition_penalty": 1.2 is important as output tends to loose focus after 800 tokens or so. You may encounter tensor mismatch errors and OOM when trying to max output to 2048 tokens.
1500 works well with 1.3B and 1000-1100 with 2.7B. Errors on my system might not be an issue on yours.

**Comment by Shane-Neeley** [comment]
Thank you @GenTxt ! I'll give that a try. I just like simpletransformers. I was able to get it running on huggingface alone but just with the 125M param model.
