### ISSUE TITLE
NER problem with accuracy_score

### ISSUE THREAD

**Issue by ChenMalobani** [ThilinaRajapakse/simpletransformers#1130]
![image](https://user-images.githubusercontent.com/55045113/117575076-ee30aa00-b0e8-11eb-989f-512b44221e74.png)

**Comment by Onkar-2803** [comment]
@ThilinaRajapakse is there any solution for this?

**Comment by ThilinaRajapakse** [comment]
A workaround, for now, would be to wrap the sklearn accuracy function in a custom function that rearranges the data into the format that sklearn expects.

**Comment by Onkar-2803** [comment]
Yeah, I'm trying to work on that too!

**Comment by Onkar-2803** [comment]
This worked for me, if anyone comes across such an error in the future then this might be useful.


# This is a class te get sentence. The each sentence will be list of tuples with its tag and pos.
class sentence(object):
    def __init__(self, df):
        self.n_sent = 1
        self.df = df
        self.empty = False
        agg = lambda s : [(w, t) for w, t in zip(s['words'].values.tolist(),
                                                       s['labels'].values.tolist())]
        self.grouped = self.df.groupby("sentence_id").apply(agg)
        self.sentences = [s for s in self.grouped]
        
    def get_text(self):
        try:
            s = self.grouped['Sentence: {}'.format(self.n_sent)]
            self.n_sent +=1
            return s
        except:
            return None

test_data = testing_data_bert

getter = sentence(test_data)
test_list = [" ".join([s[1] for s in sent]) for sent in getter.sentences]

for i in range(0, len(test_list)):
  test_list[i] = test_list[i].split()

wrong_indices = []

for i in range(0, len(preds_list)):
  if(len(preds_list[i]) != len(test_list[i])):
    wrong_indices.append(i)

print(wrong_indices)
print(len(wrong_indices))

test = []
pred = []

for i in range(0, len(preds_list)):
  if i not in wrong_indices:
    test.append(test_list[i])
    pred.append(preds_list[i])

def flatten(t):
    return [item for sublist in t for item in sublist]

test = flatten(test)
pred = flatten(pred)

accuracy_score(test, pred)
