### ISSUE TITLE
ImportError: cannot import name 'setup_logging' from 'fsspec.utils' when trying to import on Kaggle notebook

### ISSUE THREAD

**Issue by ashwani-bhat** [ThilinaRajapakse/simpletransformers#1133]
I am trying to import simpletransformers in kaggle notebook and I am getting the following import error.

ImportError: cannot import name 'setup_logging' from 'fsspec.utils' (/opt/conda/lib/python3.7/site-packages/fsspec/utils.py)

**Comment by Nighthyst** [comment]
Hello, you should check out this solution: https://github.com/ThilinaRajapakse/simpletransformers/issues/1109#issuecomment-832067762

It worked for me. You just have to go search on PyPi website all files with the version indicated or more recent then you will be able to install them in the order mentioned. Hope it will help.
