### ISSUE TITLE
Deprecated wandb plots

### ISSUE THREAD

**Issue by ariG23498** [ThilinaRajapakse/simpletransformers#1135]
**Is your feature request related to a problem? Please describe.**
[Wandb issue](https://github.com/wandb/client/issues/2186) relates to the use of `wandb.plots` API for the ROC, PR and CM plots.

**Describe the solution you'd like**
As per the docs of wandb, the new API is `wandb.plot` which are preset of the custom chart API. They directly utilize the newer features of plotting and are much more robust and maintained.

**Comment by AyushExel** [comment]
@ariG23498 We're already in talks to update this feature. I'll update you on slack :)
