### ISSUE TITLE
wrong_predictions from eval_model is empty

### ISSUE THREAD

**Issue by vivicenisilva** [ThilinaRajapakse/simpletransformers#1139]
When I run eval_model on my test dataset everything goes smooth, and I get my results and the model outputs. However, the wrong predictions variable is an empty list. Since I get no error messages I can't seem to figure it out why. 

I also noticed that something does not seem to load (see image):

![Image 2021-05-18 at 9 35 41 PM](https://user-images.githubusercontent.com/28744841/118712502-29d21f00-b821-11eb-80a8-25055c01b3d6.jpg)

I use Jupyter notebook.

Thank you! I love this library ❤️

**Comment by kamalravi** [comment]
> When I run eval_model on my test dataset everything goes smooth, and I get my results and the model outputs. However, the wrong predictions variable is an empty list. Since I get no error messages I can't seem to figure it out why.
> 
> I also noticed that something does not seem to load (see image):
> 
> ![Image 2021-05-18 at 9 35 41 PM](https://user-images.githubusercontent.com/28744841/118712502-29d21f00-b821-11eb-80a8-25055c01b3d6.jpg)
> 
> I use Jupyter notebook.
> 
> Thank you! I love this library heart

When I tried to train and eval together, wrong_predictions become empty. The issue still persists.

**Comment by tschomacker** [comment]
I have encountered the same issue. I could not solve it and left `simpletransformers` because of it. Now I work with `huggingface` and `pytorch`.

**Comment by jinschoi** [comment]
I am seeing this same issue.

**Comment by jinschoi** [comment]
I have created a pull request that _should_ fix this issue: https://github.com/ThilinaRajapakse/simpletransformers/pull/1343
