### ISSUE TITLE
Multilabel toxic comment examples: raise ValueError("Output directory ({}) already exists and is not empty.

### ISSUE THREAD

**Issue by hieudango** [ThilinaRajapakse/simpletransformers#116]
**Describe the bug**
Hi, I am following exactly your medium post: https://towardsdatascience.com/multi-label-classification-using-bert-roberta-xlnet-xlm-and-distilbert-with-simple-transformers-b3e0cda12ce5

Everything goes well until this line of code:
#Train the model
**model.train_model(train_df)**

It got this error:

Traceback (most recent call last):
  File "toxic_comments.py", line 21, in <module>
    model.train_model(train_df)
  File "/home/ec2-user/anaconda3/envs/st_env/lib/python3.7/site-packages/simpletransformers/classification/multi_label_classification_model.py", line 119, in train_model
    return super().train_model(train_df, multi_label=multi_label, eval_df=eval_df, output_dir=output_dir, show_running_loss=show_running_loss, args=args)
  File "/home/ec2-user/anaconda3/envs/st_env/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py", line 189, in train_model
    **raise ValueError("Output directory ({}) already exists and is not empty. Use --overwrite_output_dir to overcome.".format(output_dir))**
**ValueError: Output directory (outputs/) already exists and is not empty. Use --overwrite_output_dir to overcome.**

If I use another empty path:
#Train the model
**model.train_model(train_df, output_dir='/home/ec2-user/test_output')**
I have this error:

Traceback (most recent call last):
  File "toxic_comments.py", line 24, in <module>
    model.train_model(train_df, output_dir='/home/ec2-user/test_output')
  File "/home/ec2-user/anaconda3/envs/st_env/lib/python3.7/site-packages/simpletransformers/classification/multi_label_classification_model.py", line 119, in train_model
    return super().train_model(train_df, multi_label=multi_label, eval_df=eval_df, output_dir=output_dir, show_running_loss=show_running_loss, args=args)
  File "/home/ec2-user/anaconda3/envs/st_env/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py", line 199, in train_model
    train_dataset = self.load_and_cache_examples(train_examples)
  File "/home/ec2-user/anaconda3/envs/st_env/lib/python3.7/site-packages/simpletransformers/classification/multi_label_classification_model.py", line 128, in load_and_cache_examples
    return super().load_and_cache_examples(examples, evaluate=evaluate, no_cache=no_cache, multi_label=multi_label)
  File "/home/ec2-user/anaconda3/envs/st_env/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py", line 479, in load_and_cache_examples
    features = torch.load(cached_features_file)
  File "/home/ec2-user/anaconda3/envs/st_env/lib/python3.7/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/ec2-user/anaconda3/envs/st_env/lib/python3.7/site-packages/torch/serialization.py", line 613, in _load
    **result = unpickler.load()
EOFError: Ran out of input**

**Screenshots**
![image](https://user-images.githubusercontent.com/39396316/71578642-987ae380-2b2b-11ea-9b1c-af401d21269b.png)

![image](https://user-images.githubusercontent.com/39396316/71578696-c9f3af00-2b2b-11ea-87bb-3a55801e6e3b.png)

![image](https://user-images.githubusercontent.com/39396316/71578894-982f1800-2b2c-11ea-89a0-bd087aac583a.png)

**Version**
I tried all versions of 0.15, 0.14 and all got the same errors.

Please help. Thanks a lot!!!!

**Comment by ThilinaRajapakse** [comment]
The error message tells you what you need to do. Since the output directory is not empty, you either have to use a different output directory or set `'overwrite_output_dir': True`. This is to prevent accidentally overwriting saved models.

**Comment by hieudango** [comment]
> The error message tells you what you need to do. Since the output directory is not empty, you either have to use a different output directory or set `'overwrite_output_dir': True`. This is to prevent accidentally overwriting saved models.

That's what I did in the second part, and then it got the **EOFError: Run out of input** above. Any ideas why?
Also I run your multilabel_classification.py and it runs smoothly. Just when applying to the toxic comments dataset did it produce errors.

**Comment by hieudango** [comment]
Just found out the solution: Have to add 'reprocess_input_data': True in the args argument when I define the model.

Also just want to let you know that version 0.15.2 still has KeyError with tensorboard, so I have to degrade to 0.15.0 in order for the code to work.

**Comment by ThilinaRajapakse** [comment]
Sorry I didn't read your error report properly! (It was late and I was tired 😟)

What is the KeyError with tensorboard?

**Comment by hieudango** [comment]
Lol no worries :)

![image](https://user-images.githubusercontent.com/39396316/71616290-1a304700-2be8-11ea-8cc8-aaccdbc782f0.png)

  File "/home/ec2-user/anaconda3/envs/st_env/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py", line 228, in train
    tb_writer = SummaryWriter(logdir=args["tensorboard_folder"])
KeyError: 'tensorboard_folder'



Also, can you let me know how long do you train your multilabel model with toxic comment classifications with your default settings and the machine configuration you used with it? Because right now with the configuration:

model = MultiLabelClassificationModel('roberta', 'roberta-base', num_labels=6, use_cuda=False, args={'reprocess_input_data': True, 'overwrite_output_dir': True, 'train_batch_size':2, 'gradient_accumulation_steps':16, 'learning_rate': 3e-5, 'num_train_epochs': 3, 'max_seq_length': 512})

the time it estimates is about **150 hours!!!** The machine I used to train is pretty decent.

![image](https://user-images.githubusercontent.com/39396316/71616457-ee619100-2be8-11ea-843c-14795a7f7b3f.png)

**Comment by ThilinaRajapakse** [comment]
Fixed the KeyError.

I can't remember the exact amount of time but it was probably a few hours (less than 5 most likely). 

A screenshot of my system specs:
![image](https://user-images.githubusercontent.com/17320131/71626026-064d0b00-2c11-11ea-921e-54a229527275.png)

Looks like you aren't using CUDA (`use_cuda=False`). It'll definitely take waaay too long on a CPU.

**Comment by hieudango** [comment]
Thanks a lot! Indeed I was using CPU. I'll close this issue now.
