### ISSUE TITLE
mt5 cannot be loaded from cache

### ISSUE THREAD

**Issue by DebanjanaKar** [ThilinaRajapakse/simpletransformers#1164]
I keep getting this error while trying to run mt5: "ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on."

However, internet connection is fine and has been double checked. 

PFA the code snippet below. I will really appreciate any help on this.

```model_args = {
"use_multiprocessing" : False,
"max_seq_length" : 256,
"train_batch_size" : 8,
"eval_batch_size" : 8,
"num_train_epochs" : 3,
}
#model_args.evaluate_during_training = True
#"eval_batch_size" : 8

model = T5Model("mt5", "google/mt5-base", use_cuda=True, args=model_args)

# Train the model
model.train_model(train_df)
```

**Comment by whr778** [comment]
Check out this page
https://huggingface.co/transformers/installation.html

Look for env variables HF_HOME and TRANSFORMERS_CACHE the new default is
causing this.

**Comment by DebanjanaKar** [comment]
Thanks a lot @whr778. A point of confusion though, since the cache_dir is set by default, shouldn't it be loading from there?
