### ISSUE TITLE
LanguageModelingModel not able to load ELECTRA checkpoint after language modeling fine-tuning

### ISSUE THREAD

**Issue by mfernezir** [ThilinaRajapakse/simpletransformers#1165]
**Describe the bug**
```
lm_model = LanguageModelingModel(
    model_type="electra",
    model_name=BEST_MODEL_DIR,
    use_cuda=False,
)
```
Fails with the error
`OSError: Can't load tokenizer for 'electra'`

I'm following the part in the docs where I want to load the model after fine-tuning to save the discriminator.
https://simpletransformers.ai/docs/lm-specifics/#language-model-fine-tuning

The `BEST_MODEL_DIR` is the checkpoint dir that I have from the language model fine-tuning part. Here's how it looks like:

```
discriminator_config
generator_config
eval_results.txt
model_args.json
scheduler.pt
optimizer.pt
training_args.bin
vocab.txt
special_tokens_map.json
tokenizer_config.json
pytorch_model.bin
config.json
```

**To Reproduce**
I'm fine-tuning a language model from Hugging Face:
```
model = LanguageModelingModel(
    model_type="electra",
    model_name="electra",
    discriminator_name="classla/bcms-bertic",
    generator_name="classla/bcms-bertic-generator",
    args=model_args
)

model.train_model(TRAIN_FILE, eval_file=VAL_FILE)
result = model.eval_model(VAL_FILE)

```
This trains fine, but I can't load the checkpoint after training.

Model args:
```
model_args = LanguageModelingArgs()
model_args.reprocess_input_data = True
model_args.overwrite_output_dir = False
model_args.num_train_epochs = 1
model_args.dataset_type = "simple"

model_args.evaluate_during_training = True
model_args.evaluate_during_training_silent = False
model_args.evaluate_during_training_verbose = True
model_args.manual_seed = 4242

model_args.best_model_dir = BEST_MODEL_DIR
model_args.output_dir = OUTPUTS_DIR
model_args.cache_dir = CACHE_DIR
model_args.tensorboard_dir = TENSORBOARD_DIR
```

**Expected behavior**
The checkpoint to load without error after fine-tuning so that I can store the discriminator and generator parts separately.

**Desktop (please complete the following information):**
 - OS
Ubuntu 18.04.3 LTS

**Comment by mattivi** [comment]
@mfernezir how did you solve this problem? I am experiencing the same. Thanks!

**Comment by mattivi** [comment]
vocab.txt should be copied in the parent directory as well. This solved the issue.

**Comment by ThilinaRajapakse** [comment]
I'll change the saving code to save the tokenizer to the parent directory.
