### ISSUE TITLE
Inconsistency in train stage from different version

### ISSUE THREAD

**Issue by BaoshengHeTR** [ThilinaRajapakse/simpletransformers#1167]
**Describe the bug**
I trained the same 'ClassificationModel'  with the same train/dev datasets with `simpletransformers` of version `0.61.6` and `0.60.8`. The same train hyper parameters on batch size, epochs, eval steps, etc. Models are trained with the same AWS instance (so the hardware is consistent . However,  `eval_loss` during the training has different values under the two versions.

on `0.60.8`, I got `dev_loss` as:
0.36 0.38 0.32 0.29 0.36 0.28 0.44 0.36 0.31 ...

on `0.61.6`, I got `dev_loss` as:
0.30 0.37 0.30 0.41 0.43 ...

I tried to repeat the training multiple times on each version, and the results are  the same. The model trained on `0.60.8` with `eval_loss` of 0.28 is chosen as the best model. On `0.61.6`, I could not have a model trained with such low `eval_loss` with the same hyper parameters.

**Expected behavior**
I expect `dev_loss` performs consistently

**Comment by ThilinaRajapakse** [comment]
I can't think of any reason why this would happen. I assume you are also using the same `manual_seed`?

**Comment by BaoshengHeTR** [comment]
> I can't think of any reason why this would happen. I assume you are also using the same `manual_seed`?

exactly. To verify my assumption. Under `0.61.6` I alternately set `early_stopping_consider_epochs` as `True` or `False` for couple of times, and it returns the same `dev_loss` sequence as I mentioned (at the same time steps, considering we would have more values of `eval_loss` if each epoch is also counted). So I am pretty sure that is the problem it
