### ISSUE TITLE
Extension of MMBT for generation

### ISSUE THREAD

**Issue by abhaygargab** [ThilinaRajapakse/simpletransformers#1168]
Hi, thank you so much for the wonderful service.

I have some doubts regarding the training details for MM-Imdb dataset.

Are the image encoders and tokenizer embeddings fine-tuned during training on MM-Imdb dataset? If not, can you suggest a way to do it or refer any material for help?

Is there a way to modify the code so that the model’s pre-trained weights can be used for sequence-to-sequence generations tasks instead of classification?

Any suggestions or comments will be of great help.

Thank You

**Comment by ThilinaRajapakse** [comment]
It's been some time since I looked at multi modal tasks, but I believe all the weights are fine-tuned. The tokenizer embeddings should be updated for sure.

I think you might find the [CLIP model](https://arxiv.org/abs/2103.00020) interesting.
