### ISSUE TITLE
Wandb API key input

### ISSUE THREAD

**Issue by viramya-shah** [ThilinaRajapakse/simpletransformers#1171]
I intend to use this repo. on Databricks clusters (have custom codebase and run it via job over the clusters). 

The issue I am facing is regarding the wandb API key. When using it as a job/notebook over cluster, the outputs are read-only and not interactive. So there is no way I could input the API key. 

As far as I know, the wandb.init() doesn't authenticate and we need to have wandb.login() call. 

I suggest to add .login() call to the code base with API key being passed through the model args.

**Comment by ThilinaRajapakse** [comment]
Isn't it possible to call `wandb.login()` within the notebook itself? Or, you can also log in to wandb when you set up your environment, I believe.
