### ISSUE TITLE
Error installing ftfy and spacy

### ISSUE THREAD

**Issue by FORTFANOP** [ThilinaRajapakse/simpletransformers#1174]
**Describe the bug**
I have installed simpletransformers through the instruction given on the website, and the installation has gone successfully. However, when I run the ConvAI example program, it shows
ftfy or spacy is not installed using BERT BasicTokenizer instead of SpaCy & ftfy.
And proceeds to install them. 
However, after a while of failed install attempts, it errors out.

**Desktop (please complete the following information):**
 - Windows 10
 - Python (used multiple versions, but to no avail)

**Additional context**
Any help shall be appreciated

**Comment by emmajane1313** [comment]
did this get solved?

**Comment by appvoid** [comment]
just need to `pip install ftfy`
