### ISSUE TITLE
Problem continue training LM from ELECTRA checkpoint 

### ISSUE THREAD

**Issue by mattivi** [ThilinaRajapakse/simpletransformers#1175]
**Describe the bug**
I need to continue training an ELECTRA language model from a checkpoint. However, I get error as "loaded state dict contains a parameter group that doesn't match the size of optimizer's group". 

**To Reproduce**
Train ELECTRA code
```python
model = LanguageModelingModel(
    "electra",
    None,
    args=train_args,
    train_files=train_files[0],
)

# train model
model.train_model(
    train_file=train_files[0], 
    eval_file=eval_files[0]
)
```

Checkpoints are saved during the training phase. When I want to start retraining from a checkpoint, as explained [here](https://simpletransformers.ai/docs/lm-specifics/#saving-electra-models),
```python
model = LanguageModelingModel(
    "electra",
    "/matti/models/clm-electra-small-v04/checkpoint-82817-epoch-7",
    args=train_args,
    train_files=train_files[0],
)

model.train_model(
    train_file=train_files[0], 
    eval_file=eval_files[0]
)

```

I get the following error:
```python
Traceback (most recent call last):
  File "pretrain_electra_from_checkpoint.py", line 140, in <module>
    eval_file=eval_files[0]
  File "/home/rmattivi/repos/simpletransformers/simpletransformers/language_modeling/language_modeling_model.py", line 437, in train_model
    **kwargs,
  File "/home/rmattivi/repos/simpletransformers/simpletransformers/language_modeling/language_modeling_model.py", line 658, in train
    torch.load(os.path.join(args.model_name, "optimizer.pt"))
  File "/home/rmattivi/.local/lib/python3.7/site-packages/torch/optim/optimizer.py", line 124, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group
```

**Expected behavior**
Except to load model correctly and continue training

**Comment by DebanjanaKar** [comment]
I don't know if this corresponds with your exact problem, but I faced training from checkpoint earlier as well. Try saving the checkpoint without the word 'checkpoint' in it and then training the model. It should work. This is due to a change the ST code now has which is not very well documented I am afraid.

**Comment by mattivi** [comment]
I tried but didn't solve the issue. Will need to dig more. Thanks for the suggestion!

**Comment by mattivi** [comment]
I might have messed up with the checkpoint and/or library versions. It is working now, so this issue can be closed. 
For reference, it works with transformers 4.6.1 and simpletransformers 0.61.9.
