### ISSUE TITLE
Anyway to highlight decision-making?

### ISSUE THREAD

**Issue by ssdorsey** [ThilinaRajapakse/simpletransformers#118]
Has anybody worked out a way to highlight the pieces of text that the transformers primarily use to classify text?

**Comment by ssdorsey** [comment]
Using the CLS tag and this tool seems to work well: https://github.com/jessevig/bertviz

**Comment by ThilinaRajapakse** [comment]
This looks like a great tool!

**Comment by bhardwaj1230** [comment]
> Using the CLS tag and this tool seems to work well: https://github.com/jessevig/bertviz

Hello, I was looking into it too, can you please let me know how did you use bertviz with simpletransformers ?
