### ISSUE TITLE
How can we fine-tune multi class classification model?

### ISSUE THREAD

**Issue by moh-yani** [ThilinaRajapakse/simpletransformers#1187]
Dear @ThilinaRajapakse 

Hope you are doing well. We want to use a classification model to our data. Could we fine-tune the model with ours using simpletransformers? If so, how to do that?

Kind regards,

Mohammad Yani

**Comment by NiksMer** [comment]
Hi,

please check the docs:
https://simpletransformers.ai/docs/multi-class-classification/

or read this article:
https://medium.com/swlh/simple-transformers-multi-class-text-classification-with-bert-roberta-xlnet-xlm-and-8b585000ce3a

**Comment by moh-yani** [comment]
Hi @NiksMer ,

Thank you for the assistance.


Kind regards,

MY
