### ISSUE TITLE
Supporting other optimizers

### ISSUE THREAD

**Issue by zanderkent** [ThilinaRajapakse/simpletransformers#119]
Hi
Are we able to add support for other optimizer to improve training? The LAMB optimizer has show to train faster than the other optimizer. In a recent paper it improved training time of BERT from 3 days to 76 minutes.

Thanks!
Zander

**Comment by ThilinaRajapakse** [comment]
Not at the moment (although you can edit the training loop to use a different optimizer). I'll look into it.

**Comment by zanderkent** [comment]
> Not at the moment (although you can edit the training loop to use a different optimizer). I'll look into it.

Training loop in the base code you mean?

**Comment by ThilinaRajapakse** [comment]
Yeah. I think it could just be changed [here](https://github.com/ThilinaRajapakse/simpletransformers/blob/master/simpletransformers/classification/classification_model.py#L245).

**Comment by zanderkent** [comment]
I'll give it a shot! Thanks!
