### ISSUE TITLE
Loss calculation fluctuation

### ISSUE THREAD

**Issue by samarthsarin** [ThilinaRajapakse/simpletransformers#12]
Is there any specific reason for too much fluctuation in loss calculation? Please find the attached calculation results.

Current iteration:  70%|███████   | 1321/1875 [09:50<04:06,  2.25it/s]Running loss: 0.496334
Current iteration:  71%|███████   | 1322/1875 [09:51<04:06,  2.24it/s]Running loss: 0.607332
Current iteration:  71%|███████   | 1323/1875 [09:51<04:06,  2.24it/s]Running loss: 0.981335
Current iteration:  71%|███████   | 1324/1875 [09:52<04:05,  2.24it/s]Running loss: 0.564045
Current iteration:  71%|███████   | 1325/1875 [09:52<04:06,  2.23it/s]Running loss: 0.813926
Current iteration:  71%|███████   | 1326/1875 [09:53<04:05,  2.24it/s]Running loss: 0.495253
Current iteration:  71%|███████   | 1327/1875 [09:53<04:04,  2.24it/s]Running loss: 0.877046
Current iteration:  71%|███████   | 1328/1875 [09:54<04:04,  2.23it/s]Running loss: 0.935980
Current iteration:  71%|███████   | 1329/1875 [09:54<04:03,  2.24it/s]Running loss: 1.029763
Current iteration:  71%|███████   | 1330/1875 [09:54<04:03,  2.24it/s]Running loss: 0.401378
Current iteration:  71%|███████   | 1331/1875 [09:55<04:02,  2.25it/s]Running loss: 0.995074
Current iteration:  71%|███████   | 1332/1875 [09:55<04:01,  2.25it/s]Running loss: 1.740216
Current iteration:  71%|███████   | 1333/1875 [09:56<04:01,  2.24it/s]Running loss: 0.489634
Current iteration:  71%|███████   | 1334/1875 [09:56<04:02,  2.23it/s]Running loss: 0.216885
Current iteration:  71%|███████   | 1335/1875 [09:57<04:00,  2.24it/s]Running loss: 0.847103
Current iteration:  71%|███████▏  | 1336/1875 [09:57<03:59,  2.25it/s]Running loss: 0.480067

**Comment by ThilinaRajapakse** [comment]
Usually, it's because the learning rate is too high. Is this the Yelp dataset?

**Comment by samarthsarin** [comment]
No, I am working on my dataset for sentiment analysis.
Should I reduce the learning rate?

**Comment by ThilinaRajapakse** [comment]
You could try doing that. There are no guarantees, but it's one thing to try.

**Comment by AliOsm** [comment]
Try to increase the batch size, it works for me.
