### ISSUE TITLE
Downloading Models from Repository

### ISSUE THREAD

**Issue by zanderkent** [ThilinaRajapakse/simpletransformers#120]
Hi,
I work on a closed network to when I call 
`model = Classification('distilbert','distilbert-base-uncased')`

It starts to download the model (if it doesn't already exist), and on my network, the download will be blocked by the firewall. Is it possible to create the "outputs" folder through downloading the "official" models from Google?

Thanks,
Zander!

**Comment by ThilinaRajapakse** [comment]
Yup. You just need to point to the model directory.

`model = ClassificationModel('distilbert', '<model_directory>')`

**Comment by kinoute** [comment]
By the way, where are the models stored when downloaded? In a `/tmp` folder? I'm trying to find a good strategy to dockerize the library and avoid downloading again and again the model, i.e. store it somewhere. Guess that solution might work.

**Comment by ThilinaRajapakse** [comment]
It's not stored in a temporary folder, so it shouldn't be downloaded again after the first time. The default location is `/home/<user>/.cache/torch/transformers`.

**Comment by zanderkent** [comment]
> Yup. You just need to point to the model directory.
> 
> `model = ClassificationModel('distilbert', '<model_directory>')`

We would have to build a pytorch version of the model correct? Since Google only has the TF/TF hub version of it right?

**Comment by ThilinaRajapakse** [comment]
Yeah, but [HuggingFace](https://huggingface.co/transformers/converting_tensorflow_models.html) makes it easy.

**Comment by zanderkent** [comment]
> Yeah, but [HuggingFace](https://huggingface.co/transformers/converting_tensorflow_models.html) makes it easy.

I'll give it a shot and let you know! Thanks!

**Comment by zanderkent** [comment]
So I converted the model from [here](https://tfhub.dev/s?module-type=text-embedding&q=albert) using this script provided by [HuggingFace](https://github.com/huggingface/transformers/blob/master/src/transformers/convert_albert_original_tf_checkpoint_to_pytorch.py). I downloaded the albert_base model.



I saved it in my working directory as "/home/zander/albert_base/pytorch.bin"

But when I ran the classification model code I got some errors.

`Model name '/home/zander/albert_base/' was not found in tokenizers model name list (albert-base-v1, albert-large-v1, albert-xlarge-v1, albert-xxlarge-v1, albert-base-v2, albert-large-v2, albert-xlarge-v2, albert-xxlarge-v2). We assumed '/home/zander/albert_base/' was a path or url to a directory containing vocabulary files named ['spiece.model'] but couldn't find such vocabulary files at this path or url.`

Any thoughts?

**Comment by kinoute** [comment]
I had the same error with a different model. Either you didn't download all the needed files, either your path to the directory is wrong (that was my error). Try to use the absolute path.

**Comment by rabitwhte** [comment]
@ThilinaRajapakse 

> It's not stored in a temporary folder, so it shouldn't be downloaded again after the first time. The default location is /home/<user>/.cache/torch/transformers.

How can I change the default storage location? I'm trying to use simpletransformers in TF docker and I get permission error while downloading the model:

`
PermissionError                           Traceback (most recent call last)
~usr/local/lib/python3.6/dist-packages/transformers/configuration_utils.py in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    157             resolved_config_file = cached_path(config_file, cache_dir=cache_dir, force_download=force_download,
--> 158                                                proxies=proxies, resume_download=resume_download)
    159             # Load config

~usr/local/lib/python3.6/dist-packages/transformers/file_utils.py in cached_path(url_or_filename, cache_dir, force_download, proxies, resume_download, user_agent)
    210             force_download=force_download, proxies=proxies,
--> 211             resume_download=resume_download, user_agent=user_agent)
    212     elif os.path.exists(url_or_filename):

~usr/local/lib/python3.6/dist-packages/transformers/file_utils.py in get_from_cache(url, cache_dir, force_download, proxies, etag_timeout, resume_download, user_agent)
    311     if not os.path.exists(cache_dir):
--> 312         os.makedirs(cache_dir)
    313 

~usr/lib/python3.6/os.py in makedirs(name, mode, exist_ok)
    209         try:
--> 210             makedirs(head, mode, exist_ok)
    211         except FileExistsError:

~usr/lib/python3.6/os.py in makedirs(name, mode, exist_ok)
    209         try:
--> 210             makedirs(head, mode, exist_ok)
    211         except FileExistsError:

~usr/lib/python3.6/os.py in makedirs(name, mode, exist_ok)
    219     try:
--> 220         mkdir(name, mode)
    221     except OSError:

PermissionError: [Errno 13] Permission denied: '/.cache'
`

**Comment by kinoute** [comment]
I don't change the directory but with docker compose I set a volume like this :

```
volumes:
  - ./cache/distilbert:/root/.cache/torch/transformers
```

That way, the model doesn't get downloaded again.
