### ISSUE TITLE
prepare_seq2seq_batch is deprecated and will be removed in version 5 of HuggingFace Transformers

### ISSUE THREAD

**Issue by jenka13all** [ThilinaRajapakse/simpletransformers#1218]
**Describe the bug**
prepare_seq2seq_batch is called on the tokenizer in the following files:

simpletransformers/t5/t5_utils.py (lines 24 and 36)
simpletransformers/seq2seq/seq2seq_utils.py (lines 63 and 344)
simpletransformers/seq2seq/seq2seq_model.py (lines 1248 and 1256)
simpletransformers/t5/t5_model.py (line 1027)

**To Reproduce**
call model.train_model() where model is type mt5, with name mt5-small 

**Expected behavior**
no deprecation warning after update

**Screenshots**
![future-warning](https://user-images.githubusercontent.com/3694565/127292692-e7187114-e282-43bf-a5f8-658a5a423db2.png)

**Desktop (please complete the following information):**
Ubuntu

**Comment by mistel1225** [comment]
same issue, and causing the program shut down eventually.
