### ISSUE TITLE
Using CPU instead of GPU

### ISSUE THREAD

**Issue by alelasantillan** [ThilinaRajapakse/simpletransformers#122]
I don't have CUDA, but use_cuda=True by default.
How can I change to False in order to use only my CPU?

**Comment by ThilinaRajapakse** [comment]
Pass in `use_cuda=False` when creating any model.

E.g:

`model = ClassificationModel('bert', 'bert-base-cased', use_cuda=False)`

Please note that Transformer models are far too big to be trained on CPUs generally. You might be better served using Google Colab.

**Comment by alelasantillan** [comment]
Thank you! worked like a charm!

**Comment by tyomik-mnemonic** [comment]
@ThilinaRajapakse  Hi! Can I choose num of core, when use_cuda = False?
