### ISSUE TITLE
[Question] Do I need CUDA support on prod?

### ISSUE THREAD

**Issue by slusarczyk41** [ThilinaRajapakse/simpletransformers#1222]
If I train a model with CUDA enabled and then deploy it on some other server, do I need to have there a GPU or CUDA supported? Just to load the model and call predict()

**Comment by Zhylkaaa** [comment]
No, just specify `use_cuda=False` while initialising model, and that's all.
Also you may want to look at quantisation or onnx arguments, because fp16 is not available on CPU, so u may want to make your model faster and more memory efficient in some other way.
