### ISSUE TITLE
Simpletransformers not using all the data for training

### ISSUE THREAD

**Issue by biggestanticlimax** [ThilinaRajapakse/simpletransformers#1223]
**Describe the bug**
When running the example code for multilabel classification from simpletransformers.ai on google colab, the model is not using all the data. It is only using 1/3 rows of data. The same thing happens with binary classification where not all the data is being used.

**To Reproduce**
I copied and pasted the code from the example here:
https://simpletransformers.ai/docs/multi-label-classification/ 

**Expected behavior**
I was expecting all the data to be used so that it would say 3/3 not 1/3

**Screenshots**
![colab error](https://user-images.githubusercontent.com/67701113/128260401-92dc3b2d-b8a5-46ba-b5a1-4027010a5171.png)

**Desktop (please complete the following information):**
 - OS- Google Colab

**Comment by IS5882** [comment]
@biggestanticlimax  did you figure out the reason ? I am facing the same problem

**Comment by biggestanticlimax** [comment]
Hi, I was able to get past it by setting the model argument: 

sliding_window=True

example:
model_args = MultiLabelClassificationArgs(num_train_epochs=1, sliding_window=True)

But then there might be another error after that I haven't figured out yet
