### ISSUE TITLE
Wandb graphs not updating on ui

### ISSUE THREAD

**Issue by ameyagokhale014** [ThilinaRajapakse/simpletransformers#1225]
I connected my Simple transformers project with Wandb and would like to see realtime trainging metrics on the UI. This is the way i have setup the classification model - 

 model_args = {"num_train_epochs": config["epochs"],
                            "save_eval_checkpoints": False, "save_steps": False,
                                "learning_rate": config["learning_rate"],"config": layer_config,
                                "train_batch_size": config["batchsize"],"eval_batch_size": config["batchsize"],
                            "overwrite_output_dir" : True, "fp16": True, "n_gpu": config["n_gpu"], "wandb_project": "testing_project", "wandb_kwargs" : {'entity': 'xxx'}}                   

model = ClassificationModel(
                                config["modelName"],
                                config["modelSubName"],
                                num_labels=config["num_classes"],
                                args=model_args, use_cuda=False)

<img width="1677" alt="Screen Shot 2021-08-04 at 6 05 53 PM" src="https://user-images.githubusercontent.com/33142900/128275121-96ab4674-fb37-438c-abb3-b1da2452cc22.png">

**Comment by Zhylkaaa** [comment]
meybe you need to specify `evaluate_during_training_steps` argument. Default is 2000 so it can take some time to reach the point where you will evaluate aseptically on cpu. (Is `use_cuda=False` is conscious decision or just configuration error? setting this to False make your model train on cpu, so for most bert models it will take insane amount of time)
