### ISSUE TITLE
Error when loading saved model - ModuleNotFoundError: No module named 'transformers.configuration_bert'

### ISSUE THREAD

**Issue by Rebero** [ThilinaRajapakse/simpletransformers#1227]
When trying to reload a model, that I  trained before with simpletransformers, I am getting an error message: ModuleNotFoundError: No module named 'transformers.configuration_bert'. Trying to import the module manually isn't resolving the issue unfortunately. I saved the model with "torch.save(model, PATH)".

I am using the same conda environment as when I trained the model. The same error persists also when trying to replicate the same on Colab rather than my local machine.

<img width="1229" alt="Screen Shot 2021-08-05 at 16 15 15" src="https://user-images.githubusercontent.com/1615237/128365529-2df79a99-dea8-4a04-a238-2e62705b8d4b.png">

- Ubuntu 20.04
- python = "3.8.5"
- torch = "^1.7.1"
- wandb = "^0.10.13"
- pandas = "^1.2.0"
- numpy = "^1.19.5"
- simpletransformers = "^0.51.16"

Thank you for your help resolving the issue.

**Comment by Franck-Dernoncourt** [comment]
> I am using the same conda environment as when I trained the model

Are you also using the same `transformers` version?

**Comment by Rebero** [comment]
@Franck-Dernoncourt thanks! Trying different transformer versions resolved the issue. Ideally the correct transformers version would be installed alongside simpletransformers automatically.

**Comment by jiluojiluo** [comment]
yes,please do this:
pip uninstall transformers
pip install transformers --user
