### ISSUE TITLE
generate.py - cannot generate more than one sequence 

### ISSUE THREAD

**Issue by GenTxt** [ThilinaRajapakse/simpletransformers#1242]
In 'generate.py' have line:

model = LanguageGenerationModel("gpt2", "models/gpt2-xl", args={"max_length": 100, "top_p": 0.9, "temperature": 0.09, "num_return_sequences": 10}

Unfortunately it only generates a single sequence. Doesn't matter which number used. 

Also changed value in config/model_args.py :

    model_class: str = "LanguageGenerationModel"
    do_sample: bool = True
    early_stopping: bool = True
    evaluate_generated_text: bool = False
    length_penalty: float = 2.0
    max_length: int = 20
    max_steps: int = -1
    num_beams: int = 1
    num_return_sequences: int = 10 #1
    etc.

  Same result. All other parameter values can be changed. Am I missing something here?

  Using python3.7 and ubuntu18.04

**Comment by ELELUABDULSALAM** [comment]
Is there any update on the issue team
