### ISSUE TITLE
eval_mode predictions

### ISSUE THREAD

**Issue by FahriBilici** [ThilinaRajapakse/simpletransformers#1245]
Hello, i need to get classification prediction of my test_df. if i use eval_model it only returns wrong predictions but i need predictions of each text in my dataframe. if i use predict in for loop it takes long time. how can i get predictions in eval_model?

**Comment by anaconda121** [comment]
I'm also wondering this as well. If someone could please answer, that would be great!

**Comment by anaconda121** [comment]
@FahriBilici Have you found a solution?

**Comment by FahriBilici** [comment]
I found. I can give mu test set as a list to prediction function. Problem solved for me.

**Comment by anaconda121** [comment]
@FahriBilici Just to clarify, you fed the prediction function a list of your sequences that were part of your held out test set?
