### ISSUE TITLE
Bert Onnx value error Model requires 3 inputs. Input Feed contains 2

### ISSUE THREAD

**Issue by FahriBilici** [ThilinaRajapakse/simpletransformers#1257]
Hello, I am following doc but in bert but i am taking error on prediction. model loading without problem.

`model = ClassificationModel("bert","onnx",onnx_execution_provider="CPUExecutionProvider")`
`model.predict(['test])`

**Comment by hkaraoguz** [comment]
I have the same problem too.

**Comment by kongyurui** [comment]
I believe the pull request at https://github.com/ThilinaRajapakse/simpletransformers/pull/1220 will fix this problem.
