### ISSUE TITLE
Is there any way we can change the num_of_layers in classifier.weights and classifier.base.

### ISSUE THREAD

**Issue by hiiamsid** [ThilinaRajapakse/simpletransformers#1260]
**Describe the bug**
I am trying to use pretrained multi-class classification model(say 5 classes) for binary classification(i.e. 2 classes) without any modification. It is  giving : 
```
RuntimeError: Error(s) in loading state_dict for BertForSequenceClassification:
	size mismatch for classifier.weight: copying a param with shape torch.Size([5, 768]) from checkpoint, the shape in current model is torch.Size([2, 768]).
	size mismatch for classifier.bias: copying a param with shape torch.Size([5]) from checkpoint, the shape in current model is torch.Size([2]). 

```
**To Reproduce**
```

model_save_path = "/content/drive/MyDrive/ticket_suggestion/model_nlptown"

model_args = ClassificationArgs(
        do_lower_case=True,
        num_train_epochs=4,
        output_dir=model_save_path,
        best_model_dir=model_save_path + "/best_model",
        train_batch_size=4,
        eval_batch_size=8,
        evaluate_during_training=True,
        evaluate_during_training_steps=40,
        save_model_every_epoch=False,
        save_eval_checkpoints=False,
        save_steps=-1,
        overwrite_output_dir=True,
        manual_seed=42,
        fp16=False,
        use_multiprocessing=False,
        labels_list=["ticket_no", "ticket_yes"]
    )


model = ClassificationModel('bert', "nlptown/bert-base-multilingual-uncased-sentiment", num_labels=2,
                                use_cuda=torch.cuda.is_available(), args=model_args)
start_time = time.time()
model.train_model(traindf, eval_df=validdf)
print("time taken to load the model is %s", str(time.time()-start_time))
```

**Desktop (please complete the following information):**
 - Ubuntu

**Comment by ThilinaRajapakse** [comment]
That is not possible. The original classification layer has 5 outputs and your model should have the same shape - otherwise, you can't load the model. Which is what this error is saying.

A workaround would be to just use the model with the 5 classes but add a post-processing step to remove the other labels from the predictions. (or change them to one of the 2 labels you want).

**Comment by hiiamsid** [comment]
Thanks for the reply @ThilinaRajapakse. Actually while searching for the possible solutions i found out that transformers huggingface allows to change num_layers by first acquiring config of the pretrained model i.e. for e.g. 
`config = AutoConfig.from_pretrained(model_name)`

Then, 
`config.num_layers = 2`

Then loading model from config:
`model= AutoModel.from_config(config)`

So, as per your reply i think this is not possible in Simple Transformer. And as you said adding post-processing step can be helpful to remove other label. Can you please give me some hint how it can be done as i am new to transformers.
