### ISSUE TITLE
getting error while trainingAttributeError: 'float' object has no attribute 'strip'

### ISSUE THREAD

**Issue by ahujaravinder022** [ThilinaRajapakse/simpletransformers#127]
Hello
         I am getting this error while executing the line. I have data set containing two columns only. one is float type another is comments(Text)
model.train_model(train_df) on my data set.

AttributeError: 'float' object has no attribute 'strip'

**Comment by ThilinaRajapakse** [comment]
Please check whether there are any values in the text column which contain only numbers. These could be interpreted as floats rather than strings.

**Comment by ahujaravinder022** [comment]
Thanks.... Its working now...

**Comment by kinoute** [comment]
I'm getting this error as well now. I tried different Pandas functions to find text with only numbers but no luck. Is there a way to enforce the column to be interpreted as string?

**Comment by kinoute** [comment]
Nevermind, found two empty rows..
