### ISSUE TITLE
Multi-Label Classification

### ISSUE THREAD

**Issue by XFR1998** [ThilinaRajapakse/simpletransformers#1277]
Hi,  my task is a multi-label classification, every data in my datasets has nums_label=6, but each class label has 4 levels of 0,1,2,3.
such as the following pic: 
![image](https://user-images.githubusercontent.com/65661019/135725989-cd59c344-501b-4f60-bb45-dcbd9586ec38.png)

However, "Multi-Label Classification" in simpletransformers only support class label has 0, 1 level. How can I use "Multi-Label Classification" in simpletransformers to finish my task? Thanks~

**Comment by XFR1998** [comment]
I know from the file: multi_label_classification_model.py and classification_model.py, 
![image](https://user-images.githubusercontent.com/65661019/135726560-03072008-ef99-494f-8649-81b5e2f9a1be.png)
the predict function only return 0 or 1, it can not suport my task. how can I do?

**Comment by helloeng** [comment]
I have the same problem, has your problem been solved?
