### ISSUE TITLE
Use Python logging instead of print statements

### ISSUE THREAD

**Issue by todd-cook** [ThilinaRajapakse/simpletransformers#128]
**Describe the bug**
A clear and concise description of what the bug is. Please specify the class causing the issue.
While running inference, the code outputs text that is not useful and is annoying. Inspection of the code reveals many print statements. Print statements can only be turned off by redirecting standard out, which has side effects; better is to use python logging as then users can programmatically adjust the logging levels.

**To Reproduce**
Run inference on using the Question Answer model.

**Comment by flaviussn** [comment]
Why logging was reverted to print statements? @ThilinaRajapakse

**Comment by ThilinaRajapakse** [comment]
Mainly because of #135 

It looks like the PR replaced all `print` statements with `logger.info` leading to bugs when print options were used.
