### ISSUE TITLE
ValueError: too many values to unpack (expected 2) when using eval_df

### ISSUE THREAD

**Issue by FahriBilici** [ThilinaRajapakse/simpletransformers#1286]
Hello, I create the model with this code:
`model = ClassificationModel(
    "bert", "dbmdz/bert-base-turkish-uncased",use_cuda=cuda_available,num_labels=num_labels,args={'reprocess_input_data': True, 'overwrite_output_dir': True
                                                                                         , 'num_train_epochs': 2,"evaluate_during_training":True,
                                                                                        "evaluate_each_epoch":True,"save_best_model":True,
                                                                                        "save_model_every_epoch":True,"best_model_dir":"best_bert/"}
)`

then I call train_model function like this:
`model.train_model(train_df,eval_df=eval_df)`

but after first epoch it return to me too many values to unpack (expected 2) error on here
`ValueError                                Traceback (most recent call last)
<ipython-input-28-ab826287928d> in <module>
----> 1 model.train_model(train_df,eval_df=eval_df)

~/.conda/envs/sentiment/lib/python3.6/site-packages/simpletransformers/classification/classification_model.py in train_model(self, train_df, multi_label, output_dir, show_running_loss, args, eval_df, verbose, **kwargs)
    610             eval_df=eval_df,
    611             verbose=verbose,
--> 612             **kwargs,
    613         )
    614 

~/.conda/envs/sentiment/lib/python3.6/site-packages/simpletransformers/classification/classification_model.py in train(self, train_dataloader, output_dir, multi_label, show_running_loss, eval_df, test_df, verbose, **kwargs)
   1180 
   1181                 for key, value in flatten_results(
-> 1182                     self._get_last_metrics(training_progress_scores)
   1183                 ):
   1184                     try:

ValueError: too many values to unpack (expected 2)
`

How can I solve this?

**Comment by b-kaufman** [comment]
In fact elsewhere in the code the .items() is present for example:
https://github.com/ThilinaRajapakse/simpletransformers/blob/8859e3a9e30900f1575509c7a7a6eb3ddece6cef/simpletransformers/ner/ner_model.py#L1031-L1041
so this seems like a quick fix.

**Comment by s3766882** [comment]
It looks like the same issue with this one
https://github.com/ThilinaRajapakse/simpletransformers/issues/105

**Comment by kamalravi** [comment]
> > Hello, I create the model with this code: `model = ClassificationModel( "bert", "dbmdz/bert-base-turkish-uncased",use_cuda=cuda_available,num_labels=num_labels,args={'reprocess_input_data': True, 'overwrite_output_dir': True , 'num_train_epochs': 2,"evaluate_during_training":True, "evaluate_each_epoch":True,"save_best_model":True, "save_model_every_epoch":True,"best_model_dir":"best_bert/"} )`
> > then I call train_model function like this: `model.train_model(train_df,eval_df=eval_df)`
> > but after first epoch it return to me too many values to unpack (expected 2) error on here `ValueError Traceback (most recent call last) in ----> 1 model.train_model(train_df,eval_df=eval_df)
> > ~/.conda/envs/sentiment/lib/python3.6/site-packages/simpletransformers/classification/classification_model.py in train_model(self, train_df, multi_label, output_dir, show_running_loss, args, eval_df, verbose, **kwargs) 610 eval_df=eval_df, 611 verbose=verbose, --> 612 **kwargs, 613 ) 614
> > ~/.conda/envs/sentiment/lib/python3.6/site-packages/simpletransformers/classification/classification_model.py in train(self, train_dataloader, output_dir, multi_label, show_running_loss, eval_df, test_df, verbose, **kwargs) 1180 1181 for key, value in flatten_results( -> 1182 self._get_last_metrics(training_progress_scores) 1183 ): 1184 try:
> > ValueError: too many values to unpack (expected 2) `
> > How can I solve this?
> 
> version 0.60.0 is working correctly :)

I am using Version: 0.62.2. The issue still persists.

**Comment by moyan007** [comment]
So，How to solve this problem for the classification task？I meet the same bug when doing like this “model.train_model(tra, eval_df=val)”

**Comment by ThilinaRajapakse** [comment]
This should be fixed now in the latest version (`0.62.4`)
