### ISSUE TITLE
[Question] Is it possible to save simpletransformers models in MLFlow?

### ISSUE THREAD

**Issue by baymears** [ThilinaRajapakse/simpletransformers#1287]
Hi all, I've been attempting to save simpletransformers ClassificationModel to an MLFlow server today without much luck. I was wondering if anyone has done this or knows a neat way to do it?

**Comment by skshahidur** [comment]
You need a wrapper for this. The MLFlow guide mentions it [here](https://www.mlflow.org/docs/latest/models.html#example-saving-an-xgboost-model-in-mlflow-format). 

Follow the steps as in the example and your code will work.
    1. Create a model using simpletransformers' ClassificationModel and save it in local.
    2. Create a wrapper class including `load_context()` and `predict()` methods. You can add more methods if required.
    3. Use `mlflow.pyfunc.save_model()` from MLFlow to save it locally. This step is extra compared to the example link. This convert the model artifacts to the format MLFlow requires.
    4. Now you can use `mlflow.pyfunc.log_model()` to log in your registry. 
    
Code for 4th step is,
    
```python
conda_env = {
    'channels': ['defaults'],
    'dependencies': [
      'python=3.8',
      'pip',
        {
            'pip': [
                'mlflow',
                'simpletransformer==0.62.2',
                'cloudpickle==2.0.0',
            ],
        },
    ],
    'name': 'cm_env'
}

mlflow.pyfunc.log_model(
    artifact_path=f"{your_path_where_you_saved_at_step_3}/",
    python_model=YourWrapper(),
    conda_env=conda_env,
    registered_model_name="<Your_model_registry_name>"
)
```
I hope this helps @baymears

**Comment by kskarakostas** [comment]
Hi, 
@skshahidur nice approach although it seems to me that it is kind of workaround with a significant detour.

How about create a custom callback function?

To be honest I am not able to find a way to add callback on trainer but if this is possible I would be more than happy to contribute and add that extra feature.
