### ISSUE TITLE
CPU mode for prediction not possible to choose number of cores to use

### ISSUE THREAD

**Issue by oriolcmp** [ThilinaRajapakse/simpletransformers#1290]
**Describe the bug**
We are using *ConvAIModel* to create  a chatbot. We train the model in a GPU machine but once we have the model, for prediction we need to run it in a machine that do not have GPUs. We are monitoring the machine which has 8 CPUs and we see that the method interact_single when it runs only takes 4 CPUs. We don't see any documentation explaining how the number of CPUs is chosen or how to increase them.

**Expected behavior**
I think it should be documented how the number of CPUs is chosen or provide a way to choose the number of CPUs to use

**Desktop (please complete the following information):**
 - Linux

**Comment by ThilinaRajapakse** [comment]
This is not implemented for the `ConvAIModel` but you can set it with `torch.set_num_threads(N_CPUS)`
