### ISSUE TITLE
Retraining previously trained model with new data

### ISSUE THREAD

**Issue by Roosh27** [ThilinaRajapakse/simpletransformers#1293]
Hi Team,

I am using simpletransformers (roberta) for text classification. I have trained the model on a set of data for 6 classes and it is performing well. I want to know if there is any way that I can use this trained model with a separate dataset to train for 2 new classes? At last, I want a model which can classify 8 classes but I dont want to train the model again on the whole data. 

Is it possible or if you can give some suggestions on this??

**Comment by ThilinaRajapakse** [comment]
Technically, you can. But, I'm not sure how well it would work. To do it, you should load the model trained on the first dataset when training on the second dataset. E.g.:

```python
model = ClassificationModel("roberta", "<path_to_trained_model>"
```
