### ISSUE TITLE
Load a checkpoint after training

### ISSUE THREAD

**Issue by AliOsm** [ThilinaRajapakse/simpletransformers#13]
Is there a way to load the checkpoint after training the model? I looked into the code and I didn't find anything.

**Comment by ThilinaRajapakse** [comment]
`model = TransformerModel('roberta', '<path_to_model>')`

It should have been clearer in the readme. Updated it now.

**Comment by AliOsm** [comment]
Thanks, I will try it.

**Comment by AliOsm** [comment]
It works fine with me, but I changed two things:
1- The path should point to the folder contains the model file not the `.bin` file itself, `output_dir/` not `output_dir/pytorch_model.bin`.
2- The model should be moved to the GPU manually like this `model.model.to(model.device)`.

**Comment by ThilinaRajapakse** [comment]
Yes, it should be the directory and not the file itself. The docs were ambiguous on that, but it should be clear now.

The model gets moved to device when you train or evaluate, but it was missing in the predict method. Added that as well.

**Comment by AliOsm** [comment]
It works fine now, thanks!

**Comment by ThilinaRajapakse** [comment]
Awesome!

**Comment by sarim-zafar** [comment]
I get the following error when I try to load after training
`Model` name 'outputs/checkpoint-2000/' was not found in tokenizers model name list (distilbert-base-uncased, distilbert-base-uncased-distilled-squad). We assumed 'outputs/checkpoint-2000/' was a path or url to a directory containing vocabulary files named ['vocab.txt'] but couldn't find such vocabulary files at this path or url.`

Following is the command
`model = TransformerModel('distilbert', 'outputs/checkpoint-2000/',num_labels=len(le.classes_)
                         ,use_cuda=True,args={'fp16':False,
                                               'max_seq_length': 256,
                                              'train_batch_size': 16,
                                              'reprocess_input_data': True,
                                               'overwrite_output_dir': True
                                              }`

**Comment by ThilinaRajapakse** [comment]
The checkpoints aren't saving the tokenizer files. I'll fix this later today. For now, you can copy the missing files from the final output.

![image](https://user-images.githubusercontent.com/17320131/67179849-5c255b80-f3f5-11e9-8f69-b38248e9d8a4.png)

These are the files you need.
