### ISSUE TITLE
assertion Error len(label_ids) != max_seq_length

### ISSUE THREAD

**Issue by mezanass** [ThilinaRajapakse/simpletransformers#130]
when trying NER with "bert-base-uncased" i get this error 

> /usr/local/lib/python3.6/dist-packages/simpletransformers/ner/ner_utils.py in convert_example_to_feature()

    161     assert len(input_mask) == max_seq_length
    162     assert len(segment_ids) == max_seq_length
--> 163     assert len(label_ids) == max_seq_length
    164 
    165     return InputFeatures(

AssertionError: 

>

**Comment by alexander131313** [comment]
I got the same error and in my case it was caused by my data having leading spaces on few lines and some lines with just a space and a tag.  You could check for that with something like: train_data = [line for line in train_data if len(line.split()) == 2]

**Comment by mezanass** [comment]
thanks @alexander131313 I hade some weird characters in my data like \x97
