### ISSUE TITLE
About padding and truncation

### ISSUE THREAD

**Issue by Lpn-98** [ThilinaRajapakse/simpletransformers#1304]
Hi, I saw in the simpletransformers/classification/classification_model.py there is a function named 'preprocess_data_multiprocessing' , there is truncation and padding, but it seems not be used in bert model?

I am not sure whether the bert model has 'add_special_token', 'max_length',  'pad_to_max_length' , 'truncation', can someone give me any advice? Very thanks.

Here is the part of function preprocess_data_multiprocessing:
```

def preprocess_data_multiprocessing(data):
    text_a, text_b, tokenizer, max_seq_length = data

    examples = tokenizer(
        text=text_a,
        text_pair=text_b,
        max_length=max_seq_length,
        truncation=True,
        padding="max_length",
        return_tensors="pt",
    )

    return examples
```

**Comment by ThilinaRajapakse** [comment]
I am not sure I understand what you mean. All models have truncation/padding.
