### ISSUE TITLE
Can you please guide me how i can pretrain T5 from scratch using this library?

### ISSUE THREAD

**Issue by shaileshj2803** [ThilinaRajapakse/simpletransformers#1307]
**Describe the bug**
I would like to pretrain T5 from scratch on my dataset on GPU. I am not sure how to proceed with this library. Any help would be appreciated.

Thanks

**Comment by ELELUABDULSALAM** [comment]
https://www.youtube.com/watch?v=MQdniwKmJnE&t=352s

check this out

**Comment by ThilinaRajapakse** [comment]
You can't pretrain T5 from scratch with Simple Transformers. In fact, you can't pretrain T5 with any library unless you have access to insane amounts of compute resources on par with Google.
