### ISSUE TITLE
Support for T5 model

### ISSUE THREAD

**Issue by AliOsm** [ThilinaRajapakse/simpletransformers#131]
Hello,

When you are planning to support [T5](https://arxiv.org/abs/1910.10683) model for text classification and other tasks?

Thanks!

**Comment by ThilinaRajapakse** [comment]
I have the classes implemented for creating the T5 model as well as data preparation/conversion stuff. I'm a little stuck on the decoding part though. I'm not sure how they've implemented it. I looked at the Google implementation but it's in Tensorflow and seems to be written only for TPUs (also uses a _lot_ of internal functions from Tensorflow). It's tough for me to follow as I'm not well versed in TF and I haven't had the time to really dive deep into it.

To answer your question, I can support it as soon as Hugging Face releases a working example using it. Other than that, I'm afraid I can't say for sure.
