### ISSUE TITLE
Still getting "mismatch for classifier.weight and classifier.bias" error after providing model_args.labels_list to NER model

### ISSUE THREAD

**Issue by ShaidaMuhammad** [ThilinaRajapakse/simpletransformers#1310]
I'm fine-tuning a BERT model for Named Entity Recognition with a custom **dataset having 13 entities**.
I provided the labels to the model via `model_args.labels_list` but still I get the following error.

```
RuntimeError: Error(s) in loading state_dict for BertForTokenClassification:
	size mismatch for classifier.weight: copying a param with shape torch.Size([9, 768]) from checkpoint, the shape in current model is torch.Size([13, 768]).
	size mismatch for classifier.bias: copying a param with shape torch.Size([9]) from checkpoint, the shape in current model is torch.Size([13]).
```
There is no option of `model_args.num_labels` in NER model args. So I can't specify it either. Is it a bug or what should be the possible solution?

**Comment by whr778** [comment]
I had this happen when I set the label list incorrectly as opposed to
loading the label list from the model config json file.  If you explicitly
set the labels in the config to an empty list it should load the labels
correctly from the model_config.json file.

Bill
