### ISSUE TITLE
Inference without using multiprocessing.Pool 

### ISSUE THREAD

**Issue by bafonso** [ThilinaRajapakse/simpletransformers#1317]
**Is your feature request related to a problem? Please describe.**
Currently multiprocessing prevents from running simpletransformers on AWS Lambda functions 

**Describe the solution you'd like**
Not using Pool for inference

**Describe alternatives you've considered**
Using an alternative multiprocessing.Pool, requiring maintaining a parallel version or either simpletransfomers  or multiprocessing.

**Additional context**
https://stackoverflow.com/questions/34005930/multiprocessing-semlock-is-not-implemented-when-running-on-aws-lambda

**Comment by ThilinaRajapakse** [comment]
You can set `use_multiprocessing` to False to disable multiprocessing.

**Comment by bafonso** [comment]
> You can set `use_multiprocessing` to False to disable multiprocessing.

I was indeed setting that but it wasn't working the way I expected. Upon further inspection, I wonder if maybe I have run into a bug. I have two models, one has:

```
    "use_multiprocessing": false,
    "use_multiprocessing_for_evaluation": false,
```

the other has:

```     
"use_multiprocessing": true,
"use_multiprocessing_for_evaluation": true,
```

I am loading the models using 
```
    model = MultiLabelClassificationModel(
        model_type,
        model_foldername,
        num_labels=num_labels,
        use_cuda=cuda_available,
        args=model_args,
    )
```

If I use this approach to generate model_args, the flags do not appear to make it to the model's config

```
model_args = ClassificationArgs(
    use_multiprocessing=False, use_multiprocessing_for_evaluation=False
)
```

but this does:

```
    model_args = {
        'use_multiprocessing':False, 
        'use_multiprocessing_for_evaluation':False
    }
```
