### ISSUE TITLE
Model not training on whole data (As shown in brackets under epochs bar)

### ISSUE THREAD

**Issue by IS5882** [ThilinaRajapakse/simpletransformers#1329]
**Describe the bug**

My data has 1751 sentences however when training a number appears under the epochs bars. Sometimes it is 1751 which makes sense it's the number of sentences I have, but most of the times it's 50% the number of data (sentences I have as shown in the figure below).

I tried to look in the documentation to understand if the number should be the same as my training set size but I couldn't find an answer.

**To Reproduce**
Just train the model and check the number shown after the brackets.

**Expected behavior**
Number shown in brackets should match my dataset size.

**Screenshots**
![image](https://user-images.githubusercontent.com/47028011/147410265-c0c7fb7a-4dc6-4d13-bda6-066887bd2708.png)

![image](https://user-images.githubusercontent.com/47028011/147410250-b01b9619-be4f-4a27-b543-e0257cfbf222.png)

![image](https://user-images.githubusercontent.com/47028011/147410064-4ae15d7b-856d-4859-8b83-03fd781f5b90.png)

**Desktop (please complete the following information):**
 Kaggle GPU backend

**Additional context**

**Comment by whr778** [comment]
Injy,

What's your batch size?  You should be seeing the number of batches being
processed.  If batch size if 1 then it will be equal to the number of
sentences, if it's 8, then number of sentences / 8.

E.g. 1751÷8 = 218.875.  The first 218 batches are full with 8 sentences
each batch... there are less items in the last batch so the rounded up
number of 219 is the correct number of batches.

Bill

**Comment by IS5882** [comment]
> Injy, What's your batch size? You should be seeing the number of batches being processed. If batch size if 1 then it will be equal to the number of sentences, if it's 8, then number of sentences / 8. E.g. 1751÷8 = 218.875. The first 218 batches are full with 8 sentences each batch... there are less items in the last batch so the rounded up number of 219 is the correct number of batches. Bill

Hello Bill, Thanks for your reply! Yes, I am using the default settings so batch size =8 and 218 beside each epoch makes sense but my main concern was the number below the epochs bar at the very end **(876,0.049)**  (which is batch size * # of epochs) , it made uncertain that it is actually training on the whole data, do you have any ideas regarding that or is it just # of epochs * batch size and it is indeed training on the whole 1751 sentences?

**Comment by whr778** [comment]
Injy,

1751÷8 = 218.875 <== Round this up to 219

Where 219 batches and 4 epochs
Sure 219*4 = 876

The very last batch has 7 sentences 7/8 = .875  It's still a batch even if
it has less than 8 so you should be using 219 for the number of batches not
218.

Bill
