### ISSUE TITLE
BERT Model returning error that not enough compute resources for trivial predict task

### ISSUE THREAD

**Issue by anaconda121** [ThilinaRajapakse/simpletransformers#1330]
**Describe the bug**
Using BERT Model to predict on text (NOT TRAINING).  When I run my predict code, I get an error saying that my computer does not have enough cores to run the predict process. This doesn't make much sense to me since I have already trained the model and predicting on sequences should not require much compute power. 

**To Reproduce**
Using sensitive data so cannot share code. 

**Expected behavior**
Model should run a give me an output.

**Screenshots**
![image](https://user-images.githubusercontent.com/38384138/147523696-385f9bbf-c8b8-49ad-9919-90873ecbddb9.png)

**Desktop (please complete the following information):**
Windows 10 PRO, Lenovo 64 bit PC
![image](https://user-images.githubusercontent.com/38384138/147523804-c0e22c53-2b3a-4a1b-9163-81212dfe1457.png)

**Comment by anaconda121** [comment]
Thanks in advance!!!!

**Comment by ThilinaRajapakse** [comment]
Try predicting with multiprocessing off (`model_args.use_multiprocessing = False`).

**Comment by anaconda121** [comment]
Thank you so much! That worked!
