### ISSUE TITLE
Add evaluation for epochs

### ISSUE THREAD

**Issue by zexuan-zhou** [ThilinaRajapakse/simpletransformers#134]
First of all. It's a great repo. Thanks for the contribution.

Is it possible to add evaluation for specified epochs?
Like, in the model args

```
{'eval_epochs': True, 'eval_every_epochs': 1}
```

**Comment by ThilinaRajapakse** [comment]
You are welcome!

It's possible but I'm a little wary about adding more configuration options to the `args` dict. I feel like it's blowing up a little too much. You can, however, set the `evaluate_during_training_steps` to be the same as (or a factor of) the number of steps per epoch to get the same effect.

**Comment by kinoute** [comment]
@ThilinaRajapakse So If I understood well, when you added the `global_step` column to the CSV results file instead of `checkpoints`, you didn't add the evaluation of each epoch as well? I was pretty sure it was the case when I tested it, weird. Now that I'm looking at my last training, I, indeed, don't see the epoch evaluation results in the csv file.

**Comment by zexuan-zhou** [comment]
@ThilinaRajapakse Yes I did that and that works. I wasn't aware of that when I wrote this issue. Thanks!

**Comment by ThilinaRajapakse** [comment]
@kinoute I didn't add the epoch evaluations. But I suppose there's no harm in adding them as well.

**Comment by kinoute** [comment]
@ThilinaRajapakse I think I found the issue. When `sliding_window` is set to False, the evaluation that happens at the end of every epoch (the eval_results.txt in epoch-X folder) is added to the CSV file.

When `sliding_window` is to True, it doesn't seem to happen.

**Comment by ThilinaRajapakse** [comment]
Thanks. I'll look into this.

**Comment by kinoute** [comment]
@ThilinaRajapakse nice addition. It would be nice to find a way to distinguish a global_step from a checkpoint than from an epoch. I run a training for 1 epoch with checkpoints every 50 steps. Up to 350, I got "checkpoint-x" folders. The epoch evaluation was then stored in the "epoch-1" folder.

But in the CSV file, the epoch 1 evaluation is stored with a global_step of 364. If it's the best checkpoint. It's kind of misleading. Either we could add a epoch column, either we could simply remove the "epoch-x" format and use checkpoint-x instead for epochs.

**Comment by ThilinaRajapakse** [comment]
Good point. I don't want to add a separate epoch column as it's likely to cause issues with mismatched numbers of fields in checkpoint rows Vs epoch rows.

I don't want to remove the "epoch-x" format as it may be important to know which checkpoints are end of epochs.

Maybe the simplest solution would be to be use "checkpoint-x-epoch-x" name for epoch checkpoints.

**Comment by kinoute** [comment]
Good idea! Epoch-x-checkpoint-y might be more readable.

**Comment by kinoute** [comment]
@ThilinaRajapakse Good job. Sorry, I got confused in my last message. I thought you were going to change all the checkpoint folders format. But nevermind, it's perfect now. Cheers.

**Comment by ThilinaRajapakse** [comment]
Great!

**Comment by ThilinaRajapakse** [comment]
@all-contributors please add @kinoute  for question

**Comment by ThilinaRajapakse** [comment]
@all-contributors please add @kinoute  for ideas
