### ISSUE TITLE
BUG? _log() got an unexpected keyword argument 'end'

### ISSUE THREAD

**Issue by zexuan-zhou** [ThilinaRajapakse/simpletransformers#135]
```
Traceback (most recent call last):                                                      | 0/949 [00:00<?, ?it/s]
  File "train_bert.py", line 105, in <module>
    main()
  File "train_bert.py", line 95, in main
    model.train_model(train_df=df_train)
  File "/opt/conda/lib/python3.6/site-packages/simpletransformers/classification/classification_model.py", line 219, in train_model
    global_step, tr_loss = self.train(train_dataset, output_dir, multi_label=multi_label, show_running_loss=show_running_loss, eval_df=eval_df, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/simpletransformers/classification/classification_model.py", line 330, in train
    logger.info("\rRunning loss: %f\n" % loss, end="")
  File "/opt/conda/lib/python3.6/logging/__init__.py", line 1307, in info
    self._log(INFO, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'end'
```
Looks like switching from `print` to `logging` is causing this issue

**Comment by senthilmk** [comment]
+1

**Comment by kinoute** [comment]
Yeah same here. I'm trying to get the training logs back but no luck.

**Comment by zexuan-zhou** [comment]
Current solution is to install the old version `pip install simpletransformers==0.16.1`

**Comment by ThilinaRajapakse** [comment]
I changed it back to prints as logging was weirding out on me as well. I'll look into this.

**Comment by todd-cook** [comment]
Can we please follow best practices? 
see: https://docs.python.org/3/howto/logging.html#library-config

logging.info()... is bad form, not recommended, should actually declare a Logger instance.
This is a library, if folks want info from it, they should initialize a logger:
import logging
logging.basicConfig(level=logging.DEBUG)

**Comment by kinoute** [comment]
@todd-cook That's what I was doing after the PR with `logging` was merged. The library wasn't working correctly afterwards. Give it some time and I'm sure @ThilinaRajapakse will implement it nicely.

**Comment by todd-cook** [comment]
@ThilinaRajapakse let me know if you want me to take a stab at this.

**Comment by ThilinaRajapakse** [comment]
It's fine, I'll look into it. Thanks guys.
