### ISSUE TITLE
Running and eval loss are `nan` when using multilingual t5 model (e.g. google/mt5-small).

### ISSUE THREAD

**Issue by pashok3d** [ThilinaRajapakse/simpletransformers#1359]
**Describe the bug**
Running and eval loss are `nan` when using multilingual t5 model (e.g. google/mt5-small).
Setting model type to `mt5` doesn't solve the problem.

**To Reproduce**
Replace model name in [T5 Minimal Start](https://simpletransformers.ai/docs/t5-minimal-start/) from `t5-base` to `google/mt5-small`.
Setting model type to `mt5` doesn't solve the problem.

**Expected behavior**
While training `Running Loss` must be defined.

**Screenshots**
![image](https://user-images.githubusercontent.com/35535358/153428718-83c0cbc5-81bb-4cba-a53e-271337a23f1b.png)

**Desktop (please complete the following information):**
 - Google Colab

**Additional context**

**Comment by ArtanisTheOne** [comment]
This also shows up in training mt5-base, as returned loss shows nan in training progress

**Comment by JoeTseHot** [comment]
I also have the same problem with mT5.  Actually I cannot get the fine-tune task (translation between two languages) to work.  Is it just a display problem or it actually affects the fine-tuning?  Thanks!
