### ISSUE TITLE
The freeze supoport line can be ommitted 

### ISSUE THREAD

**Issue by blossom2016** [ThilinaRajapakse/simpletransformers#136]
**Describe the bug**
When i run the programs i get this error. for both the binary classification and multiclass clasifiction

**To Reproduce**

**Expected behavior**

**Screenshots**
![bbb](https://user-images.githubusercontent.com/25477729/72067680-a4ad3080-32e3-11ea-87fd-1766f1e61d42.PNG)
.

**Desktop (please complete the following information):**
 - Windows 10

**Additional context**
I am using pycharm

**Comment by ThilinaRajapakse** [comment]
This is most likely caused by Windows not playing nice with multiprocessing. Can you try turning it off and see if helps?

`model = ClassificationModel('bert', 'bert-base-cased', args={'use_multiprocessing': False})`

**Comment by blossom2016** [comment]
Thanks it worked
