### ISSUE TITLE
low gpu utilization on multiple gpu training

### ISSUE THREAD

**Issue by FahriBilici** [ThilinaRajapakse/simpletransformers#1377]
Hello, i am trying to fine tune a language modelling model with 8 gpu. But on the training gpu utilization levels are about %50 on just first gpu others are like %10. I made train_batch_size parameter to 256. What should I do for full utilization?

**Comment by ThilinaRajapakse** [comment]
Have you set `n_gpus=8`?

**Comment by FahriBilici** [comment]
> 

yeah i set

**Comment by apivadee** [comment]
I have got the same problem as @FahriBilici. 
Any solution to this issue?
