### ISSUE TITLE
Evaluation on eval_data gives nan when using multi GPUs

### ISSUE THREAD

**Issue by medmediani** [ThilinaRajapakse/simpletransformers#1378]
Traini Roberta from scratch on multi GPUs. 
The evaluation on eval_data gives nan. Whereas the same configuration gives correct results when training on a single GPU. 

In addition, I didn't see any speedup benifit from using multiple GPUs.

**Comment by ThilinaRajapakse** [comment]
Multi GPU training is currently implemented with PyTorch DataParallel. Unfortunately, this does seem to have some problems.
