### ISSUE TITLE
RunTime warning

### ISSUE THREAD

**Issue by blossom2016** [ThilinaRajapakse/simpletransformers#138]
I get this run time warning. I am using a windows PC, and pycharm to run the program. I do not understand what this means
![error2](https://user-images.githubusercontent.com/25477729/72211283-fcf15780-34c8-11ea-912b-205148693cb1.PNG)

![error](https://user-images.githubusercontent.com/25477729/72211269-c4517e00-34c8-11ea-932d-04731c66b165.PNG)

**Comment by ThilinaRajapakse** [comment]
If you get this when running the minimal examples, it's because they aren't real datasets. Calculating metrics can cause divisions by zero.

It won't happen with a real dataset.
