### ISSUE TITLE
Classification Model Training Hangs in Google Colab 

### ISSUE THREAD

**Issue by bpisaneschi** [ThilinaRajapakse/simpletransformers#1402]
After the most recent Python upgrade in colab (3.7.13 April 24,2022) the ClassificationModel training hangs.

Here is my code:
![Screen Shot 2022-05-03 at 11 36 43 AM](https://user-images.githubusercontent.com/65873432/166432597-a2d3192b-e3e3-45d8-bbfe-899a225a4b2d.png)

Here is what its doing:
![Screen Shot 2022-05-03 at 11 31 08 AM](https://user-images.githubusercontent.com/65873432/166431799-b0b1ff1d-9ff6-42bb-89e7-abc7b6a73a8f.png)

Ive waited a long time and nothing happens. This same cell worked perfectly fine before the upgrade.

**Comment by ThilinaRajapakse** [comment]
Try setting `use_multiprocessing = False` in the model args. That's usually the source of most problems with Colab.

**Comment by bpisaneschi** [comment]
That did it! Thank you.

**Comment by bpisaneschi** [comment]
For others with the same issue... In addition to 'use_multiprocessing': False, 'use_multiprocessing_for_evaluation' should also be added to args and set to False.

**Comment by SamCox822** [comment]
I am still getting an issue when I try to use the solution posed here. @ThilinaRajapakse , @bpisaneschi, am I incorrect in how I've implemented these things?

```
model = ClassificationModel(
    "roberta",
    "seyonec/ChemBERTa_zinc250k_v2_40k",
    num_labels=1,
    args={"num_train_epochs": 1, "regression": True, "use_multiprocessing" : False, "use_multiprocessing_for_evaluation": False},
    use_cuda=False
)
```

I get the following error now:
```
TypeError: __init__() got an unexpected keyword argument 'use_multiprocessing'
```

**Comment by Agrover112** [comment]
Oh I have been facing the same issue on Collab pro

**Comment by Agrover112** [comment]
> 

Ohh, exactly this is where I'm getting stuck. @ThilinaRajapakse  I believe this should be opened? And also what's the reason for the same issue?

**Comment by Agrover112** [comment]
> 

These are Model-Args


```python
model_args = ClassificationArgs(num_train_epochs=5,output_dir='outputs_roberta_synb_5/',optimizer='AdamW',use_multiprocessing=False,use_multiprocessing_for_evaluation=False)

model = ClassificationModel("roberta", "roberta-base",use_cuda=True,args=model_args)
````

**Comment by SamCox822** [comment]
@Agrover112 I have no idea why, but it just starting working for me. I don't think I changed anything... Maybe it is a version issue? (my code is here - https://dmol.pub/dl/pretraining.html#running-this-notebook)

**Comment by Agrover112** [comment]
> @Agrover112 I have no idea why, but it just starting working for me. I don't think I changed anything... Maybe it is a version issue? (my code is here - https://dmol.pub/dl/pretraining.html#running-this-notebook)

I'm using `0.63.9-py3-none-any.whl` version
