### ISSUE TITLE
Other community models from Hugging Face

### ISSUE THREAD

**Issue by siberio76** [ThilinaRajapakse/simpletransformers#141]
Hi... I was asking if simpletransformers supports all Higging Face supported models, including "Other community models". 
I need other models because I should performs some experiments in not English Language...

Thanks for you great work!

**Comment by ThilinaRajapakse** [comment]
You can find the supported models for each task in the readme. Any fine-tuned model based on those is supported. E.g: scibert is supported as it is a fine-tuned BERT model (and BERT models are supported).
