### ISSUE TITLE
RunTimeError when running sample code 

### ISSUE THREAD

**Issue by nobughhh** [ThilinaRajapakse/simpletransformers#1429]
When I run the binary_classification [sample code](https://github.com/whr778/simpletransformers/blob/master/examples/text_classification/binary_classification.py), there is always an error saying that:
```
File "multiprocessing\spawn.py", line 134, in _check_not_importing_main  raise RuntimeError(
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

I havn't changed anything in the sample code, so I don't why it can't run. I will be more than grateful if anybody can help! Thank you!

**Comment by luketudge** [comment]
Not absolutely certain, but this looks like a persistent bug with multiprocessing, already noted for example in #1375 . There is a workaround given [here](https://github.com/ThilinaRajapakse/simpletransformers/issues/1375#issuecomment-1107790951) for switching off multiprocessing. That might help if you need to get the examples working and do not need multiprocessing.
