### ISSUE TITLE
Load pre-trained model from private HuggingFace repo

### ISSUE THREAD

**Issue by rayenebech** [ThilinaRajapakse/simpletransformers#1437]
I am trying to load a model that I trained using `QuestionAnsweringModel` from `simpletransformers`. 
The model is now hosted on a  private repository in the HuggingFace hub.

 Using the normal transformers library I could load it by logging first into the console using `huggingface-cli login` command and then pass `use_auth_token=True`  as follows:
`model = RobertaForQuestionAnswering.from_pretrained(PRIVATE_REPO_PATH,use_auth_token= True)` 
 
Which does not work with the `QuestionAnsweringModel`. I tried  logging first into the console using `huggingface-cli login` command and then using this syntax:
`model = QuestionAnsweringModel("roberta",PRIVATE_REPO_PATH)`
but I get this error:
<img width="1345" alt="Screenshot 2022-07-20 at 17 56 01" src="https://user-images.githubusercontent.com/34574318/180028178-81284a3b-2767-4f5b-baa6-131ea301e1e3.png">
I am not sure where can I pass the  `use_auth_token=True` to the model? (not listed amongst the config parameters)

**Comment by carlcrede** [comment]
> I am trying to load a model that I trained using `QuestionAnsweringModel` from `simpletransformers`. The model is now hosted on a private repository in the HuggingFace hub.
> 
> Using the normal transformers library I could load it by logging first into the console using `huggingface-cli login` command and then pass `use_auth_token=True` as follows: `model = RobertaForQuestionAnswering.from_pretrained(PRIVATE_REPO_PATH,use_auth_token= True)`
> 
> Which does not work with the `QuestionAnsweringModel`. I tried logging first into the console using `huggingface-cli login` command and then using this syntax: `model = QuestionAnsweringModel("roberta",PRIVATE_REPO_PATH)` but I get this error: <img alt="Screenshot 2022-07-20 at 17 56 01" width="1345" src="https://user-images.githubusercontent.com/34574318/180028178-81284a3b-2767-4f5b-baa6-131ea301e1e3.png"> I am not sure where can I pass the `use_auth_token=True` to the model? (not listed amongst the config parameters)

According to the docs, use_auth_token is supposed to be used as kwargs. However, I couldn't make it work either. Instead I used the login() function from huggingface_hub, and provided the token

```python
from huggingface_hub import login
login(token=os.getenv("HUGGINGFACE_TOKEN"))
```
