### ISSUE TITLE
CamemBERT for Multilabel Classification

### ISSUE THREAD

**Issue by adrienrenaud** [ThilinaRajapakse/simpletransformers#149]
Is there plans to implement the Multilabel Classification for CamemBERT?

**Comment by ThilinaRajapakse** [comment]
Not immediate plans, but I'll keep this in the backlog to look at as soon as possible.

**Comment by ThilinaRajapakse** [comment]
Implemented.

**Comment by adrienrenaud** [comment]
Dear @ThilinaRajapakse, I don't see any support for multilabel classification with CamemBERT in https://github.com/ThilinaRajapakse/simpletransformers/blob/master/simpletransformers/classification/multi_label_classification_model.py.
It seems in contradiction with you previous comment. Could you clarify please? Thanks

**Comment by adrienrenaud** [comment]
Also documentation (https://simpletransformers.ai/docs/classification-specifics/) is saying that multilabel is not available for CamemBERT. Still in contradiction with your previous comment.
Would you be interested in a PR?

**Comment by adrienrenaud** [comment]
I made a PR for this #743.
