### ISSUE TITLE
How to do validation after each training epoch?

### ISSUE THREAD

**Issue by wshuyi** [ThilinaRajapakse/simpletransformers#15]
I would like to select a validation dataset and try to valid on it after each training epoch. Any possibility to support this feature? Thanks!

**Comment by ThilinaRajapakse** [comment]
Yeah, I'll add this.

**Comment by wshuyi** [comment]
Great! Thanks!

**Comment by nwams** [comment]
Hi there, great tutorial! Like @wshuyi I also have a validation set already that I'd like to be able to incorporate while following along with your guide. I'm using it for a classification task as well to benchmark it against my non-deep learning logistic regression model (where I also used validation set).

**Comment by ThilinaRajapakse** [comment]
Validation during training is added!

```
model = ClassificationModel('roberta', 'roberta-base', args={ 'evaluate_during_training': True, 'logging_steps': 50})

model.train_model(train_df, eval_df=eval_df)
```

**Comment by wshuyi** [comment]
Terrific! Thanks a lot!
