### ISSUE TITLE
Not able to load the checkpoint 

### ISSUE THREAD

**Issue by ankurgoel256** [ThilinaRajapakse/simpletransformers#151]
When I am trying to load a checkpoint. It is showing a error.
my code is--

model=MultiLabelClassificationModel('distilbert', 'outputs/checkpoint-3183', num_labels=6,
                                            args={'fp16': False, 'do_lower_case': True,
                                            'evaluate_during_training': True, 'evaluate_during_training_steps': 53000, 'save_steps': 53000,
                                            'learning_rate': 3e-5, 'num_train_epochs': 5, 'logging_steps': 50, 'adam_epsilon': 1e-6, 
                                            'max_seq_length': 100, 'reprocess_input_data': True, 'tensorboard_folder': None,
                                            'train_batch_size': 16, 'eval_batch_size': 8, 'weight_decay': 0.1,'regression':False,'use_cached_eval_features':True})

and the error is--

OSError: Model name 'outputs/checkpoint-3183' was not found in model name list (distilbert-base-uncased, distilbert-base-uncased-distilled-squad, distilbert-base-german-cased, distilbert-base-multilingual-cased). We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/outputs/checkpoint-3183/config.json' was a path or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.

**Comment by ThilinaRajapakse** [comment]
Do you have the config.json file in outputs/checkpoint-3183?

**Comment by flobarrios** [comment]
Same problem here! And I do have the config.json file in the epoch I'm trying to load.
