### ISSUE TITLE
See tokenized version of text

### ISSUE THREAD

**Issue by kinoute** [ThilinaRajapakse/simpletransformers#152]
I was wondering if there is a way to see how the library tokenizes our text for debugging purpose. I can see we have a `text_a` method for `wrong_predictions`to see the raw text but there is no such way to see the text with tokens.

With the recent release of tokenizers by HuggingFace, I used their library to see what my text might look like after tokenization (for distilbert multilingual) but I'm not sure if the results are the same I will have with this library.

I mainly do that to look for the best `max_seq_length` number.

With their new library, I do:

```python
from tokenizers import BertWordPieceTokenizer

tokenizer = BertWordPieceTokenizer(
                                "bert-base-multilingual-cased-vocab.txt", 
                                add_special_tokens=True, 
                                clean_text=True, 
                                handle_chinese_chars=True, 
                                strip_accents=False, 
                                lowercase=False)
 
tokens_avg = 0

for email in train_dataset.text:
  tokens = tokenizer.encode(email).tokens
  tokens_avg += len(tokens)
  print("Length:", len(tokens), "/ Tokens:", tokens)

print('Average Tokens:', tokens_avg / len(train_dataset))

**Comment by ThilinaRajapakse** [comment]
Yes, this should work here as well as I am importing the tokenizers from Hugging Face directly.

**Comment by kinoute** [comment]
So you can confirm that the results should be similar on DistilBert multilingual cased with your library and their new library? (strip_accents set to False, clean_text to True etc)?

**Comment by ThilinaRajapakse** [comment]
I didn't check out the new tokenizers yet, so I can't confirm it (without checking). I can confirm that I didn't make any changes to the tokenizers on my side though.
