### ISSUE TITLE
Version 0.63.11 not compatible with Transformers 4.31.0

### ISSUE THREAD

**Issue by owendw1** [ThilinaRajapakse/simpletransformers#1538]
**Describe the bug**
Version 0.63.11 doesn't appear to be compatible with the latest version of the Transformers dependency, which is [version 4.31.0](https://pypi.org/project/transformers/4.31.0/).

**To Reproduce**
1. Install Simple Transformers using pip
pip install simpletransformers

2. In the Python interpreter or a Python script, try to import key Simple Transformers modules
from simpletransformers.classification import ClassificationModel, ClassificationArgs

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/<dirs>/venv/lib/python3.8/site-packages/simpletransformers/classification/__init__.py", line 5, in <module>
    from simpletransformers.classification.multi_modal_classification_model import (
  File "/home/<dirs>/venv/lib/python3.8/site-packages/simpletransformers/classification/multi_modal_classification_model.py", line 47, in <module>
    from transformers.models.mmbt.configuration_mmbt import MMBTConfig
ModuleNotFoundError: No module named 'transformers.models.mmbt'

**Expected behavior**
The above error to not appear

**Desktop (please complete the following information):**
Ubuntu 20.04.6 LTS

**Cause**
In the latest version of Transformers, the model mmbt appears to have been moved to transformers/models/deprecated/mmbt/, which Simple Transformers cannot find.

**Workaround**
A workaround for the above problem can be used. When installing Simple Transformers using pip, add the following dependency resolution:

pip install simpletransformers "transformers==4.30.2"

**Comment by ColinFerguson** [comment]
I have also had this issue today and downgrading transformers worked for me.  I don't love that solution, but it works for now.

**Comment by bver** [comment]
^^^ Workaround works for me as well, thanks.

**Comment by owendw1** [comment]
Fixed (see issue #1539): Simple Transformers 0.64.3 now available.
