### ISSUE TITLE
Feature request: add the option to use CRF for NER

### ISSUE THREAD

**Issue by marctorrellas** [ThilinaRajapakse/simpletransformers#154]
Addidng a layer of CRF on top of BERT + linear could improve performance and I think it's quite state of the art. I see it like a boolean option to add when creating the model. 

I'd be happy to write a PR if this idea is supported and no volunteers show up :)

**Comment by ThilinaRajapakse** [comment]
I think this would be an excellent addition. I had an implementation with a LSTM on top but it didn't seem to make a significant improvement, so I didn't push it. If a CRF improves performance, it would be most welcome.

**Comment by marctorrellas** [comment]
An LSTM wouldn't improve because does kind of the same as BERT. That's why one the best previous architectures before LMs was BiLSTM+CRF

**Comment by marctorrellas** [comment]
Let's see if someone volunteers for that :) otherwise I'll eventually do it

**Comment by flaviussn** [comment]
> Let's see if someone volunteers for that :) otherwise I'll eventually do it

Any progress on that :) ? Thx

**Comment by marctorsoc** [comment]
not really. If you wanna go with it, I'm very happy to help but can't get it on my stack as I'm really busy these weeks

**Comment by datalee** [comment]
> Let's see if someone volunteers for that :) otherwise I'll eventually do it

Any progress on that :) ? Thx
