### ISSUE TITLE
Cache takes up all the disk space for a large dataset

### ISSUE THREAD

**Issue by klimentij** [ThilinaRajapakse/simpletransformers#157]
It's not a problem for smaller datasets, but once I train on 200k+ samples, cache takes up hundreds of gigabytes and takes some 20 minutes to persist on SSD. 

In fact, I don't need features to be cached. 

Some suggestions:
– Include `no_cache` parameter of a `load_and_cache_examples` function to model args so users can have control over it
– Automatically set `no_cache=True` for training if `reprocess_input_data` is `True`

**Comment by ThilinaRajapakse** [comment]
Yes, the `no_cache` option should be exposed to users. That was how I originally planned to do it, actually. Must have slipped through.

I'll add an option to disable caching the features.

**Comment by klimentij** [comment]
Perfect, thank you!

**Comment by ThilinaRajapakse** [comment]
This is now added.

Set `'no_cache': True` to prevent feature caching.

**Comment by klimentij** [comment]
Brilliant!
