### ISSUE TITLE
Slow training 

### ISSUE THREAD

**Issue by AI-World-tech** [ThilinaRajapakse/simpletransformers#158]
Training is too slow , only 5000 training examples took 2 hrs of training on a TPU ! 
Is there a better way of approaching this model and using it ?

**Comment by ThilinaRajapakse** [comment]
Is the 2 hours for a single training epoch?

I haven't tested this on a TPU. Are you sure that the code is running on the TPU and not on the CPU?

**Comment by AliOsm** [comment]
What is the model that you are using and what is the batch size?

**Comment by KnutJaegersberg** [comment]
I had instances too where training was slow. This is why I try to use happytransformers when possible. It can also take ages before training starts. Has that been changed?

**Comment by KnutJaegersberg** [comment]
The option use_multiprocessing can prevent training from starting. It just hangs for a long time and then it starts. Without multiprocessing it starts right away.
