### ISSUE TITLE
how to apply pos_weigth in multilabel classification

### ISSUE THREAD

**Issue by phrenol** [ThilinaRajapakse/simpletransformers#159]
pos_weight (optional): A list of length num_labels containing the weights to assign to each label for loss calculation.

how do I apply this? If I have 4 labels and 100 entries, devided like this:

label 1: 50
label 2: 25
label 3: 15
label 4: 10

will this result in?
``` pos_weight=[50, 25, 15, 10]```

thanks!

**Comment by ThilinaRajapakse** [comment]
I would go with these weights.

`[1, 2, 50/15, 5]`

**Comment by phrenol** [comment]
ah I see, thanks!
