### ISSUE TITLE
Can the user choose the columns as text or label?

### ISSUE THREAD

**Issue by wshuyi** [ThilinaRajapakse/simpletransformers#16]
By default, the framework regards the first column as text, while the second one as label. Could you please provide a parameter to select the role of different columns? Thanks a lot!

**Comment by ThilinaRajapakse** [comment]
Yes, I could. But it seemed unnecessary since it's trivial to switch them around with pandas.

**Comment by wshuyi** [comment]
Indeed. Thanks for the reply! :)

**Comment by ThilinaRajapakse** [comment]
Just an FYI, this feature has been added now. You can use column names `text`, and `labels` to indicate the role.

**Comment by wshuyi** [comment]
Glad to hear! Thanks a lot!
