### ISSUE TITLE
Raw_outputs with sliding window feature

### ISSUE THREAD

**Issue by kinoute** [ThilinaRajapakse/simpletransformers#160]
I need to return a single value between 0 and 1 as a prediction for a binary classification task. It works perfectly (thanks to you in another issue) when we don't use the sliding window feature. I basically just do:

```python
from scipy.special import softmax

predicted_label, probabilities = model.predict([text])
# format correctly the returns (label integer to string, tensor to probability between 0 and 1)
label = get_label(predicted_label[0])
probability = max(softmax(probabilities[0]).tolist())
return label, probability
```

Label is the predicated class as string (like "spam" or "clean") and probability is a value between 0 and 1 like 0.9848747.

The problem is, when using the great sliding_window feature (it gives me great results despite being longer obviously), the `raw_outputs` *can* contain more than one prediction for a single entry if the original text was longer than `max_seq_length`.

What is the best approach in this case, to return a single probability? How could we return/use `raw_outputs` to return one list instead of 2 or three (depending of the text length) like [0.123 0.977] instead of  [0.123 0.977] [0.23 0.12] [0.784 0.223] (random values) for a single entry.

I tried to softmax the predictions and then mean the result but it gives wrong percentage. Like [0.44 0.56] when the predicted label is 0.

Any ideas?

**Comment by ThilinaRajapakse** [comment]
How did you softmax the outputs?

I think it would work if you softmax each of the list items separately, then take the probabilities for the 0 class and mean them. For example, (with random values):

raw_outputs -> [[-2.33, 4.04], [2.33, -0.3], [-1.2, 4.5]]
after softmax -> [[0.01, 0.99[, [0.96, 0.04], [0.02, 0.98]]
Take first column -> [0.01, 0.96, 0.02]
Mean -> [0.33]
