### ISSUE TITLE
probability for binary classification tasks

### ISSUE THREAD

**Issue by caprone** [ThilinaRajapakse/simpletransformers#161]
HI!
ther's way to get probability scores in range [0, 1] from ClassificationModel output ? or I need to adapt -- for exmple -- "RobertaClassificationHead" with sigmoid activation on top linear layer? 
thanks again!

**Comment by caprone** [comment]
a ok (tks to kinoute hint), we can process directly raw_outputs:

 probabilities = [softmax(prb)[1] for prb in raw_outputs]

**Comment by marctorrellas** [comment]
please close if solved

**Comment by ThilinaRajapakse** [comment]
@all-contributors please add @marctorrellas  for maintenance
