### ISSUE TITLE
Error in Camembert implementation (single separator token)

### ISSUE THREAD

**Issue by pommedeterresautee** [ThilinaRajapakse/simpletransformers#163]
**Describe the bug**
Current generation of features when using Camembert model doesn't follow model expectation for sentence pair classification task.
Camembert documentation is available there:
https://github.com/huggingface/transformers/blob/569da80cedcf9022b869fbb398666c93b3219956/src/transformers/modeling_camembert.py

>  Inputs:
        **input_ids**: ``torch.LongTensor`` of shape ``(batch_size, sequence_length)``:
            Indices of input sequence tokens in the vocabulary.
            To match pre-training, CamemBERT input sequence should be formatted with <s> and </s> tokens as follows:
            (a) For sequence pairs:
                ``tokens:         <s> Is this Jacksonville ? </s> </s> No it is not . </s>``
            (b) For single sequences:
                ``tokens:         <s> the dog is hairy . </s>``
            Fully encoded sequences or sequence pairs can be obtained using the CamembertTokenizer.encode function with
            the ``add_special_tokens`` parameter set to ``True``.
            CamemBERT is a model with absolute position embeddings so it's usually advised to pad the inputs on
            the right rather than the left.
            See :func:`transformers.PreTrainedTokenizer.encode` and
            :func:`transformers.PreTrainedTokenizer.convert_tokens_to_ids` for details.

In simple transformers code, Camembert doesn't require an extra SEP token.
```python
                sep_token_extra=bool(args["model_type"] in ["roberta"]),
```
And even when updating the list by adding Camembert, when inspecting the generated examples, there is only one SEP token in the code (don't know why).

According to the documentation, the model requires 2 SEP tokens between sentences.  
It makes sense as Camembert is based Roberta 

**To Reproduce**
NA

**Expected behavior**
Code follow Camembert documentation

**Comment by pommedeterresautee** [comment]
Checking the code, I understand there is a second issue, the extra separator token is never generated, whatever the model chosen (including Roberta). The code only manages the max len for an extra sep token but never insert it from my understanding.

**Comment by ThilinaRajapakse** [comment]
You are right. There is an issue with the extra token not being added. I think this was overlooked when sentence pair tasks were added. I'll add the extra token. I'm double checking now, but this is only an issue on RoBERTa based models with sentence pair tasks, right?

**Comment by ThilinaRajapakse** [comment]
The extra token is added now. Hopefully, this issue is fixed.

**Comment by pommedeterresautee** [comment]
👍 closing the issue
