### ISSUE TITLE
Tokenizers

### ISSUE THREAD

**Issue by ricknichols84** [ThilinaRajapakse/simpletransformers#165]
Hi Thilina,

Will you be adding the new tokenizers that Hugging Face put out couple weeks ago?

**Comment by ThilinaRajapakse** [comment]
Yeah, but I need to be careful about breaking stuff. I still haven't had the time to look into it properly.

**Comment by ricknichols84** [comment]
Sounds good, I would think new tokenizers would really boost the usage of your library since we can push more models faster :)
Thanks again for your contribution.
