### ISSUE TITLE
Can I use custom pre-trained models?

### ISSUE THREAD

**Issue by wshuyi** [ThilinaRajapakse/simpletransformers#17]
I want to do classification with Chinese texts. Though there is a BERT Chinese pre-trained model by default, it's quite out-dated. I would like to select different pre-trained models, like wwm BERT, XLnet and RoBERTa which trained on Chinese corpus. They have already been converted into pytorch-transformers format. Can I use them with simpletransformers? Thanks!

**Comment by ThilinaRajapakse** [comment]
Yes, you can. You just need to provide the path to the directory containing the model when you create the `SimpleTransformer` object.

**Comment by wshuyi** [comment]
Thanks! I will give it a try.
