### ISSUE TITLE
regex not used

### ISSUE THREAD

**Issue by jklaise** [ThilinaRajapakse/simpletransformers#19]
It looks like the `regex` module is not used anywhere, but it's still specified as a dependency. Is it possible to remove this from setup.py as it causes a whole build process on Linux (the author only released a Python wheel for Windows).

**Comment by ThilinaRajapakse** [comment]
That could be removed. But it is a dependency for the `transformers` library which is required to run `simpletransformers`. So `regex` will need to be installed anyway.

**Comment by ThilinaRajapakse** [comment]
No problem!
