### ISSUE TITLE
distilbert reach only 77% when using ConLL dataset. 

### ISSUE THREAD

**Issue by piperod** [ThilinaRajapakse/simpletransformers#195]
**Describe the bug**
I am trying to reproduce the results of distilbert reported on the website of transformers for Name Entity Recognition. (here)[https://huggingface.co/transformers/examples.html#named-entity-recognition] But the performance is way lower than the reported one. It only reaches 77%. 

**To Reproduce**

Download ConLL dataset and run train and test steps. 

**Expected behavior**
The reported performance was 94%

**Desktop (please complete the following information):**
 - Linux

**Comment by ThilinaRajapakse** [comment]
How many training epochs did you try? I got these results with BERT, but I didn't try to improve upon it.

```
{'eval_loss': 0.10684790916955669, 'precision': 0.9023580786026201, 'recall': 0.9153082919914954, 'f1_score': 0.9087870525112148}
```

**Comment by piperod** [comment]
I got the same on BERT but the issue is on distilbert.

**Comment by piperod** [comment]
Literally I ran with the params that come from the invocation of NERModel, I did not touched the conf thinking that it was the "Right" one. I can try with more do.

**Comment by ThilinaRajapakse** [comment]
Unfortunately, there is no "right" configuration that works for everything (actually, it might be fortunate as some of us might be out of jobs if there was a right config :wink: ).

The default configuration is just a set of typical hyperparameter values. They are shared across all models and tasks, so you might need to tweak them to get better results depending on the situation.

**Comment by piperod** [comment]
Well, it should be the right configuration for the example dataset. At least it is for BERT and Robert-large ( it is reproducible). The fact that distilbert is not, it is the reason I am opening the issue.
