### ISSUE TITLE
AttributeError: 'str' object has no attribute 'to'

### ISSUE THREAD

**Issue by gevezex** [ThilinaRajapakse/simpletransformers#198]
**Describe the bug**
I am trying the following code:
model2 = NERModel('roberta', 'pdelobelle/robBERT-base', use_cuda=False, args={'fp_16': False})
model2.train('data/NER_NL/NER_from_wikipedia/perfect_ner.txt', output_dir='output1')

I get the following error:
AttributeError                            Traceback (most recent call last)
<ipython-input-40-a7811f59f351> in <module>
----> 1 model2.train('data/NER_NL/NER_from_wikipedia/perfect_ner.txt', output_dir='output1')

~/anaconda3/envs/trans/lib/python3.8/site-packages/simpletransformers/ner/ner_model.py in train(self, train_dataset, output_dir, show_running_loss, eval_df)
    331                 tqdm(train_dataloader, desc="Current iteration", disable=args["silent"])
    332             ):
--> 333                 batch = tuple(t.to(device) for t in batch)
    334 
    335                 inputs = self._get_inputs_dict(batch)

~/anaconda3/envs/trans/lib/python3.8/site-packages/simpletransformers/ner/ner_model.py in <genexpr>(.0)
    331                 tqdm(train_dataloader, desc="Current iteration", disable=args["silent"])
    332             ):
--> 333                 batch = tuple(t.to(device) for t in batch)
    334 
    335                 inputs = self._get_inputs_dict(batch)

AttributeError: 'str' object has no attribute 'to'

Any clue?

**Comment by kinoute** [comment]
You're not supposed to use the `train` function directly as stated in the README:

> train(self, train_dataset, output_dir)
>Trains the model on train_dataset. Utility function to be used by the train_model() method. Not intended to be used directly.

Try `train_model`.

**Comment by gevezex** [comment]
Feel so stupid. Thnx!

**Comment by ThilinaRajapakse** [comment]
We've all been there! :wink:

**Comment by kinoute** [comment]
@ThilinaRajapakse That made me think that maybe this kind of infos should be removed from the README as it might confuse people.

And for people digging into the source code, the `train` function could be renamed as `_train` to make them understand that it is not designed to be called from the outside.
