### ISSUE TITLE
Use spacy or another tokenizer for NER?

### ISSUE THREAD

**Issue by marctorrellas** [ThilinaRajapakse/simpletransformers#200]
Hi all,

This is more a question, but can turn into a feature request depending on the answer. My understanding is that BERT & Co use their own tokenizers to split the words into pieces, e.g:

"Jim Henson was a puppeteer" --> ["Jim" , "Hen" , "##son",  "was" , "a" , "puppet", "##eer"]

On the other hand, NER labels typically come in a character range, and we associate it to tokens, e.g. using a conventional tokenizer like spacy:

"Jim Henson was a puppeteer" --> ["Jim", "Henson", "was", "a", "puppeteer"]
                                                            ["B-PER", "I-PER", "O", "O", "O"]

Then, that's the input to the Transformers which internally do the word piece tokenisation, predict, and return something like ["B-PER", "I-PER", "O", "O", "O"], with 5 tokens, not 7

While usually tokenizing by space can be enough, that's not the best as there might be tokens separated by other characters. However, It seems to me that here

https://github.com/ThilinaRajapakse/simpletransformers/blob/master/simpletransformers/ner/ner_model.py

we are just tokenising by space. 

Is this correct? Would it be valuable to allow using other tokenizers like spaCy ?
Please feel free to criticise any bit of my explanation :)

**Comment by marctorrellas** [comment]
not sure whether this is related to https://github.com/ThilinaRajapakse/simpletransformers/issues/165

**Comment by ThilinaRajapakse** [comment]
We are using WordPiece tokenization as well. Or rather, I am importing the tokenizer from the Transformers package directly, which is using WordPiece tokenization. If we were tokenizing by spaces, we'd be overrun with out of vocabulary errors!

**Comment by marctorrellas** [comment]
I'm referring to this https://github.com/ThilinaRajapakse/simpletransformers/blob/d8493eb82f28c8cc77a8e64bb386e979c1eba0a6/simpletransformers/ner/ner_model.py#L617

Probably I'm misunderstanding something

**Comment by ThilinaRajapakse** [comment]
Ah, yeah. I see what you mean.

I think the simplest solution would be to let users pass in either a list of "words" (tokenized) or a string. If it's strings, we keep the current behaviour. If it's a list, we assume the user has already performed tokenization. This would let the user decide how to tokenize if they want.

**Comment by marctorrellas** [comment]
Yeah, that an option. This way you don't add more dependencies to your package
