### ISSUE TITLE
model evaluation error for classification problem

### ISSUE THREAD

**Issue by mrpophali** [ThilinaRajapakse/simpletransformers#208]
**Describe the bug**
I am loading the model using below and then trying to evaluate on eval dataframe which has 'text' and 'labels' columns along with existing column
```
modelMclass = ClassificationModel('bert', 'outputs/'),# this works fine
```
below is sample eval_df
```
 	Policy Name 	Question 	text 	labels
5297 	Responsible Use of Technology and Microsoft's ... 	Are there laptop guidelines? 	Are there laptop guidelines? 	18
7529 	Company Travel Policy 	May I book first class for travel? 	May I book first class for travel? 	2
```
```
Model.args
{'sliding_window': False,
 'tie_value': 1,
 'stride': 0.8,
 'regression': False,
 'output_dir': 'outputs/',
 'best_model_dir': 'outputs/best_model',
 'cache_dir': 'cache_dir/',
 'fp16': True,
 'fp16_opt_level': 'O1',
 'max_seq_length': 128,
 'train_batch_size': 8,
 'gradient_accumulation_steps': 1,
 'eval_batch_size': 8,
 'num_train_epochs': 1,
 'weight_decay': 0,
 'learning_rate': 4e-05,
 'adam_epsilon': 1e-08,
 'warmup_ratio': 0.06,
 'warmup_steps': 0,
 'max_grad_norm': 1.0,
 'do_lower_case': False,
 'logging_steps': 50,
 'save_steps': 2000,
 'no_cache': False,
 'save_model_every_epoch': True,
 'evaluate_during_training': False,
```

When i try below
result, model_outputs, wrong_predictions = modelMclass.eval_model(df_eval)

I get below value error which i am not sure how to resolve

************************************************************************
```
Features loaded from cache at cache_dir/cached_dev_bert_128_24_1590

0%
0/199 [00:00<?, ?it/s]


---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-68ab6ec520a9> in <module>
      1 # Evaluate the model
      2 #result, model_outputs, wrong_predictions = modelMclass.eval_model(df_eval, f1=f1_multiclass, acc=accuracy_score)
----> 3 result, model_outputs, wrong_predictions = modelMclass.eval_model(df_eval)

/anaconda/envs/py37_default/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py in eval_model(self, eval_df, multi_label, output_dir, verbose, silent, **kwargs)
    528 
    529         result, model_outputs, wrong_preds = self.evaluate(
--> 530             eval_df, output_dir, multi_label=multi_label, verbose=verbose, silent=silent, **kwargs
    531         )
    532         self.results.update(result)

/anaconda/envs/py37_default/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py in evaluate(self, eval_df, output_dir, multi_label, prefix, verbose, silent, **kwargs)
    595                 inputs = self._get_inputs_dict(batch)
    596 
--> 597                 outputs = model(**inputs)
    598                 tmp_eval_loss, logits = outputs[:2]
    599 

/anaconda/envs/py37_default/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

/anaconda/envs/py37_default/lib/python3.7/site-packages/simpletransformers/classification/transformer_models/bert_model.py in forward(self, input_ids, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, labels)
     78             else:
     79                 loss_fct = CrossEntropyLoss(weight=self.weight)
---> 80                 loss = loss_fct(logits.view(-1, self.num_labels), labels.view(-1))
     81             outputs = (loss,) + outputs
     82 

/anaconda/envs/py37_default/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

/anaconda/envs/py37_default/lib/python3.7/site-packages/torch/nn/modules/loss.py in forward(self, input, target)
    914     def forward(self, input, target):
    915         return F.cross_entropy(input, target, weight=self.weight,
--> 916                                ignore_index=self.ignore_index, reduction=self.reduction)
    917 
    918 

/anaconda/envs/py37_default/lib/python3.7/site-packages/torch/nn/functional.py in cross_entropy(input, target, weight, size_average, ignore_index, reduce, reduction)
   2019     if size_average is not None or reduce is not None:
   2020         reduction = _Reduction.legacy_get_string(size_average, reduce)
-> 2021     return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
   2022 
   2023 

/anaconda/envs/py37_default/lib/python3.7/site-packages/torch/nn/functional.py in nll_loss(input, target, weight, size_average, ignore_index, reduce, reduction)
   1834     if input.size(0) != target.size(0):
   1835         raise ValueError('Expected input batch_size ({}) to match target batch_size ({}).'
-> 1836                          .format(input.size(0), target.size(0)))
   1837     if dim == 2:
   1838         ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)

**ValueError: Expected input batch_size (8) to match target batch_size (192).**
```

**Expected behavior**
Expected to get mcc results for my model

**Desktop (please complete the following information):**
 - OS Ubuntu 18.04 

_Edited for readability - Thilina_

**Comment by ThilinaRajapakse** [comment]
If you are doing multiclass classification, you need to set the number of labels when loading the model from `outputs` as well.

**Comment by mrpophali** [comment]
> If you are doing multiclass classification, you need to set the number of labels when loading the model from `outputs` as well.

I did below as per your suggestions
1. Load the model with number of classes
modelMclass = ClassificationModel('bert', 'outputs/',num_labels=24)
2. created new df_eval2 with just 2 columns (text, labels)
3. result, model_outputs, wrong_predictions = modelMclass.eval_model(df_eval2)

df_eval2.info()
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1590 entries, 3569 to 7629
Data columns (total 2 columns):
text      1590 non-null object
labels    1590 non-null int64
dtypes: int64(1), object(1)
memory usage: 37.3+ KB

I am still seeing the same issue as before. Is there anything else that is required? Thanks for your help.
-Mandar

**Comment by junxuwdc** [comment]
I got some similar problems. However, if i simply change the num_labels=actual_num_labels+1, it can work.

**Comment by ThilinaRajapakse** [comment]
> I got some similar problems. However, if i simply change the num_labels=actual_num_labels+1, it can work.

If this is the issue, that likely means your labels start from 1 rather than from 0. The library will expect labels from `0` up to `n` (but not `n`) for `num_labels=n`.

**Comment by mrpophali** [comment]
Thanks for pointers...i did below

1. I double checked my labels. I am using label encoder from Sklearn and it starts with zero. So for 24 labels, the values are from 0-23.
2. I re-ran the whole model again from start and i can see that the eval step is giving same error. The only difference here is that i am not using loading option. 
result, model_outputs, wrong_predictions = modelMclass.eval_model(df_eval, f1=f1_multiclass, acc=accuracy_score)
Running loss: 0.001844Training of bert model complete. Saved to outputs/.
Features loaded from cache at cache_dir/cached_dev_bert_128_24_1590
Traceback (most recent call last):
  File "pia-classify-bert-multi-class.py", line 83, in <module>
    result, model_outputs, wrong_predictions = modelMclass.eval_model(df_eval, f1=f1_multiclass, acc=accuracy_score)
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py", line 530, in eval_model
    eval_df, output_dir, multi_label=multi_label, verbose=verbose, silent=silent, **kwargs
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py", line 597, in evaluate
    outputs = model(**inputs)
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/simpletransformers/classification/transformer_models/bert_model.py", line 80, in forward
    loss = loss_fct(logits.view(-1, self.num_labels), labels.view(-1))
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 916, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/torch/nn/functional.py", line 2021, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/torch/nn/functional.py", line 1836, in nll_loss
    .format(input.size(0), target.size(0)))
**ValueError: Expected input batch_size (8) to match target batch_size (192).**

**Comment by ThilinaRajapakse** [comment]
Ok, let's take a step back. Can you tell me whether you get the error with the minimal script below?

```
from simpletransformers.classification import ClassificationModel
import pandas as pd


# Train and Evaluation data needs to be in a Pandas Dataframe of two columns. The first column is the text with type str, and the second column in the label with type int.
train_data = [['Example sentence belonging to class 1', 1], ['Example sentence belonging to class 0', 0], ['Example eval senntence belonging to class 2', 2]]
train_df = pd.DataFrame(train_data, columns=['text', 'labels'])

eval_data = [['Example eval sentence belonging to class 1', 1], ['Example eval sentence belonging to class 0', 0], ['Example eval senntence belonging to class 2', 2], ['Another', 3]]
eval_df = pd.DataFrame(train_data)

train_args = {
    'reprocess_input_data': True, 
    'overwrite_output_dir': True,
    'num_train_epochs': 5,
}

# Create a TransformerModel
model = ClassificationModel('roberta', 'roberta-base', num_labels=4, args=train_args)

# Train the model
model.train_model(train_df, eval_df=eval_df)

# Evaluate the model
result, model_outputs, wrong_predictions = model.eval_model(eval_df)

```

**Comment by junxuwdc** [comment]
Traceback (most recent call last):
  File "C:/Users/Python/transformers_test1.py", line 38, in <module>
    result, model_outputs, wrong_predictions = model.eval_model(eval_df)
  File "M:\Python\transformers\lib\site-packages\simpletransformers\classification\classification_model.py", line 548, in eval_model
    eval_df, output_dir, multi_label=multi_label, verbose=verbose, silent=silent, **kwargs
  File "M:\Python\transformers\lib\site-packages\simpletransformers\classification\classification_model.py", line 597, in evaluate
    eval_dataset = self.load_and_cache_examples(eval_examples, evaluate=True, verbose=verbose, silent=silent)
  File "M:\Python\transformers\lib\site-packages\simpletransformers\classification\classification_model.py", line 753, in load_and_cache_examples
    all_input_ids = torch.tensor([f.input_ids for f in features], dtype=torch.long)
  File "M:\Python\transformers\lib\site-packages\simpletransformers\classification\classification_model.py", line 753, in <listcomp>
    all_input_ids = torch.tensor([f.input_ids for f in features], dtype=torch.long)
AttributeError: 'list' object has no attribute 'input_ids'

**Comment by ThilinaRajapakse** [comment]
The latest version of Pytorch should work.

Can you give me a minimal script with a few rows of data to reproduce the error?
