### ISSUE TITLE
Tesla K80 sentence classification training time? 

### ISSUE THREAD

**Issue by Rysias** [ThilinaRajapakse/simpletransformers#210]
I'm trying to to follow the binary sentence classification example on a Tesla K80 GPU without fp16 but otherwise following the example. Atm the "Current Iteration" is set to complete in a total of ~4 hours, which seems like a lot in comparison to [other tutorials/implementation](https://towardsdatascience.com/bert-for-dummies-step-by-step-tutorial-fb90890ffe03). This is, however, my first experience with distillBERT so I don't really have any intuitions for training time. Is this normal or way longer than expected? 

I love the general feel of the package by the way - very intuitive, flexible and easy to use.

**Comment by ThilinaRajapakse** [comment]
The training portion of the code in this package is almost identical to the code in the Hugging Face implementation, barring some additional support for metrics and visualizations baked in. While those things will generate _some_ overhead, it's never been noticeable for me. Which example are you running? I can see how long it takes on my rig for comparison.

Thank you! I'm glad you are enjoying it!

**Comment by Rysias** [comment]
Thanks for the quick response! I did the Yelp sentiment train data example - let me know if you need more information:)
