### ISSUE TITLE
Preloading : ClassificationModel always return the same output per class initialization ( for each subsequent predict() ) 

### ISSUE THREAD

**Issue by TheCodingLand** [ThilinaRajapakse/simpletransformers#211]
**Describe the bug**

From my experiments with Bert and DistillBert (I could not test others yet), if I load a model with :

model = ClassificationModel(model_type, model_path, use_cuda=False)

And do a prediction with model.predict([text])

I get a correct return on the first predict.

Now, if I do a new prediction, model.predict([new_text]), i always get the same result as the first one.

**To Reproduce**

You can use this code from my use case to reproduce : (a service listening on port 8080)

```

from simpletransformers.classification import ClassificationModel
from simpletransformers.experimental.classification import ClassificationModel as ExperimentalClassificationModel

import json

from bottle import run, post, request, response

loaded_models = { }

@post('/process')
def process():
    msg = json.loads(request.body.read())
    model_name = msg['model_name']
    text = msg['text']
    model_type= msg['model_type']
    model_path= msg['model_path']
    experimental = msg['experimental']
    cuda= msg['cuda']

    if model_name not in loaded_models:
        if experimental:
            model =ExperimentalClassificationModel(model_type, model_path, use_cuda=cuda, sliding_window=True)
        else:
            model = ClassificationModel(model_type, model_path, use_cuda=cuda)
        loaded_models[model_name] = model
    else:
        model = loaded_models[model_name]

    prediction, output = model.predict([text])
    print(prediction)
    print(output)
    return {} # you can improve the return value by parsing the ndarray to dict

print("Running prediction models pre-loader")

run(host='0.0.0.0', port=8080, debug=True)
```

And another little script to call the model (will trigger the prediction which should be  outputed to the console on the other script)

```
import http.client

preloaded_models = http.client.HTTPConnection('localhost', 8080)

text = "your text here"
model_name= 1 #a unique model name 
path = "/your/model/location"

req = { 'model_name' : model_name, "text" :text, 'model_type' : 'bert', 'cuda' : False, "model_path": path, "experimental" : False}

req = json.dumps(req)
preloaded_models.request('POST', '/process', req)
```

 
**Expected behavior**

I should get the correct model_output corresponding to the input text.
This problem prevents pre-loading the models in memory for faster predictions.

#edit: typos

**Comment by ThilinaRajapakse** [comment]
I think this issue is caused by the `predict()` method using cached features. The default behaviour for `predict()` was supposed to not use cache but it looks like it is.

Can you check whether this issue is solved if you set `reprocess_input_data` to `True`?

```
model = ClassificationModel(model_type, model_path, use_cuda=cuda, args={"reprocess_input_data": True})
```

**Comment by TheCodingLand** [comment]
I did actually initialize the models with 'reprocess_input_data': True while training.

For some reason I thought it would be initialized as well by loading the model afterwards.
I'll test passing the argument when initializing it for predictions and update the issue.

**Comment by ThilinaRajapakse** [comment]
The arguments are not carried over from training when you load a saved model, atm. This will be addressed though, as I think it's reasonable to expect this behaviour.

**Comment by TheCodingLand** [comment]
Thank you @ThilinaRajapakse , I managed to fix it. 
I added the option 'reprocess_input_data' to True, but it didn't fix it, then I added 'use_cached_eval_features' : False. it now works.


```python
from simpletransformers.classification import ClassificationModel
from simpletransformers.experimental.classification import ClassificationModel as ExperimentalClassificationModel

import json

from bottle import run, post, request, response

loaded_models = { }

@post('/process')
def process():
    msg = json.loads(request.body.read())
    model_name = msg['model_name']
    text = msg['text']
    model_type= msg['model_type']
    model_path= msg['model_path']
    experimental = msg['experimental']
    cuda= msg['cuda']

    if model_name not in loaded_models:
        if experimental:
            model =ExperimentalClassificationModel(model_type, model_path, use_cuda=cuda, sliding_window=True, args={'use_cached_eval_features' : False,'reprocess_input_data': True})
        else:
            model = ClassificationModel(model_type, model_path, use_cuda=cuda, args={'use_cached_eval_features' : False,'reprocess_input_data': True})
        loaded_models[model_name] = model
    else:
        model = loaded_models[model_name]

    prediction, output = model.predict([text])
    print(prediction)
    print(output)
    return {} # you can improve the return value by parsing the ndarray to dict

print("Running prediction models pre-loader")

run(host='0.0.0.0', port=8080, debug=True)
```

Great work on the library.
I think just updating the documentation should be enough.
It makes sense that we should specify this only for predictions, as they do not affect the training.

Maybe you could specify if arguments are used while training, predicting or evaluating the models in the arguments part of the documentation ?

**Comment by ThilinaRajapakse** [comment]
Yeah, I agree the documentation is in need of an overhaul. It's been backlogged a little too much.,

**Comment by ranju2015** [comment]
I am working on a regression problem.  But model.predict returns same value for all test samples.

I reloaded the model file as below:
model = ClassificationModel('albert', 'outputs/', num_labels = 1, use_cuda=False, args={'use_cached_eval_features' : False,'reprocess_input_data': True})

But having the below error:

Traceback (most recent call last):
  File "bert_regression_st_mongo.py", line 201, in <module>
    predictionsX, raw_outputs = model.predict([v2])
  File "/home/bigdata/s2830250/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py", line 710, in predict
    outputs = model(**inputs)
  File "/home/bigdata/s2830250/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/bigdata/s2830250/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/simpletransformers/classification/transformer_models/albert_model.py", line 67, in forward
    loss = loss_fct(logits.view(-1), labels.view(-1))
  File "/home/bigdata/s2830250/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/bigdata/s2830250/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 431, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/home/bigdata/s2830250/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/torch/nn/functional.py", line 2204, in mse_loss
    ret = torch._C._nn.mse_loss(expanded_input, expanded_target, _Reduction.get_enum(reduction))
RuntimeError: Expected object of scalar type Float but got scalar type Long for argument #2 'target' in call to _thnn_mse_loss_forward

**Comment by ThilinaRajapakse** [comment]
```
Regression
Regression tasks also use the ClassificationModel with 2 caveats.

num_labels should be 1.
regression should be True in args dict.
Regression can be used with either single sentence or sentence pair tasks.
```

From the docs

**Comment by ranju2015** [comment]
Many thanks.

**Comment by ForLittleBeauty** [comment]
Hi, I have encountered a similar problem and it is very strange.
When I training base model like 'bert-base-uncased' ,
then I use:   model.eval_model()
I will get the right result,
However, when I am trying to use bert/roberta/xlnet large model,
and use model.eval_model(), 
I will always get the same result as the model without training, even if I  add this args 
 **args={'use_cached_eval_features' : False,'reprocess_input_data': True}**
will no help.
Do you know how can I fix my problem?
Thank you very much,
Here is my code

def data_process():
    prefix = 'data/'
    train_df = pd.read_csv(prefix + '0_train.csv',header=0)
    eval_df = pd.read_csv(prefix + '0_test.csv', header=0)
    train_df = pd.DataFrame({
        'text': train_df['review'].replace(r'\n', ' ', regex=True),
        'label':train_df['result']
    })
    #print(train_df.head())
    eval_df = pd.DataFrame({
        'text': eval_df['review'].replace(r'\n', ' ', regex=True),
        'label':eval_df['result']
    })
    #print(eval_df.head())
    return train_df,eval_df

def train_eval(train_df,eval_df,args=None):
    model = ClassificationModel('bert', 'bert-large-uncased',args={'max_seq_length':512,'overwrite_output_dir': True, 'use_cached_eval_features' : False,'reprocess_input_data': True,'n_gpu':2,'fp16':False})
    # Train the model
    model.train_model(train_df)

    # Evaluate the model
    result, model_outputs, wrong_predictions = model.eval_model(eval_df, acc=sklearn.metrics.accuracy_score)
    return result,model_outputs,wrong_predictions
def main():
    train_df,eval_df = data_process()
    result,_,_ =     train_eval(train_df,eval_df)
    print(result)

**Comment by ThilinaRajapakse** [comment]
Just to check whether I understood correctly, do you mean that you get the same output when using the _large_ models, but it works properly with the _base_ models?

**Comment by ForLittleBeauty** [comment]
yeah, at first I think it may be overfitting, however, it always returns the same output for each input in the evaluation dataset

**Comment by ThilinaRajapakse** [comment]
I think that makes it unlikely to be an issue with the model implementation of this library. There is an issue with Transformer models seeming to break and return the same answer if the learning rate is too large or if the model is trained for too long. #234 

Maybe this is related to that?
