### ISSUE TITLE
Accessing the running loss in model.train_model()

### ISSUE THREAD

**Issue by texturejc** [ThilinaRajapakse/simpletransformers#212]
Thanks for creating this super useful library. I have a feature request, or perhaps the feature I want already exists and I don't know how to access it. 

When run `model.train_model(train_df)`, the terminal displays the running loss for the  training epoch. I sometimes find it useful to have this so I can chart how log_loss drops off by epoch, as per the figure below. It's a pain to have to manually retrieve this and paste it into a .csv file or whatever.

Is there any way to systematically retrieve running loss from the model?

![image](https://user-images.githubusercontent.com/24894080/73884059-fc947400-485c-11ea-858c-f5165efa9c0f.png)

**Comment by kinoute** [comment]
There is a CSV file that sums up the training and the train_loss is saved in it:

![](https://user-images.githubusercontent.com/623763/73384923-83c97100-42cc-11ea-82b3-502a08019fd7.png)

You can use it to generate a chart then

**Comment by texturejc** [comment]
Thanks kinoute, it's great to know that resource is there. But how do I access the file? Is it saved in a particular directory? (I work with Google colab notebooks, so I can't go and check without creating a new instance.)

**Comment by kinoute** [comment]
As far as I remember, by default, the `training_progress_scores.csv` file is generated and saved in the `output_dir` folder.

**Comment by texturejc** [comment]
Great, thanks. So I'll look there so. And so long as I know it exists, I can find it even if it isn't in that exact location.

**Comment by kinoute** [comment]
Remember that you can use Tensorboard to visualize metrics during and after training. It includes the train_loss by default.
