### ISSUE TITLE
"Weight" argument in multi-class classification

### ISSUE THREAD

**Issue by ricknichols84** [ThilinaRajapakse/simpletransformers#213]
Hi Thilina,

I'm curious to know more about this argument:

_weight (optional): A list of length num_labels containing the weights to assign to each label for loss calculation._

I'm doing multi-class classification and i'm just wondering what this argument does and what is the proper syntax to use it?

Thank you.

**Comment by ThilinaRajapakse** [comment]
This lets you assign per-class weights. It is specially useful when dealing with imbalanced data. For example, if you had a dataset with 4 classes each with 1000, 500, 200, and 100 examples respectively, you might run into issues during inference on unseen data.

In such a situation, you can use weights to balance out the uneven distribution of training samples to prevent the model from being biased towards the classes with more samples.

The way you would use it would be to provide a list of weights that should be assigned to each of the classes. So, for the previous example you could go with something like this.

`weights=[0.5, 1, 2.5, 5]`

**Comment by ricknichols84** [comment]
I see, thank you!
