### ISSUE TITLE
Prediction latency and optimization

### ISSUE THREAD

**Issue by ns-hxue** [ThilinaRajapakse/simpletransformers#215]
I have a question regarding optimization. I found out that the time to make a prediction using the trained model is very long. Comparing to native TensorFlow/Keras, I am wondering if there is any optimization I can do to reduce this latency?

**Comment by ThilinaRajapakse** [comment]
Do you mean a transformer model implemented in Tensorflow/Keras? Can you give me an example where you are doing inference and a rough idea about the difference in inference time?

**Comment by ns-hxue** [comment]
Sure. For example., If I implement a binary classification model using
Keras (e,g, LSTM), the inference time is very fast. However, while using
the simple transformer model, it takes much longer. For instance, It takes
roughly 1 sec doing the inference for one single sentence in sentiment
analysis. The time converting the sentence into features is the main issue.

**Comment by ThilinaRajapakse** [comment]
A LSTM is going to be much faster compared to a Transformer model as they are usually much smaller than Transformers.

However, it shouldn't take 1 second to convert a single sentence into features. Are you sure that it's the conversion that's taking 1 second? The model initialization and loading the model into the GPU might be the culprit. If you are doing inference on something like a web server, it's best to load the model once when the server starts and keep it in memory from there.

**Comment by ns-hxue** [comment]
Thanks for the reply. I do understand the difference between transformers
and LSTM. I know the mode just needs to be loaded once. However, it does
take around 1 sec when I use the method model.predict(). It outputs this on
my end

Converting to features started.

HBox(children=(FloatProgress(value=0.0, max=1.0), HTML(value='')))

HBox(children=(FloatProgress(value=0.0, max=1.0), HTML(value='')))


I don't know why it takes so long.

**Comment by ThilinaRajapakse** [comment]
The rate of conversion for me is around 25 sentences per second. It does take around 1 second for inference but it is not due to the time taken for conversion.

**Comment by ns-hxue** [comment]
I think the fun part is the inference time is roughly the same if I

**Comment by ns-hxue** [comment]
Thanks for the clarification. I think the fun part is the inference time is
roughly the same either predicting 1 sentence or 25 sentences.

So there is no optimization we can do for this?

**Comment by ThilinaRajapakse** [comment]
That's probably because of batch sizes and multiprocessing.

I can't say for sure that there is no optimization possible but there isn't anything I can think of that would make a significant change.

**Comment by alejandrojcastaneira** [comment]
I am also agree with @ns-hxue that would be great to optimize the inference time.

**Comment by ThilinaRajapakse** [comment]
Unless you guys can find something in my code that is unnecessarily slowing things down, I am afraid there is nothing I can do. I agree that it would be great if the inference time could be cut down, but short of getting better hardware and/or optimizing inference times on Transformer models directly, it just isn't possible (assuming I didn't mess something up).

**Comment by alejandrojcastaneira** [comment]
Actually after doing a few the tests, the inference is mostly slower in the first run of the predict method  around 1 - 2s. After the first call I'm getting constantly 0.4s by call.

**Comment by flobarrios** [comment]
Hi! did anyone figure out a way to making it faster? For me, it takes about 1 second on every single prediction and in batches about 0.8s each (very far away from the 25 sentences per second of @ThilinaRajapakse) with GPU. Maybe I'm missing something? I need to predict more than 4MM comments  😢

**Comment by ThilinaRajapakse** [comment]
25 sentences per second were only for the tokenization/feature conversion part if I remember correctly. Do you mean 4 million comments?

**Comment by flobarrios** [comment]
I was missing the flag `'use_multiprocessing': True,`, now it takes 3 seconds for 100 sentences (tokenization + prediction). Yes, 4 million comments 😱

**Comment by ThilinaRajapakse** [comment]
Well then, it might take a couple of days but at least it's not weeks or months now! :sweat_smile:

**Comment by flobarrios** [comment]
Exactly!! And thanks a lot for the library, it works great!!

**Comment by ThilinaRajapakse** [comment]
You are welcome! That's great!

**Comment by joe-webb** [comment]
If anyone is stumbling across this who is having very slow predictions on GPU instances, deliberately setting use_multiprocessing = False solved our issue with nearly a 10X improvement in prediction times.
