### ISSUE TITLE
BioBert model 

### ISSUE THREAD

**Issue by wadhwasahil** [ThilinaRajapakse/simpletransformers#216]
Hey,

Thanks for this amazing repository. I am wondering if I could use BioBert/ClinicalBert as my model for training? If yes, how could I add it to my code?

Thanks

**Comment by ThilinaRajapakse** [comment]
You can. You can just grab the Pytorch checkpoint and use it. Assuming the Pytorch checkpoint is saved in `biobert_checkpoint/`;

model = ClassificationModel('bert', 'biobert_checkpoint`)

**Comment by wadhwasahil** [comment]
So I tried converting BioBert checkpoint which was in tensorflow to pytorch. So my folder has two things, **pytorch.bin** and **config.json**. However, when I try to run the 

`model = MultiLabelClassificationModel('bert', '../model/BioBert/')`,

I get the following error
`
OSError: Model name '../model/BioBert/' was not found in tokenizers model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased, bert-base-finnish-cased-v1, bert-base-finnish-uncased-v1, bert-base-dutch-cased). We assumed '../model/BioBert/' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.txt'] but couldn't find such vocabulary files at this path or url.`

**Comment by ThilinaRajapakse** [comment]
You need a vocab file for the model as well. I used BioBert some time ago but I can't remember whether they had a released Pytorch version or whether I converted it myself. Either way, I've attached the vocab file I _think_ I used. Let me know if it works for you.
[vocab.txt](https://github.com/ThilinaRajapakse/simpletransformers/files/4182458/vocab.txt)

**Comment by wadhwasahil** [comment]
It's working. Thank You!!

Keep you the great work.

**Comment by RishiBugz** [comment]
> So I tried converting BioBert checkpoint which was in tensorflow to pytorch. So my folder has two things, **pytorch.bin** and **config.json**. However, when I try to run the

Could you please share the converted **pytorch.bin** and **config.json**?

**Comment by wadhwasahil** [comment]
@RishiBugz give me your email I will forward it you

**Comment by arjun-bhatt** [comment]
Can you please post the full code for using biobert with simpletransformers?
