### ISSUE TITLE
Possibility to exclude WandB?

### ISSUE THREAD

**Issue by tsavinho** [ThilinaRajapakse/simpletransformers#221]
Is there a possibility to exclude WandB from the pip package? The newest version 0.8.26 causes issues in Google Colab due to new dependencies that need six>=1.13.0, which is higher than the colab provided six=1.12.0. This renders this library unusable in Google Colab.

**Comment by ThilinaRajapakse** [comment]
I think it should still work even with the dependency issue (I get it locally as well). But I agree that wandb, while useful, should be optional rather than a dependency. I've changed it so that you can install wandb if you want to use it, but the library won't break if it's not.
