### ISSUE TITLE
DeepSpeed

### ISSUE THREAD

**Issue by nickcoch** [ThilinaRajapakse/simpletransformers#222]
I know it just came out today, but does DeepSpeed already work with SimpleTransformers?  

https://github.com/microsoft/DeepSpeed/blob/master/README.md

**Comment by ThilinaRajapakse** [comment]
Not yet. It's definitely something I'll look into but it's probably going to take a few days at least.

**Comment by tshrjn** [comment]
Is this supported now?

**Comment by ThilinaRajapakse** [comment]
Not yet.

**Comment by tshrjn** [comment]
Are there any plans to integrate fairscale and/or deepspeed?

**Comment by ThilinaRajapakse** [comment]
I want to, but I can't say for sure when/if it'll be done. I'm quite busy these days.
