### ISSUE TITLE
output_dir not created; where's model?

### ISSUE THREAD

**Issue by sherman6** [ThilinaRajapakse/simpletransformers#224]
**Describe the bug**
Hi there - are there any reasons why the output directory, 'outputs', is not being created for me?  
Training has completed, but I can't find my model.  _(Author Correction: "Feature Conversion" had finished, training had not)_

Details:  Training has completed (100% finished) _(Author Correction: it had not)_; the cache directory has been created by the code ("cache_dir"), results folder was created ("results") with the submission ("submission.json"), but I see no "outputs" folder. 

**To Reproduce**
I followed the steps described in the article, https://towardsdatascience.com/question-answering-with-bert-xlnet-xlm-and-distilbert-using-simple-transformers-4d8785ee762a.
Note, I loaded the models locally, rather than from the Hugging Face server.  All relevant files are within the same sub-directory within my working directory. 
Note, instead of creating 'data/', I just put the SQuAD2.0 json's in the same directory as the code.  I adjusted the code accordingly.  I also tried with a 'data/' folder.

**My attempts at troubleshooting:**
- I tried creating 'outputs/' prior to running the code, and just using the default argument for 'output_dir' - but no luck (nothing is inside). 
- I specified an 'output_dir': location as 'outputs/' - but with no luck 
- I specified an 'output_dir': location as a full directory pathway '/home/.../outputs/' - no luck
- I tried 'overwrite_output_dir': True
- I re-tried running all code from inside a separate directory (a fresh start) - no luck
- re-ran all code from inside a separate directory, this time creating the 'data/' folder - no luck

**Expected behavior**
By default, 'outputs/' is created within the main directory, and holds the trained model, right? I'm not getting any 'outputs/' directory, can't find my model.  
Note, there is a large, single file in the 'cache_dir' folder - is that my model?  

**Screenshots**
If applicable, I can add screenshots.

This shows that training has completed: 
![2020 scrnsht QA Model finished training](https://user-images.githubusercontent.com/56887273/74504951-7a8af780-4ebb-11ea-94cb-3c3186dd8dc5.JPG)

**Machine:**
 - I am running this from an ipynb on a linux-based server from my university. 
- I have 1 GPU available. 

**Additional context**
- I am attempting to train the bert-base-cased architecture on SQuAD 2.0, to create a QA Model. 
- I am also getting the below error, after training finishes, but I noticed it is within a 'try:' command:  is the module optional?  

model.train_model(train_data)
ModuleNotFoundError: No module named 'apex'
ImportError: Please install apex from https://www.github.com/nvidia/apex to use fp16 training.

Thanks - sherman6

**Comment by ThilinaRajapakse** [comment]
The tqdm bar you are seeing is probably the progress of feature conversion and not the training itself.  That is why the outputs folder is not being created.

Apex is an optional module that enables mixed precision training. If you aren't using it, set 
`'fp16': False`
in your args.

**Comment by sherman6** [comment]
Thanks for the quick reply!  

I'm not sure that answers my original question, however it does bring up new questions:

The step, `model.train_model(train_data)`, took approximately 22 minutes. Is that timing expected/reasonable, if only feature conversion had been accomplished, and I had been using use_cuda=True on an NVIDIA RTX 2080 GPU?  

What is in my cache_dir?   Screenshot of size:
 
  ![cache_dir_screenshot](https://user-images.githubusercontent.com/56887273/74538207-4fc39200-4f01-11ea-9b41-42a35b013526.JPG)


Will a submission be created (submission.json) even if training has not been completed?  
(my submission file is [linked here](https://github.com/sherman6/Text_Analysis/blob/master/submission.json) ).

Thanks!

**Comment by sherman6** [comment]
I have used the `'fp16': False` argument, and doublechecked the code, but here is what the output of the training line shows:   

![error apex module](https://user-images.githubusercontent.com/56887273/74546408-25c59c00-4f10-11ea-93f3-2f08954fa015.JPG)

It appears to end after feature conversion, but before training.

**Comment by ThilinaRajapakse** [comment]
I think it's unlikely that a dataset of ~130k samples will be completed in ~22 minutes on a RTX 2080, so it does seem reasonable. Also, the conversion speed depends on the CPU rather than the GPU.

Did you manage to get it to train?

**Comment by sherman6** [comment]
Thanks for the help troubleshooting, and letting me know what to expect on timing.  Using `'fp16': False`  fixed it (the model trained).  
I appreciate your help!
