### ISSUE TITLE
Weights and Biases Sweeps

### ISSUE THREAD

**Issue by splevine** [ThilinaRajapakse/simpletransformers#232]
I have been able to get the code working well and am very impressed by the smooth integration with weights and biases for experiment tracking.

I'm looking to move to the next step and start hyperparameter optimization (HPO). I've noticed that the weights and biases initialization and logging is done "under the hood." So far, I have been able to set up sweeps, but it seems to stop after the first sweep. 

I was wondering if there were any recommendations for using W&B sweeps for text classification. Is anybody else exploring this? Any guidance would be appreciated. Thanks!

**Comment by ThilinaRajapakse** [comment]
This is certainly something that I want to look into. It will be added as soon as I have the time to get it done.

I'm afraid I can't give any specific recommendations as I haven't tried this yet myself.
