### ISSUE TITLE
Confidences for predictions?

### ISSUE THREAD

**Issue by sherman6** [ThilinaRajapakse/simpletransformers#233]
For a QA Model, is it possible to get confidences for the predictions? Default prediction object seems to be a list of the 'id' and 'answer'. Thanks!

**Comment by ThilinaRajapakse** [comment]
It's a little more awkward with QA models but you can. It'll be saved in the `n_best_predictions.json` files in the output directory.

**Comment by sherman6** [comment]
Gotcha - is that file produced by default in the outputs directory, or is there anything special I need to do to see it?  Thanks.

**Comment by ThilinaRajapakse** [comment]
It's saved by default into the outputs directory.
