### ISSUE TITLE
File write error while training

### ISSUE THREAD

**Issue by brinew27** [ThilinaRajapakse/simpletransformers#24]
I received this error while training:

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-9-3553b5f6eb60> in <module>
      6 
      7 # Train the model
----> 8 model.train_model(train_df)
      9 
     10 # Evaluate the model

~\Miniconda3\envs\transformers\lib\site-packages\simpletransformers\model.py in train_model(self, train_df, output_dir, show_running_loss, args)
    140 
    141         train_dataset = self.load_and_cache_examples(train_examples)
--> 142         global_step, tr_loss = self.train(train_dataset, output_dir, show_running_loss=show_running_loss)
    143 
    144         if not os.path.exists(output_dir):

~\Miniconda3\envs\transformers\lib\site-packages\simpletransformers\model.py in train(self, train_dataset, output_dir, show_running_loss)
    405                         # Take care of distributed/parallel training
    406                         model_to_save = model.module if hasattr(model, "module") else model
--> 407                         model_to_save.save_pretrained(output_dir)
    408 
    409         return global_step, tr_loss / global_step

~\Miniconda3\envs\transformers\lib\site-packages\transformers\modeling_utils.py in save_pretrained(self, save_directory)
    202         # If we save using the predefined names, we can load using `from_pretrained`
    203         output_model_file = os.path.join(save_directory, WEIGHTS_NAME)
--> 204         torch.save(model_to_save.state_dict(), output_model_file)
    205         logger.info("Model weights saved in {}".format(output_model_file))
    206 

~\Miniconda3\envs\transformers\lib\site-packages\torch\serialization.py in save(obj, f, pickle_module, pickle_protocol)
    222         >>> torch.save(x, buffer)
    223     """
--> 224     return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
    225 
    226 

~\Miniconda3\envs\transformers\lib\site-packages\torch\serialization.py in _with_file_like(f, mode, body)
    145             (sys.version_info[0] == 3 and isinstance(f, pathlib.Path)):
    146         new_fd = True
--> 147         f = open(f, mode)
    148     try:
    149         return body(f)

FileNotFoundError: [Errno 2] No such file or directory: 'outputs/checkpoint-2000\\checkpoint-4000\\checkpoint-6000\\checkpoint-8000\\checkpoint-10000\\checkpoint-12000\\checkpoint-14000\\checkpoint-16000\\checkpoint-18000\\checkpoint-20000\\checkpoint-22000\\checkpoint-24000\\pytorch_model.bin'

It looks like it's creating another sub directory under each directory after each 2000 iterations. I'm assuming the path eventually becomes too long for windows and it fails. Any advice?

**Comment by ThilinaRajapakse** [comment]
It shouldn't be creating sub directories. A recent update must have messed with this, I'll check.

**Comment by ThilinaRajapakse** [comment]
Can you try it now please?

`pip install simpletransformers==0.4.5`

**Comment by brinew27** [comment]
This appears to have addressed the issue, thanks.
