### ISSUE TITLE
n_gpu is ignored

### ISSUE THREAD

**Issue by ErikTromp** [ThilinaRajapakse/simpletransformers#242]
When I run training for a model with n_gpu: 1 I see that (for this example I am running) ~4.5GB VRAM is used from my GPU. When I set n_gpu: 0, it still uses 4.5GB VRAM and uses the GPU for training.

Note that I am loading a model from disk, not a pretrained one.

**Comment by mirzakhalov** [comment]
If you set the "use_cuda" to False, it will use CPU instead. I am assuming it overrides the "n_gpus" somehow.

**Comment by ThilinaRajapakse** [comment]
Yeah, `use_cuda` is the arg that controls whether or not the GPU (or GPUs) are used.

**Comment by ErikTromp** [comment]
Confirmed

**Comment by ErikTromp** [comment]
Seems like I was too fast closing this. I suppose that if a model was once trained on a GPU I cannot finetune it on CPU?

```
>>> from simpletransformers.classification import MultiLabelClassificationModel
>>> model = MultiLabelClassificationModel('bert', 'bert-base-dutch-cased/bertje-base', num_labels=47, args={'use_cuda': False, 'train_batch_size':32, 'gradient_accumulation_steps':16, 'learning_rate': 1e-4, 'num_train_epochs': 5, 'max_seq_length': 256, 'fp16': False, 'reprocess_input_data': True, 'use_cached_eval_features': False, 'evaluate_during_training': True, 'evaluate_during_training_verbose': True, 'output_dir': 'outputs/'})
[... truncated for brevity]
cate 96.00 MiB (GPU 0; 8.00 GiB total capacity; 6.45 GiB already allocated; 16.54 MiB free; 12.65 MiB cached)
```

Note that I clearly state use_cuda: False yet it uses my GPU

**Comment by ThilinaRajapakse** [comment]
I made a mistake in my previous answer (I really need to stop responding to issues at 3 in the morning). `use_cuda` is a parameter to the init method and not an arg in the args dictionary. 

```
model = MultiLabelClassificationModel('bert', 'bert-base-dutch-cased/bertje-base', use_cuda=False)
```

**Comment by ErikTromp** [comment]
Ah I see, I could've (should've) read the readme better. My bad.
