### ISSUE TITLE
error on test data for NER

### ISSUE THREAD

**Issue by girijesh97** [ThilinaRajapakse/simpletransformers#243]
Hi,
I trained a custom NER model using simpletranformers library. I followed your sample code from your github repo [](https://github.com/ThilinaRajapakse/simpletransformers). I used the following line of code to create my model. Since I am using custom labels.

```
# Create a NERModel
model = NERModel('bert', 'bert-base-cased',labels=lbl, args={'overwrite_output_dir': True, 'reprocess_input_data': True}, use_cuda=False)
```
Training was pretty smooth. But when I tried to evaluate the model on test data. I am getting some error. Since the assertion error (AssertionError: ) is blank, I am not able to locate the exact issue.

Just a glimpse of my data

`train.shape` 
(273434, 3)

`test.shape`
(14392, 3)

I am attaching the screenshot of the error. Kindly look into it at your earliest convenience.
<img width="810" alt="i1" src="https://user-images.githubusercontent.com/19616698/75354402-ed8c6900-58d2-11ea-8c9d-d261851e423f.PNG">
<img width="853" alt="i2" src="https://user-images.githubusercontent.com/19616698/75354414-ef562c80-58d2-11ea-8084-f8a477fd6ad0.PNG">
<img width="837" alt="i3" src="https://user-images.githubusercontent.com/19616698/75354418-f0875980-58d2-11ea-8873-f8dfd5740332.PNG">
<img width="834" alt="i4" src="https://user-images.githubusercontent.com/19616698/75354421-f11ff000-58d2-11ea-9c82-0c76441c967a.PNG">
<img width="843" alt="i5" src="https://user-images.githubusercontent.com/19616698/75354424-f1b88680-58d2-11ea-9a34-681bdfe7fe57.PNG">

**Comment by Jean717p** [comment]
Probably linked to issue [#130](https://github.com/ThilinaRajapakse/simpletransformers/issues/130)
There is likely an error in the format of your test set.

**Comment by ThilinaRajapakse** [comment]
Yeah, this is most likely what is going on.

**Comment by girijesh97** [comment]
Well in my case it was sklearn train test split. I don't know the exact reason behind it but when I simply split data based on the index then error was resolved.

**Comment by zwd13122889** [comment]
hi,I followed the sample code from the github repo. I find some error.
![image](https://user-images.githubusercontent.com/49578851/76221220-b6637380-6253-11ea-8fef-02592e5c1062.png)
How i can add a path to the train_data?Thank you!
