### ISSUE TITLE
Unbalanced class for NER

### ISSUE THREAD

**Issue by seo-95** [ThilinaRajapakse/simpletransformers#245]
I'm training my model on the wikiNER dataset. I was wondering, since the 'O' NER tag is the most present, and since the library does not handle loss weights based on class support, why the final model does not try to always predict the 'O'?

**Comment by ThilinaRajapakse** [comment]
Probably because predicting 'O' for everything doesn't improve the loss. Did you run into this issue or is this a hypothetical question?

**Comment by seo-95** [comment]
> Probably because predicting 'O' for everything doesn't improve the loss. Did you run into this issue or is this a hypothetical question?

Is just an hypotetical question. Some weeks ago I tried to run my own NER BERT-based model but I have the issue that the model will always predict 'O'. I then solved by weighting the loss for each entity type but the results were lower compared to the actual state of the art (the most class with largest support reach 0.91 of f1, while other with minor support like MISC achieve only 0.79).

**Comment by ThilinaRajapakse** [comment]
That is interesting indeed. I would have said that BERT like models are capable of figuring out the difference between O labels and the others effectively so that it doesn't become a problem. But the fact that it didn't work on your own model might point to some other reason. Just to be sure, are you sure that the effect you observed was due to the class imbalance rather than some other implementation detail?

**Comment by seo-95** [comment]
> That is interesting indeed. I would have said that BERT like models are capable of figuring out the difference between O labels and the others effectively so that it doesn't become a problem. But the fact that it didn't work on your own model might point to some other reason. Just to be sure, are you sure that the effect you observed was due to the class imbalance rather than some other implementation detail?

The model implemented in your library does not have such a problem, so I think it could be something related with a wrong implementation of mine. I only wanted to listen for your opinion before taking this conclusion. So thank you!

**Comment by ThilinaRajapakse** [comment]
No problem!

**Comment by yoeldk** [comment]
Hi Guys,
I actually ran into this problem now - I trained a a NER "roberta-base" model and got zero for all recall/precision/f1 . My training/testing data contains just a small fraction of tokens with a label different than O (less than 1%).

**Comment by msobroza** [comment]
I had the same issue using NER from simpletransformers. If I use the transformers library directly in the same dataset there is not this issue.

**Comment by yoeldk** [comment]
Thanks @msobroza . I think a proper solution would be to add the option to add weights for the labels. 
I'd appreciate if you can share a sample code of how you trained your NER with the underlying transformers.

**Comment by ThilinaRajapakse** [comment]
> I had the same issue using NER from simpletransformers. If I use the transformers library directly in the same dataset there is not this issue.

Curious. I wonder if there's something missing in the NER implementation here then.

**Comment by msobroza** [comment]
I found the issue in my case was the format of the dataset. It needs a whitespace between the token and the label instead of a tabulation character.

**Comment by alwanrahmanas** [comment]
> Hi Guys, I actually ran into this problem now - I trained a a NER "roberta-base" model and got zero for all recall/precision/f1 . My training/testing data contains just a small fraction of tokens with a label different than O (less than 1%). I will try to remove some sentences containing only Os to improve the ratio and see if it helps.

i face the sam issue here. Does what you did work well?
