### ISSUE TITLE
MultiModalClassificationModel ImportError: cannot import name 'FlaubertConfig'

### ISSUE THREAD

**Issue by bharathichezhiyan** [ThilinaRajapakse/simpletransformers#246]
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from simpletransformers.classification.multi_modal_classification_model import MultiModalClassificationModel
I0228 15:15:43.452808 140543353997056 file_utils.py:35] PyTorch version 1.1.0 available.
/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:469: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:470: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:471: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:472: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:473: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/bharaj/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:476: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/bharaj/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bharaj/multimodal_work/simpletransformers/simpletransformers/classification/__init__.py", line 1, in <module>
    from simpletransformers.classification.classification_model import ClassificationModel
  File "/home/bharaj/multimodal_work/simpletransformers/simpletransformers/classification/classification_model.py", line 33, in <module>
    from transformers import (
ImportError: cannot import name 'FlaubertConfig'

**Describe the bug**
A clear and concise description of what the bug is. Please specify the class causing the issue.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS

**Additional context**

**Comment by TharinduDR** [comment]
Please update your transformers library to the most recent one. 
transformers 2.5.1

**Comment by bharathichezhiyan** [comment]
> Please update your transformers library to the most recent one.
> transformers 2.5.1

Thanks for quick answer. However it is little vague. 
Anyway it works. I found the solution. 

git clone https://github.com/huggingface/transformers
cd transformers
pip install .

When you update the repository, you should upgrade the transformers installation and its dependencies as follows:

git pull
pip install --upgrade .

**Comment by bharathichezhiyan** [comment]
>>> model = MultiModalClassificationModel("bert", "bert-base-uncased")
I0228 16:10:11.542361 140000799450880 configuration_utils.py:256] loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-config.json from cache at /home/bharaj/.cache/torch/transformers/4dad0251492946e18ac39290fcfe91b89d370fee250efe9521476438fe8ca185.8f56353af4a709bf5ff0fbc915d8f5b42bfff892cbb6ac98c3c45f481a03c685
I0228 16:10:11.543435 140000799450880 configuration_utils.py:292] Model config BertConfig {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": null,
  "do_sample": false,
  "eos_token_ids": null,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "is_decoder": false,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1
  },
  "layer_norm_eps": 1e-12,
  "length_penalty": 1.0,
  "max_length": 20,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_beams": 1,
  "num_hidden_layers": 12,
  "num_labels": 2,
  "num_return_sequences": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pad_token_id": null,
  "pruned_heads": {},
  "repetition_penalty": 1.0,
  "temperature": 1.0,
  "top_k": 50,
  "top_p": 1.0,
  "torchscript": false,
  "type_vocab_size": 2,
  "use_bfloat16": false,
  "vocab_size": 30522
}

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bharaj/multimodal_work/simpletransformers/simpletransformers/classification/multi_modal_classification_model.py", line 130, in __init__
    self.num_labels = self.config.num_labels
AttributeError: 'MultiModalClassificationModel' object has no attribute 'config'

**Comment by ThilinaRajapakse** [comment]
Yeah, there is a bug with MultiModalClassificationModel atm. The fix will be pushed soon, but in the meantime, you can work around it by specifying giving the positional argument `num_labels` when you create the model.

**Comment by ThilinaRajapakse** [comment]
Is this problem fixed now?

**Comment by srulikbd** [comment]
I had a similar problem:
"ImportError: cannot import name 'FlaubertConfig'"
I just updated the Transformers library and it's fixed.
thanks!
