### ISSUE TITLE
MultiModalClassificationModel - bug in labels type + the fix

### ISSUE THREAD

**Issue by yonatanbitton** [ThilinaRajapakse/simpletransformers#249]
File classification_utils.py, Method __getitem__ in JsonlDataset contains the following line:
`label = torch.tensor(self.labels.index(self.data[index][self.labels_label]))`

There is a bug here if `type(self.data[index][self.labels_label])` is int, and self.labels are all strings.
(The error message is `28 not in list`) 

This is what I did in order to fix it, and it was fixed: 
```
label_as_int = self.data[index][self.labels_label]
if label_as_int not in self.labels:
    label_as_int = str(label_as_int)
label = torch.tensor(self.labels.index(label_as_int))
```

Thanks

**Comment by ThilinaRajapakse** [comment]
This won't be an issue if all labels are strings, right?

**Comment by yonatanbitton** [comment]
It depends. 
I've started from strings, e.g "yellow", "blue", "red".
Then I had to transform it to numbers with label encoder:
"yellow" -> 0, "blue" -> 1, etc
Then it needs to ne converted back to numbers as string: 0 -> "0", and it won't cause a problem. But with words it does cause a problem. Regardless of the problem, thank you very much for this helpfull repo :)

**Comment by ThilinaRajapakse** [comment]
Do you need to use the label encoder? If I remember correctly, any kind of string labels should work for Multi-Modal tasks.

You are welcome!

**Comment by yonatanbitton** [comment]
Yes, I had to use it. 

df_train_cat['labels'].tail(2)
```
Out[6]: 
3198    yes
3199     no

model.train_model(df_train_cat, image_path=dataset_type_to_dir_map['train'] + os.sep + 'images',
                  show_running_loss=False)

Traceback (most recent call last):
  File "C:\Users\PC-1\.conda\envs\vqa_env\lib\site-packages\IPython\core\interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-e2124e79aa45>", line 2, in <module>
    show_running_loss=False)
  File "C:\Users\PC-1\.conda\envs\vqa_env\lib\site-packages\simpletransformers\classification\multi_modal_classification_model.py", line 335, in train_model
    **kwargs,
  File "C:\Users\PC-1\.conda\envs\vqa_env\lib\site-packages\simpletransformers\classification\multi_modal_classification_model.py", line 418, in train
    for step, batch in enumerate(tqdm(train_dataloader, desc="Current iteration", disable=args["silent"])):
  File "C:\Users\PC-1\.conda\envs\vqa_env\lib\site-packages\tqdm\std.py", line 1104, in __iter__
    for obj in iterable:
  File "C:\Users\PC-1\.conda\envs\vqa_env\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "C:\Users\PC-1\.conda\envs\vqa_env\lib\site-packages\torch\utils\data\dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "C:\Users\PC-1\.conda\envs\vqa_env\lib\site-packages\torch\utils\data\dataloader.py", line 881, in _process_data
    data.reraise()
  File "C:\Users\PC-1\.conda\envs\vqa_env\lib\site-packages\torch\_utils.py", line 394, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\PC-1\.conda\envs\vqa_env\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\PC-1\.conda\envs\vqa_env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\PC-1\.conda\envs\vqa_env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\PC-1\.conda\envs\vqa_env\lib\site-packages\simpletransformers\classification\classification_utils.py", line 481, in __getitem__
    label = torch.tensor(self.labels.index(label_as_int))
ValueError: 'yes' is not in list
```

**Comment by QAQOAO** [comment]
Did this errors be fixed?

I also got ValueError : [1,0,0,0,1,1,0,0,1,1] is not this list

my labels look like this

labels : [0 , 0 , 1 ,  ... ]

Can the required labels look like this form?

If not, how should I convert to the desired format?

**Comment by QAQOAO** [comment]
What do you mean "strings", though?

I converted it to ['0', '1', '0', '1', '1', '1', '0', '0', '0', '1'] but still got the same error.

I even tried just using one label without list like '0'

It didn't show the same error but at the end of training it showed me another ValueError : Input is not valid. Should be a string, ...

By the way, it showed me the warning below continuously while training.

"Token indices sequence length is longer than the specified maximum sequence length for this model (618 > 512). Running this sequence through the model will result in indexing errors"

So is it still the problem of my labels of other things?

**Comment by ThilinaRajapakse** [comment]
Can you show your training script and a few of your samples?

**Comment by QAQOAO** [comment]
OK, my code for training

model = MultiModalClassificationModel("bert", "bert-base-uncased", args={"label_list":label_cols})
model.train_model(train_df, files_list=file_list, image_path='/content/drive/My Drive/')

file_list : all the '___.png' in images column
label_cols : list of ten names of labels
train_df looks like this

   | text                           | images       |  labels
0 | an intersection of ... | Epochs.png | [0, 0, 0, 1, 0, 0, 0, 0, 1, 0]
1 | this here is real     ... | Ledisi.png   | [0, 1, 0, 1, 1, 0, 0, 1, 0, 0]
...  ....                                                     ........................

labels actually look like this if you want to check its type
[['0', '0', '0', '1', '0', '0', '0', '0', '1', '0'],
 ['0', '1', '0', '1', '1', '0', '0', '1', '0', '0'],
 ['1', '0', '0', '0', '0', '0', '1', '1', '1', '0'],
 ['0', '1', '0', '1', '1', '0', '0', '1', '1', '1'], ...]

the complete error
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/simpletransformers/classification/classification_utils.py", line 478, in __getitem__
    label = torch.tensor(self.labels.index(self.data[index][self.labels_label]))
ValueError: ['0', '1', '1', '1', '1', '0', '0', '1', '0', '0'] is not in list

**Comment by ThilinaRajapakse** [comment]
Multilabel tasks are not supported with multimodal models right now.

**Comment by QAQOAO** [comment]
Really? 

I saw "multi_label (optional): Set to True for multi label tasks." in "Args:" below "Creating a Model", 

so I thought it was fine to train multi-label tasks.

Anyway, will you add this support soon?

**Comment by higopires** [comment]
Having this issue right now. Tried to use yonatan's solution, with no success. Did I missed something?

```
def __getitem__(self, index):
        sentence = torch.LongTensor(self.tokenizer.encode(self.data[index][self.text_label], add_special_tokens=True))
        start_token, sentence, end_token = sentence[0], sentence[1:-1], sentence[-1]
        sentence = sentence[: self.max_seq_length]

        if self.multi_label:
            label = torch.zeros(self.n_classes)
            label[[self.labels.index(tgt) for tgt in self.data[index][self.labels_label]]] = 1
        else:
          label_as_int = self.data[index][self.labels_label]
          if label_as_int not in self.labels:
            label_as_int = str(label_as_int)
          label = torch.tensor(self.labels.index(label_as_int))
```

**Comment by mohamadhabash** [comment]
> Multilabel tasks are not supported with multimodal models right now.

Are multi-label tasks supported now? If not, will they be anytime soon?
Thank you.
