### ISSUE TITLE
Loading the  Saved Classification  Model

### ISSUE THREAD

**Issue by rambabusure** [ThilinaRajapakse/simpletransformers#253]
Hi,
I appreciate your time to develop the package. I am able to train the multi- class classification model and saved to a folder. How can we load the saved model ?

**Comment by aamin21** [comment]
Hope this helps: 

MultiLabelClassificationModel('distilbert', '.PATH/TO/YOUR/SAVED/MODEL', num_labels=158, use_cuda=False,args={'train_batch_size':2, 'gradient_accumulation_steps':16, 'learning_rate': 3e-5, 'num_train_epochs': 1, 'max_seq_length': 512})

**Comment by rambabusure** [comment]
Thanks
