### ISSUE TITLE
[feature request] will multi-choice QA be supported?

### ISSUE THREAD

**Issue by yuchenlin** [ThilinaRajapakse/simpletransformers#254]
Thanks for the great repo. Do you plan to support multi-choice qa? 

https://github.com/huggingface/transformers/blob/master/examples/run_multiple_choice.py

**Comment by ThilinaRajapakse** [comment]
I don't have any immediate plans to add multiple choice right now, but I don't think it won't be too hard to do. I'll keep this in mind and see whether I can squeeze it in when I have some free time.
