### ISSUE TITLE
Question and Answering

### ISSUE THREAD

**Issue by rambabusure** [ThilinaRajapakse/simpletransformers#257]
Currently , the predict method returns only one answer  in QuestionAnsweringModel . Is there any way to get all the nearest possible answers from the context and probability of the answer ?

**Comment by ThilinaRajapakse** [comment]
Looks like there is a bug somewhere in there. I'm looking into it. You can get the n_best_answers and probabilities with the `eval_model()` method though.

**Comment by LiuYYSS** [comment]
@ThilinaRajapakse I suspect there is something going wrong with"_get_best_indexes" method under "question_answerin_utils.py" file. the return value of this method is wrong. I haven't dug in deeply. However, I think you can spend some time on this method
