### ISSUE TITLE
simple transformers for QnA tasks

### ISSUE THREAD

**Issue by vivekam101** [ThilinaRajapakse/simpletransformers#26]
How can i customize simpletransformers library for question answering tasks. i've dataset in squad format.. Please help

**Comment by ThilinaRajapakse** [comment]
Question answering will be added to the library _soon_ (hopefully in a few days, but it depends on how much free time I get). Until then, there's an example with the Squad dataset on the Hugging Face library you can refer to if you want to give it a shot yourself.

**Comment by ThilinaRajapakse** [comment]
Question answering is now implemented.
