### ISSUE TITLE
from simpletransformers.classification import ClassificationModel

### ISSUE THREAD

**Issue by Adrizzledefizzle** [ThilinaRajapakse/simpletransformers#265]
**Describe the bug**
The line `from simpletransformers.classification import ClassificationModel` results in the error statet in the title.
**To Reproduce**
Set up new environment and follow the instructions in the repo. All required packeges loaded. execute line statet in Bugdescription

**Additional context**

Complete Errormsg:

```
from simpletransformers.classification import ClassificationModel
Traceback (most recent call last):

  File "<ipython-input-15-e269f817f0ec>", line 1, in <module>
    from simpletransformers.classification import ClassificationModel

  File "C:\Users\ga2943\AppData\Local\Continuum\anaconda3\envs\Envneuer\lib\site-packages\simpletransformers\classification\__init__.py", line 1, in <module>
    from simpletransformers.classification.classification_model import ClassificationModel

  File "C:\Users\ga2943\AppData\Local\Continuum\anaconda3\envs\Envneuer\lib\site-packages\simpletransformers\classification\classification_model.py", line 33, in <module>
    from transformers import (

ImportError: cannot import name 'FlaubertConfig' from 'transformers' (C:\Users\ga2943\AppData\Local\Continuum\anaconda3\envs\Envneuer\lib\site-packages\transformers\__init__.py)
```
Any ideas how to resolve it? Am I the only one with the problem?
Thanks in advance

**Comment by Adrizzledefizzle** [comment]
I can not solve the issue. I have

-Tensorboard 2.1.0
-TensorboardX 2.0
-Tensorflow 2.1.0
-Transformers 2.3.0
-Torch 1.4.0
-Tensorflow_hub 0.7.0
-Python 3.7.6
-Sklearn 0.22.2.post1
-Seqeval _version unknown_
-tqdm 4.43.0

installed. These are all the requirements I need to fulfill, they seem to be up to date. Why can I not import FlaubertConfig from the transformers library?
Really glad for help! regards

**Comment by ThilinaRajapakse** [comment]
Flaubert was added to Transformers in 2.4.1. There should be a way to install the latest version of Transformers. What package/environment manager are you using?

**Comment by Adrizzledefizzle** [comment]
I found the issue. I had another package called Sentence-Transformer in my venv. It forched Transformers back to a former version. Without Sentence-Transformer the code works. Thanks anyway :-)
