### ISSUE TITLE
clarification about "sliding_window"

### ISSUE THREAD

**Issue by acadTags** [ThilinaRajapakse/simpletransformers#266]
In the README.md file, it is said 

> This experimental feature moves a sliding window over each sequence and generates sub-sequences with length max_seq_length. The model output for each sub-sequence is averaged into a single output before being sent to the linear classifier.

However, I did not find how the "model output for each sub-sequence is averaged" from the code. It looks like all the sub-sequence were treated as an independent document for training, and they all share the same label. 

Could you help clarify this point? Many thanks!

Best wishes,
H

**Comment by ThilinaRajapakse** [comment]
The experimental sliding window feature with averaging is only implemented in `simpletransformers.experimental.classification.classification_model.py`. It is different from the one in the standard `simpletransformers.classification.classification_model.py` which simply splits longer sequences.

**Comment by acadTags** [comment]
> The experimental sliding window feature with averaging is only implemented in `simpletransformers.experimental.classification.classification_model.py`. It is different from the one in the standard `simpletransformers.classification.classification_model.py` which simply splits longer sequences.

Thanks! It looks like the original "sliding_window" for multi-label classification is now moved to "experimental features", if I am not wrong?

Best wishes,
H
