### ISSUE TITLE
Same prediction for different inputs

### ISSUE THREAD

**Issue by zahra-rou** [ThilinaRajapakse/simpletransformers#267]
I have created a multiclass classification model with 17 classes. Whenever I run the predict function for the first time, based on the number of strings in the input list a cache file is created which it seems to be messing with the next predictions. For example, if I pass a list with 3 strings to the predict function for the first time, the predictions are fine. But if run the predict function for the second time with 3 new strings, it will use the cache file created with the last call and it will give me the same results as previous call although the sentences are totally different from previous ones.

This is my model definition:
```
model definition:

model = ClassificationModel('bert', 'bert-base-cased', use_cuda=False, num_labels=17, args={																			

'train_batch_size': 8, 																				

'evaluate_during_training': True,																				

'evaluate_during_training_verbose': True,																				

'num_train_epochs': 6, 

ing_rate': 4e-5,																						

'reprocess_input_data': True, 																						

'overwrite_output_dir': True}) 
```

And this is the sample code that produces this problem:
```
# model train:

model.train_model(train_df, output_dir= model_path, eval_df=eval_df)

# prediction:

list = ['sample string 1', 'sample string 2', 'sample string 3'] 

predictions, raw_outputs = model.predict(list)

# output log:

Converting to features started. Cache is not used.

predictions: 

array([16, 10,  9])

list2 =  ['sample string 4', 'sample string 5', 'sample string 6'] 

predictions, raw_outputs = model.predict(list2)

# output log: 

Features loaded from cache at cache_dir/cached_dev_bert_128_17_3

predictions: 

array([16, 10,  9])   # This is wrong because it's only repeating the old predictions although the query sentences are completely different
```

It seems that the model only searchs for a cache file with same number of inputs, and it doesn't understand that the inputs are different in the second call. How can I fix this such that the model understands that the inputs are different and produces a new output?

**Comment by ThilinaRajapakse** [comment]
Looks like there was a bug hiding in the data loading method. This should be fixed now. Please let me know if it works properly now.

**Comment by zahra-rou** [comment]
Yes, thanks. It works fine now. Actually it doesn't save a cache file anymore, so everytime it predicts different from the previous pedictions.
