### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by kandalto** [ThilinaRajapakse/simpletransformers#268]
Hi!

I was following your excellent guide: https://towardsdatascience.com/question-answering-with-bert-xlnet-xlm-and-distilbert-using-simple-transformers-4d8785ee762a. 

While replicating your setup, I encountered an out of memory error: 

RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 1.96 GiB total capacity; 1.22 GiB already allocated; 2.69 MiB free; 37.42 MiB cached)

I created a toy dataset out of 10 SQuAD questions. I tried 'train_batch_size' =1 and 'eval_batch_size' = 1.  Reducing 'max_seq_length' doesn't help as well. I tried to look at question_answering_model.py , but couldn't find what consumes so much memory. 

Thanks!

**Comment by ThilinaRajapakse** [comment]
It's possible that 2 GB of GPU memory is not sufficient to use the model that you are trying to use. The model itself takes over 1 GB if I remember correctly.

**Comment by kandalto** [comment]
Thank you for the reply!

It seems like the model doesn't crush during training. While training, both full and toy datasets consume around 800mb of memory. It seems that the model crushes during the phase that comes after training (validation or saving the model). Maybe you have ideas how to free up some memory?

**Comment by ThilinaRajapakse** [comment]
Training usually takes up the most amount of GPU memory. I don't see how it could crash afterwards unless something weird is going on like the model being loaded twice.

**Comment by romainr** [comment]
Might be related https://github.com/ThilinaRajapakse/simpletransformers/issues/443
