### ISSUE TITLE
 'bert-base-japanese' not found... Support AutoTokenizer/AutoModel

### ISSUE THREAD

**Issue by gkaramanolakis** [ThilinaRajapakse/simpletransformers#269]
I tried to use 'bert-base-japanese':

`clf = ClassificationModel('bert', 'bert-base-japanese')
`

but I am getting the following error: "OSError: Model name 'bert-base-japanese' was not found in tokenizers model name list..."

The reason is that bert-base-japanese requires a BertJapaneseTokenizer instead of the standard BertTokenizer. Indeed, when I use AutoTokenizer/Automodel, I load 'bert-base-japanese' without any issues: 

```
from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained('bert-base-japanese')
model = AutoModel.from_pretrained('bert-base-japanese')
```
 (The tokenizer object is: <transformers.tokenization_bert_japanese.BertJapaneseTokenizer at 0x7fd6382c2150>.)

It would be great to support BertJapaneseTokenizer in this repo. It would be even better to switch to AutoTokenizer/AutoModel to avoid any similar future issues.  

Thanks!

**Comment by ThilinaRajapakse** [comment]
I'll add support for the BertJapaneseTokenizer soon. I'm holding off the AutoTokenizer/fast tokenizers stuff until the dust settles down a bit. I want to see where they are headed first.
