### ISSUE TITLE
runtime error torch.cuda.FloatTensor Torch.FloatTensor mismatch

### ISSUE THREAD

**Issue by MrRobot2211** [ThilinaRajapakse/simpletransformers#27]
HI I have set apex. An I am trying to run the example code but there appears to be a conflict.

RuntimeError: Found param roberta.embeddings.word_embeddings.weight with type torch.FloatTensor, expected torch.cuda.FloatTensor.
When using amp.initialize, you need to provide a model with parameters
located on a CUDA device before passing it no matter what optimization level
you chose. Use model.to('cuda') to use the default device.

**Comment by ThilinaRajapakse** [comment]
Can you give me the exact steps you followed to the point where you got this error, please?

**Comment by MrRobot2211** [comment]
conda install pytorch
 installed apex with the recommended installation
pip install simple-transformes

The rest of the packages were already installes



Interestingly enough when I set 
args={'fp16': False}
it runs

**Comment by ThilinaRajapakse** [comment]
Is this for the classifier model or the NER model? Either way, that's an odd error to get. Which line in the example code is generating the error?

**Comment by MrRobot2211** [comment]
It is for the classifier
odel = TransformerModel('roberta', 'roberta-base')
model.train_model(train_df) _> this line raises error

**Comment by MrRobot2211** [comment]
I am copying the full traceback 
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-25-435cd7a772e7> in <module>
      1 # Train the model
----> 2 model.train_model(train_df,output_dir="../data/output-gputest1")

~/anaconda3/lib/python3.7/site-packages/simpletransformers/model.py in train_model(self, train_df, output_dir, show_running_loss, args)
    142 
    143         train_dataset = self.load_and_cache_examples(train_examples)
--> 144         global_step, tr_loss = self.train(train_dataset, output_dir, show_running_loss=show_running_loss)
    145 
    146         if not os.path.exists(output_dir):

~/anaconda3/lib/python3.7/site-packages/simpletransformers/model.py in train(self, train_dataset, output_dir, show_running_loss)
    353                     "Please install apex from https://www.github.com/nvidia/apex to use fp16 training.")
    354 
--> 355             model, optimizer = amp.initialize(model, optimizer, opt_level=args["fp16_opt_level"])
    356 
    357         if args["n_gpu"] > 1:

~/anaconda3/lib/python3.7/site-packages/apex/amp/frontend.py in initialize(models, optimizers, enabled, opt_level, cast_model_type, patch_torch_functions, keep_batchnorm_fp32, master_weights, loss_scale, cast_model_outputs, num_losses, verbosity, min_loss_scale, max_loss_scale)
    356         maybe_print("{:22} : {}".format(k, v), True)
    357 
--> 358     return _initialize(models, optimizers, _amp_state.opt_properties, num_losses, cast_model_outputs)
    359 
    360 

~/anaconda3/lib/python3.7/site-packages/apex/amp/_initialize.py in _initialize(models, optimizers, properties, num_losses, cast_model_outputs)
    169 
    170     if not _amp_state.allow_incoming_model_not_fp32:
--> 171         check_params_fp32(models)
    172 
    173     # In the future, when FP16_Optimizer can be deprecated and master weights can

~/anaconda3/lib/python3.7/site-packages/apex/amp/_initialize.py in check_params_fp32(models)
     91                         "located on a CUDA device before passing it no matter what optimization level\n"
     92                         "you chose. Use model.to('cuda') to use the default device.".format(
---> 93                         name, param.type()))
     94 
     95         # Backward compatibility for PyTorch 0.4

~/anaconda3/lib/python3.7/site-packages/apex/amp/_amp_state.py in warn_or_err(msg)
     30         print("Warning:  " + msg)
     31     else:
---> 32         raise RuntimeError(msg)
     33         # I'm not sure if allowing hard_override is a good idea.
     34         # + "  If you're sure you know what you're doing, supply " +

RuntimeError: Found param roberta.embeddings.word_embeddings.weight with type torch.FloatTensor, expected torch.cuda.FloatTensor.
When using amp.initialize, you need to provide a model with parameters
located on a CUDA device before passing it no matter what optimization level
you chose. Use model.to('cuda') to use the default device.

**Comment by MrRobot2211** [comment]
Solved it it was a problem with torch not detecting CUDA. WHen seting CUDA=True in the model ando not finding it , should throw an error or a warning.
