### ISSUE TITLE
Cached file saving disabled with UTF-8 encoding error

### ISSUE THREAD

**Issue by jseale** [ThilinaRajapakse/simpletransformers#272]
All my cached files have errors similar to this: 
Error! /path/cached_dev_bert_128_2_573 is not UTF-8 encoded. Saving disabled. 

**To Reproduce**
I'm training a text classifier like this:
model.train_model(train_df[:5], 
                  args={'sliding_window': True, 
                        'num_train_epochs' : 1,
                        'overwrite_output_dir' : True, 
                        'cache_dir' : '{}/bio_cache'.format(path)})

**Desktop**
 - Ubuntu on an EC2 instance

**Comment by ThilinaRajapakse** [comment]
I can't reproduce this locally. It looks like the error occurs when trying to read the cached file. Maybe they got corrupted somehow.

Try adding `"reprocess_input_data": True` to args.
