### ISSUE TITLE
How to load dynamically quantized model for binary classification model

### ISSUE THREAD

**Issue by suryapa1** [ThilinaRajapakse/simpletransformers#273]
**Describe the bug**
I have converted Roberta model (1.4gb) to the 500MB suing quantization provided below, but while loading the model using simple classification model ,it is downloading the pre-trained model again. is there any way to bypass the loading process

Actual Model :
==========
model = ClassificationModel('robert','model_base_path')
torch.save(model.model.state_dict(), "model.pth")
model.model.load_state_dict(torch.load('model.pth'))
model.model.eval()
print(model)

Quantized Model:
========
model_qu= Classification('bert','bert-base')
quantized_model = torch.quantization.quantize_dynamic(
    model_qu.model, {torch.nn.Linear}, dtype=torch.qint8
)

How should I load the quantized model and do inference on the same 👍 

model_qu.predict() kind of, i could not load the same as Actual load as am facing this error.. kindly help me out..

RuntimeError: Error(s) in loading state_dict for RobertaForSequenceClassification:
	Missing key(s) in state_dict: "roberta.encoder.layer.0.attention.self.query.weight", "roberta.encoder.layer.0.attention.self.query.bias", "roberta.encoder.layer.0.attention.self.key.weight", "roberta.encoder.layer.0.attention.self.key.bias", "roberta.encoder.layer.0.attention.self.value.weight", "roberta.encoder.layer.0.attention.self.value.bias", "roberta.encoder.layer.0.attention.output.dense.weight", "roberta.encoder.layer.0.attention.output.dense.bias", "roberta.encoder.layer.0.intermediate.dense.weight", "roberta.encoder.layer.0.intermediate.dense.bias", "roberta.encoder.layer.0.output.dense.weight", "roberta.encoder.layer.0.output.dense.bias", "roberta.encoder.layer.1.attention.self.query.weight", "roberta.encoder.layer.1.attention.self.query.bias", "roberta.encoder.layer.1.attention.self.key.weight", "roberta.encoder.layer.1.attention.self.key.bias", "roberta.encoder.layer.1.attention.self.value.weight", "roberta.encoder.layer.1.attention.self.value.bias", "roberta.encoder.layer.1.attention.output.dense.weight", "roberta.encoder.layer.1.attention.output.dense.bias", "roberta.encoder.layer.1.intermediate.dense.weight", "roberta.encoder.layer.1.intermediate.dense.bias", "roberta.encoder.layer.1.output.dense.weight", "roberta.encoder.layer.1.output.dense.bias", "roberta.encoder.layer.2.attention.self.query.weight", "roberta.encoder.layer.2.attention.self.query.bias", "roberta.encoder.layer.2.attention.self.key.weight", "roberta.encoder.layer.2.attention.self.key.bias"...
	Unexpected key(s) in state_dict: "roberta.encoder.layer.0.attention.self.query.scale",

**Comment by ThilinaRajapakse** [comment]
Quantized models aren't natively supported. The `predict()` method won't work as quantized models require special treatment for the inputs.

You should be able to quantize and save a trained model with Simple Transformers but using the saved model will have to be done on your end at the moment.

**Comment by suryapa1** [comment]
Okay..

model_qu= Classification('bert','bert-base')
quantized_model = torch.quantization.quantize_dynamic(
model_qu.model, {torch.nn.Linear}, dtype=torch.qint8
)

Above code generate a quantized model for me, then how to deal these quantized model here to pass on inputs  Could you share some inputs on this please.

**Comment by ThilinaRajapakse** [comment]
That will need to be done in PyTorch. You'll have to create a class that can use the quantized model. I'm afraid I can't give you any specifics as I've never done it myself.

**Comment by erip** [comment]
@suryapa1 If you figure this out, I'd love if you could report your findings here. ඉස්තුති for the awesome library, @ThilinaRajapakse!

**Comment by ThilinaRajapakse** [comment]
You are welcome! (and nice touch :wink: )

**Comment by suryapa1** [comment]
Hi guys,
I have done some code on the quantization of models here. However, the outputs for actual model & quantized models are varying and also not sure why time taken for quantization is more in this context.

Quantization Code:
============
model_qu= Classification('bert','bert-base')
model_qu.train()
Got model directory after training few epochs.

Code for Quantization:
=============
quantized_model = torch.quantization.quantize_dynamic(
model_qu.model, {torch.nn.Linear}, dtype=torch.qint8
)



## Saving Quantized Model
quantized_model.save_pretrianed("quantized_output_dir")
{Any better way to save quantized models for deseraialize inference)

### Loading the Quantized Model in regular style of simple_transformer way
quantized_output_dir is the 
Model_quantized = ClassificationModel('bert', quantized_output_dir, use_cuda=False), Not sure why saving & loading for inferece is yielding different resutls for Normal model.predict & quantizedMoel.predict along with more inference for quantized model

Any comments on these would help to point out the issue here!!!

**Comment by suryapa1** [comment]
Btw, quantized size were  were reduced 1/3rd actual model size.. But inference speed & accuracy are going for a toss..
