### ISSUE TITLE
Can predict data be reused after processing on first model and pass to subsequent models on inference time

### ISSUE THREAD

**Issue by suryapa1** [ThilinaRajapakse/simpletransformers#274]
**Describe the bug**
I want to pipeline  inference data around 200 rows through multiple binary classifiers about 30 binary classification models and get consolidated results from  all of them

Overall i want to improvise the performance of the entire pipeline, as it taking hours to process

1)Any way to process data for first model and reuse same for others by caching or some other mechanism???

Your inputs are greatly helpful..

**Comment by ThilinaRajapakse** [comment]
The converted features (from words into tensors of numbers) can be cached (and should be cached automatically).

A more radical change would be to use a multilabel classifier instead of multiple binary classifiers. I am not sure whether that would work in your use case but a multilabel classifier is essentially a collection of binary classifiers.

**Comment by suryapa1** [comment]
Thanks for the information.



Inference Model:
===========

 model_create_args = {
	  'overwrite_output_dir': True,
	  'max_seq_length' : 256,
	  'reprocess_input_data': True,
	  'use_cached_eval_features': False,
	  'no_cache' : True,
	  'output_dir':'model1_save_dir',
  }

model1_to_create = ClassificationModel('bert', model1_save_dir, num_labels=2,args=model_create_args))
model1_to_create.train_model(train_df_300rows)

Model is saved in 'model1_save_dir'  at first step
================================


inference_train_args = {
	 'reprocess_input_data' :True,
	  'use_cached_eval_features': False,
	  'no_cache' : True,	  
}

Loading Model & Infer Model steps:

model1_to_infer = ClassificationModel('roberta', 'model1_save_dir', num_labels=2, use_cuda=False, args=inference_train_args)

model1_to_infer.predict(pred_df_300rows)


model2_to_infer = ClassificationModel('roberta', 'model2_save_dir', num_labels=2, use_cuda=False, args=inference_train_args)

model2_to_infer.predict(pred_df_300rows)

Actually, I have trained model1,model2.. model10 classifiers already using cache disabled and generated 10 model files. Will, it is possible to inference all classifiers one by one by caching at first inference time (by passimng cache=True in loading models as shoen above)  so that i won't cache every time new model is loaded.Basically i want to improvise the performance  of pipeline here. 

i tried model2_to_infer with cache enabled,  but still it is not takling cache as it might taking from train arguments alone.. please clarify ??

**Comment by ThilinaRajapakse** [comment]
The `predict()` method never caches anything as it is designed to be used for one-off predictions. I think the easiest way for you to use caching would be to use the `eval_model()` method instead. Just give your pred_df a dummy labels columns and collect the predictions from `eval_model()`.
