### ISSUE TITLE
Is it possible to train the model again and integrating up into the existing trained model file!

### ISSUE THREAD

**Issue by djSharma7** [ThilinaRajapakse/simpletransformers#277]
I have trained a multi label model with 10k rows and now  i have new 15k rows.
Is it possible that i can train the model with new 15 k rows and the result comes out to be merged result of previous and present trained model?

**Comment by ThilinaRajapakse** [comment]
You _can_ retrain your fine-tuned model on the new dataset but I would recommend just doing the training by scratch for the whole dataset.

**Comment by djSharma7** [comment]
Tried fine tuning again with the new dataset but i don't believe i'm getting it right!!
Can you let me know the right arguments i must be having !

**Comment by ThilinaRajapakse** [comment]
That would fall under continual learning which is beyond the scope of this library. Hypothetically, if you were to retrain the same transformer model on new data every week, the best-case scenario would probably be the model learning from the new data while "forgetting" the previous training. Worst-case would be that continuous training eventually leads to catastrophic forgetting.

**Comment by CMobley7** [comment]
I had a few similar question to this. How do I use a previously trained in-domain LM to create my classifier? How could I load a previously trained classier, binary in this case, and use it to predict on new unseen data?
