### ISSUE TITLE
Calling succesive eval_model returns the same value

### ISSUE THREAD

**Issue by MrRobot2211** [ThilinaRajapakse/simpletransformers#28]
Hi, I am trying todo a binary classification.
The model seems to train well , but when calling an eval model on one dataframe and then on other keeps returning the same values of the first eval. 
For example

_,output,_=model.eval_model(df_train)
_,output2,_=model.eval_model(df_train.head())

returns equal outputs both in value and llength

**Comment by ThilinaRajapakse** [comment]
It is probably caching the first data frame. Set reprocess_input_data to True for the model. 

`model = TransformerModel('roberta', 'your_model', args={'reprocess_input_data': True})`

**Comment by MrRobot2211** [comment]
Excellent.Solved.Than you very much.
