### ISSUE TITLE
class weights adjusted for imbalnce data problem

### ISSUE THREAD

**Issue by suryapa1** [ThilinaRajapakse/simpletransformers#281]
Could converge the binary imbalanced data problem using class weight as balanced. However, still, i couldn't reduce the no. of FP and increase TP. Please suggest some other way to improvise FP to TP by adjusting of cost function any arguments forsake. Even training more epochs didnt helped me anyway. Please throw some light on direction of convergence in improivising true psoitives.

train results:
{'mcc': 0.5744784130736582, 'tp': 37, 'tn': 1346, 'fp': 9, 'fn': 48, 'acc': 0.564885496183206, 'eval_loss': 0.36999255191080416}

test results:
{'mcc': 0.2027032450879563, 'tp': 12, 'tn': 1173, 'fp': 23, 'fn': 63, 'acc': 0.21818181818181817, 'eval_loss': 1.4085788520832976}

**Comment by ThilinaRajapakse** [comment]
You could try increasing the weight for the positive samples further.
