### ISSUE TITLE
ERROR: got an unexpected keyword argument 'logdir'

### ISSUE THREAD

**Issue by jonathan-goh** [ThilinaRajapakse/simpletransformers#284]
Hi there,

I am just running the Minimal Start for Multiclass Classification codes.

But I keep getting the unexpected keyword argument 'logdir' when I run model.train_model(train_df).

How do i get pass this problem?

I am using the latest version of SimpleTransformers.

**Comment by ThilinaRajapakse** [comment]
Can you post the full error message? Seems like an issue with Tensorboard.

**Comment by jonathan-goh** [comment]
![Capture](https://user-images.githubusercontent.com/20589514/77516144-cbc3d900-6eb4-11ea-8779-4f74bc259f3f.JPG)

This is the full error. I also think the issue is with tensorboard, probably a version issue or something

**Comment by ThilinaRajapakse** [comment]
Yeah, you probably need to update tensorboard. The older version used `log_dir` instead of `logdir`.

**Comment by jonathan-goh** [comment]
or can I simply disable tensorboard?

Would that work?

**Comment by ThilinaRajapakse** [comment]
It would, but there is no way to simply disable it with Simple Transformers. You would have to edit it out yourself.
