### ISSUE TITLE
using XLM-R for multiclass classification

### ISSUE THREAD

**Issue by aeshapar** [ThilinaRajapakse/simpletransformers#286]
I'm trying to train XLM-R for multiclass classification on a small dataset (1000 text samples), and it has been displaying "Converting to features started. Cache is not used" repeatedly, along with progress bars, for the past 6-7 hours. Since preprocessing/training/testingfor mBERT was taking only about 25 min on the same dataset, I would expect the duration to be similar for XLM-R. 
What could be causing feature conversion to take so long?

**Comment by ThilinaRajapakse** [comment]
It's possible that the message is being generated from `evaluate_during_training`. Are you using that feature?

**Comment by aeshapar** [comment]
Yes, I am using the evaluate_during_training feature. However, I still can't make sense of what is taking it so long?

**Comment by ThilinaRajapakse** [comment]
It might be because the interval between evaluations is too small. Try turning it off and see whether the performance improves.

**Comment by aeshapar** [comment]
The issue persists even when I turn off the evaluate_during_training feature.

**Comment by ThilinaRajapakse** [comment]
Can you show the output?
