### ISSUE TITLE
Very slow training for simpletransformers compared to transformers? 

### ISSUE THREAD

**Issue by PieterDujardin** [ThilinaRajapakse/simpletransformers#288]
I am trying out the simpletransformers for a NER-task on a movie review dataset. I first trained a model (using a GPU accessed through the collab) with the standard transformers API and this got me good performance and reasonably fast training (for 5 epochs). When I now try the simpletransformers API, it takes much longer to do even one epoch. At the end of the training, I get similar performance with both API's, but there is quite a difference in time...  It might be that I am doing something wrong but since the interface of the simpletransformers is so 'simple' I do not know what it could be... Any suggestions?

FYI: the train_df is a dataframe
```
model = NERModel("bert", "bert-base-cased",labels = ['I-SONG','I-YEAR','B-TRAILER','I-CHARACTER','I-TRAILER','I-DIRECTOR','B-YEAR','B-PLOT','I-GENRE','I-REVIEW','B-CHARACTER','O',
                                                     'I-PLOT','B-REVIEW','B-RATINGS_AVERAGE','B-SONG','B-RATING','I-RATING','I-ACTOR','I-TITLE','B-TITLE','B-ACTOR','B-DIRECTOR','B-GENRE','I-RATINGS_AVERAGE'] 
                 ,use_cuda=True, args={"overwrite_output_dir": True, "reprocess_input_data": True})

model.train_model(train_df)
```

**Comment by ThilinaRajapakse** [comment]
Are you using the same training parameters for both experiments (particularly batch sizes)? If so, can you share a colab notebook that I can run quickly to verify the issue?
