### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 1)

### ISSUE THREAD

**Issue by djstrong** [ThilinaRajapakse/simpletransformers#292]
ValueError in evaluation if `labels` and `preds` are all ones (or zeros). Then `confusion_matrix` returns an array 1x1.

https://github.com/ThilinaRajapakse/simpletransformers/blob/7529ee13f9ac9bb2251b93ffec7b083027dbe757/simpletransformers/classification/classification_model.py#L833

**Comment by djstrong** [comment]
Fix `confusion_matrix(labels, preds, labels=[0,1])` will be correct?

**Comment by suryapa1** [comment]
Does this fix goes to simple transformer API ??
