### ISSUE TITLE
model.predict() function

### ISSUE THREAD

**Issue by KingLeo2000** [ThilinaRajapakse/simpletransformers#299]
the predict function has modified the passed in data and I have trouble in evaluating model performance (Kfold)
![image](https://user-images.githubusercontent.com/52401767/78417404-dff99a00-765b-11ea-9ff6-7a5a93e698e3.png)

**Comment by ThilinaRajapakse** [comment]
The predict function doesn't use ground truths (it sets them to blank to prevent the model from breaking when the answers/truth isn't specified). You should use the `eval_model()` method to do an evaluation.
