### ISSUE TITLE
question answering save model issue 

### ISSUE THREAD

**Issue by jeugregg** [ThilinaRajapakse/simpletransformers#300]
https://github.com/ThilinaRajapakse/simpletransformers/blob/4472e21df38cef510a3b33cb5322e7f588df6e03/simpletransformers/question_answering/question_answering_model.py#L433

_save_model method  failed and program stops  with default args when doing a Question/Answering training.
It is because _save_model need two more positional arguments : optimizer, scheduler

**Comment by ThilinaRajapakse** [comment]
Looks like some method calls weren't updated properly. This should be fixed now.

**Comment by jeugregg** [comment]
OK. it is fixed. thanks
