### ISSUE TITLE
Custom corpus

### ISSUE THREAD

**Issue by JeffSaa** [ThilinaRajapakse/simpletransformers#302]
Hi I want to use a pretrained model Bert for any task but I need to use my own corpus with my own tokenizer. It is possible with this library?

**Comment by ThilinaRajapakse** [comment]
You can. The tokenizer will be loaded from the same directory where your model files are. So you can put your model files and your tokenizer files into a directory and provide the path to that directory as the `model_name`.

**Comment by Shane-Neeley** [comment]
Can you use community models this way? Like transformers `from_pretrained("emilyalsentzer/Bio_ClinicalBERT")`

**Comment by ThilinaRajapakse** [comment]
The `from_pretrained()` method will be called internally with whatever value you pass for `model_name` when creating a model.

`model = ClassificationModel("bert", "emilyalsentzer/Bio_ClinicalBERT")`

This should work.
