### ISSUE TITLE
Training Roberta for QuestionAnswering

### ISSUE THREAD

**Issue by rohitsingh02** [ThilinaRajapakse/simpletransformers#303]
Can you please add support for `roberta`  for QA. I have tried adding myself but ran into this error `RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling cublasCreate(handle)`.
Thanks in advance.

**Comment by ThilinaRajapakse** [comment]
Unfortunately, there is no ready to use `RobertaForQuestionAnsweringModel` in transformers. I'll look into implementing it myself, but I can't be sure when that'll be.
