### ISSUE TITLE
ELECTRA model

### ISSUE THREAD

**Issue by djstrong** [ThilinaRajapakse/simpletransformers#304]
Recently, transformers added ELECTRA model. It would be useful here.

**Comment by ThilinaRajapakse** [comment]
Been working on this for the last couple of days. Should be ready soon.

**Comment by djstrong** [comment]
Thank you!

**Comment by ThilinaRajapakse** [comment]
You are welcome!

It's live!

**Comment by djstrong** [comment]
Can it be used for text classification?

**Comment by ThilinaRajapakse** [comment]
ELECTRA is more of a pre-training method than an entirely new model. The final model is nearly identical to BERT. Because of this, we only have it for language modelling atm.

**Comment by flozi00** [comment]
Electra for multilabel classification tasks would be very nice.
Is the way to implement the same as in ner task ?

**Comment by ThilinaRajapakse** [comment]
Yeah, I'll probably be adding it soon for the other tasks.

**Comment by Shane-Neeley** [comment]
Trying to run the minimal-start-for-multilabel-classification from the readme: 

```
Traceback (most recent call last):
  File "test_simpletransformers.py", line 2, in <module>
    from simpletransformers.classification import MultiLabelClassificationModel
  File "/Users/mm_shane/anaconda3/envs/transformers/lib/python3.6/site-packages/simpletransformers/classification/__init__.py", line 2, in <module>
    from simpletransformers.classification.multi_label_classification_model import MultiLabelClassificationModel
  File "/Users/mm_shane/anaconda3/envs/transformers/lib/python3.6/site-packages/simpletransformers/classification/multi_label_classification_model.py", line 8, in <module>
    from simpletransformers.custom_models.models import (
  File "/Users/mm_shane/anaconda3/envs/transformers/lib/python3.6/site-packages/simpletransformers/custom_models/models.py", line 14, in <module>
    from transformers import ElectraForMaskedLM, ElectraForPreTraining
ImportError: cannot import name 'ElectraForMaskedLM'
```

**Comment by ThilinaRajapakse** [comment]
You need to update the transformers library.

`pip install --upgrade transformers`

**Comment by ThilinaRajapakse** [comment]
ELECTRA is now supported for classification, ner, and question answering.

**Comment by djstrong** [comment]
@ThilinaRajapakse Now, I see that `ElectraForSequenceClassification` is implemented in transformers, but here you have made your own implementation. Would it be okay to replace your implementation with transformers one to simplify code?

**Comment by ThilinaRajapakse** [comment]
Yeah, it's probably a good idea.
