### ISSUE TITLE
Issue in Binary Sequence Tagging using NERModel

### ISSUE THREAD

**Issue by Raphy-N** [ThilinaRajapakse/simpletransformers#307]
I am trying to train the NERModel with my own dataset for binary sequence tagging. I don't know if there are issues in my dataset. I've attached my training and evaluation data as Excel files here.

I made sure that the data is exactly as the NER example showed. Here is my Notebook on Colab:
[Notebook](https://colab.research.google.com/drive/1qInwvnDXAZG197kIkc0nZnbmsyGSSXSs)

After I changed the dtypes of "words" and "labels" columns to strings, the **train_model** method showed no error. But the **eval_model** method continues to give the error:
AttributeError: 'NAType' object has no attribute 'strip'
I do not know how to figure out why this error occurs. The dev-set data came from the same noisy source as my train-set. Please help me out. THANK YOU!

-----UPDATE------
I removed all NaN values by pd.df.dropna(). The **train_model** method completes without error, but I get two other errors:

1. The **eval_model** method doesn't returns predictions equal to the examples it received in **eval_df**
2. The **predict** method doesn't work. It still uses the 9 standard NER tags at back-end.

Please see if these bugs can be resolved. Thanks!

[dev-set.xlsx](https://github.com/ThilinaRajapakse/simpletransformers/files/4459008/dev-set.xlsx)
[train-set.xlsx](https://github.com/ThilinaRajapakse/simpletransformers/files/4459009/train-set.xlsx)

**Comment by ThilinaRajapakse** [comment]
Can you check and see which examples are missing from `eval_model()`?

The `predict()` method doesn't use the standard tags. It uses whatever is set as the `labels` for the model. There is a potential issue with data preprocessing inside the `predict()` function if the `O` tag is not present. I think this is probably leftover from earlier versions where custom labels were not supported. If your error is something along the lines of "O" missing, you are probably running into this issue. I'll push a fix to that shortly.
