### ISSUE TITLE
One hot encoding to BERT for multilabel classification

### ISSUE THREAD

**Issue by wadhwasahil** [ThilinaRajapakse/simpletransformers#309]
Hi there,

I have used **simpletransformers** for multilabel classification where my input was just a bunch of sentences. Now I want to add more features to the classifier. These features would be numerical arrays. Is there a way where I can get the embeddings of the sentences and augment them with my numerical data and get final multilabel predictions? 

Thanks

**Comment by ThilinaRajapakse** [comment]
Maybe a look at the `MultiModalClassificationModel` will help? I think it is similar to what you want to do.

The general idea would be to write your own model class that incorporates the multilabel classification model as well as the additional features you want.

**Comment by krannnn** [comment]
@wadhwasahil did you make any progress in this matter? I have the same idea that I want to implement and I started using simple transformers as well for the basic text multi-label classification and now I want to add features ( one hot encoded vector) to the model/classifier while training.
@ThilinaRajapakse  can you elaborate more please on your comment? I'm confused between using the MultiModalClassificationModel or the MultiLabelClassificationModel and making changes to the latter to make this possible ?

**Comment by ThilinaRajapakse** [comment]
You'll need to make changes to the MultiLabelClassificationModel. My suggestion was to look at the MultiModalClassificationModel to get an idea about how this could be done.
