### ISSUE TITLE
Logging training losses tied to evaluate during training 

### ISSUE THREAD

**Issue by Pradhy729** [ThilinaRajapakse/simpletransformers#314]
For the classification models, I want to plot my model training losses by epoch to compare how different models train. Why is _create_training_progress_scores tied to the "evaluate during training" argument? What if I don't have a eval dataframe but simply want to track training losses/acc during training? Could we maybe store and return train losses/accs in the train_model method by default regardless of whether evaluation happens?

**Comment by ThilinaRajapakse** [comment]
Training losses will be logged with Tensorboard even if you aren't using evaluation. Does that help with your use case?

**Comment by Pradhy729** [comment]
Yeah I think that does what most of what I need. Thanks.
Maybe we could optionally log a few more metrics like accuracy. Let me know if you like the idea and I can help add that to the args.

**Comment by AMR-KELEG** [comment]
> Training losses will be logged with Tensorboard even if you aren't using evaluation. Does that help with your use case?

Hi @ThilinaRajapakse,
Are there any updates regarding this feature?

**Comment by ThilinaRajapakse** [comment]
You will need to do an evaluation if you want to calculate accuracy metrics. So, if you are going to be doing it anyway, you can simply pass the `train_df` itself as the `eval_df` and use the `evaluation_during_training` feature. I don't think it makes sense to duplicate the same feature for the tensorboard logs.

**Comment by Pradhy729** [comment]
How about something like the compute metrics functionality that they have in transformers [Trainer](https://github.com/huggingface/transformers/blob/master/src/transformers/trainer.py) Class. It basically gives you an option of creating a function that takes in preds and labels and you can create a function that calculates any metrics you want using those two tensors.

**Comment by ThilinaRajapakse** [comment]
It's been implemented in Simple Transformers from the beginning.
