### ISSUE TITLE
Improvement suggestion: black formatting & pre-commit hooks

### ISSUE THREAD

**Issue by jmrf** [ThilinaRajapakse/simpletransformers#315]
As the library grows in complexity and contributors, could be a nice improvement to adhere to `pep8` formatting guidelines and guarantee linting before commits.

I usually use `black` formatter which, in addition to adhere to pep8 also minimizes diffs across changes.

One way to simplify the use of this kind of tools is using `pre-commit hooks`. Which makes it an automatic process applying this linting tools before a commit.

Would this be of interest?

If so happy to submit a PR to include it

**Comment by ThilinaRajapakse** [comment]
We already use black (albeit with 120 line length limit) and flake8 for linting and style checking. (`make lint`)

Would using pre-commit hooks add a significant benefit to this? I was under the impression that pre-commit hooks have to be installed and run locally. I might be mistaken though!

I do think that it's about time we add a contributions guideline. :sweat_smile:

**Comment by jmrf** [comment]
Oh I see!

Actually Flavius, friend of mine, added what you mentioned in a `Makefile`. Perfect!

You are totally right, `pre-commit hooks` are executed locally, is git who invokes the hooks on execution of the `commit`.

I think we can safely close this one. Apologies for the noise :sweat_smile:

**Comment by ThilinaRajapakse** [comment]
Yes, your friend was very insistent (and rightly so) that we follow pep-8 and use black! His PR added all of it.
