### ISSUE TITLE
Sliding windows for classification

### ISSUE THREAD

**Issue by fatotoro** [ThilinaRajapakse/simpletransformers#316]
Hi - the description for the sliding windows seems to differ between what is given in readme in the section for classification and the experimental features - I wonder if  it is the mode or an averaged embedding that is used for final prediction? Also for the sliding window is there overlapping text between windows if the stride is smaller than 1? Thanks!

**Comment by ThilinaRajapakse** [comment]
With experimental features, the mean of all the _windows_ is used for classification. With the normal classification model, the mode of all predictions for each _window_ is given as the final prediction.

Yeah, a stride smaller than 1 will mean overlapping text.

**Comment by fatotoro** [comment]
Got it. Thanks a lot!
