### ISSUE TITLE
expected torch.cuda.FloatTensor

### ISSUE THREAD

**Issue by vkocaman** [ThilinaRajapakse/simpletransformers#32]
Here is the error when I try to run the basic example

Found param roberta.embeddings.word_embeddings.weight with type torch.FloatTensor, expected torch.cuda.FloatTensor.
When using amp.initialize, you need to provide a model with parameters
located on a CUDA device before passing it no matter what optimization level
you chose. Use model.to('cuda') to use the default device.

**Comment by ThilinaRajapakse** [comment]
If you are not using CUDA (or running on CPU), you have to disable CUDA.

```
model = TransformerModel('bert', 'bert-base-cased', use_cuda=False)
```

**Comment by vkocaman** [comment]
still same... please see the full descriotion

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-ad87da0deaa7> in <module>()
     14 
     15 # Train the model
---> 16 model.train_model(train_df)
     17 
     18 # Evaluate the model

/anaconda3/lib/python3.6/site-packages/simpletransformers/model.py in train_model(self, train_df, output_dir, show_running_loss, args)
    142 
    143         train_dataset = self.load_and_cache_examples(train_examples)
--> 144         global_step, tr_loss = self.train(train_dataset, output_dir, show_running_loss=show_running_loss)
    145 
    146         if not os.path.exists(output_dir):

/anaconda3/lib/python3.6/site-packages/simpletransformers/model.py in train(self, train_dataset, output_dir, show_running_loss)
    353                     "Please install apex from https://www.github.com/nvidia/apex to use fp16 training.")
    354 
--> 355             model, optimizer = amp.initialize(model, optimizer, opt_level=args["fp16_opt_level"])
    356 
    357         if args["n_gpu"] > 1:

/anaconda3/lib/python3.6/site-packages/apex/amp/frontend.py in initialize(models, optimizers, enabled, opt_level, cast_model_type, patch_torch_functions, keep_batchnorm_fp32, master_weights, loss_scale, cast_model_outputs, num_losses, verbosity, min_loss_scale, max_loss_scale)
    356         maybe_print("{:22} : {}".format(k, v), True)
    357 
--> 358     return _initialize(models, optimizers, _amp_state.opt_properties, num_losses, cast_model_outputs)
    359 
    360 

/anaconda3/lib/python3.6/site-packages/apex/amp/_initialize.py in _initialize(models, optimizers, properties, num_losses, cast_model_outputs)
    168 
    169     if not _amp_state.allow_incoming_model_not_fp32:
--> 170         check_params_fp32(models)
    171 
    172     # In the future, when FP16_Optimizer can be deprecated and master weights can

/anaconda3/lib/python3.6/site-packages/apex/amp/_initialize.py in check_params_fp32(models)
     90                         "located on a CUDA device before passing it no matter what optimization level\n"
     91                         "you chose. Use model.to('cuda') to use the default device.".format(
---> 92                         name, param.type()))
     93 
     94         # Backward compatibility for PyTorch 0.4

/anaconda3/lib/python3.6/site-packages/apex/amp/_amp_state.py in warn_or_err(msg)
     30         print("Warning:  " + msg)
     31     else:
---> 32         raise RuntimeError(msg)
     33         # I'm not sure if allowing hard_override is a good idea.
     34         # + "  If you're sure you know what you're doing, supply " +

RuntimeError: Found param bert.embeddings.word_embeddings.weight with type torch.FloatTensor, expected torch.cuda.FloatTensor.
When using amp.initialize, you need to provide a model with parameters
located on a CUDA device before passing it no matter what optimization level
you chose. Use model.to('cuda') to use the default device.

**Comment by ThilinaRajapakse** [comment]
`model = TransformerModel('bert', 'bert-base-cased', use_cuda=False, args={'fp_16': False})`

I'm sorry, I forgot about the fp_16 argument.

**Comment by ThilinaRajapakse** [comment]
```
model = TransformerModel('bert', 'bert-base-cased', use_cuda=False, args={'fp16': False})
```

Should be `fp16`.

**Comment by vkocaman** [comment]
Great, it worked ! thx .. is it possible to make this compatible with TF backend, instead of torch ? and in Spark as well?

**Comment by ThilinaRajapakse** [comment]
I didn't do anything specific to include TF support (I _dislike_ working with TF :sweat_smile:) or other platforms like Spark. What do you want to do with TF/Spark?

**Comment by vkocaman** [comment]
letting it run over large train datasets with distributed processing (Spark)

**Comment by ThilinaRajapakse** [comment]
Multi GPU training will be added in the next update (still in Pytorch). Unfortunately, I don't have much experience with Spark, so I don't really know how to support it.

**Comment by Aoudsung** [comment]
i want to cuda rather than cpu,how can i do (i have the same problem)

**Comment by petervandenabeele** [comment]
So, there are 2 fixes:

* Work-around:

Do _not_ use nvidia cuda and fp16 on a laptop (with a small GPU) works well. E.g. in the Binary Classification example https://simpletransformers.ai/docs/binary-classification/
To avoid `ImportError("Please install apex from https://www.github.com/nvidia/apex to use fp16 training.")`

Work-around (CPU only) (I did not need to set `fp16` : False in the model_args for this to work):

```
# Create a ClassificationModel
model = ClassificationModel(
    "roberta", "roberta-base", args=model_args, use_cuda=False
)
```

* Install apex:

On Ubuntu 20.04 this originally fails because of the default gcc version 9 that is installed (with the error:

`/usr/local/cuda/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!`

The "work-around" I used for that is to use update-alternatives to use gcc and g++ version 8.
That is described here:

https://github.com/NVIDIA/apex/issues/278#issuecomment-633218502
