### ISSUE TITLE
Does the simpletranformer is used for multioutput as well???

### ISSUE THREAD

**Issue by GawandeC** [ThilinaRajapakse/simpletransformers#323]
@ThilinaRajapakse  does the simpletransformer is used to predict multiple values like category & subcategory both??

**Comment by GawandeC** [comment]
@ThilinaRajapakse

**Comment by ThilinaRajapakse** [comment]
I am not sure exactly what you mean, but, you can do multiclass and multilabel classification with Simple Transformers.

**Comment by GawandeC** [comment]
I mean I need to predict multiple output.
i.e single model should predict category & subcategory both

**Comment by ThilinaRajapakse** [comment]
If I am understanding correctly, that would be a multilabel classification.

**Comment by GawandeC** [comment]
in my case multilable classification will not work as it having binary output.

Multioutput regression assigns each sample a set of target values. This can be thought of as predicting several properties for each data-point, such as wind direction and magnitude at a certain location.

**Comment by ThilinaRajapakse** [comment]
Ah, I see. I'm afraid that is not supported at the moment. Regression is limited to a single output.
