### ISSUE TITLE
Unable to train language model from scratch

### ISSUE THREAD

**Issue by MatthewCaron** [ThilinaRajapakse/simpletransformers#324]
Somehow, I get the following error:

```
"model_name and tokenizer_name are not specified."
ValueError: model_name and tokenizer_name are not specified.You must specify train_files to train a Tokenizer.
```

when trying to train a language model from scratch using the provided example:

```
train_args = {
    "reprocess_input_data": True,
    "overwrite_output_dir": True,
    "vocab_size": 52000,
}

model = LanguageModelingModel('roberta', None, args=train_args)
model.train_model(train_file=TRAIN, eval_file=VAL)
```

Am I missing something here? According to the documentation, "_Setting model_name to None will indicate that the language model should be trained from scratch_".

simpletransformers ==  0.24.8 
tokenizers == 0.5.2
transformers == 2.8.0

**Comment by ThilinaRajapakse** [comment]
To train a new tokenizer with your train file, you can do;

`model = LanguageModelingModel('roberta', None, args=train_args, train_files=train_file)`

This looks to be missing from the docs.

Alternatively, you should also be able to use a pre-trained tokenizer by specifying it in the train args.

E.g.
```
train_args = {
    "reprocess_input_data": True,
    "overwrite_output_dir": True,
    "vocab_size": 52000,
    "tokenizer_name": "roberta-base"
}
```

**Comment by MatthewCaron** [comment]
Thanks! Adding the `train_files` parameter did the trick! It may also be important to mention that the `"vocab_size"` argument is also required in order to train a model from scratch.

**Comment by MatthewCaron** [comment]
Thanks! Adding the `train_files` parameter did the trick! It may also be important to mention that the `"vocab_size"` argument is also required in order to train a model from scratch.
