### ISSUE TITLE
To Feed raw input vectors for Classificaiton Model training

### ISSUE THREAD

**Issue by suryapa1** [ThilinaRajapakse/simpletransformers#327]
1. Build simple Text Classification Model using Roberta by feeding raw_text and label
2. I want to retrain model incrementally in next run with new training data as numerical vectors, 

Queries:
1. Does simple transformers Classifcation model supports feeding raw input vectors, some thing like (tokenizer.encode("raw new train data"))  as i have restriction to save text in prodcution as feedback loop, if so, How can you leverage existing API.

**Comment by ThilinaRajapakse** [comment]
This is not supported directly. However, I think you might be able to leverage the feature caching functionality to do something like this. Keep in mind that it will be _extremely_ hacky.

If you check out the `load_and_cache_examples()` method, you'll see that it looks for a cached features file on disk before doing the conversions. If you can create a file with the new training data converted into features (numeric), give it the expected name, and pass in a dummy DF (should contain the same number of rows as the training data) to the `train_model()` method, you just might be able to make it work.

Again, I'm afraid it's quite ugly and hacky.
