### ISSUE TITLE
Can torchvision import be made optional

### ISSUE THREAD

**Issue by pHequals7** [ThilinaRajapakse/simpletransformers#329]
So from the code, I can see this package can be used for vision applications as well hence in the classification utils code you have imported torchvision, but when I'm using it for only NLP purposes, that import becomes unnecessary, especially if I'm trying to deploy it to a service like Heroku where the slugsize is capped at 500MB for free/student tiers. Can you suggest a workaround here?

Thanks

**Comment by ThilinaRajapakse** [comment]
I can look into making the import optional. A workaround would be to simply delete the import line in your local package. I don't _think_ this would cause issues for the NLP tasks.

**Comment by flaviussn** [comment]
I also agree with @pHequals7. `torchvision` should not cause any issue with a `standalone` package, but, if you use `simpletransformers` along with others packages this would potentially cause problems. As long as this is a NLP library, I think that `torchvision` should be optional. :thinking:

**Comment by ThilinaRajapakse** [comment]
The reason for including `torchvision` is the multi-modal classification functionality which needs it. Making it optional would mean that multi-modal classification wouldn't work _out of the box_, so to speak.

But, I do see your guys' point as this is _primarily_ an NLP library. I am in two minds about this so if you feel it's best to make it optional, I'd be inclined to agree. Unless there is another solution which could solve both problems.

**Comment by flaviussn** [comment]
Implemented in [v0.27.3](https://github.com/ThilinaRajapakse/simpletransformers/releases/tag/0.27.3)
