### ISSUE TITLE
NER >>  'InputFeatures' object has no attribute 'label_ids'

### ISSUE THREAD

**Issue by vkocaman** [ThilinaRajapakse/simpletransformers#33]
I created my custom label list and stated in the NerModel.. but I got the following error

/anaconda3/lib/python3.6/site-packages/simpletransformers/ner/ner_model.py in train_model(self, train_data, output_dir, show_running_loss, args)
    144         self._move_model_to_device()
    145 
--> 146         train_dataset = self.load_and_cache_examples(train_data)
    147 
    148         global_step, tr_loss = self.train(train_dataset, output_dir, show_running_loss=show_running_loss)

/anaconda3/lib/python3.6/site-packages/simpletransformers/ner/ner_model.py in load_and_cache_examples(self, data, evaluate, no_cache, to_predict)
    524         all_input_mask = torch.tensor([f.input_mask for f in features], dtype=torch.long)
    525         all_segment_ids = torch.tensor([f.segment_ids for f in features], dtype=torch.long)
--> 526         all_label_ids = torch.tensor([f.label_ids for f in features], dtype=torch.long)
    527 
    528         dataset = TensorDataset(all_input_ids, all_input_mask, all_segment_ids, all_label_ids)

/anaconda3/lib/python3.6/site-packages/simpletransformers/ner/ner_model.py in <listcomp>(.0)
    524         all_input_mask = torch.tensor([f.input_mask for f in features], dtype=torch.long)
    525         all_segment_ids = torch.tensor([f.segment_ids for f in features], dtype=torch.long)
--> 526         all_label_ids = torch.tensor([f.label_ids for f in features], dtype=torch.long)
    527 
    528         dataset = TensorDataset(all_input_ids, all_input_mask, all_segment_ids, all_label_ids)

AttributeError: 'InputFeatures' object has no attribute 'label_ids'

**Comment by ThilinaRajapakse** [comment]
Can you show me your setup code?

**Comment by vkocaman** [comment]
I removed the labels (kept it default, but still same)

model = NERModel('bert', 'bert-base-cased', use_cuda=False, args={'fp16': False})

model.train_model('conll2003/eng.train', output_dir="transformers_ner")

**Comment by ThilinaRajapakse** [comment]
I couldn't reproduce this error but this may have happened in an older version.

Can you try using the most recent version (0.6.0)?

**Comment by vkocaman** [comment]
I just did.. but no change...

anaconda3/lib/python3.6/site-packages/simpletransformers/ner/ner_model.py in train_model(self, train_data, output_dir, show_running_loss, args)
    151         self._move_model_to_device()
    152 
--> 153         train_dataset = self.load_and_cache_examples(train_data)
    154 
    155         global_step, tr_loss = self.train(train_dataset, output_dir, show_running_loss=show_running_loss)

/anaconda3/lib/python3.6/site-packages/simpletransformers/ner/ner_model.py in load_and_cache_examples(self, data, evaluate, no_cache, to_predict)
    531         all_input_mask = torch.tensor([f.input_mask for f in features], dtype=torch.long)
    532         all_segment_ids = torch.tensor([f.segment_ids for f in features], dtype=torch.long)
--> 533         all_label_ids = torch.tensor([f.label_ids for f in features], dtype=torch.long)
    534 
    535         dataset = TensorDataset(all_input_ids, all_input_mask, all_segment_ids, all_label_ids)

/anaconda3/lib/python3.6/site-packages/simpletransformers/ner/ner_model.py in <listcomp>(.0)
    531         all_input_mask = torch.tensor([f.input_mask for f in features], dtype=torch.long)
    532         all_segment_ids = torch.tensor([f.segment_ids for f in features], dtype=torch.long)
--> 533         all_label_ids = torch.tensor([f.label_ids for f in features], dtype=torch.long)
    534 
    535         dataset = TensorDataset(all_input_ids, all_input_mask, all_segment_ids, all_label_ids)

AttributeError: 'InputFeatures' object has no attribute 'label_ids'

**Comment by ThilinaRajapakse** [comment]
Does the minimal example with the pandas DFs work?

**Comment by vkocaman** [comment]
Yep I have no problem with that.. I just have an issue with NERModel

**Comment by ThilinaRajapakse** [comment]
```
from simpletransformers.ner import NERModel


model = NERModel('bert', 'bert-base-cased', args={'reprocess_input_data': True, 'overwrite_output_dir': True})

model.train_model('data/train.txt')

results, model_outputs, predictions = model.eval_model('data/eval.txt')
```

This is working for me. For reference, my `train.txt` file looks like this.

[train.txt](https://github.com/ThilinaRajapakse/simpletransformers/files/3820504/train.txt)

**Comment by vkocaman** [comment]
Ok got it.. the followıng works for me.. thx !

from simpletransformers.ner import NERModel

model = NERModel('bert', 'bert-base-cased',use_cuda=False, args={'reprocess_input_data': True, 'fp16': False, 'overwrite_output_dir': True})

model.train_model('transformer_ner_train.txt', output_dir="ner_output")

results, model_outputs, predictions = model.eval_model('transformer_ner_eval.txt')

**Comment by vkocaman** [comment]
it just takes too much time to train though.. does it work with DistillBert ?

**Comment by ThilinaRajapakse** [comment]
Great!

Not at the moment. Bert is the only model that supports token level classification so far.

**Comment by vkocaman** [comment]
The NER training is finally done after 24 hrs ! I trained 5 epoches with CoNLL 2003 dataset.. here are the metrics:

{'eval_loss': 0.05429522173813599, 'precision': 0.9506276150627615, 'recall': 0.9568733153638814, 'f1_score': 0.9537402401141801}

Looks promising ! which DL architecture is being used to train this model ?

**Comment by ThilinaRajapakse** [comment]
Nice!

```
model = NERModel('bert', 'bert-base-cased', args={'reprocess_input_data': True, 'overwrite_output_dir': True})
```
The architecture is a Bert model. The weights are from bert-base-cased.

**Comment by vkocaman** [comment]
No no, I mean the DL architecture for NER training.. Bert embeddings are used as features and then trained with CRF layer I guess ?

**Comment by ThilinaRajapakse** [comment]
It's a BERT core model with a linear classification layer on top. The classification layer takes the BERT outputs for all tokens in the sequence and assigns a label to each (instead of just using the pooled output as in sequence classification). The training process is finetuning the BERT layers as well as the classification layer. 

```
class BertForTokenClassification(BertPreTrainedModel):
    def __init__(self, config):
        super(BertForTokenClassification, self).__init__(config)
        self.num_labels = config.num_labels

        self.bert = BertModel(config)
        self.dropout = nn.Dropout(config.hidden_dropout_prob)
        self.classifier = nn.Linear(config.hidden_size, config.num_labels)

        self.init_weights()

    def forward(self, input_ids=None, attention_mask=None, token_type_ids=None,
                position_ids=None, head_mask=None, inputs_embeds=None, labels=None):

        outputs = self.bert(input_ids,
                            attention_mask=attention_mask,
                            token_type_ids=token_type_ids,
                            position_ids=position_ids,
                            head_mask=head_mask,
                            inputs_embeds=inputs_embeds)

        sequence_output = outputs[0]

        sequence_output = self.dropout(sequence_output)
        logits = self.classifier(sequence_output)

        outputs = (logits,) + outputs[2:]  # add hidden states and attention if they are here
        if labels is not None:
            loss_fct = CrossEntropyLoss()
            # Only keep active parts of the loss
            if attention_mask is not None:
                active_loss = attention_mask.view(-1) == 1
                active_logits = logits.view(-1, self.num_labels)[active_loss]
                active_labels = labels.view(-1)[active_loss]
                loss = loss_fct(active_logits, active_labels)
            else:
                loss = loss_fct(logits.view(-1, self.num_labels), labels.view(-1))
            outputs = (loss,) + outputs

        return outputs  # (loss), scores, (hidden_states), (attentions)
```

Full code [here](https://huggingface.co/transformers/_modules/transformers/modeling_bert.html#BertForTokenClassification).

**Comment by vkocaman** [comment]
Thanks for the explanation and link !

**Comment by ThilinaRajapakse** [comment]
You are welcome!
