### ISSUE TITLE
add multiprocessing option to convert_examples_to_features in question_answering_utils

### ISSUE THREAD

**Issue by alexucb** [ThilinaRajapakse/simpletransformers#335]
@ThilinaRajapakse is there any plan to include multiprocessing option in _convert_examples_to_features_ in simpletransformers/question_answering/question_answering_utils.py? for a large train set (say 200k paragraphs and each has 3 q-a pairs), this step is the rate_limiting_step for model training. Thanks in advance.

**Comment by ThilinaRajapakse** [comment]
Yeah, I can look into it. I think this was just overlooked on my end.
