### ISSUE TITLE
Language model fine-tuning of dbmdz/bert-base-italian-xxl-cased'

### ISSUE THREAD

**Issue by freeIsa** [ThilinaRajapakse/simpletransformers#337]
Hello, I am trying to use simpletransformers to fine-tune the Italian version of BERT ('dbmdz/bert-base-italian-xxl-cased') with my own dataset. As an exercise, I also would like to do the same directly with the transformers package. I have set the same seed for both projects, and tried to ensure that the language model is always trained with the same training_args, so I would expect to get the same results when running the two versions of my code. However, results are slightly different. Can you please suggest other sources of discrepancies I may have to look into?

Moreover, I intended to use the "line_by_line" dataset_type, but I cannot get this to work under simpletransformers (whereas it does work when using transformers directly) with the above mentioned Bert model, as I get the following error message:

```
100         tokenizer = ByteLevelBPETokenizer(
--> 101             f"{args['tokenizer_name']}/vocab.json", f"{args['tokenizer_name']}/merges.txt",
    102         )
[...]
Exception: Error while initializing BPE: No such file or directory (os error 2)
```

Thank you in advance for any help you can give me with these issues!

**Comment by ThilinaRajapakse** [comment]
How different are the results? Are you using the same dataset type in both libraries?

Looks like something is going wrong with loading the tokenizer. Does this only happen for `bert` models and "line_by_line" datasets?

**Comment by freeIsa** [comment]
Results are not dramatically different, differences were in the order of 1e-01 (when using the same dataset type, of course).
As per your last question, I only tried with that one model (Bert type), and yes, the error seems to arise only when trying to use the line_by_line dataset type; otherwise the tokenizer is loaded correctly.

**Comment by ThilinaRajapakse** [comment]
I'm not sure what is causing the difference, but I think it can be safely ignored if the difference are minimal.

I'll look into the BERT issue. I suspect the wrong tokenizer is being loaded.
