### ISSUE TITLE
Error while installing simpletransformers

### ISSUE THREAD

**Issue by Sreelakshmi-k** [ThilinaRajapakse/simpletransformers#34]
i get an error while installing simpletransformer. I command i have ran and the error is given below. Could you suggest me a solution. I am also getting error while installing apex.

pip install simpletransformers
ERROR: Could not find a version that satisfies the requirement simpletransformers (from versions: none)
ERROR: No matching distribution found for simpletransformers

**Comment by ThilinaRajapakse** [comment]
What is your operating system?

**Comment by Sreelakshmi-k** [comment]
Thank you for your response sir. I am using gpu.

**Comment by ThilinaRajapakse** [comment]
I meant operating system as in Ubuntu, windows, Mac, etc.

**Comment by Sreelakshmi-k** [comment]
Ubuntu.

**Comment by ThilinaRajapakse** [comment]
Did you install all the prerequisite packages given in the readme? What is the error you get when installing apex?

**Comment by Sreelakshmi-k** [comment]
yes i installed all the prerequisits
This is the error that i got while installing apex

No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'

    Compiling cuda extensions with
    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2016 NVIDIA Corporation
    Built on Tue_Jan_10_13:22:03_CST_2017
    Cuda compilation tools, release 8.0, V8.0.61
    from /usr/local/cuda/bin

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-3n6d93c7/setup.py", line 100, in <module>

check_cuda_torch_binary_vs_bare_metal(torch.utils.cpp_extension.CUDA_HOME)
      File "/tmp/pip-req-build-3n6d93c7/setup.py", line 77, in
check_cuda_torch_binary_vs_bare_metal
        "https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  "
    RuntimeError: Cuda extensions are being compiled with a version of Cuda
that does not match the version used to compile Pytorch binaries.  Pytorch
binaries were compiled with Cuda 10.1.243.
    In some cases, a minor-version mismatch will not cause later errors:
https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  You can try
commenting out this check (at your own risk).
    Running setup.py install for apex ... error
  Rolling back uninstall of apex
  Moving to
/home/namosvision/.virtualenvs/cv/lib/python3.5/site-packages/apex-0.1.dist-info/
   from
/home/namosvision/.virtualenvs/cv/lib/python3.5/site-packages/~pex-0.1.dist-info
  Moving to
/home/namosvision/.virtualenvs/cv/lib/python3.5/site-packages/apex/
   from /home/namosvision/.virtualenvs/cv/lib/python3.5/site-packages/~pex
  Replacing
/home/namosvision/.virtualenvs/cv/lib/python3.5/site-packages/apex-0.1.dist-info/
from
/home/namosvision/.virtualenvs/cv/lib/python3.5/site-packages/~pex-0.1.dist-info
  Replacing
/home/namosvision/.virtualenvs/cv/lib/python3.5/site-packages/apex/ from
/home/namosvision/.virtualenvs/cv/lib/python3.5/site-packages/~pex
Cleaning up...
  Removing source in /tmp/pip-req-build-3n6d93c7
Removed build tracker '/tmp/pip-req-tracker-cgh6bu2j'
ERROR: Command errored out with exit status 1:
/home/namosvision/.virtualenvs/cv/bin/python3 -u -c 'import sys,
setuptools, tokenize; sys.argv[0] =
'"'"'/tmp/pip-req-build-3n6d93c7/setup.py'"'"';
__file__='"'"'/tmp/pip-req-build-3n6d93c7/setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
--cpp_ext --cuda_ext install --record
/tmp/pip-record-3lz27_a8/install-record.txt
--single-version-externally-managed --compile --install-headers
/home/namosvision/.virtualenvs/cv/include/site/python3.5/apex Check the
logs for full command output.
Regards,
Sreelakshmi

**Comment by ThilinaRajapakse** [comment]
What python version are you using? Usually this error is because you are using an incompatible version of python and/or required packages.

**Comment by Sreelakshmi-k** [comment]
Python 3

**Comment by ThilinaRajapakse** [comment]
Make sure you are using 3.7. Also, can you install transformers without any errors?

`pip install transformers`

**Comment by Sreelakshmi-k** [comment]
S i am able to install transformers. There is no error in that

**Comment by ThilinaRajapakse** [comment]
Try cloning the repo and running `pip -m install .`

**Comment by Sreelakshmi-k** [comment]
Ok sir i will try that. Thank you so much for your response sir. If the
issue still persists I will mail you.

**Comment by Sreelakshmi-k** [comment]
Thank you sir for your suggestion. I was able to install without error.

**Comment by ThilinaRajapakse** [comment]
Great.
