### ISSUE TITLE
TypeError when classifying with fine-tuned Distilbert model - Am I doing it right?

### ISSUE THREAD

**Issue by bdalal** [ThilinaRajapakse/simpletransformers#340]
I finetuned `distilbert-base-uncased` on some of my own data using the example provided in the readme as a reference.
I'm now load this finetuned model like so:

    args = {
    "fp16": False, 
    "evaluate_during_training": True, 
    "save_model_every_epoch": False, 
    "save_eval_checkpoints": False,
    "num_train_epochs":20, 
    "use_early_stopping": True,
    "do_lower_case": True,
    "output_dir": "outputs/distilbert-base-finetuned-classifier/",
    "best_model_dir": "outputs/distilbert-base-finetuned-classifier/",
    "wandb_project": "distilbert-base-finetuned-classifier",
    "reprocess_input_data": True,
    "use_cached_eval_features": False
    }
    model = ClassificationModel('distilbert-base-finetuned', 'outputs/distilbert-base-finetuned', num_labels=9, use_cuda=True, args=args)

Note: I modified `classification_models.py` and added a line to the `MODEL_CLASSES` so the name I've used gets picked up: `"distilbert-base-finetuned": (DistilBertConfig, DistilBertForSequenceClassification, DistilBertTokenizer),`

When I start training now on my classification dataset, I get the following error:

    TypeErrorTraceback (most recent call last)
    <ipython-input-8-cb300fa642b9> in <module>
    ----> 1 model.train_model(train_df, eval_df=val_df)

    ~/miniconda3/envs/classification/lib/python3.8/site-packages/simpletransformers/classification/classification_model.py in train_model(self, train_df, multi_label, output_dir, show_running_loss, args, eval_df, verbose, **kwargs)
    257         os.makedirs(output_dir, exist_ok=True)
    258 
    --> 259         global_step, tr_loss = self.train(
    260             train_dataset,
    261             output_dir,

    ~/miniconda3/envs/classification/lib/python3.8/site-packages/simpletransformers/classification/classification_model.py in train(self, train_dataset, output_dir, multi_label, show_running_loss, eval_df, verbose, **kwargs)
    383 
    384                 inputs = self._get_inputs_dict(batch)
    --> 385                 outputs = model(**inputs)
    386                 # model outputs are always tuple in pytorch-transformers (see doc)
    387                 loss = outputs[0]

    ~/miniconda3/envs/classification/lib/python3.8/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
    --> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

    TypeError: forward() got an unexpected keyword argument 'token_type_ids'

My guess is that I'm doing something wrong while loading the model. I set `reprocess_input_data` to `True` and `use_cached_eval_features` to False but this did not help.

The base model works fine with my classification dataset.

Am I using the finetuned model correctly? If not, what should I change?

Thanks you in advance and thanks for your hard work on this amazing repo!

**Comment by ThilinaRajapakse** [comment]
The trained model has to be loaded with the model type + model name.

```python
model = ClassificationModel('distilbert', 'outputs/distilbert-base-finetuned', num_labels=9, use_cuda=True, args=args)
```

The convention is that the model type is the generic type of the model (BERT, RoBERTa, XLNet, etc.) while the model name is the more specific name for a particular instance of a trained model. This means that the model name can be either the name of a particular pre-trained model or the path to your locally saved model.

Happy to help!

**Comment by bdalal** [comment]
That worked. Thanks for the prompt response!
