### ISSUE TITLE
QuestionAnsweringModel for Electra  fine_tuning 

### ISSUE THREAD

**Issue by caprone** [ThilinaRajapakse/simpletransformers#341]
HI
how I can load  'electra_base' pretrained into  QuestionAnsweringModel for fine-tuning on custom json dataset?
seems that it' s only possible load 'generators or discriminatros' models...is that correct?
thanks

**Comment by ThilinaRajapakse** [comment]
ELECTRA models are always available as a generator-discriminator pair (list of pre-trained ELECTRA [models](https://huggingface.co/models?search=electra)).

When using them for any task other than language model training, you just use the discriminator. The generator is only used for LM training.

So, the model that you are looking for is `google/electra-base-discriminator`.

**Comment by caprone** [comment]
oh, thanks for great explanation!!

**Comment by ThilinaRajapakse** [comment]
Check out this [article](https://towardsdatascience.com/understanding-electra-and-training-an-electra-language-model-3d33e3a9660d?source=friends_link&sk=2b4b4a79954e3d7c84ab863efaea8c65) if you'd like to know more about ELECTRA!
