### ISSUE TITLE
ValueError: Found input variables with inconsistent numbers of samples: [27321, 27223]

### ISSUE THREAD

**Issue by kommerzienrat** [ThilinaRajapakse/simpletransformers#343]
The number of predictions of `model.eval_model` compared to the inserted data does not fit. This also corresponds to `model.predict` (and here may be the cause of the error).
That is: I provide a `pandas dataframe` e.g. of length 12 to the function `model.eval_model `(or text data to `model.predict`) and receive an output of length 10. This is pretty weird. I, however, do use the `classification_report` in the args, but I am missing the '`O`'-label, so I wanted to calculate the report myself. I am using the most recent version of the library. Besides, using `verbose=True` does not get the `classification_report` to get printed in a Jupyter Notebook. And here comes the code:

```
# lis is a list in the form required for the NER-class of the library. [[101, 'word1', 'label-1'],[...]]
df_prepared = pd.DataFrame(lis, columns=['sentence_id', 'words', 'labels'])
print(len(df_prepared))
df_prepared.head()

#%%

train_df, eval_df = train_test_split(df_prepared, test_size=0.1, shuffle=False)

#%%

# Create a NERModel
model = NERModel('bert', 'bert-base-german-cased', args={'overwrite_output_dir': True, 'reprocess_input_data': True,
                 'num_train_epochs': 5, 'classification_report' : True, 'use_cached_eval_features' : False},
                 labels=list(set(train_df.labels)))

# Train the model
model.train_model(train_df, eval_df=eval_df)

#%%

# Evaluate the model
result, model_outputs, predictions = model.eval_model(eval_df, verbose=True)

print(result)

predictions_flat = [item for sublist in predictions for item in sublist]
print(classification_report(eval_df['labels'].tolist(), predictions_flat))


#%%
## Another way to calculate input for classification_report, but does fail the same way. The error must be somewhere in model.eval_model or predict:
id = eval_df.iloc[0].sentence_id
sent_lis = list()
sents = list()
for row in eval_df.itertuples():
    if row.sentence_id == id:
        sent_lis.append(row.words)
    else:
        id = row.sentence_id
        sents.append(' '.join(sent_lis))
        sent_lis = list()
        sent_lis.append(row.words)

preds, model_outputs=model.predict(sents)
predictions_flat = [list(item.values())[0] for sublist in preds for item in sublist]




```

Error:

```
-------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

<ipython-input-19-cc4cd7440094> in <module>
----> 1 print(classification_report(eval_df.labels.tolist(), predictions_flat))
      2 
      3 

~/anaconda3/envs/pytorch_1.3/lib/python3.7/site-packages/sklearn/metrics/_classification.py in classification_report(y_true, y_pred, labels, target_names, sample_weight, digits, output_dict, zero_division)
   1965     """
   1966 
-> 1967     y_type, y_true, y_pred = _check_targets(y_true, y_pred)
   1968 
   1969     labels_given = True

~/anaconda3/envs/pytorch_1.3/lib/python3.7/site-packages/sklearn/metrics/_classification.py in _check_targets(y_true, y_pred)
     78     y_pred : array or indicator matrix
     79     """
---> 80     check_consistent_length(y_true, y_pred)
     81     type_true = type_of_target(y_true)
     82     type_pred = type_of_target(y_pred)

~/anaconda3/envs/pytorch_1.3/lib/python3.7/site-packages/sklearn/utils/validation.py in check_consistent_length(*arrays)
    210     if len(uniques) > 1:
    211         raise ValueError("Found input variables with inconsistent numbers of"
--> 212                          " samples: %r" % [int(l) for l in lengths])
    213 
    214 

ValueError: Found input variables with inconsistent numbers of samples: [27321, 27223]


```

**Comment by ThilinaRajapakse** [comment]
This can be caused by invalid characters in the text, although I'm not sure if that's what's going on here. Can you show me the dataframe with 12 rows which ends up with 10? I can run it on my end to test.

**Comment by kommerzienrat** [comment]
Hey, thank you for the quick reply. The characters should be utf-8 -- or at least, I do not have issues with them anywhere else, because we use them with other frameworks as well. However, I am not allowed to share them now. Do you have any other idea? I re-checked whether some of the chars 'look wrong' but they don't. Or am I missing something with python3 and unicode?

**Comment by ThilinaRajapakse** [comment]
Can you try to reproduce a dataframe that has the same issue? Or, try to find which word/words are causing the problem? For example, replace each word with some other filler word (the sequence doesn't need to make sense) one by one to see which word is causing the issue.

**Comment by kommerzienrat** [comment]
Hey, I checked the data. However, I found a portion of the data that must cause the issue.
The error now is: 

`---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

<ipython-input-67-fc44889f87d1> in <module>
     26 
     27 predictions_flat = [item for sublist in predictions for item in sublist]
---> 28 print(classification_report(eval_df['labels'].tolist(), predictions_flat))
     29 

~/anaconda3/envs/pytorch_1.3/lib/python3.7/site-packages/sklearn/metrics/_classification.py in classification_report(y_true, y_pred, labels, target_names, sample_weight, digits, output_dict, zero_division)
   1965     """
   1966 
-> 1967     y_type, y_true, y_pred = _check_targets(y_true, y_pred)
   1968 
   1969     labels_given = True

~/anaconda3/envs/pytorch_1.3/lib/python3.7/site-packages/sklearn/metrics/_classification.py in _check_targets(y_true, y_pred)
     78     y_pred : array or indicator matrix
     79     """
---> 80     check_consistent_length(y_true, y_pred)
     81     type_true = type_of_target(y_true)
     82     type_pred = type_of_target(y_pred)

~/anaconda3/envs/pytorch_1.3/lib/python3.7/site-packages/sklearn/utils/validation.py in check_consistent_length(*arrays)
    210     if len(uniques) > 1:
    211         raise ValueError("Found input variables with inconsistent numbers of"
--> 212                          " samples: %r" % [int(l) for l in lengths])
    213 
    214 

ValueError: Found input variables with inconsistent numbers of samples: [110, 100]`

So it seems like there are 10 lines that cause an error?

The data here are:
```

sentence_id,words,labels
11593,völlige,O
11593,Katastrophe,O
11593,:,O
11593,Zum,O
11593,Arzt,O
11593,:,O
11593,-,O
11593,Arrogant,I-fr
11593,-,O
11593,Überheblich,I-fr
11593,-,O
11593,trotzig,I-fr
11593,-,O
11593,Respektlos,I-fr
11593,-,O
11593,immer,I-fr
11593,genervt,I-fr
11593,Also,O
11593,wirklich,O
11593,",",O
11593,was,O
11593,mit,O
11593,diesem,O
11593,Doc,O
11593,los,O
11593,ist,O
11593,versteh,O
11593,ich,O
11593,nicht,O
11593,",",O
11593,immer,I-fr
11593,am,I-fr
11593,meckern,I-fr
11593,",",O
11593,entweder,O
11593,mit,O
11593,dem,O
11593,Personal,O
11593,oder,O
11593,Patienten,O
11593,...,O
11593,sehr,I-fr
11593,launischer,I-fr
11593,Arzt,O
11593,",",O
11593,seine,O
11593,ganze,O
11593,Art,O
11593,und,O
11593,Weise,O
11593,ist,O
11593,sowas,O
11593,von,O
11593,respektlos,I-fr
11593,...,O
11593,Also,O
11593,dieser,O
11593,Doc,O
11593,ist,O
11593,überhaupt,O
11593,nicht,O
11593,zu,O
11593,empfehlen,O
11593,und,O
11593,ich,O
11593,hoffe,O
11593,für,O
11593,den,O
11593,Doc,O
11593,",",O
11593,dass,O
11593,er,O
11593,seine,O
11593,Probleme,O
11593,oder,O
11593,Sorgen,O
11593,oder,O
11593,was,O
11593,auch,O
11593,immer,O
11593,Ihn,O
11593,zu,O
11593,diesem,O
11593,Auftreten,O
11593,führt,O
11593,",",O
11593,in,O
11593,den,O
11593,griff,O
11593,bekommt,O
11593,",",O
11593,der,O
11593,tut,O
11593,mir,O
11593,nur,O
11593,Leid,O
11593,....,O
11593,aber,O
11593,viel,O
11593,mehr,O
11593,tun,O
11593,mir,O
11593,die,O
11593,Patienten,O
11593,leid,O
11593,",",O
11593,denn,O
11593,sein,O
11593,Verhalten,O
11593,gerechtfertig,O
```
(I exported them via `eval_df.to_csv('test.csv', index=False)`)
Can you see something unusual? Many thanks!

**Comment by ThilinaRajapakse** [comment]
There does seem to be an issue with certain characters like these when using the `NERModel`. It's possibly related to how the tokenization happens. I'll see if I can do something about this.

**Comment by kommerzienrat** [comment]
Are the tokens somehow joined (e.g., `' '.join(tokens)`), because that might causes the disappearance of words even though we hand in already tokenized words.

**Comment by Jefffish09** [comment]
Same problem, any updates now?
