### ISSUE TITLE
Loading checkpoint and training

### ISSUE THREAD

**Issue by Sreelakshmi-k** [ThilinaRajapakse/simpletransformers#346]
I  am using Bert model for a classification task and now i am trying to load the check points saved in the output directory. When i load it is throwing a error 

**OSError: Error no file named ['pytorch_model.bin', 'tf_model.h5', 'model.ckpt.index'] found in directory models/checkpoint-564-epoch-2 or `from_tf` set to False**

Could you please help me to resolve it.

**Comment by ThilinaRajapakse** [comment]
Can you show the contents of your checkpoint directory please?
