### ISSUE TITLE
Docs: "You must also configure the model's args dict"...

### ISSUE THREAD

**Issue by JacksonKearl** [ThilinaRajapakse/simpletransformers#349]
Unclear what the note means. Isn't the above configuring the model's args dict? Is there a different args dict?
 
![image](https://user-images.githubusercontent.com/8586769/81054206-3afcf780-8e7b-11ea-97bd-7e836e68cde0.png)

**Comment by ThilinaRajapakse** [comment]
It is the same. The note is supposed to emphasize the fact that just setting `num_labels` isn't enough for regression. I'll fix the wording on this.
