### ISSUE TITLE
can you support albert_zh?

### ISSUE THREAD

**Issue by zhu1090093659** [ThilinaRajapakse/simpletransformers#35]
For many students,who haven't large GPU,so they will use small model(eg albert),hence I hope you will support loading albert, Thanks so much!

**Comment by ThilinaRajapakse** [comment]
I'll see what I can do!

**Comment by zhu1090093659** [comment]
> I'll see what I can do!

Thanks again

**Comment by QAQOAO** [comment]
Hi, I have tried out all of MultiLabelClassificationModel in your package. I am curious that how other models available in huggingface will perform. So I wonder when you have time, will you add GPT-2, CTRL, Transformer-XL ... in the future?

**Comment by ThilinaRajapakse** [comment]
I think I've added all the models provided by HuggingFace for particular tasks. E.g. GPT-2 is not used for classification. That is not to say that those models can't be used for other tasks though. I don't know whether adding them will be useful though, as the available models are the best ones for the given tasks.

**Comment by QAQOAO** [comment]
Now that ALBERT is provided by HuggingFace! Looking forward to use it soon.

**Comment by ThilinaRajapakse** [comment]
Classification with Albert is now supported!

**Comment by sarim-zafar** [comment]
@ThilinaRajapakse  What about the Transformer-XL model? I think it can be used for classification as well

**Comment by ThilinaRajapakse** [comment]
It can be. The Hugging Face library model doesn't come with any specific head on top but it can certainly be added. But, I don't think I'll have the time to add any new models for a couple of weeks. Any PRs are most welcome though!
