### ISSUE TITLE
'bert-base-cased-finetuned-mrpc', Error(s) in loading state_dict for BertForSequenceClassification 

### ISSUE THREAD

**Issue by datashinobi** [ThilinaRajapakse/simpletransformers#350]
The bert-base-cased model fine-tuned on MRPC seem to fail on loading
simpletransformers==0.26.0

```
model = ClassificationModel("bert", "bert-base-cased-finetuned-mrpc", 
                            args= {'fp16':False,'silent':True,
                                   'overwrite_output_dir':True,
                                   'num_train_epochs': 1},
                            num_labels=10,
                           use_cuda=True)
```

=============
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-3956d84fc637> in <module>
      5                                    'num_train_epochs': 1},
      6                             num_labels=10,
----> 7                            use_cuda=True)
      8 eval_df = wiki_df.iloc[0:100,:]
      9 input_df = wiki_df.iloc[100:,:]

/extdrive1/anaconda3/envs/amlsamples_env/lib/python3.6/site-packages/simpletransformers/classification/classification_model.py in __init__(self, model_type, model_name, num_labels, weight, args, use_cuda, cuda_device, **kwargs)
    155             )
    156         else:
--> 157             self.model = model_class.from_pretrained(model_name, config=self.config, **kwargs)
    158 
    159         self.results = {}

/extdrive1/anaconda3/envs/amlsamples_env/lib/python3.6/site-packages/transformers/modeling_utils.py in from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    611                 raise RuntimeError(
    612                     "Error(s) in loading state_dict for {}:\n\t{}".format(
--> 613                         model.__class__.__name__, "\n\t".join(error_msgs)
    614                     )
    615                 )

RuntimeError: Error(s) in loading state_dict for BertForSequenceClassification:
	size mismatch for classifier.weight: copying a param with shape torch.Size([2, 768]) from checkpoint, the shape in current model is torch.Size([10, 768]).
	size mismatch for classifier.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([10]).

**Comment by ThilinaRajapakse** [comment]
I'm guessing this is a peculiarity of `"bert-base-cased-finetuned-mrpc"`, but it appears that you can only use it for binary classification. The code works if you set `num_labels=2`.
