### ISSUE TITLE
Update a saved (tuned) model by incrementally resuming training on new samples

### ISSUE THREAD

**Issue by marley1** [ThilinaRajapakse/simpletransformers#353]
Hi,

Thank you for this project - its brilliant.

Apologies if my query is in the documentation - I have gone through it but am still a little unsure.

I'm keen to load a local save of a classifier that I've already trained using the library, and then resume (and update) the model with new samples.

Is this best achieved by the *train_model* method? (e.g. see below)

```
# Load local saved classifier
model_clf = ClassificationModel("bert", path_to_saved_classifier, use_cuda=cuda_available)

# Update on new samples
model_clf.train_model(df_new_samples[['text', 'label']]
```

Thanks again.

**Comment by ThilinaRajapakse** [comment]
You can do it this way. But because of the way transfer learning works, it might be better to just retrain the pre-trained model with the new data and the old data.

**Comment by marley1** [comment]
Thanks for your response - appreciated
