### ISSUE TITLE
T5 training error

### ISSUE THREAD

**Issue by flozi00** [ThilinaRajapakse/simpletransformers#354]
Error:
`Reason: 'RuntimeError('unable to open shared memory object </torch_24037_2079770963> in read-write mode')'`

`INFO:simpletransformers.t5.t5_utils: Creating features from dataset file at cache_dir/
  0%|                                                                    | 0/2658084 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "trainTranslator.py", line 70, in <module>
    model.train_model(train_df)
  File "/home/a-ware/anaconda3/envs/skillserver/lib/python3.7/site-packages/simpletransformers/t5/t5_model.py", line 157, in train_model
    train_dataset = self.load_and_cache_examples(train_data, verbose=verbose)
  File "/home/a-ware/anaconda3/envs/skillserver/lib/python3.7/site-packages/simpletransformers/t5/t5_model.py", line 702, in load_and_cache_examples
    return T5Dataset(tokenizer, self.args, data, mode,)
  File "/home/a-ware/anaconda3/envs/skillserver/lib/python3.7/site-packages/simpletransformers/t5/t5_utils.py", line 68, in __init__
    tqdm(p.imap(preprocess_data, data, chunksize=500), total=len(data), disable=args["silent"],)
  File "/home/a-ware/anaconda3/envs/skillserver/lib/python3.7/site-packages/tqdm/std.py", line 1127, in __iter__
    for obj in iterable:
  File "/home/a-ware/anaconda3/envs/skillserver/lib/python3.7/multiprocessing/pool.py", line 325, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/home/a-ware/anaconda3/envs/skillserver/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
multiprocessing.pool.MaybeEncodingError`

training on trainslation dataset with two prefixes (translate de to en and translate en to de)

args: 
`model_args = {'reprocess_input_data': True, 'overwrite_output_dir': True, 'num_train_epochs': 1, "train_batch_size": 1, "eval_batch_size": 1, 'no_cache': True, 'use_cached_eval_features' : False, 'save_model_every_epoch':False, "max_seq_length": 32,}`

model is t5-small

dataset contains 1329042 lines for each language with about 15 words per line

edit: works with using "use_multiprocessing":False in args
is it possible to set an limit for multiprocessing ?

**Comment by ThilinaRajapakse** [comment]
Yes, you can use `process_count` to specify the number of cores to use. By default, it will use the available number of cores minus 2, if more than two cores are available.

More details [here](https://thilinarajapakse.github.io/simpletransformers/docs/usage/#configuring-a-simple-transformers-model).

**Comment by flozi00** [comment]
> Yes, you can use `process_count` to specify the number of cores to use. By default, it will use the available number of cores minus 2, if more than two cores are available.
> 
> More details [here](https://thilinarajapakse.github.io/simpletransformers/docs/usage/#configuring-a-simple-transformers-model).

having 24 cores, but event with `process_count = 5` the error returns

**Comment by ThilinaRajapakse** [comment]
I think this is a possible issue with multiprocessing with extremely large files. Can you test with a smaller file to confirm this?

I am planning to implement dynamically loaded datasets soon so that the training data can be in multiple files, which might help with this if it is actually due to the multiprocessing issue.

**Comment by flozi00** [comment]
can confirm that small datasets works with multiprocessing

**Comment by ThilinaRajapakse** [comment]
I think that confirms the issue is with large file multiprocessing. The best solution would be dynamically loaded datasets, I believe. Especially as it will help with memory usage a lot as well.

**Comment by philipperemy** [comment]
@flozi00 why this issue was closed? I still have the problem as of March 2021.
