### ISSUE TITLE
Use discriminator and generator for electra pretrian model.

### ISSUE THREAD

**Issue by liangyuoutreach** [ThilinaRajapakse/simpletransformers#356]
**Describe the bug**
We try to use electra language model training with pretrained discriminator and generator.
Actually, these two models form electra model.
However, we can only specify model name for pretrained electra model.
Is there any way that we can import pretrained electra model from discriminator and generator models instead of pretrained electra model.

We can only find pretrained discriminator and generator on transformers web and can't find pretrained electra model on web.

https://huggingface.co/models

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS

**Additional context**

**Comment by ThilinaRajapakse** [comment]
```python
"""
generator_name (optional): A pretrained model name or path to a directory containing an ELECTRA generator model.
discriminator_name (optional): A pretrained model name or path to a directory containing an ELECTRA discriminator model.
"""
```

You can specify the generator and discriminator separately.
