### ISSUE TITLE
ModuleNotFoundError: No module named 'torchvision'

### ISSUE THREAD

**Issue by Mahmoodmubarak** [ThilinaRajapakse/simpletransformers#358]
Hi @ThilinaRajapakse, 

I installed the 'simpletransformers' by following the installation guide available at https://simpletransformers.ai/docs/installation/.

When I tried to import the Classification model as:
'from simpletransformers.classification.classification_model import ClassificationModel'

it returns me the  'ModuleNotFoundError: No module named 'torchvision''.

I am using the miniconda and I understood from the error message the 'torchvision' package is missing in my virtual environment. I am bit confused here because the installation document doesn't mention for 'torchvision' package. 
Question: Do I need to install 'torchvision' and if yes then which version?

Thanks,

**Comment by ThilinaRajapakse** [comment]
This should be fixed in the latest version (https://github.com/ThilinaRajapakse/simpletransformers/compare/d665494...HEAD)  I just pushed.

**Comment by Mahmoodmubarak** [comment]
Hi @ThilinaRajapakse,

Thanks for your reply. Now I followed the installation step as mentioned in Documentation. This time I got,  the following Error:

**from PIL import Image
ModuleNotFoundError: No module named 'PIL'**

**Comment by ThilinaRajapakse** [comment]
`pip install Pillow`

**Comment by flaviussn** [comment]
> Hi @ThilinaRajapakse,
> 
> Thanks for your reply. Now I followed the installation step as mentioned in Documentation. This time I got, the following Error:
> 
> **from PIL import Image ModuleNotFoundError: No module named 'PIL'**
@Mahmoodmubarak 
If you don't need to classify images and text at the same time, I would recommend you to ignore the issue and just install the last version where these imports are optional.
