### ISSUE TITLE
use case: classify rss feeds and articles

### ISSUE THREAD

**Issue by x0rzkov** [ThilinaRajapakse/simpletransformers#361]
Hi,

Hope you are all well !

I work on a rss news feed aggregator and I d like to classify them with a model.
url: ncarlier/feedpushr.

Being quite new to nlp related fields, I was wondering if is it possible to train it with your package in order to find categories/topics for articles or rss feeds ?

Thanks in advance for your inputs and insights about that question.

Cheers,
X

**Comment by ThilinaRajapakse** [comment]
As long as you have labelled data (articles mapped to the correct category), it's certainly possible.

**Comment by x0rzkov** [comment]
I have those data but they are linked to tags not categories. Is it a problem ?

**Comment by ThilinaRajapakse** [comment]
I think that would be multilabel. If the same article can be tagged with different tags, then it is multilabel.

**Comment by x0rzkov** [comment]
Lats question, sorry, I have 1,820,950 articles with 424,194 tags is too much for multilabel classification training ?

**Comment by ThilinaRajapakse** [comment]
Yeah, that's probably going to be tough. But doesn't hurt to try.

**Comment by lucmichalski** [comment]
How can I test it ? do you have a script ?

**Comment by x0rzkov** [comment]
How can I test it ? do you have a script ?

**Comment by ThilinaRajapakse** [comment]
[Readme](https://github.com/ThilinaRajapakse/simpletransformers#minimal-start-for-multilabel-classification).
