### ISSUE TITLE
Use T5 for classification

### ISSUE THREAD

**Issue by mmmjung** [ThilinaRajapakse/simpletransformers#362]
How can I use it for classification?
Should I replace the "convert" keyword with some other keyword?

**Comment by ThilinaRajapakse** [comment]
Yes. You can change the `prefix` value to perform other tasks.

**Comment by mmmjung** [comment]
Thanks, but I can't find the possible values for the `prefix` anywhere. Sorry, maybe this is obvious...

**Comment by ThilinaRajapakse** [comment]
You can find the pre-trained prefixes in Appendix D of the [paper](https://arxiv.org/pdf/1910.10683.pdf).

However, you can include any other prefix/task you like. There is no finite set of possible `prefix` values.

Basically, you can use any of the pre-trained prefixes from the paper and/or you can define your own prefix/task, and train the model with your data. The minimal start is essentially defining a new prefix/task which is specified by setting the `prefix` to `convert`.

No worries!
