### ISSUE TITLE
Error when instantiating the pre-trained model using ClassificationModel

### ISSUE THREAD

**Issue by namrathaurs** [ThilinaRajapakse/simpletransformers#367]
Hello there!

I have been trying to use the ClassificationModel and have been noticing an error related to the `args` dictionary, which I think was a recent addition to your library. I assumed this was a new update to your library since other Python scripts that refer to yours was working fine a couple of weeks ago. Following is the error message being encountered:

```
Traceback (most recent call last):
  File "tweetonly_seqclsfn_A.py", line 177, in <module>
    main()
  File "tweetonly_seqclsfn_A.py", line 39, in main
    model = ClassificationModel('bert', 'bert-base-uncased', use_cuda=True)
  File "/storage/scratch2/nvu0001/pycharm_remote/smpl_trnsfrmr/code/package_tweet/classification_model.py", line 108, in __init__
    self.config = config_class.from_pretrained(model_name, **self.args["config"])
KeyError: 'config'
```

When I compared the `classification_model.py` file to what I had previously, I noticed that the previous version of this script used `**kwargs` instead of `**self.args["config"]`. I even looked through the history of commits for this repository and observed a change was made with the inclusion of a `config` dictionary. However, I'm not sure if it is just me who is facing this or was this previously reported, which I might have missed noticing.

Can the repo owner or anyone who have been using this repository off late suggest if I have missed on knowing some important detail (something in the documentation that has been updated or anything that relates to this issue) since the recent changes to the repository?

Thanks in advance!

**Comment by ThilinaRajapakse** [comment]
Yes, there was a change from using `**kwargs` to a separate `config` key in the `args` dict. But, this shouldn't be causing a key error. You can find `config` in `simpletransformers/config/global_args.py`.

Are you on the latest version of the library?

**Comment by namrathaurs** [comment]
Looks like my script was not using the latest version of the library. I have updated the same and it works as expected. Thanks for the quick clarification! Hence, closing this issue.
