### ISSUE TITLE
How to configure the model in order to load offline pre trained models and config

### ISSUE THREAD

**Issue by DavideVilla** [ThilinaRajapakse/simpletransformers#368]
Hello,
In the server on which i'll have to perform the training i don't have access to internet and i need to load offline all the configs and pretrained models and afterwards train the model on my data.
Please can you help me to understand how to do this ?
Thank you

**Comment by flaviussn** [comment]
You can download form [here](https://huggingface.co/models) the models that you need and then, if you want per example to perform `multiclass_clasification`, you have to set the path of your model to the second parameter of ClassificationModel.
https://github.com/ThilinaRajapakse/simpletransformers/blob/79d83f3f31c4dc8b2d150a4882bd02d6ae32c2b2/examples/text_classification/multiclass_classification.py#L21
