### ISSUE TITLE
Generic Encoder-Decoder minimal start Error

### ISSUE THREAD

**Issue by baiduflhs** [ThilinaRajapakse/simpletransformers#369]
When I tried to run the Generic Encoder-Decoder minimal start[https://github.com/ThilinaRajapakse/simpletransformers#generic-encoder-decoder-minimal-start](url), the error occurred, the details are as follows
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
     46     args=model_args,
---> 47     use_cuda=True,
     48 )
~/miniconda3/envs/transformers/lib/python3.6/site-packages/simpletransformers/seq2seq/seq2seq_model.py in __init__(self, encoder_type, encoder_name, decoder_name, encoder_decoder_type, encoder_decoder_name, config, args, use_cuda, cuda_device, **kwargs)
    139         self.args.update(global_args)
    140 
--> 141         saved_model_args = self._load_model_args(encoder_decoder_name)
    142         if saved_model_args:
    143             self.args.update(saved_model_args)

~/miniconda3/envs/transformers/lib/python3.6/site-packages/simpletransformers/seq2seq/seq2seq_model.py in _load_model_args(self, input_dir)
    924 
    925     def _load_model_args(self, input_dir):
--> 926         model_args_file = os.path.join(input_dir, "model_args.json")
    927         if os.path.isfile(model_args_file):
    928             with open(model_args_file, "r") as f:

~/miniconda3/envs/transformers/lib/python3.6/posixpath.py in join(a, *p)
     78     will be discarded.  An empty last part will result in a path that
     79     ends with a separator."""
---> 80     a = os.fspath(a)
     81     sep = _get_sep(a)
     82     path = a

TypeError: expected str, bytes or os.PathLike object, not NoneType
---------------------------------------------------------------------------
What should i do 😭

**Comment by ThilinaRajapakse** [comment]
This was a bug. It's been fixed just now in [0.28.2](https://github.com/ThilinaRajapakse/simpletransformers/compare/1695fc4...HEAD).
