### ISSUE TITLE
Load trained classification model

### ISSUE THREAD

**Issue by zaowad** [ThilinaRajapakse/simpletransformers#377]
So how do I load a classification model for inference purpose that has already been trained? I mean shouldn't there be a function in the ClassificationModel class that would work like this ">>>model=ClassificationModel.load(path_to_model)" >>> model.predict('a random string'or list of strings)? All I see that there is a function called _load_model_args that is supposed to load the args that has been used to train the model. I would really appreaciate a solution.

**Comment by ThilinaRajapakse** [comment]
[Readme](https://github.com/ThilinaRajapakse/simpletransformers#loading-saved-models)
