### ISSUE TITLE
Disable automatic trained model output

### ISSUE THREAD

**Issue by sgummidipundi** [ThilinaRajapakse/simpletransformers#378]
Is there any way to disable the function from outputting the trained model into the outputs folder after completion of training?

I'm attempting to a massive gridsearch using this in an HPC environment but the outputting of the model is causing issues.

**Comment by ThilinaRajapakse** [comment]
I think it might be worth having a blanket `no_save` option which prevents any models from being saved. I'll add that to the next release.

In the meantime, use `overwrite_output_dir` if you aren't already using it. I'm not sure if it'll help but it will mean that only one save will exist on the disk at any given time.

**Comment by ThilinaRajapakse** [comment]
Resolved in [0.28.5](https://github.com/ThilinaRajapakse/simpletransformers/releases/tag/0.28.5)

**Comment by sgummidipundi** [comment]
Thanks! I bet this might already be there, but is there a way to completely disable all outputs? Such as tensorboard, etc?
