### ISSUE TITLE
T5 Transformers clarity in readme

### ISSUE THREAD

**Issue by joshzwiebel** [ThilinaRajapakse/simpletransformers#380]
The T5 transformer can perform multiple tasks. it would be nice if the readme provided a list of the prefixes that indicate what tasks can be performed for ease of use when starting up  with the trasnformer

**Comment by ThilinaRajapakse** [comment]
Yes, I am planning on adding those to the docs when the T5 section is added to the [docs](https://simpletransformers.ai/).

The readme only contains the bare minimum for now as the docs are being moved to the website anyway.

#342

**Comment by joshzwiebel** [comment]
thanks for that update!
