### ISSUE TITLE
Downloading pretrained behind ssl proxy (disable verify possible?)

### ISSUE THREAD

**Issue by remcovergoossen** [ThilinaRajapakse/simpletransformers#381]
Hi,

Is there an option to disable ssl verification or passing a cert to the tokenizers?
I could find info about proxies but not certificates.

using following code (or variation thereof to retrieve data):

from transformers import ElectraTokenizer, TFElectraForTokenClassification
tokenizer = ElectraTokenizer.from_pretrained('google/electra-small-discriminator')

Receiving the following error:
Note that the exact same code works outside of the environment where the proxy (that requires verification) is located.

OSError: Model name 'google/electra-small-discriminator' was not found in tokenizers model name list (google/electra-small-generator, google/electra-base-generator, google/electra-large-generator, google/electra-small-discriminator, google/electra-base-discriminator, google/electra-large-discriminator). We assumed 'google/electra-small-discriminator' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.txt'] but couldn't find such vocabulary files at this path or url.

**Comment by ThilinaRajapakse** [comment]
I'm not sure about this. The network stuff and downloading the models are all being handled by the Hugging Face Transformers library.

A workaround would be to manually download the models. I'm not sure how practical that is in your case though.
