### ISSUE TITLE
Error when predicting with "Sliding window"

### ISSUE THREAD

**Issue by ddofer** [ThilinaRajapakse/simpletransformers#384]
**Describe the bug**
When "Sliding window" is enabled in training aregs (of a custom language/Electra model), when we run `model.eval_model(eval_df)`, we get an error. 
Setting "Sliding window" to False in the train params stops this error. 

**To Reproduce**

`model = ClassificationModel("electra","models/lm1", num_labels=7,)

train_args = {
  "num_train_epochs": 1,
  "learning_rate": 1e-2,
  "train_batch_size": 128,
  "sliding_window": True, # BUG: results in error in prediction/evaluation? 
"fp16": False}

model.train_model(train_df,args=train_args)
result, model_outputs, wrong_predictions = model.eval_model(eval_df)`

> Output: 
> 
> Running loss: 1.611265
> 
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-22-c8b864bfe41b> in <module>
>      12 
>      13 # Evaluate the model
> ---> 14 result, model_outputs, wrong_predictions = model.eval_model(eval_df)
> 
> C:\ProgramData\Anaconda3\envs\transformers\lib\site-packages\simpletransformers\classification\classification_model.py in eval_model(self, eval_df, multi_label, output_dir, verbose, silent, **kwargs)
>     629         self._move_model_to_device()
>     630 
> --> 631         result, model_outputs, wrong_preds = self.evaluate(
>     632             eval_df, output_dir, multi_label=multi_label, verbose=verbose, silent=silent, **kwargs
>     633         )
> 
> C:\ProgramData\Anaconda3\envs\transformers\lib\site-packages\simpletransformers\classification\classification_model.py in evaluate(self, eval_df, output_dir, multi_label, prefix, verbose, silent, **kwargs)
>     675 
>     676         if args["sliding_window"]:
> --> 677             eval_dataset, window_counts = self.load_and_cache_examples(
>     678                 eval_examples, evaluate=True, verbose=verbose, silent=silent
>     679             )
> 
> C:\ProgramData\Anaconda3\envs\transformers\lib\site-packages\simpletransformers\classification\classification_model.py in load_and_cache_examples(self, examples, evaluate, no_cache, multi_label, verbose, silent)
>     834 
>     835         if args["sliding_window"] and evaluate:
> --> 836             window_counts = [len(sample) for sample in features]
>     837             features = [feature for feature_set in features for feature in feature_set]
>     838 
> 
> C:\ProgramData\Anaconda3\envs\transformers\lib\site-packages\simpletransformers\classification\classification_model.py in <listcomp>(.0)
>     834 
>     835         if args["sliding_window"] and evaluate:
> --> 836             window_counts = [len(sample) for sample in features]
>     837             features = [feature for feature_set in features for feature in feature_set]
>     838 
> 
> **TypeError: object of type 'InputFeatures' has no len()**
> 

**Expected behavior**
Normal results returned

**Desktop (please complete the following information):**
 - Windows 10, custom Conda Py3 environment

**Comment by ThilinaRajapakse** [comment]
I'm not getting this error when running the provided script with either `google/electra-base-discriminator` or with an ELECTRA model trained from scratch. Are you on the latest version of the library?

If so, would it be possible to share your model to test this?

**Comment by ddofer** [comment]
I'm running on a custom data set. I can share it, how would be best?

**Comment by BjarkePedersen** [comment]
I had this same problem using 'bert_base_cased' for classifcation. I was able to create a fix / workaround https://github.com/ThilinaRajapakse/simpletransformers/pull/468
