### ISSUE TITLE
The results generated by SEQ2SEQ are meaningless.

### ISSUE THREAD

**Issue by ScottishFold007** [ThilinaRajapakse/simpletransformers#386]
I tried to use the SEQ2SEQ model, but the results generated were meaningless:

![image](https://user-images.githubusercontent.com/36957508/82431976-f6e83480-9ac1-11ea-8097-6075679e484e.png)
![image](https://user-images.githubusercontent.com/36957508/82432102-2434e280-9ac2-11ea-9256-d132c04f1782.png)
![image](https://user-images.githubusercontent.com/36957508/82432179-3dd62a00-9ac2-11ea-8cbc-1cd96625b0d5.png)
why?

**Comment by ThilinaRajapakse** [comment]
There seems to be an issue with loading saved Seq2Seq models.

@flozi00 Was this problem resolved? :thinking:

**Comment by flozi00** [comment]
@ThilinaRajapakse no its not solved with custom seq2seq models
Bart and marian models are working correctly

**Comment by ThilinaRajapakse** [comment]
Ah, right. Thank you for the update!

I'll investigate this.

**Comment by flozi00** [comment]
@ThilinaRajapakse the loading bug should be fixed now

**Comment by ScottishFold007** [comment]
> @ThilinaRajapakse the loading bug should be fixed now

Yes,The problem with transformers has been solved：
![image](https://user-images.githubusercontent.com/36957508/83320936-79b97e00-a27e-11ea-91f2-14905b22fcd9.png)

**Comment by ThilinaRajapakse** [comment]
Awesome! I'm guessing we don't need to change anything on this end, right?

**Comment by flozi00** [comment]
Yeah, I think so
