### ISSUE TITLE
BERT Question and answer, How to pick the right paragraph to answer a user query?

### ISSUE THREAD

**Issue by rafacast77** [ThilinaRajapakse/simpletransformers#387]
so I'm working on with python on colab on Q&A BERT base model using simple-transformers library (https://simpletransformers.ai/) I have a model which has been trained with squad it works pretty well and all, but! every time i ask a question i have to also provide a context where that question can be subtracted from.

Now here is the case, let's say i have a table containing a bunch of paragraphs with specific information about depression. Now let's say someone asks a query like: "what can i do to deal with depression?". What techniques do you guys recommend or know about so that based on the question i can choose the best paragraph where the answer will be taken from?

Thank you for your time guys

Im sorry if i should not ask this type of questions here, tell me and i will delete it and not ask these things again.

**Comment by ThilinaRajapakse** [comment]
It's fine to ask questions like this, although they are kinda harder to answer!

I don't really know which approach would be best but I can give you some ideas off the top of my head.

Easiest way to do it would probably be to concatenate all the paragraphs into one piece of text and use that as the context. Keep in mind that the inference will slow down as the length of the context increases though.

Another possibility would be to answer the question separately from all the contexts, and then pick the answer with the highest probability. But the probabilities for the answers from separate contexts are independent of each other, so the context with the highest probability is not necessarily going to be the best answer.

If the number of contexts you have are fixed, you could treat it as a classification problem. That is, for each question, the classification model will predict a label which corresponds to the best context. You will have to create a dataset to train this classifier though.

**Comment by rafacast77** [comment]
Thank you Thilina for taking the time to answer this quest and giving me a place to start, appreciated a lot men, and also thanks for all the work behind simple transformers I'm using it for my honours project and is a lifesaver. Don't worry you'll get a place in my report for the credits
