### ISSUE TITLE
[DOC] spell mistake - upgrading pip

### ISSUE THREAD

**Issue by simepy** [ThilinaRajapakse/simpletransformers#388]
Hi !

In the new documentation, I seen some spell mistake, here: https://simpletransformers.ai/docs/upgrading/

in line : `pip install --uprade simpletransformers` and `pip install --uprade transformers`
is not `--uprade` but `--upgrade`

Otherwise the new documentation is great, Thanks :+1:, Bye

**Comment by ThilinaRajapakse** [comment]
Oh, good spot. I'll fix it.

#342
