### ISSUE TITLE
Store ClassificationModel

### ISSUE THREAD

**Issue by prabhakar267** [ThilinaRajapakse/simpletransformers#391]
**Describe the bug**
I have trained a `ClassificationModel` and passed `output_dir` in `args` but the model is not stored at the location. I tried passing the `output_dir` in the `train_model` method as well but it doesn't store the model.
Can I store the model, after the training is complete? 

**To Reproduce**
Train a `ClassificationModel` and pass `output_dir` in args or in the `train_model` method 

**Expected behavior**
I should be able to store the model after the training is complete and model is still loaded in memory.

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by ThilinaRajapakse** [comment]
This is a bug. I just realized that the model is not being passed to the `self._save_model()` call in `train_model()`.

I'll push a fix in a couple of hours.
