### ISSUE TITLE
Issue with `output_hidden_states = True`

### ISSUE THREAD

**Issue by nicogj** [ThilinaRajapakse/simpletransformers#392]
I'm running a binary classifier (BERT-based) and I would like to save the embeddings as I run predictions. However, when I set `model.config.output_hidden_states = True`, I get an error message when I run `model.predict()`. Screenshot attached below.
Thanks for your help!

![image](https://user-images.githubusercontent.com/30536918/82561236-52262f80-9b73-11ea-87c8-94467c4939e3.png)

**Comment by ThilinaRajapakse** [comment]
Any changes to the config file have to be passed in with the model args.

```python
model_args={
    'reprocess_input_data': True,
    'overwrite_output_dir': True,
    "config": {
        "output_hidden_states": True
    }
}

model = ClassificationModel('roberta', 'roberta-base', args=model_args)

predictions, raw_outputs, all_embedding_outputs, all_layer_hidden_states = model.predict(["I'd like to puts some CD-ROMS on my iPad, is that possible?' — Yes, but wouldn't that block the screen?"])

```
