### ISSUE TITLE
auto model class question answering

### ISSUE THREAD

**Issue by tuner007** [ThilinaRajapakse/simpletransformers#393]
How to use auto model class for question answering.
Actually i wanted to use distilroberta.

Thanks!

**Comment by flozi00** [comment]
Hey, just replace the model type with the `auto` and choose your pretrained distilroberta model.
You can even use distilroberta models with Roberta as model type, there is no seperate model class for it

**Comment by tuner007** [comment]
> Hey, just replace the model type with the `auto` and choose your pretrained distilroberta model.
> You can even use distilroberta models with Roberta as model type, there is no seperate model class for it

thanks for the info but i already tried both ways and was facing errors.

**Comment by flozi00** [comment]
Could you please post the errors here ?

**Comment by tuner007** [comment]
> Could you please post the errors here ?

```
model = QuestionAnsweringModel("auto", "distilroberta-base")
model.train_model(train_data, eval_data=eval_data)
```
    620 
    621         # Instantiate model.
--> 622         model = cls(config, *model_args, **model_kwargs)
    623 
    624         if state_dict is None and not from_tf:
TypeError: __init__() got an unexpected keyword argument 'do_lower_case'

**Comment by ThilinaRajapakse** [comment]
This works for me.

```python
model = QuestionAnsweringModel("roberta", "distilroberta-base")
```

Are you on the latest library version?

**Comment by tuner007** [comment]
> This works for me.
> 
> ```python
> model = QuestionAnsweringModel("roberta", "distilroberta-base")
> ```
> 
> Are you on the latest library version?

Thanks it worked !!

Btw any plan for auto model class to start working for other models ?
