### ISSUE TITLE
Logs not getting properly written to tensorboard logs

### ISSUE THREAD

**Issue by prabhakar267** [ThilinaRajapakse/simpletransformers#396]
**Describe the bug**
While training `ClassificationModel`, I provided `tensorboard_dir` argument. It does create a file in the right directory for each run but the file is empty.

**Expected behavior**
Should be able to use TensorBoard for baby-sitting the classification.

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by ThilinaRajapakse** [comment]
Does your training terminate before it reaches `logging_steps` by any chance?

**Comment by prabhakar267** [comment]
I don't think so, the model training was completed successfully
