### ISSUE TITLE
Error while loading model

### ISSUE THREAD

**Issue by akupka** [ThilinaRajapakse/simpletransformers#40]
Hello, I trained a ClassificationModel model with 125 labels. When I try to reload this model from the output folder with:

model = ClassificationModel('xlm', 'outputs/')

I got this Error message:

RuntimeError: Error(s) in loading state_dict for XLMForSequenceClassification:
	size mismatch for sequence_summary.summary.weight: copying a param with shape torch.Size([125, 1024]) from checkpoint, the shape in current model is torch.Size([2, 1024]).
	size mismatch for sequence_summary.summary.bias: copying a param with shape torch.Size([125]) from checkpoint, the shape in current model is torch.Size([2]).

**Comment by ThilinaRajapakse** [comment]
Probably related to the error mentioned here. https://github.com/ThilinaRajapakse/simpletransformers/issues/30#issuecomment-552184411

This will be fixed soon.

**Comment by akupka** [comment]
Ok, thanks for the fast answer

**Comment by ThilinaRajapakse** [comment]
Fixed.

**Comment by james-owen-ryan** [comment]
It appears that the `num_labels` argument must be passed such that its value matches that of the pre-trained model. Thus, `model = ClassificationModel('xlm', 'outputs/')` should be `model = ClassificationModel(model_type='xlm', model_name='outputs/', num_labels=125)`.

**Comment by ThilinaRajapakse** [comment]
Yeah, that is right. I didn't spot that the `num_labels` argument is missing when creating the model.

**Comment by akupka** [comment]
Thanks a lot, it's working now
