### ISSUE TITLE
Is there some semblance between Language Model Training and Language Generation?

### ISSUE THREAD

**Issue by ankitvad** [ThilinaRajapakse/simpletransformers#402]
Considering the examples in the Readme is there any similarity between the two approaches for Language Model Training and Text Generation? Could the trained language model be used for text generation? Probably not right since it isn't auto-regressive? Is Language Model Training ~ Text Representation (ie. Embedding representation) for tasks like classification?

**Comment by ThilinaRajapakse** [comment]
It depends on the language model you train. If it is a model like BERT, you can't use it directly for text generation. But, if you train a model like GPT2, you can use it for text generation.

**Comment by ankitvad** [comment]
So, Since
