### ISSUE TITLE
longformer model not recognized

### ISSUE THREAD

**Issue by AlexMRuch** [ThilinaRajapakse/simpletransformers#411]
Love this library! Thanks so much for developing it!

I was wondering if compatibility will be added for the longformer model (https://huggingface.co/transformers/model_doc/longformer.html#)? I have some text that's over 1000 tokens long and using this model with `simpletransformers` would be awesome.

Thanks!

**Comment by ThilinaRajapakse** [comment]
Thank you!

Yes, Longformer is definitely something I want to add. Hopefully soon but it's hard to give an exact time frame.

**Comment by AlexMRuch** [comment]
Awesome! Sounds great!

**Comment by AlexMRuch** [comment]
Is there a specific reason why Longformer can't be used with multi-label classification models?
