### ISSUE TITLE
Load large dataset in batch on simple Transformer

### ISSUE THREAD

**Issue by TechyNilesh** [ThilinaRajapakse/simpletransformers#413]
Hello,
I have a dataset of 160k rows and I am classifying them using ClassificationModel on Bert pertain model but I am facing issue's of out of memory. So i want to load in batch, So my question is how to we can perform batch processing on ClassificationModel???

**Comment by ThilinaRajapakse** [comment]
I assume the memory issues you are facing is due to system memory and not GPU VRAM.

I am currently working on adding lazy loading functionality. It seems to be working fine but I still need to do some polishing. Hopefully, this will be ready in the next few days.

Memory will no longer be an issue when using lazy loading.

**Comment by TechyNilesh** [comment]
Itry on colab, Kaggle kernel but facing same issue Cuda out of memory....any solution now ??

**Comment by plc-dev** [comment]
@ThilinaRajapakse 
Are there any news on the lazy loading feature?

**Comment by ThilinaRajapakse** [comment]
Yeah, it was implemented about a month back ([details](https://simpletransformers.ai/docs/classification-specifics/#lazy-loading-data)).

The OP's issue seems to be unrelated though. CUDA out of memory means the GPU memory is insufficient. The easiest way to deal with that is to use a smaller batch size. Shorter sequence lengths also help quite a bit although you might want to be careful about longer sequences being truncated.

**Comment by plc-dev** [comment]
@ThilinaRajapakse 
Thanks for the fast response. I recognize the original question was in the context of the ClassificationModel and the documentation you linked also mentioned the feature for classification only, so I'll be happy to open a new issue if my follow up question is unfitting.
Is there an equivalent feature for NER tasks? (passing reprocess_input_data=True, doesn't seem to allow streaming arbitrarily large conll-files)

**Comment by ThilinaRajapakse** [comment]
Lazy loading is only supported with classification, atm. Please do open a feature request for NER and I'll see what I can do.

**Comment by plc-dev** [comment]
@ThilinaRajapakse 
Done #514 Thanks for the great work so far
