### ISSUE TITLE
best_output_dir being overwritten when training multiple models

### ISSUE THREAD

**Issue by jyjyj** [ThilinaRajapakse/simpletransformers#415]
**Describe the bug**
I'm running `ClassificationModel()` on multiple models to find the best-performing one, and I'm specifying `best_model_dir` for each of them as `model_args["best_model_dir"] = os.path.join("outputs", model_name, "best_model")`. However, I only see a single `best_model_dir`, in one of the directories (I'm specifying `output_dir` like `model_args["output_dir"] = os.path.join("outputs", model_name)`).

**To Reproduce**
Mentioned above

**Expected behavior**
I'm expecting each `output_dir` to contain its own `best_model` folder. Or is that incorrect?

**Desktop (please complete the following information):**
OS: Ubuntu 18.04 if it matters (python3 in anaconda in jupyter notebook)

**Comment by ThilinaRajapakse** [comment]
You need to specify both the `output_dir` and `best_model_dir` for each model.

**Comment by jyjyj** [comment]
Hey @ThilinaRajapakse, I did specify that. I'll test again and update if I see anything different!

**Comment by ThilinaRajapakse** [comment]
As long as they are unique, they should be saved to different directories. :thinking:

**Comment by jyjyj** [comment]
Hi,

I have just tested, and this time I don't get any `best_model` created at all. For reference, this is my `model_args`:

`{'num_train_epochs': 3, 'use_early_stopping': True, 'early_stopping_delta': 0.01, 'early_stopping_metric': 'mcc', 'early_stopping_metric_minimize': False, 'early_stopping_patience': 5, 'evaluate_during_training_steps': 1000, 'save_model_every_epoch': False, 'save_eval_checkpoints': False, 'eval_batch_size': 32, 'overwrite_output_dir': True, 'train_batch_size': 16, 'fp16': False, 'output_dir': 'outputs/google/electra-small-discriminator', 'best_model_dir': 'outputs/google/electra-small-discriminator/best_model'}`

and I am training these models:

`
    if model_type == "bert":
        model_name = "bert-base-cased"

    elif model_type == "roberta":
        model_name = "roberta-base"

    elif model_type == "distilbert":
        model_name = "distilbert-base-cased"

    elif model_type == "distilroberta":
        model_type = "roberta"
        model_name = "distilroberta-base"

    elif model_type == "electra-base":
        model_type = "electra"
        model_name = "google/electra-base-discriminator"

    elif model_type == "electra-small":
        model_type = "electra"
        model_name = "google/electra-small-discriminator"

    elif model_type == "xlnet":
        model_name = "xlnet-base-cased"
`

I am also doing `model.train_model(train, eval_df=test)`. Do I need to do evaluation separately or something? Thanks!

**Comment by jyjyj** [comment]
Yep, just tried again and no `best_model` is created either. All I have in each folder directory (used 3 epochs) is `checkpoint-2000` folder, `checkpoint-4000` folder, `checkpoint-6000` folder and an `eval_results.txt`

**Comment by ThilinaRajapakse** [comment]
You also need to set `evaluate_during_training` to `True`.

**Comment by jyjyj** [comment]
Noted, thanks! That makes sense, I'll try that :)

**Comment by jyjyj** [comment]
Thanks, that works! I thought I did the correct thing, but it seems like each time I tried I left out a different parameter. Works now, thanks!
