### ISSUE TITLE
How to use multiple fields as training?

### ISSUE THREAD

**Issue by jyjyj** [ThilinaRajapakse/simpletransformers#416]
I'm aware of [this](https://simpletransformers.ai/docs/classification-data-formats/#sentence-pair-data-format), where one can use multiple text fields to classify a single thing. However, afaik this sentence-pair concept is typically used for fields which are related to each other (e.g. plagiarism analysis). Is it possible to have 2 completely independent fields used in conjunction to hopefully get a more accurate classification result?

Specifically, I'm trying to predict a person's attributes (e.g. gender, age, education level) based on his/her other known attributes (particularly name, LinkedIn profile info, social media posts). I am able to train a single classifier that predicts e.g. age from name, and age from social media post, but I would like to combine these and more accurately predict age from both name and social media post, if both are available, and one of them if only one piece of info is available. Can I simply use the a/m link? I think `sklearn` can feed tuples in, but was wondering if that would be relevant in this case.

Thanks!

**Comment by ThilinaRajapakse** [comment]
What about simply concatenating the two texts into a single text? For training, you could use a mixture of concatenated and single texts so that the classifier can work with either of the two texts and with both concatenated.

**Comment by jyjyj** [comment]
Hi @ThilinaRajapakse, thanks for your suggestion! Would that be similar to feeding a tuple of strings instead of a single string? My only concern is that when it comes to posts / profile information vs. name, the length of strings is heavily skewed towards the former, so I'm not sure if it would make much difference if there was a combination of e.g. a 15-word post and 2-word name. However, I'm open to trying it. Do let me know if you think what I've mentioned is a valid concern, thanks!

**Comment by ThilinaRajapakse** [comment]
Assuming you have a list of strings for both kinds of information (`train_text_a` and `train_text_b`), you can simply concatenate them together as shown below.

```python
train_text = [a + b for a, b in zip(train_text_a, train_text_b)]
```
The input to the model has to be a single string (unless you are using the sentence pair format).

I wouldn't worry about the relative lengths of the two. The model should learn which parts of the text are the most important and pay attention to those. Indeed, this is partly why Transformers work so well.

**Comment by jyjyj** [comment]
Ok, thanks! I'll try that. I assume no special delimiters are needed, and this can also scale as required? E.g. if I have 3 or more fields that I wish to test in the future. Thank you!

**Comment by ThilinaRajapakse** [comment]
Yes, it should scale without using delimiters. You could try using delimiters as well, but since the model isn't pre-trained on such a format, I'm not sure whether or not that will help.

**Comment by jyjyj** [comment]
Ok, I'll just use spaces then. Thank you!
