### ISSUE TITLE
Issue regarding InputFeature attributes

### ISSUE THREAD

**Issue by iknoorjobs** [ThilinaRajapakse/simpletransformers#418]
Hi!

While evaluating, the wrong_predictions contains list of InputFeature of each incorrect prediction
<simpletransformers.classification.classification_utils.InputExample>

If we do InputFeature.text_a we get the input text of incorrect prediction.

Now, when we do InputFeature.label, it gives the label as output. Is this a true label or a wrongly classified label by model?

Thanks

**Comment by ThilinaRajapakse** [comment]
It is the true label.

**Comment by iknoorjobs** [comment]
Yes, got it. Creating a PR to document that on README.md.
