### ISSUE TITLE
[Feature Request]Longformer

### ISSUE THREAD

**Issue by flozi00** [ThilinaRajapakse/simpletransformers#425]
**Is your feature request related to a problem? Please describe.**
There is no specific problem

**Describe the solution you'd like**
Implementation of longformer for all these tasks

Here is the longformer implementation:
https://github.com/huggingface/transformers/pull/4352

Here are the some important information about the longformer:
https://github.com/huggingface/transformers/pull/4500

**Additional context**

> So make sure
>    You are encoding the input with question at the beginning and with 3 sep tokens
>   input_ids is always a batch of examples

**Comment by flozi00** [comment]
Here is even explained how to convert an existing model to it's long version:
https://github.com/allenai/longformer/blob/master/scripts/convert_model_to_long.ipynb

**Comment by ThilinaRajapakse** [comment]
Doesn't the `LongformerTokenizer` take care of encoding the input correctly? :thinking:

**Comment by flozi00** [comment]
Of you mean that the model can just be plugged into the library, no.
`<s>question</s></s> context</s>`

That's what the model excepts and the question must be encoded at the beginning.

**Comment by ThilinaRajapakse** [comment]
Ok, so I guess it has to be handled separately like with T5. I think I got it.

**Comment by patil-suraj** [comment]
@ThilinaRajapakse 
The `LongformerTokenizer` takes care of this if you encode it as a input pair i.e
`tokenizer.encode(question, context)`

You wont't need to handle it separately

**Comment by ThilinaRajapakse** [comment]
That's nice! Makes it straightforward.

Thank you for the link! That will definitely help.

**Comment by AlexMRuch** [comment]
Not sure if this is helpful, but Hugging Face put more longformer models on the hub: https://twitter.com/huggingface/status/1267829830659174400?s=19

**Comment by flozi00** [comment]
Yeah, already tested trivia QA, squad v1 + v2.

Little bit slow and memory hungry on 4096 sequence but good results for QA

**Comment by AlexMRuch** [comment]
Ah, hopefully someone will distill it soon, haha. Looking forward to using it for classifying longer texts. 😄

**Comment by flozi00** [comment]
Reformer is in progress too.
Hopefully they will add more features for it in next week's too.
I think it would happen much earlier than distillongformer.
But with reformer you need a large dataset cause it's overfitting pretty fast
