### ISSUE TITLE
How to interpret raw_outputs from NER model

### ISSUE THREAD

**Issue by ColinFerguson** [ThilinaRajapakse/simpletransformers#426]
Hello and thank you for your work on this repository.  I am having trouble making sense of the raw model outputs returned by the NER model.

I have trained an NER model with three custom labels:
`model = NERModel('bert', 'bert-base-cased', labels=['O', 'B-clinical_trial', 'I-clinical_trial'], use_cuda=True)`

Training works just fine and the predictions are fine as well.  But I would like to use probabilities from the raw outputs (as I do in text classification).  In particular, I would like a probability for each label for each input token.

Question 1: 
`sample_text = 'HER2CLIMB is the first randomized pivotal trial completed to enroll patients with metastatic HER2 positive breast cancer who have untreated or previously treated and progressing brain metastases.'`
`preds, outputs = model.predict([sample_text])`
`outputs = softmax(outputs, axis=1)`
`print(len(preds[0]))`
`print(outputs[0].shape)`

The code above gives 27 predictions (preds) and 128 outputs (shape=(128,3)).  Can you explain how to interpret the 'extra' outputs?

Question 2:
I was expecting that, after running the softmax, I could interpret the value in each column of `outputs` as the probability that the token has the given label.  And that each row with a max in column 0 would be given the same label, each with a max in column 1 would be given the same label, and the same for column 2.  But that does not appear to be the case

| pred | argmax(row) |
|-------|----------|
|{'HER2CLIMB': 'B-clinical_trial'}|0|
|{'is': 'O'}|1|
|{'the': 'O'}|2|
|{'first': 'O'}|2|
|{'randomized': 'O'}|2|
|{'pivotal': 'O'}|2|
|{'trial': 'O'}|2|
|{'completed': 'O'}|0|
|{'to': 'O'}|0|
|{'enroll': 'O'}|0|
|{'patients': 'O'}|0|
|{'with': 'O'}|0|
|{'metastatic': 'O'}|0|
|{'HER2': 'O'}|0|
|{'positive': 'O'}|0|
|{'breast': 'O'}|0|
|{'cancer': 'O'}|0|
|{'who': 'O'}|0|
|{'have': 'O'}|0|
|{'untreated': 'O'}|0|
|{'or': 'O'}|0|
|{'previously': 'O'}|0|
|{'treated': 'O'}|0|
|{'and': 'O'}|0|
|{'progressing': 'O'}|0|
|{'brain': 'O'}|0|
|{'metastases.': 'O'}|0|

Notices that sometimes a token is assigned 'O' (correctly, I might add) and the max `probability` is in column 0, sometimes column 1, sometimes column 2.

Any help you can give me interpreting these values will be very much appreciated.  Thank you for your work on this project.

**Comment by ThilinaRajapakse** [comment]
I think both these things happen because of the same thing. The length of the raw model outputs for each word will depend on the tokenized length of the word. The softmax is computed over the mean of the model outputs for each token. I.e. the model output for an actual word is the mean of the outputs for each of its constituent tokens.

This [example](https://github.com/ThilinaRajapakse/simpletransformers/blob/master/examples/named_entity_recognition/named_entity_recognition.py) might shed some light as well. (Note the `np.mean()` before `softmax` in line 64)

**Comment by ColinFerguson** [comment]
Hi Thilina, thank you for the response.  I worked with that example yesterday and I think there may be an error.  Lines 62 and 63 are

`key = list(pred.keys())[0]`
 `new_out = out[key]`

I believe this is an error because `key` is a string in this case, but `out` is an array, not a dict, so `out[key]` won't work.  I tried to figure out the index of `out` that `key` might represent, but I couldn't come up with anything.

From your example, the first `key` is `Some`, but the corresponding `out` is `[ 3.7382812 -1.6835938 -1.6152344]`, so `out[key]` will give an error.

Thanks again for any help you can give me.

**Comment by ThilinaRajapakse** [comment]
Did you run the script? It runs without any errors. `out` is a dict that is being generated from a nested for loop (`raw_outputs` -> `outs` -> `out`).

**Comment by ColinFerguson** [comment]
Hello, thank you again for the reply.  I am sorry to push back on this, but I do not believe that any of the outputs you have listed above are dicts (raw_outputs, outs, out).  I ran the script as written (running in jhub with apex installed) as both a notebook cell and as a standalone script.  Same error every time.  Then I added some print statements to track the different variables.  The results are below.  Thank you again for your help in this matter.

```
-----
predictions is a <class 'list'>
raw outputs is a <class 'numpy.ndarray'>
-----

___________________________
Sentence:  Some arbitary sentence
-----
preds is a <class 'list'>
outs is a <class 'numpy.ndarray'>
------
------
pred is a <class 'dict'>
out is a <class 'numpy.ndarray'>
------
The prediction is: {'Some': 'B-PER'}

And out is: [ 0.1508789  -0.03887939 -0.33935547  0.34838867 -0.19543457 -0.28808594
  0.24487305 -0.04129028 -0.16503906]

The key is: Some
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-32-1be190039a83> in <module>
     68         key = list(pred.keys())[0]
     69         print('The key is: {}'.format(key))
---> 70         new_out = out[key]
     71         preds = list(softmax(np.mean(new_out, axis=0)))
     72         print(key, pred[key], preds[np.argmax(preds)], preds)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

**Comment by ColinFerguson** [comment]
Upgrading to `0.30.0` solved the problem.  Thank you ThilinaRajapakse.
