### ISSUE TITLE
Setting global_step back to 0

### ISSUE THREAD

**Issue by manueltonneau** [ThilinaRajapakse/simpletransformers#428]
Hi and thanks for the great repo :) 

I am currently using models that I already fine-tuned on a dataset and further tine-tuning them on another one. I am aware that fine-tuning again from scratch on the combination of the two datasets is [probably a better idea](https://github.com/ThilinaRajapakse/simpletransformers/issues/353). 

Still, in my case, my problem is the second dataset is smaller and so when the model 'skips to saved global_step', it takes into account the size of the new dataset and therefore considers that we are way ahead in the number of epochs. For example, say I take the first epoch of a model fine-tuned on my big dataset. When initiating fine-tuning with this model on my smaller dataset, it tells me that it is continuing training from epoch 41 and therefore directly ending fine-tuning (in the case where I set the number of epochs to 20). Is it possible to initiate with this model but set global_step back to 0 so the model further fine-tunes without being influenced by the characteristics of the former fine-tuning?

Thanks a lot in advance!

**Comment by ThilinaRajapakse** [comment]
What if you renamed the checkpoint directory? Simple Transformers tries to resume training because the model path indicates that it is a checkpoint. I think. if you renamed the directory to something else (e.g. `fine-tune-stage-1`), it should start from the beginning.

**Comment by manueltonneau** [comment]
Very cool, will try and let you know if that works, thanks :)

**Comment by manueltonneau** [comment]
I tried with the `best_model` folder and it started back to 0. Thanks for the tip :)

**Comment by IS5882** [comment]
Hello @manueltonneau, I was wondering what is your idea on fine-tuning twice on different datasets vs fine-tuning once on the contamination of the 2 dataset? why did you opt for the first option?
