### ISSUE TITLE
An exception while using `output_hidden_states` with number of examples passed to `predict` exceding `eval_batch_size `

### ISSUE THREAD

**Issue by jpotoniec** [ThilinaRajapakse/simpletransformers#429]
**Describe the bug**
The following exception is thrown due to an incorrect usage of `np.append` in line 967 of `simpletransformers/classification/classification_model.py`
`TypeError: append() missing 1 required positional argument: 'values'`

**To Reproduce**
```
from simpletransformers.classification import ClassificationModel
import pandas as pd

model = ClassificationModel("bert", "bert-base-cased", use_cuda=True, args={'config': {"output_hidden_states": True}})
data = pd.Series(['a','b','c','d','e','f','g','h','i','j']).astype('str')
model.predict(data)
```
If the array passed to `pd.Series` contains at most 8 examples (the default value of `eval_batch_size`) or `output_hidden_states` is set to `False` (the default value) the code does not raise an exception.

**Expected behavior**
The code presented above does not raise an exception.

**Desktop (please complete the following information):**
 - OS: `Linux 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux`

**Additional context**
Attached is a patch against the current master branch which solves the issue
[simpletransformers.txt](https://github.com/ThilinaRajapakse/simpletransformers/files/4701374/simpletransformers.txt)

**Comment by ThilinaRajapakse** [comment]
Thanks! Would you like to submit this as a PR so that you will be added as a contributor?
