### ISSUE TITLE
Obtaining Embeddings

### ISSUE THREAD

**Issue by rohanvartak1996** [ThilinaRajapakse/simpletransformers#43]
Is there a way I can obtain the embeddings for the text when I use any of the pre-trained models.

**Comment by AliOsm** [comment]
Can you try this: https://github.com/AliOsm/simplerepresentations

**Comment by rohanvartak1996** [comment]
Thank you so much, Ali!  That's a great help!!  Also, thanks Thilina for creating such a wonderful wrapper for transformers.

**Comment by ThilinaRajapakse** [comment]
Great job, Ali!
You are welcome, Rohan!
