### ISSUE TITLE
Difference implementation of LineByLineTextDataset in Transformers and SimpleTransformers

### ISSUE THREAD

**Issue by cahya-wirawan** [ThilinaRajapakse/simpletransformers#439]
Hi, thanks for the great wrapper for Transformers. Btw, I compared the implementation of LineByLineTextDataset in Transformers and SimpleTransformers, it seems they are difference. in SimpleTransformers you used tokenizer = ByteLevelBPETokenizer(),  and tokenizer._tokenizer.post_processor = BertProcessing(), but the Transformers use either the default tokenizer (PreTrainedTokenizer) or the tokenizer set in LineByLineTextDataset. If I don't misunderstood, your LineByLineTextDatasets implementation will only be working for Bert, is it correct?

**Comment by ThilinaRajapakse** [comment]
You are right, there's a bug there. It should follow the Transformers implementation.

This is probably also causing #337.

**Comment by ThilinaRajapakse** [comment]
Would be great if you could submit a fix for this in a PR! :wink:

**Comment by cahya-wirawan** [comment]
Ok, I will try

**Comment by cahya-wirawan** [comment]
Hi, is there any special purpose why simpletransformer has its own LineByLineTextDataset and TextDataset class?
Otherwise it would be better to use both classes from transformers to avoid code redundancy which could lead discrepancy in the future (and now also)

**Comment by Pradhy729** [comment]
I can help with this. Will create a PR.

**Comment by ThilinaRajapakse** [comment]
@Pradhy729 Thank you for the offer! But, this was fixed in #450
