### ISSUE TITLE
Distributed training processes

### ISSUE THREAD

**Issue by cahya-wirawan** [ThilinaRajapakse/simpletransformers#440]
Hi,
Is it possible to run SimpleTransformers in multiple distributed training processes with torch.distributed.launch as the normal case with Transformers? For example I can train the language model in Transformers with following command : 
`$ python -m torch.distributed.launch --nproc_per_node=8 run_language_modeling.py ...`
Thanks

**Comment by ThilinaRajapakse** [comment]
Theoretically, yes. But it's not guaranteed and I haven't tested it. Please let me know if you try it!

**Comment by cahya-wirawan** [comment]
I tried it, unfortunately it doesn't work. I got following errors
 ```
   tokenizer = cls(*init_inputs, **init_kwargs)
  File "/sysadmin/wirawan/miniconda3/envs/transformers/lib/python3.7/site-packages/transformers/tokenization_gpt2.py", line 152, in __init__
    self.encoder = json.load(vocab_handle)
  File "/sysadmin/wirawan/miniconda3/envs/transformers/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/sysadmin/wirawan/miniconda3/envs/transformers/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/sysadmin/wirawan/miniconda3/envs/transformers/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/sysadmin/wirawan/miniconda3/envs/transformers/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
and only a gpu is used

**Comment by cahya-wirawan** [comment]
After reading the transformers code, it needs some preparations and initialization before we can use distributed training processes. It will not work automatically without it 🙂 
I’ll let you know if I can add this functionality to simpletransformers

**Comment by cahya-wirawan** [comment]
Hi,
I have a development branch https://github.com/cahya-wirawan/simpletransformers/tree/dev which support the distributed training process. Please have a look, there are several necessary lines have been added to have a working distributed training process, some codes are just copied from transformers. the branch includes also run_lm_train.py in the main directory as an example. To run the training on 4 GPUs, we could execute it as follow:
`python -m torch.distributed.launch --nproc_per_node=4 run_lm_train.py`
Honestly, the training code in simpletranformers is not as clean as the training code in transformers which has the Trainer class. This class contains all the code for the distributed training process and support for TPU. I would suggest also to use this Trainer class instead of our own training code.
