### ISSUE TITLE
Motivation for using 2 linear layers for Distilbert classification head

### ISSUE THREAD

**Issue by bdalal** [ThilinaRajapakse/simpletransformers#442]
Hi,
The transformers `BertForSequenceClassification` model has just a dropout followed by a Linear layer mapping the pooled output to the labels.
In the distilbert model however, I see that there's an additional Linear layer before dropout and the final Linear layer is applied. https://github.com/ThilinaRajapakse/simpletransformers/blob/fe4fade1952cb56e3c8b6eccfa07ceed8de72bf6/simpletransformers/classification/transformer_models/distilbert_model.py#L52-L55

What is the motivation behind adding this `pre_classifier `?

**Comment by ThilinaRajapakse** [comment]
I can't remember off the top of my head, but I assume this is how it was implemented in the original `distilbert` model.

**Comment by bdalal** [comment]
Yes, you're right. For some reason I wasn't able to find HuggingFace's source when I was looking earlier: https://huggingface.co/transformers/_modules/transformers/modeling_distilbert.html#DistilBertForSequenceClassification

Thanks.
