### ISSUE TITLE
ImportError relating 'ROBERTA_PRETRAINED_MODEL_ARCHIVE_MAP'

### ISSUE THREAD

**Issue by EsquilliDev** [ThilinaRajapakse/simpletransformers#446]
**Describe the bug**
Importing ClassificationModel from simpletransformers.classification raises the following issue:
> ImportError: cannot import name 'ROBERTA_PRETRAINED_MODEL_ARCHIVE_MAP' from 'transformers.modeling_roberta'

**To Reproduce**
> from simpletransformers.classification import ClassificationModel

**Expected behavior**
- It should import without any issues.

**Desktop (please complete the following information):**
 - Windows 10

**Additional context**
- Yesterday, I was able to run everything without any problems. Today I'm running the same code and I keep getting the same error.

**Comment by fcggamou** [comment]
I'm having the same issue when running from google colab

**Comment by EsquilliDev** [comment]
I'm getting it in both Google Colab and Jupyter notebook.

**Comment by ThilinaRajapakse** [comment]
This is because of the breaking changes in the latest transformers version. Please use `transformers==2.10.0` until this is fixed.

**Comment by SaadTazroute** [comment]
How can i use transforemers  2.10.00 with simpletransformers ???
> This is because of the breaking changes in the latest transformers version. Please use `transformers==2.10.0` until this is fixed.

**Comment by svmihar** [comment]
`pip install transformers==2.10.0`

**Comment by ThilinaRajapakse** [comment]
transformers v2.11.0 should be compatible with simple transformers [v0.32.3](https://github.com/ThilinaRajapakse/simpletransformers/tree/v0.32.3)

**Comment by ThilinaRajapakse** [comment]
Compatibility issues resolved.

**Comment by radhavinodsutd** [comment]
Hi Sir,
I am still getting this error on google colab.
/content/drive/My Drive/task_detector/simpletransformers-master/simpletransformers/classification/transformer_models/roberta_model.py in <module>()
----> 1 from transformers.modeling_roberta import RobertaConfig, RobertaModel, RobertaClassificationHead, ROBERTA_PRETRAINED_MODEL_ARCHIVE_MAP, BertPreTrainedModel
      2 import torch
      3 import torch.nn as nn
      4 from torch.nn import CrossEntropyLoss, MSELoss
    
ImportError: cannot import name 'ROBERTA_PRETRAINED_MODEL_ARCHIVE_MAP'

I had tried installing versions mentioned:
!pip install simpletransformers==0.32.3
!pip install transformers==2.11.0

But the error is still persisting. 
Could you help me out with this, please?

Thanks,
Radha

**Comment by ThilinaRajapakse** [comment]
This is quite old now. You can use the latest versions of both transformers and simpletransformers.

```bash
pip install --upgrade simpletransformers
```

**Comment by radhavinodsutd** [comment]
Thank you so much. That worked.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
