### ISSUE TITLE
Getting error while executing code

### ISSUE THREAD

**Issue by ahujaravinder022** [ThilinaRajapakse/simpletransformers#45]
Hi
 I have executed the code and getting error:

I have attached code file which I executed

ValueError                                Traceback (most recent call last)
<ipython-input-6-44e3b58a00f8> in <module>
----> 1 model.train_model(train_df)

~\Anaconda3\envs\simpletransformers\lib\site-packages\simpletransformers\classification\multi_label_classification_model.py in train_model(self, train_df, multi_label, output_dir, show_running_loss, args)
     98 
     99     def train_model(self, train_df, multi_label=True, output_dir=None, show_running_loss=True, args=None):
--> 100         return super().train_model(train_df, multi_label=multi_label, output_dir=output_dir, show_running_loss=show_running_loss, args=args)
    101 
    102     def eval_model(self, eval_df, multi_label=True, output_dir=None, verbose=False, **kwargs):

~\Anaconda3\envs\simpletransformers\lib\site-packages\simpletransformers\classification\classification_model.py in train_model(self, train_df, multi_label, output_dir, show_running_loss, args, eval_df)
    159 
    160 
--> 161         train_dataset = self.load_and_cache_examples(train_examples)
    162         global_step, tr_loss = self.train(train_dataset, output_dir, show_running_loss=show_running_loss, eval_df=eval_df)
    163 

~\Anaconda3\envs\simpletransformers\lib\site-packages\simpletransformers\classification\multi_label_classification_model.py in load_and_cache_examples(self, examples, evaluate, no_cache, multi_label)
    107 
    108     def load_and_cache_examples(self, examples, evaluate=False, no_cache=False, multi_label=True):
--> 109         return super().load_and_cache_examples(examples, evaluate=evaluate, no_cache=no_cache, multi_label=multi_label)
    110 
    111     def compute_metrics(self, preds, labels, eval_examples, multi_label=True, **kwargs):

~\Anaconda3\envs\simpletransformers\lib\site-packages\simpletransformers\classification\classification_model.py in load_and_cache_examples(self, examples, evaluate, no_cache, multi_label)
    444 
    445         if output_mode == "classification":
--> 446             all_label_ids = torch.tensor([f.label_id for f in features], dtype=torch.long)
    447         elif output_mode == "regression":
    448             all_label_ids = torch.tensor([f.label_id for f in features], dtype=torch.float)

ValueError: too many dimensions 'str'

**Comment by ahujaravinder022** [comment]
I am using toxic comment data from Kaggle and following the instructions present on https://towardsdatascience.com/multi-label-classification-using-bert-roberta-xlnet-xlm-and-distilbert-with-simple-transformers-b3e0cda12ce5.



#!/usr/bin/env python
# coding: utf-8

# In[1]:



import pandas as pd
train_df = pd.read_csv(r'C:\Users\Lenovo\Desktop\Toxic Comments Classification\train.csv')
train_df.head()


# In[2]:


df=train_df.copy()


# In[3]:


df['labels'] = list(zip(df.toxic.tolist(), df.severe_toxic.tolist(), df.obscene.tolist(), df.threat.tolist(),  df.insult.tolist(), df.identity_hate.tolist()))
df['text'] = df['comment_text'].apply(lambda x: x.replace('\n', ' '))

df.head()



from sklearn.model_selection import train_test_split


train_df, eval_df = train_test_split(df, test_size=0.2)

from simpletransformers.classification import MultiLabelClassificationModel

model = MultiLabelClassificationModel('roberta', 'roberta-base', num_labels=6, args={'train_batch_size':2, 'gradient_accumulation_steps':16, 'learning_rate': 3e-5, 'num_train_epochs': 3, 'max_seq_length': 512},use_cuda=False)

model.train_model(train_df)

**Comment by ThilinaRajapakse** [comment]
The code you p[rovided is working for me.

Try adding `'reprocess_input_data': True` to args. The model might be using cached features that are bugged.

**Comment by ahujaravinder022** [comment]
Hi
    model is training from the last 6 hrs. I am using a machine with an i3 (2.3Ghz)processor with 4GB RAM. Can you please suggest me any other way in which this code can be executed faster or any machine which I can purchase for these types of code.

**Comment by ThilinaRajapakse** [comment]
The most important factor for deep learning is the GPU. I'd recommend at least a GTX 1060 6 GB. Training on CPU is not really feasible. You'll probably want at least 16 GB of RAM as well.

For now, it might be best if you ran the code on Google Colab using their free GPU (12 hour sessions).

**Comment by ahujaravinder022** [comment]
Thanks a lot..
