### ISSUE TITLE
Loading a trained ClassificationModel

### ISSUE THREAD

**Issue by marley1** [ThilinaRajapakse/simpletransformers#455]
Hi,

When loading a trained ClassificationModel(), is it possible to do so from an an s3 bucket?

**Comment by ThilinaRajapakse** [comment]
I'm not sure, but you can try providing the S3 bucket link as the `model_name`. This is essentially how the Hugging Face models are loaded.

**Comment by marley1** [comment]
Thanks for your response (and apologies for my late one) - unfortunately no luck specifying the link as `model_name`

**Comment by ThilinaRajapakse** [comment]
That's unfortunate. In that case, I guess you would have to write some setup code to download the model to local storage first and then load the model from there.

**Comment by marley1** [comment]
Yes, looks like I'll have to implement that way - thanks again.
