### ISSUE TITLE
Loading a simpletransformers model back in huggingface?

### ISSUE THREAD

**Issue by Robert60CB** [ThilinaRajapakse/simpletransformers#456]
I'm so sorry if this is a naive question - I'm new to NLP and am starting to work with transformer models. This library looks fantastic - but I'm wondering if the models it outputs are compatible with the HuggingFace library too, and can be loaded there?

Reason being is I'm hoping to fine tune a LM on Simple Transformers then port it to UKPLAB's SentenceTransformers library. The one library that connects SimpleTransformers to SentenceTransformers is HuggingFace.

**Comment by guy-mor** [comment]
If model is your simple transformers object, then model.model is the Huggingface pytorch model. You can operate on this object via usual methods from the huggingface library.
