### ISSUE TITLE
Incorrect padding token - RoBERTa classification

### ISSUE THREAD

**Issue by guy-mor** [ThilinaRajapakse/simpletransformers#457]
While training a multilabel RoBERTa classification model I noticed that the padding token used is 0 
 (`<s>`) rather than 1 (`<pad>`). This appears to be caused by `convert_examples_to_features` (from `classification\classification_utils.py`) not passing along pad_token when calling `convert_example_to_feature.` `convert_example_to_feature`'s default padding value of 0 is then used, but this is incorrect for RoBERTa.

**Comment by ThilinaRajapakse** [comment]
This can be solved easily by passing along the pad_token to the convert function. I've updated the code accordingly.
