### ISSUE TITLE
RoBERTa tokenization does not add leading space

### ISSUE THREAD

**Issue by guy-mor** [ThilinaRajapakse/simpletransformers#458]
The GPT-2 style BPE encoding used by RoBERTa requires that all words begin with a space (see [here](https://github.com/huggingface/transformers/issues/1196) and [here](https://github.com/pytorch/fairseq/blob/master/fairseq/models/roberta/hub_interface.py#L38-L56). For this reason the encode_plus method for Huggingface RobertaTokenizer automatically adds a leading space, so that a sentence like "It's raining" become " It's raining" before adding beginning and end of string tokens. 

However, the tokenization method used by by simpletransformers (calling `.tokenize()`, manually adding special tokens, and calling `.convert_tokens_to_ids()`) does not add this space. In my investigation I saw that prediction results from a trained model may differ between the two methods. Tokenization here should probably conform to that suggested by fairseq, adding the leading space.

**Comment by ThilinaRajapakse** [comment]
Classification still uses the older code (which has these issues). I'll update the code to fix this. Should also resolve #457

**Comment by ThilinaRajapakse** [comment]
Thank you for your help!
