### ISSUE TITLE
model_output  in eval_model are not probabilities

### ISSUE THREAD

**Issue by chnlyi** [ThilinaRajapakse/simpletransformers#46]
from simpletransformers.classification import ClassificationModel
import pandas as pd

train_data = [['Example sentence belonging to class 1', 1], ['Example sentence belonging to class 0', 0]]
train_df = pd.DataFrame(train_data)

eval_data = [['Example eval sentence belonging to class 1', 1], ['Example eval sentence belonging to class 0', 0]]
eval_df = pd.DataFrame(eval_data)

model = ClassificationModel('roberta', 'roberta-base', use_cuda=False, args={'reprocess_input_data': True, 'overwrite_output_dir': True})

model.train_model(train_df)

result, model_outputs, wrong_predictions = model.eval_model(eval_df)

print(result)

print(model_outputs)

{'mcc': 0.0, 'tp': 1, 'tn': 0, 'fp': 1, 'fn': 0, 'eval_loss': 0.697429895401001}

[[-0.2112433  -0.01764951]
 [-0.2094903  -0.01733721]]

**Comment by ThilinaRajapakse** [comment]
Yeah, model_outputs are the direct outputs from the model. If you want predictions, you need to apply a softmax function to the outputs.

```
from scipy.special import softmax

probabilities = softmax(raw_outputs, axis=1)
```
