### ISSUE TITLE
little typo in train_new_lm.py?

### ISSUE THREAD

**Issue by cahya-wirawan** [ThilinaRajapakse/simpletransformers#467]
Hi Thilina,
I see in examples/language_generation/train_new_lm.py that the **output_dir** is "outputs/from_scratch_" with extra underscore at the end, but **best_model_dir** doesn't have it. Is it just a little typo or on purpose?

```
    "output_dir": f"outputs/from_scratch_",
    "best_model_dir": f"outputs/from_scratch/best_model",
```

**Comment by ThilinaRajapakse** [comment]
It's a typo. :sweat_smile:
