### ISSUE TITLE
Where does the model get saved ?

### ISSUE THREAD

**Issue by khttknoob** [ThilinaRajapakse/simpletransformers#470]
Can anyone please guide me where the model get saved after training it on my data ?

**Comment by khttknoob** [comment]
@ThilinaRajapakse Is it the "pytorch_model.bin" file ?

**Comment by ThilinaRajapakse** [comment]
That is the actual file containing the weights, yes. But to load a model, use the path to the directory which contains `pytorch_model.bin`.
