### ISSUE TITLE
ImportError relating 'ROBERTA_PRETRAINED_MODEL_ARCHIVE_LIST'

### ISSUE THREAD

**Issue by khttknoob** [ThilinaRajapakse/simpletransformers#471]
Describe the bug
Importing ClassificationModel from simpletransformers.classification raises the following issue:

ImportError: cannot import name 'ROBERTA_PRETRAINED_MODEL_ARCHIVE_LIST'

To Reproduce

from simpletransformers.classification import ClassificationModel

Expected behavior

It should import without any issues.
Desktop (please complete the following information):

Windows 10 (Google Colab)
Additional context

Yesterday, I was able to run everything without any problems. Today I'm running the same code and I keep getting the same error.

**Comment by RodriguezM** [comment]
I had that issue with a virtual environment, uninstalled and reinstalled simple transformers and transformers packages, versions 0.34.2 and 2.11.0. Reloaded the environment and everything worked fine. My versions were up to date, prior to uninstall and reinstall, maybe the simple transformers was a build behind.
