### ISSUE TITLE
Importing Weights for Multimodal Model from URL

### ISSUE THREAD

**Issue by botelhoa** [ThilinaRajapakse/simpletransformers#473]
**Is your feature request related to a problem? Please describe.**

***Describe the bug***
A FileNotFoundError is triggered by the line 

self.model.load_state_dict(torch.load(os.path.join(model_name, "pytorch_model.bin"))) 

when using the suggested model_name conventions (ex: bert-base-uncased). It seems this handling is for only when the weights are stored locally and not imported from Hugging Face.

***To Reproduce***
model = MultiModalClassificationModel("bert", "bert-base-uncased", num_labels= 4, args={"fp16": False, 'train_batch_size': 16, 'learning_rate': 1e-5, 'num_train_epochs': 3, 'max_seq_length': 100, "weight_decay": 0.1, "warmup_ratio": 0.06}, use_cuda= True)
model.train_model(train, eval_data=dev)
result, model_outputs, wrong_predictions = model.eval_model(test)

***Screenshots***
![image](https://user-images.githubusercontent.com/56508008/84438060-d8430c80-ac2d-11ea-90f1-7d114795ee5f.png)
![image](https://user-images.githubusercontent.com/56508008/84438151-f14bbd80-ac2d-11ea-978d-5793b28825b6.png)

**Describe the solution you'd like**
In addition to checking locally, it would be great if the model_name were also compared to existing pre-trained weights in the Hugging Face library to download them via URL

**Comment by ThilinaRajapakse** [comment]
This is due to the breaking changes in transformers=2.11.0 (#446). Looks like it was missed in the last fix.

It should be resolved in 0.34.1 that I just pushed. Please update and try again.

**Comment by botelhoa** [comment]
Thank you for the quick reply! I just reran and can confirm the issue is fixed
