### ISSUE TITLE
how to return multiple output from seq2seq model?

### ISSUE THREAD

**Issue by tiancaohz** [ThilinaRajapakse/simpletransformers#475]
Hi, is there any way to generate multiple output from seq2seq model?

Thanks

**Comment by ThilinaRajapakse** [comment]
This functionality was missing but I've just added it in v0.34.4. (Added `num_return_sequences`, `top_k`, and `top_p` args for `Seq2SeqModel`.)

**Comment by tiancaohz** [comment]
thanks for the update!
