### ISSUE TITLE
Where are the models  being saved 

### ISSUE THREAD

**Issue by mineshmathew** [ThilinaRajapakse/simpletransformers#476]
Hi
Can you please help me understand where are the models which are automatically being downloaded are saved. ( not the models  and check points while training, but models downloaded from the transformers model zoo)

For example with the below step, some files are downloaded , 
`model = QuestionAnsweringModel('distilbert', 'distilbert-base-uncased-distilled-squad', args={'reprocess_input_data': True, 'overwrite_output_dir': True})
`
Where are these models saved to. I would like to change the folder to where these files are automatically downloaded owing to space constraints in the disk where the code is

Thanks

**Comment by ThilinaRajapakse** [comment]
`/home/<user>/.cache/torch/transformers`

#120
