### ISSUE TITLE
I have tried running the roberta base model and whenever I ran the model and it produces different results. How to fix this?

### ISSUE THREAD

**Issue by nk6june** [ThilinaRajapakse/simpletransformers#478]
Model results were changing everytime

**Comment by ThilinaRajapakse** [comment]
Please provide more information regarding what you were doing, preferably along with a minimal script of the code you ran.

**Comment by nk6june** [comment]
Hi Rajapakse, I resolved myself that i didn't use manual seed parameter in model. Thank you. We can close this thread.
