### ISSUE TITLE
EmptyHeaderError

### ISSUE THREAD

**Issue by Gondolav** [ThilinaRajapakse/simpletransformers#48]
I'm running into this exception when executing .train_model(). At first I thought the problem comes from empty text strings in my train_df, but after cleaning the error persists. Do you have any idea?
Thank you very much for your work!

EmptyHeaderError                          Traceback (most recent call last)
~/anaconda3/envs/transformers/lib/python3.7/tarfile.py in next(self)
   2288             try:
-> 2289                 tarinfo = self.tarinfo.fromtarfile(self)
   2290             except EOFHeaderError as e:

~/anaconda3/envs/transformers/lib/python3.7/tarfile.py in fromtarfile(cls, tarfile)
   1094         buf = tarfile.fileobj.read(BLOCKSIZE)
-> 1095         obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
   1096         obj.offset = tarfile.fileobj.tell() - BLOCKSIZE

~/anaconda3/envs/transformers/lib/python3.7/tarfile.py in frombuf(cls, buf, encoding, errors)
   1030         if len(buf) == 0:
-> 1031             raise EmptyHeaderError("empty header")
   1032         if len(buf) != BLOCKSIZE:

EmptyHeaderError: empty header

During handling of the above exception, another exception occurred:

ReadError                                 Traceback (most recent call last)
~/anaconda3/envs/transformers/lib/python3.7/site-packages/torch/serialization.py in _load(f, map_location, pickle_module, **pickle_load_args)
    594         try:
--> 595             return legacy_load(f)
    596         except tarfile.TarError:

~/anaconda3/envs/transformers/lib/python3.7/site-packages/torch/serialization.py in legacy_load(f)
    505 
--> 506         with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
    507                 mkdtemp() as tmpdir:

~/anaconda3/envs/transformers/lib/python3.7/tarfile.py in open(cls, name, mode, fileobj, bufsize, **kwargs)
   1590                 raise CompressionError("unknown compression type %r" % comptype)
-> 1591             return func(name, filemode, fileobj, **kwargs)
   1592 

~/anaconda3/envs/transformers/lib/python3.7/tarfile.py in taropen(cls, name, mode, fileobj, **kwargs)
   1620             raise ValueError("mode must be 'r', 'a', 'w' or 'x'")
-> 1621         return cls(name, mode, fileobj, **kwargs)
   1622 

~/anaconda3/envs/transformers/lib/python3.7/tarfile.py in __init__(self, name, mode, fileobj, format, tarinfo, dereference, ignore_zeros, encoding, errors, pax_headers, debug, errorlevel, copybufsize)
   1483                 self.firstmember = None
-> 1484                 self.firstmember = self.next()
   1485 

~/anaconda3/envs/transformers/lib/python3.7/tarfile.py in next(self)
   2303                 if self.offset == 0:
-> 2304                     raise ReadError("empty file")
   2305             except TruncatedHeaderError as e:

ReadError: empty file

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-14-5b001e654f20> in <module>
      3 
      4 # Train the model
----> 5 model.train_model(train_df)
      6 
      7 # # Evaluate the model

~/anaconda3/envs/transformers/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py in train_model(self, train_df, multi_label, output_dir, show_running_loss, args, eval_df)
    159 
    160 
--> 161         train_dataset = self.load_and_cache_examples(train_examples)
    162         global_step, tr_loss = self.train(train_dataset, output_dir, show_running_loss=show_running_loss, eval_df=eval_df)
    163 

~/anaconda3/envs/transformers/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py in load_and_cache_examples(self, examples, evaluate, no_cache, multi_label)
    410 
    411         if os.path.exists(cached_features_file) and not args["reprocess_input_data"] and not no_cache:
--> 412             features = torch.load(cached_features_file)
    413             print(f"Features loaded from cache at {cached_features_file}")
    414         else:

~/anaconda3/envs/transformers/lib/python3.7/site-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    424         if sys.version_info >= (3, 0) and 'encoding' not in pickle_load_args.keys():
    425             pickle_load_args['encoding'] = 'utf-8'
--> 426         return _load(f, map_location, pickle_module, **pickle_load_args)
    427     finally:
    428         if new_fd:

~/anaconda3/envs/transformers/lib/python3.7/site-packages/torch/serialization.py in _load(f, map_location, pickle_module, **pickle_load_args)
    595             return legacy_load(f)
    596         except tarfile.TarError:
--> 597             if _is_zipfile(f):
    598                 # .zip is used for torch.jit.save and will throw an un-pickling error here
    599                 raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))

~/anaconda3/envs/transformers/lib/python3.7/site-packages/torch/serialization.py in _is_zipfile(f)
     73         match = True
     74         for magic_byte, read_byte in zip(magic_number, read_bytes):
---> 75             if ord(magic_byte) != ord(read_byte):
     76                 match = False
     77                 break

TypeError: ord() expected a character, but string of length 0 found

**Comment by ThilinaRajapakse** [comment]
Can you try running it with `reprocess_input_data` set to True? I think the model is still using the cached features.

`model = ClassificationModel('bert', 'bert-base-cased', args={'reprocess_input_data': True})`

**Comment by Gondolav** [comment]
Thank you very much, it's working now!

**Comment by ThilinaRajapakse** [comment]
Great!
