### ISSUE TITLE
Custom Model Loading (different layers number)

### ISSUE THREAD

**Issue by antmarakis** [ThilinaRajapakse/simpletransformers#483]
Hi!

I have built a custom model based on BERT, but when I try to load it using:

`model = ClassificationModel('bert', 'path_to_custom_bert', num_labels=2)`

it doesn't seem to work properly (always predicts same class).

The custom model was built this way:

1) Took BERT-Base-uncased
2) Removed some of the layers
3) Saved it

Even though the model is based on BERT, I do not seem to be able to load it properly. Is there a workaround to this?

Thanks!

**Comment by ThilinaRajapakse** [comment]
I am surprised it loaded without an error!

My intuition is that removing some of the layers will essentially destroy the model's capability, at least without training it further. Can you fine-tune this custom model?

**Comment by antmarakis** [comment]
Basically, what I am trying to do is probing: https://www.aclweb.org/anthology/P19-1356/

In probing, you take single layers, stick a classifier on top of them, and test them on some task.

I am wondering if your code could be modified to accommodate such custom models. Using some bare-bones PyTorch code, I can remove layers with:

```
model.encoder.layer = torch.nn.ModuleList([model.encoder.layer[i]])
```

The problem is, I don't think currently I could get it running with your code, and unfortunately without your library training/testing BERT can be quite painful, haha.

**Comment by ThilinaRajapakse** [comment]
Oh, so the model is being loaded with the pre-trained weights _before_ the layers are stripped away? In that case, I don't see why it wouldn't work though. Are there any errors, or is it just bad predictions?

**Comment by antmarakis** [comment]
There are no errors, the predictions are just always the same, no matter how much I train the model.

**Comment by ThilinaRajapakse** [comment]
Can you check whether the weights change in the layers (during/after training)? Maybe stripping layers somehow messes it up.

**Comment by antmarakis** [comment]
I just did some testing, and it seems I messed it up a little bit. I was saving a `BertModel`, while your library requires a `BertSequenceClassification` model (can't remember the exact name).

It now seems to work. Cheers!
