### ISSUE TITLE
ClassificationModel with output_hidden_states=True results in IndexError

### ISSUE THREAD

**Issue by N8Brooks** [ThilinaRajapakse/simpletransformers#484]
**Problem**
I'm using the classification model with the config={'output_hidden_states':True}. When I predict for a set it creates an error with 'tuple index out of range.

**Here is the code:**
`from simpletransformers.classification import ClassificationModel

args = dict(
            overwrite_output_dir=True, 
            max_seq_length=512,
            train_batch_size=8,
            test_batch_size=8,
            gradient_accumulation_steps=2,
            num_train_epochs=1,
            sliding_window=True,
            use_early_stopping=False,
            config=dict(output_hidden_states=True)
           )

model = ClassificationModel('electra', 'google/electra-base-discriminator', num_labels=5, args=args)

model.train_model(train, show_running_loss=True, eval_df=val)

test['pred'], *_ = model.predict(test['text'])`

**The error:**
Traceback (most recent call last):

  File "<ipython-input-25-6a26f3dc4ca6>", line 1, in <module>
    model.predict(test['text'])

  File "/home/nathan/anaconda3/envs/py38/lib/python3.8/site-packages/simpletransformers/classification/classification_model.py", line 976, in predict
    embedding_outputs, layer_hidden_states = outputs[2][0], outputs[2][1:]

IndexError: tuple index out of range

**Additional context**
I'm trying to get the document embedding from the training data. I was planning on using the average of the second to last hidden layer. If you have any other ideas to achieve the same thing let me know :P

**Comment by ThilinaRajapakse** [comment]
This seems specific to the `electra` model. It doesn't seem to be giving the hidden states for some reason. I'll investigate why, but you can do what you wanted to do with the other models if that works for you.
