### ISSUE TITLE
use_cuda= False generates ValueError

### ISSUE THREAD

**Issue by NaRuecker** [ThilinaRajapakse/simpletransformers#486]
Hi,

thank you so much for the wonderful and easy to use package!

I have been happily using it for a few days running a binary classification script. It works fine on google colabs using the available GPU. Now I wanted to test a new environment that only has CPU, suddenly the use_cuda argument throws an error. I went back to colabs, same error in there.

Here is my code:
![image](https://user-images.githubusercontent.com/12310354/84824061-5bc57a80-afed-11ea-8589-540b8259f787.png)

Here is the unexpected output:
![image](https://user-images.githubusercontent.com/12310354/84824118-713aa480-afed-11ea-8557-1aa4fc1c17bc.png)

**1. The error content seems wrong to me.**
ValueError: 'use_cuda' set to True when cuda is unavailable. Make sure CUDA is available or set use_cuda=False.
Shouldn't it rather be 'use_cuda' set to True when cuda is **available**. Make sure CUDA is available or set use_cuda=False
**2. I have set use_cuda=False. So why won't it run anymore?**

Anyone any ideas?

**Comment by ThilinaRajapakse** [comment]
`use_cuda` is a method argument and not part of the model's `args`. It should work with something like this:

```python
model = ClassificationModel(model_type=mt, model_name=mn, use_cuda=False, args=model_args)
```

**Comment by NaRuecker** [comment]
Thank you Thilina! That worked!
