### ISSUE TITLE
NER prediction function words limit 

### ISSUE THREAD

**Issue by ns-hxue** [ThilinaRajapakse/simpletransformers#489]
Hi there,

When I tried to use NER model to make a prediction, it only returns parts of the results if the text is too long. 
Most weird thing is , when I checked the length of raw_outputs, it is different from the length of results.

Is there somewhat words limit for prediction or I did something wrong?

**Comment by ThilinaRajapakse** [comment]
There is a limit (`max_seq_length`). The difference in the length of raw_outputs is probably because `raw_outputs` contains the outputs per token and not per word.
