### ISSUE TITLE
Training and Finetuning support for models supported in Language Generation

### ISSUE THREAD

**Issue by shaoormunir** [ThilinaRajapakse/simpletransformers#494]
**Is your feature request related to a problem? Please describe.**
Some of the models supported in the language generation pipeline are not supported for training. It limits users to only use the pretrained versions of those models or manually train them. Examples are XLNet, XLM, Transformer XL, and CTRL.

**Describe the solution you'd like**
Adding support for training for language models such as XLNet and XLM which are supported in Language Generation.

**Describe alternatives you've considered**
I have tried using auto as an option for those models but the results were bad for downstream tasks. Added XLNetConfig, XLNetLMHeadModel, XLNetTokenize to language_modeling_model.py but there seems to be additional need for fine-tuning processes for each model.

**Comment by ThilinaRajapakse** [comment]
Each model has its own peculiarities, which makes adding these to Language Modeling a non-trivial task. I'll see what I can do in a future update though.
