### ISSUE TITLE
[CLS] token in ELECTRA

### ISSUE THREAD

**Issue by ghk829** [ThilinaRajapakse/simpletransformers#495]
**Describe the bug**
A clear and concise description of what the bug is. Please specify the class causing the issue.

https://github.com/ThilinaRajapakse/simpletransformers/blob/cf66100fafedc7a6277288d4eb1cf2aed6b3e676/simpletransformers/language_modeling/language_modeling_model.py#L263

ELECTRA doens't need to insert CLS in first of sentence

**To Reproduce**

https://github.com/ThilinaRajapakse/simpletransformers/blob/cf66100fafedc7a6277288d4eb1cf2aed6b3e676/simpletransformers/language_modeling/language_modeling_model.py#L263

**Expected behavior**

the CLS token and SEP tokens should not show

**Screenshots**

**Desktop (please complete the following information):**
 - OS
- MAC

**Additional context**

In paper, They doens't say the CLS token at all

**Comment by ghk829** [comment]
the problem happens because the tokenizer is shared over all models in the library

**Comment by ThilinaRajapakse** [comment]
Isn't the ElectraTokenizer being used when the model type is Electra? :thinking:

**Comment by ghk829** [comment]
@ThilinaRajapakse 

Yeah but, the **ELECTRA** tokenizer is the same as **BERT's**.
So, It doesn't matter whether **[CLS]** token is in vocab.
But, google-research team's tokenizer doens't have CLS token or special tokens in their vocab.
