### ISSUE TITLE
For ELECTRA, masking 15% tokens should replace with [MASK], not include random word

### ISSUE THREAD

**Issue by dev-sngwn** [ThilinaRajapakse/simpletransformers#496]
https://github.com/ThilinaRajapakse/simpletransformers/blob/cf66100fafedc7a6277288d4eb1cf2aed6b3e676/simpletransformers/language_modeling/language_modeling_utils.py#L243

In [ELECTRA (Clark et al)](https://openreview.net/pdf?id=r1xMH1BtvB), they mentioned about this issue in **3.5 EFFICIENCY ANALYSIS**

> masked tokens are replaced with a random token 10% of the time and are kept the same 10% of the time. However, our results suggest these simple heuristics are insufficient to fully solve the issue.

So, their [official implementation (google-research/electra)](https://github.com/google-research/electra/blob/81f7e5fc98b0ad8bfd20b641aa8bc9e6ac00c8eb/pretrain/pretrain_helpers.py#L188) does not including replacing random word process. Please check this out and let me know if I wrong.

_Thanks & best regards,_

**Comment by ThilinaRajapakse** [comment]
I think you are right. I'll double-check and fix this.

**Comment by ThilinaRajapakse** [comment]
This should be fixed now. Please reopen if it isn't.
