### ISSUE TITLE
Support for environments without ipywidgets

### ISSUE THREAD

**Issue by Lunchb0ne** [ThilinaRajapakse/simpletransformers#503]
**Is your feature request related to a problem? Please describe.**
No, but many online notebook platforms don't allow for using ipywidgets yet, and not being able to see some progress is disruptive.

**Describe the solution you'd like**
Just want to put in a feature request to have an option to disable ipywidgets

**Describe alternatives you've considered**
I haven't considered any alternatives.

**Additional context**
nope

**Comment by ThilinaRajapakse** [comment]
Setting `silent=True` will disable tqdm.

**Comment by Lunchb0ne** [comment]
Okay, got it. But would be still nice to specify the tqdm type we want for the package. I can try to implement this if that's okay

**Comment by ThilinaRajapakse** [comment]
The library uses `tqdm.auto`. This should automatically use the correct tqdm type for the environment. Am I missing something? 🤔
