### ISSUE TITLE
Create a wrapper to obtain word embeddings 

### ISSUE THREAD

**Issue by pablonm3** [ThilinaRajapakse/simpletransformers#505]
**Is your feature request related to a problem? Please describe.**
Obtaining word representations using the tokenizer and model classes requires some boilerplate

**Describe the solution you'd like**
What do you think about writing a wrapper that given a list of text sentences, a model name and an embedding function name(how to combine token vectors, eg: "concat", "sum", etc) would return the sentence representations?

**Describe alternatives you've considered**
Below is the boilerplate code I use in my projects to obtain sentence representations from a BERT model, I'm thinking of a wrapper to do all of that under the hood:

```
def mean_across_all_tokens(hidden_states):
    return torch.mean(hidden_states[-1], dim=1)

def sum_all_tokens(hidden_states):
    return torch.sum(hidden_states[-1], dim=1)

def concat_all_tokens(hidden_states):
    batch_size, max_tokens, emb_dim = hidden_states[-1].shape
    return torch.reshape(hidden_states[-1], (batch_size, max_tokens * emb_dim))

def CLS_token_embedding(hidden_states):
    return hidden_states[-1][:, 0, :]

class BertTransformer(BaseEstimator, TransformerMixin):
    def __init__(
            self,
            max_length: int = 60,
            tokenizer = BertTokenizer.from_pretrained("bert-base-uncased"),
            model = BertModel.from_pretrained("bert-base-uncased", output_hidden_states=True),
            embedding_func = mean_across_all_tokens,
            combine_sentence_tokens=True
    ):
        self.tokenizer = tokenizer;
        self.combine_sentence_tokens = combine_sentence_tokens;
        self.embedding_func = embedding_func;
        self.model = model
        self.model.eval()
        self.max_length = max_length

    def _tokenize(self, text_list: List[str]) -> Tuple[torch.tensor, torch.tensor]:
        # Tokenize the text with the provided tokenizer
        input_ids = self.tokenizer.batch_encode_plus(text_list,
                                                    add_special_tokens=True,
                                                    max_length=self.max_length,
                                                    pad_to_max_length=True
                                                    )["input_ids"]

        return torch.LongTensor(input_ids)
         

    def _tokenize_and_predict(self, text_list: List[str]) -> torch.tensor:
        input_ids_tensor = self._tokenize(text_list)
        out = self.model(input_ids=input_ids_tensor)
        hidden_states = out[2]
        if(self.combine_sentence_tokens):
            return self.embedding_func(hidden_states)
        else:
            return hidden_states[-1];
    
    def transform(self, text_list: List[str]):
        if isinstance(text_list, pd.Series):
            text_list = text_list.tolist()

        with torch.no_grad():
            return self._tokenize_and_predict(text_list)

    def fit(self, X, y=None):
        """No fitting necessary so we just return ourselves"""
        return self
```

**Comment by ThilinaRajapakse** [comment]
This will be useful, I agree. Would you be interested in implementing this functionality? 😊

**Comment by pablonm3** [comment]
Sure! Any suggestions @ThilinaRajapakse ?

**Comment by pablonm3** [comment]
Starting to work on it

**Comment by ThilinaRajapakse** [comment]
I'm sorry, I seem to have missed this thread. I am not sure what the best way to implement this would be. Do you have any ideas?

What do you think about creating a separate RepresentationModel with the methods you suggested?

**Comment by pablonm3** [comment]
What do you think about creating a new folder/module called: "language_representation" inside we'll have a class called `RepresentationModel`, the class will have the following public methods:
- __init__(model_type, model, tokenizer, args, use_cuda, cuda_device, **kwargs ): constructor
- finetune(...): finetunes the model given a blob of text, I'd left the implementation of this method as a follow up task
- encode_sentences(combine_strategy, list of sentences): combine_strategy is a String representing the function used to combine the token vectors in a sentence, value is one of: "concat", "mean" or None. it returns a list of sentence vectors or a list a of lists of token vectors if combine_strategy=None, since it will return the vectors for each token in a each sentence.

Following the patterns in classification module, inside language_representation module I'll add a transformer_models directory to contain transformers model wrappers for each model_type that `RepresentationModel` supports

**Comment by ThilinaRajapakse** [comment]
Sounds perfect!

I think we can leave out the fine-tune method as that could potentially be done through one of the other tasks (e.g. Language Modeling). The `RepresentationModel` can then be used to get the model representation for any input (independent of the task-specific head).

**Comment by pablonm3** [comment]
@ThilinaRajapakse I created a local branch with the feature and when try to push it to origin to open the PR, I get the error: "ERROR: Permission to ThilinaRajapakse/simpletransformers.git denied to pablonm3.
"

**Comment by ThilinaRajapakse** [comment]
You can't push it directly to this repo. You have to fork this repo and push it to your fork. From there, you can open the PR.

Link to [guide](https://opensource.com/article/19/7/create-pull-request-github).

Since you've already made the changes, once you've forked, cloned, and created the local branch, you can just copy over the changed files to avoid having to make the changes again (step 5).

There may be easier/better ways to do this but I'm not an expert on Git, unfortunately.

**Comment by pablonm3** [comment]
thanks, that's the approach followed by most libraries.Also people that open PRs in a consisten basis could get added to an organization so they get permission to create branches in the project and then open the PRs from those branches. They still don't get permission to some protected branches like master
