### ISSUE TITLE
How to fine tune model with more features? (& other things about classification model)

### ISSUE THREAD

**Issue by DebanjanaKar** [ThilinaRajapakse/simpletransformers#510]
Hi!! Firstly many thanks for this library..it's extremely helpful. I am using the binary classification model and I had the following queries regarding it :
1. Instead of just text, is there a way to fine tune the model with some more features? I saw in one of the issues you wrote that best practice would be to write your own model class where we will be the simple transformer classifier..can you elucidate more on how to go about that?
2. How to obtain weighted fscore for the model?
3. Is there a way to fine tune bert embeddings on a given downstream task and obtain it with your library? 
Thanks a lot !!
Regards.

**Comment by ThilinaRajapakse** [comment]
1. To use more features, you do have to create your own model class. You could take a look at the Multi-Modal Classification models as a starting point. You would also need to handle the data inputs and outputs correctly. (Also discussed in #553 )

2. You can use any metric function you like. The only requirement is that the function will need to accept two arguments with the first being the true labels, and the second being the predictions.

3. I am not sure if this is what you mean, but you can access the model's hidden states by setting `config: {"output_hidden_states": True}` in the model args.

**Comment by DebanjanaKar** [comment]
Thanks a lot!!
