### ISSUE TITLE
T5 Minimal Start: is this line correct? - eval_df = train_df.copy()

### ISSUE THREAD

**Issue by tutmoses** [ThilinaRajapakse/simpletransformers#517]
**Describe the bug**
The basic T5 example has this code from line 23:

```
eval_df = pd.DataFrame(eval_data, columns=["prefix", "input_text", "target_text"])
eval_df = train_df.copy()
```

I'm wondering what the second line does and whether it should be `eval_df = eval_df.copy()`?

**Comment by ThilinaRajapakse** [comment]
Actually, that line is a typo. It's not necessary (it was just a placeholder that I seem to have forgotten to remove).

**Comment by tutmoses** [comment]
Ah ok, perfect, good to know. Thanks!
