### ISSUE TITLE
T5 orders of magnitude slower than LSTM

### ISSUE THREAD

**Issue by tutmoses** [ThilinaRajapakse/simpletransformers#518]
**Describe the bug**
Perhaps not a bug but I'm wondering why T5 can take nearly a day to process seq2seq data that for an LSTM would take a few minutes.

**To Reproduce**
T5 Minimal Start vs https://github.com/keras-team/keras/blob/master/examples/addition_rnn.py

**Expected behavior**
That the processing times would be roughly equivalent.

**Desktop (please complete the following information):**
 Mac OS Catalina

**Comment by ThilinaRajapakse** [comment]
From a quick glance at the LSTM, it seems to be a very small network. Even the base T5 model would be orders of magnitude larger (220M parameters) and that is a large part of why it's much slower. The benefit of a T5 model (or any other Transformer model) is going to be its performance with regard to the accuracy/quality of predictions. It will almost certainly be slower than most conventional networks.

**Comment by tutmoses** [comment]
Ah ok. Does an analogous 'power/weight' ratio (iterations/second /parameters?) exist for NNs in order to measure their relative efficiency? I feel the T5 would fare very badly!

What would you recommend as the best model for deep seq2seq tasks such as:

[["AgAsF6silver", "hexafluoroarsenate(V)"],
["CrB2","chromium diboride"],
["Rh(CO)2(C5H7O2)", "(acetylacetonato)dicarbonylrhodium(I)"]]

**Comment by ThilinaRajapakse** [comment]
Not that I am aware of. T5 (and other Transformers) weren't built with computational efficiency as a primary concern.

If I am understanding this correctly, you are using a NER model to generate the full name of a given chemical compound from its short notation? (Apologies for the possibly awkward terms but it has been nearly 10 years since I last read a Chemistry book!)

**Comment by tutmoses** [comment]
Exactly, yes, but I've not heard of a NER model. It seems perfectly suited for a seq2seq model to learn the underlying grammar. Would BERT be state-of-the-art for such a task?

**Comment by ThilinaRajapakse** [comment]
Sorry about that, NER is not the model for the task. Seq2seq would probably be the way to go.

How much data do you have and how were the results from the T5 model?

**Comment by tutmoses** [comment]
About 30,000 pairs so far or 50,000 including reversing and doubling the data to improve the resilience of the grammar. I gave up with the T5 because even 90 pairs was taking hours, hence looking for an alternative.

**Comment by flozi00** [comment]
Did you had a look on Marian model ?
If I understand you correctly you don't have a real NLP problem with whole sentences or language structures.
Check out the Ludwig library from uber.
There you can use CNN model (very fast).
Ludwig is an toolkit you can use without any line of code.

**Comment by ThilinaRajapakse** [comment]
Also, are you training on a CPU? T5 isn't exactly fast but it shouldn't be _that_ slow.

**Comment by tutmoses** [comment]
Yeah CPU, but the LSTM was on the same machine and the difference is enormous.

**Comment by ThilinaRajapakse** [comment]
It's not feasible to train any Transformer model on CPUs. If you don't have a local GPU, I recommend checking out Google Colab. Comparing to LSTMs doesn't really make any sense, unfortunately. It's like comparing the fuel efficiency of a Formula 1 car and a Toyota Prius. :sweat_smile:

**Comment by flozi00** [comment]
Alternative to Google colab is paperspace.
Colab stops sometimes while training

**Comment by tutmoses** [comment]
> It's not feasible to train any Transformer model on CPUs. If you don't have a local GPU, I recommend checking out Google Colab. Comparing to LSTMs doesn't really make any sense, unfortunately. It's like comparing the fuel efficiency of a Formula 1 car and a Toyota Prius. 😅

Ha! Ok good to know. Thanks.
