### ISSUE TITLE
[Feature request] distributed training

### ISSUE THREAD

**Issue by flozi00** [ThilinaRajapakse/simpletransformers#519]
**Is your feature request related to a problem? Please describe.**
Large datasets on large models takes very much time to train

**Describe the solution you'd like**
Distributed training to combine local computers with cloud computers.

**Describe alternatives you've considered**
https://medium.com/huggingface/training-larger-batches-practical-tips-on-1-gpu-multi-gpu-distributed-setups-ec88c3e51255

**Comment by ThilinaRajapakse** [comment]
This was implemented for LM training by a contributor but we still need to extend it to the other tasks.
