### ISSUE TITLE
error using evaluate_during_training

### ISSUE THREAD

**Issue by wshuyi** [ThilinaRajapakse/simpletransformers#52]
I am currently using version 0.7.9. After setting `evaluate_during_training` to True, I tried to run `model.train_model(train, eval_df=valid)`, yet got an error message saying there is no `eval_df` option in `train_model` function. Any idea? Thanks!

![](https://tva1.sinaimg.cn/large/006y8mN6ly1g94a5pmf6gj30im04adgd.jpg)

**Comment by ThilinaRajapakse** [comment]
This should be fixed now. The parameter was missing for multi label classification class.
