### ISSUE TITLE
bart minimal start

### ISSUE THREAD

**Issue by amirziai** [ThilinaRajapakse/simpletransformers#520]
**Describe the bug**
trying to run the bart [example](https://github.com/ThilinaRajapakse/simpletransformers#bart-minimal-start) and getting this:
```
OSError: Can't load config for 'bart-large'. Make sure that:

- 'bart-large' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'bart-large' is the correct path to a directory containing a config.json file
```

**To Reproduce**
Copied the sample code and ran. Tried replacing `bart-large` with `facebook/bart-large` but then i get this when i start training:
```
PicklingError: Can't pickle <function gelu at 0x7fa6f055fef0>: it's not the same object as torch.nn.functional.gelu
```

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
```
Ubuntu 18.04
simpletransformers==0.40.2
transformers==2.11.0
torch==1.5.1
```

**Additional context**
N/A

**Comment by OanaIgnat** [comment]
I have the same error when trying to run the example with 'roberta-base'.

**Comment by flozi00** [comment]
Which version of transformers library do you have installed ?

**Comment by amirziai** [comment]
@flozi00 updated my question above, i have `2.11.0`.

**Comment by flozi00** [comment]
Could you try to update your transformers version ?
Maybe 2.19.0 ?

**Comment by amirziai** [comment]
makes a bit more progress but still the same `PicklingError`:
https://gist.github.com/amirziai/1f884e4a8e2fa0cf2f9e0db368ab0da5

**Comment by tutmoses** [comment]
Same issue on Mac Catalina.
