### ISSUE TITLE
ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets

### ISSUE THREAD

**Issue by krannnn** [ThilinaRajapakse/simpletransformers#522]
I was following your multilabel classification tutorial on a different set of data that has 13 labels.
a snippet of my data : 

![image](https://user-images.githubusercontent.com/66248879/86069808-446d9f00-ba7b-11ea-8d97-b4b81e294418.png)

So I'm facing a multilabel classification task, and when computing the f1 score I'm getting this error:

```ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets```

I'm not sure why sklearn is confused (maybe because my targets are one-hot encoded ) and throwing up an error about multilabel indicator.

Can you please give any solutions ? @ThilinaRajapakse 

I can share the dataset if needed.

**Comment by ThilinaRajapakse** [comment]
I think you need to wrap the sklearn function with your own function which loops over the label:prediction pairs and averages the F1 score for each.

I'm answering from memory though, so I'm not a 100% on this.
