### ISSUE TITLE
Generic query about finetuning last-N layers

### ISSUE THREAD

**Issue by karansaxena** [ThilinaRajapakse/simpletransformers#523]
This isn't about an issue, but to check if there is a flag to specify how many layers we can finetune.
By default, is only the last layer finetuned?

**Comment by ThilinaRajapakse** [comment]
All layers are fine-tuned by default. This is the normal procedure for Transformers. But, the next update will probably feature support for specifying individual learning rates for each layer.

**Comment by karansaxena** [comment]
Is there an out-of-the-box flag to just fine-tune the last layer?

**Comment by ThilinaRajapakse** [comment]
Not yet.
