### ISSUE TITLE
'tuple' object does not support item assignment | Multimodal eval

### ISSUE THREAD

**Issue by AshishGogo** [ThilinaRajapakse/simpletransformers#529]
**Describe the bug**
Getting error **'tuple' object does not support item assignment** while running eval_model on MultiModalClassificationModel("bert", "bert-base-uncased",label_list=[0,1])

**To Reproduce**
run eval_model on any text+images multimodal problem.

**Expected behavior**
should have provided predictions

**Screenshots**

**Desktop (please complete the following information):**
 - OS

**Additional context**

**Comment by AshishGogo** [comment]
![image](https://user-images.githubusercontent.com/30543644/86268495-e6a99600-bbe5-11ea-9468-a428c0d84257.png)

**Comment by ThilinaRajapakse** [comment]
Likely the same as #525

**Comment by AshishGogo** [comment]
I have pre-installed tokenizer=0.7.0

![image](https://user-images.githubusercontent.com/30543644/86387429-c8f53300-bcb0-11ea-8989-9140ec9416f5.png)

**Comment by ThilinaRajapakse** [comment]
My bad, this is a bug.

**Comment by ThilinaRajapakse** [comment]
I pushed a quick fix, can you let me know whether it's fixed? I don't have a multimodal dataset with me to test right now.

**Comment by AshishGogo** [comment]
It works fine now. Thanks for the quick resolution.
