### ISSUE TITLE
Instructions to use pre-trained models

### ISSUE THREAD

**Issue by adrienrenaud** [ThilinaRajapakse/simpletransformers#53]
Given the current documentation, it is not clear to me how to use a pre-trained model.
My understanding is that using the following will not download the pre-trained model:
```bash
model = ClassificationModel('bert', 'bert-base-multilingual-cased')
```
If this understanding is correct, how can I download a pre-trained model and use it in *simpletransformers*. Clear instructions on how to do that would be most welcome.

**Comment by ThilinaRajapakse** [comment]
I realize that it is not explicitly stated in the docs, but that line will download the pre-trained model.

**Comment by zanderkent** [comment]
Is it possible to download the model outside of this call? I work on a closed network so the auto download will be blocked by the firewalls. Are we to download from from an official repository? And create our own outputs folder?

**Comment by thoppe** [comment]
@adrienrenaud, I've been able to get a pre-trained model to work with simple transformers simply by pointing it at the directory. For example, I downloaded the pyTorch huggingface model of [scibert](https://github.com/allenai/scibert), specifically the `scibert-scivocab-uncased` and unzipped it to a folder of the same name. This now works,

    model = ClassificationModel('bert', 'scibert-scivocab-uncased')

Some care is needed to use the correct tokenization as some models are cased and others are uncased. 

With respect to this library, I agree that the docs could use a note for loading outside models. @ThilinaRajapakse do you want me to suggest a PR just for this?

**Comment by ThilinaRajapakse** [comment]
This is actually mentioned [here](https://github.com/ThilinaRajapakse/simpletransformers#loading-saved-models).

**Comment by Shane-Neeley** [comment]
> I realize that it is not explicitly stated in the docs, but that line will download the pre-trained model.

Are community models also downloaded in this way? e.g. can you pass in anything from here?

https://huggingface.co/models

Thanks

**Comment by ThilinaRajapakse** [comment]
Yeah, community models will be downloaded as long as the primary model type (BERT, RoBERTa, XLNet, etc.) is supported for that particular task.
