### ISSUE TITLE
Encoder Decoder seq2seq Tokenization and 'lm_labels' Error

### ISSUE THREAD

**Issue by ahmetbagci8** [ThilinaRajapakse/simpletransformers#531]
**Describe the bug**
Hello,
When I train Encoder Decoder seq2seq, I get an error. Error message is 

WARNING:transformers.tokenization_utils_base:Truncation was not explicitely activated but `max_length` is provided a specific value, please use `truncation=True` to explicitely truncate examples to max length. Defaulting to 'only_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you may want to check this is the right behavior.

I suppress this warning to change transformers_logger.setLevel(logging.WARNING) line to transformers_logger.setLevel(logging.ERROR) . After that, I get this error 

TypeError: forward() got an unexpected keyword argument 'lm_labels'

I had no problem 2 days ago. Can you help me?

Thanks.

**To Reproduce**
You can try Generic Encoder-Decoder minimal start. I get same errors.

**Desktop (please complete the following information):**
 - Google Colab

**Comment by tutmoses** [comment]
+1 on Mac OS Catalina.

**Comment by kaushalshetty** [comment]
I think huggingface transformers does not support lm_labels anymore. The doc does not reflect that yet.
```
from transformers import EncoderDecoderModel, BertTokenizer
import torch

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = EncoderDecoderModel.from_encoder_decoder_pretrained('bert-base-uncased', 'bert-base-uncased') # initialize Bert2Bert
 input_ids = torch.tensor(tokenizer.encode("Hello, my dog is cute", add_special_tokens=True)).unsqueeze(0)  # Batch size 1
outputs = model(input_ids=input_ids, decoder_input_ids=input_ids)

loss, outputs = model(input_ids=input_ids, decoder_input_ids=input_ids, labels=input_ids)[:2]
```
The above line throws the error.

**Comment by ThilinaRajapakse** [comment]
Pushed a fix to this. Please let me know if it works now.

**Comment by ThilinaRajapakse** [comment]
Re-open if it isn't fixed.

**Comment by tutmoses** [comment]
Sorry for the late reply. Fixed!

**Comment by msakthi19** [comment]
Hey,

I am trying to train a T5 model on Colab and I still get this error.

Code:

model = T5Model("t5-small", args=model_args)
model.train_model(train_df, eval_data=eval_df)

Error: 

Exception ignored in: <generator object tqdm.__iter__ at 0x7ffb20e4b308>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1220, in __iter__
    self.close()
  File "/usr/local/lib/python3.6/dist-packages/tqdm/notebook.py", line 267, in close
    super(tqdm_notebook, self).close(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1325, in close
    fp_write('')
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1322, in fp_write
    self.fp.write(_unicode(s))
  File "/usr/local/lib/python3.6/dist-packages/tqdm/utils.py", line 143, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/lib/redirect.py", line 91, in new_write
    cb(name, data)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/wandb_run.py", line 600, in _console_callback
    self._backend.interface.publish_output(name, data)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/interface/interface.py", line 146, in publish_output
    self._publish_output(o)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/interface/interface.py", line 151, in _publish_output
    self._publish(rec)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/interface/interface.py", line 433, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-8459c368865d> in <module>()
     23 model = T5Model("t5-small", args=model_args)
     24 
---> 25 model.train_model(train_df, eval_data=eval_df)

2 frames
/usr/local/lib/python3.6/dist-packages/simpletransformers/t5/t5_model.py in train_model(self, train_data, output_dir, show_running_loss, args, eval_data, verbose, **kwargs)
    181             eval_data=eval_data,
    182             verbose=verbose,
--> 183             **kwargs,
    184         )
    185 

/usr/local/lib/python3.6/dist-packages/simpletransformers/t5/t5_model.py in train(self, train_dataset, output_dir, show_running_loss, eval_data, verbose, **kwargs)
    364                         loss = outputs[0]
    365                 else:
--> 366                     outputs = model(**inputs)
    367                     # model outputs are always tuple in pytorch-transformers (see doc)
    368                     loss = outputs[0]

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

TypeError: forward() got an unexpected keyword argument 'lm_labels'

PS:
torch                         1.7.0+cu101
transformers                  4.0.0          
simpletransformers            0.49.7         
sentencepiece                 0.1.94         

Thanks in advance!
