### ISSUE TITLE
Using fast tokenizers

### ISSUE THREAD

**Issue by AlecS12** [ThilinaRajapakse/simpletransformers#532]
**Is your feature request related to a problem? Please describe.**

Is there an API to enable the use of fast tokenizers?
I have to  replace the tokenizer in a model after I create it::
```# Create a ClassificationModel
model_name = "allenai/longformer-large-4096-finetuned-triviaqa"
model = ClassificationModel("longformer", model_name, args=model_args)
# replace LongformerTokenizer with LongformerTokenizerFast (it's unclear if it can be done through the simpletransformers API):
model.tokenizer = LongformerTokenizerFast.from_pretrained(model_name, do_lower_case =True, args=model_args)
```

**Describe the solution you'd like**
Create an API or describe the solution in the documentation if it already supported
**Describe alternatives you've considered**

**Additional context**

**Comment by flozi00** [comment]
I am thinking about opening an PR for fast tokenizers.
Maybe there are some errors with the multiprocessing, will check this later
