### ISSUE TITLE
KeyError: 'roberta' for Multimodalclassification model

### ISSUE THREAD

**Issue by AshishGogo** [ThilinaRajapakse/simpletransformers#536]
Getting key error on using roberta as multimodal classsification model

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS

**Additional context**
![image](https://user-images.githubusercontent.com/30543644/86490772-38892200-bd86-11ea-955a-2ec3fd761932.png)

**Comment by ThilinaRajapakse** [comment]
https://github.com/ThilinaRajapakse/simpletransformers#multi-modal-classification
