### ISSUE TITLE
Running out of memory while processing text for language model finetuning

### ISSUE THREAD

**Issue by n2ds** [ThilinaRajapakse/simpletransformers#539]
I'm trying to finetune a language model using a large dataset (~25 million sentences).  I'm creating a fresh ELECTRA model and using the same args as you do in this tutorial:
https://towardsdatascience.com/understanding-electra-and-training-an-electra-language-model-3d33e3a9660d

After training the tokenizer, during the load_and_cache_data call during train_model, I eventualy run out of memory (32gb).  Is there a more efficient way to do this?  Can I do the preprocessing step in batches?  Would there be a way to train iteratively, like break my data into chunks and train on one at a time?

Thanks!

**Comment by ThilinaRajapakse** [comment]
Support for lazy loading will be added to all tasks but it's only implemented for Classification, NER, and QA atm. Language modelling is likely to be next though.
