### ISSUE TITLE
How to pass data to model without using Pandas

### ISSUE THREAD

**Issue by woiza** [ThilinaRajapakse/simpletransformers#542]
How can I pass data to a model without using Pandas / dataframes?
I am working on a multilabel classification problem and want to split my data as follows:

http://scikit.ml/api/skmultilearn.model_selection.iterative_stratification.html#skmultilearn.model_selection.iterative_stratification.iterative_train_test_split

**Comment by ThilinaRajapakse** [comment]
You can pass the data either as dataframes or as text files.

**Comment by woiza** [comment]
ok, thanks.
