### ISSUE TITLE
Trying to use the wandb sweeps and getting "TypeError: __init__() got an unexpected keyword argument 'sweep_config'"

### ISSUE THREAD

**Issue by wiseyoungbuck** [ThilinaRajapakse/simpletransformers#544]
**Describe the bug**
A clear and concise description of what the bug is. Please specify the class causing the issue.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS

**Additional context**

**Comment by ThilinaRajapakse** [comment]
1. What version of the library are you using?
2. Which class/task is throwing the error?
3. Do the minimal examples for sweeps work?

**Comment by wiseyoungbuck** [comment]
> 1.What version of the library are you using?
pip list | grep simpletransformers
simpletransformers     0.41.2
>2. Which class/task is throwing the error?
from simpletransformers.classification import ClassificationModel
>3. Do the minimal examples for sweeps work?
No they do not. The imports for ClassificationArgs does not work
`ImportError: cannot import name 'ClassificationArgs' from 'simpletransformers.classification' (/opt/miniconda3/envs/simpletrans/lib/python3.8/site-packages/simpletransformers/classification/__init__.py)`

**Comment by wiseyoungbuck** [comment]
I resolved the issue. I was not using the  latest version. There were some issue with my pip repo, and there was a phantom version of simpletransformers==0.34.1 in there. Thanks for your help.
