### ISSUE TITLE
ImportError: cannot import name 'ClassificationModel'

### ISSUE THREAD

**Issue by daiyongya** [ThilinaRajapakse/simpletransformers#548]
**Describe the bug**
A clear and concise description of what the bug is. Please specify the class causing the issue.
Now, I have tried in terminal and pycharm, always print error 'ImportError: cannot import name 'ClassificationModel''. But used to be all right. I wonder if it is the version problem?
**To Reproduce**
Any codes with codes 'from simpletransformers.classification import ClassificationModel, ClassificationArgs' will pose the error
**Expected behavior**
No error 
**Screenshots**
![image](https://user-images.githubusercontent.com/8669262/86534714-179f0900-bf0d-11ea-8e11-27b7775f4bd7.png)
![image](https://user-images.githubusercontent.com/8669262/86534721-2be30600-bf0d-11ea-96d6-6f0c49b7609a.png)

**Desktop (please complete the following information):**
 - OS
mac-os and remote computer is linux
**Additional context**

**Comment by mapmeld** [comment]
I have a similar error caused by release of version 0.42.0 today

```
----> 1 from simpletransformers.classification import ClassificationModel
...
/usr/local/lib/python3.6/dist-packages/simpletransformers/classification/classification_model.py in <module>()
     23 )
     24 from tqdm.auto import tqdm, trange
---> 25 from tqdm.contrib import tenumerate
     26 
     27 import pandas as pd

ImportError: cannot import name 'tenumerate'
```

**Comment by daiyongya** [comment]
It seems that the package is updating and some source codes have been modified. For example, simpletransformers/simpletransformers/classification/_init_.py and classification_model.py. If so, I think it's not friendly for using if updating like this

**Comment by ThilinaRajapakse** [comment]
There was no _intentional_ change in how the imports work. But I did have a little problem with git which might have messed something up. I'll check this.

**Comment by ThilinaRajapakse** [comment]
I can import and use these models without any issues. Can you guys check whether your transformers and tokenizers versions are updated as well? It shouldn't really matter, but you never know.

Regarding the `tenumerate` import issue, you may need to update your `tqdm` package.

**Comment by mapmeld** [comment]
Looking into this more closely on CoLab where I first encountered the problem today, ```pip install --upgrade tqdm``` resolves the problem by upgrading from tqdm-4.41.1 to tqdm-4.47.0 - https://colab.research.google.com/drive/1lRXnTyfMVxG-M06tSXZ1sfyRhI7qMcs6?usp=sharing

**Comment by Chygos** [comment]
I'm also having similar problem importing the ClassificationModel, I keep on getting 
ImportError: cannot import name 'tenumerate' 

My tokenizers and transformers are up to date.

**Comment by ThilinaRajapakse** [comment]
> I'm also having similar problem importing the ClassificationModel, I keep on getting
> ImportError: cannot import name 'tenumerate'
> 
> My tokenizers and transformers are up to date.

Regarding the tenumerate import issue, you may need to update your tqdm package.

**Comment by Chygos** [comment]
I have updated tqdm but still having the same message.

**Comment by mapmeld** [comment]
If you are in a notebook, you will need to restart the runtime after updating a builtin library (```pip install --upgrade tqdm```) - if you still have issues, report the version you have installed:

```python
import tqdm
tqdm.__version__
```

**Comment by Chygos** [comment]
tqdm version is  4.41.1.
I'm running on colab

**Comment by ThilinaRajapakse** [comment]
You should be able to upgrade by running `!pip install --upgrade tqdm` in Colab. `tenumerate` seems to have been added in a very recent version.

I've also set a minimum version requirement for `tqdm` which should automatically update `tqdm` when Simple Transformers is installed. (This is `simpletransformers==0.43.0`)

**Comment by Chygos** [comment]
You mean I should upgrade simpletramsformers because it seems tqdm is in its latest version??

**Comment by ThilinaRajapakse** [comment]
No, your `tqdm` version is not the latest (0.47.0 is the latest). But, updating simple transformers should update both now.

**Comment by Chygos** [comment]
It has worked. Thank you for the quick response.

**Comment by daiyongya** [comment]
> I can import and use these models without any issues. Can you guys check whether your transformers and tokenizers versions are updated as well? It shouldn't really matter, but you never know.
> 
> Regarding the `tenumerate` import issue, you may need to update your `tqdm` package.

thank you for your detailed reply. However, I have the same problem after I have check the package you mentioned. At last, I have moved to another computer and installed a new conda environment but there is another problem 
'ImportError: cannot import name 'ClassificationModel' from partially initialized module 'simpletransformers.classification.classification_model' (most likely due to a circular import) (/home/yongdai/.conda/envs/transformers/lib/python3.8/site-packages/simpletransformers/classification/classification_model.py)'

**Comment by ThilinaRajapakse** [comment]
I can only imagine that this is either due to a messed up environment or due to some weird file name which is causing the interpreter to try to import the script into itself (hence the circular import complaint).

In your second screenshot, it appears that the error is being thrown by `transformers.py` despite the import being executed directly inside the Python shell. I am not sure _why_ this happens but I'm pretty sure it _shouldn't_ be happening.

**Comment by daiyongya** [comment]
> I can only imagine that this is either due to a messed up environment or due to some weird file name which is causing the interpreter to try to import the script into itself (hence the circular import complaint).

Thank you so much, your answer gives me the clue. After I changed the name 'transformer.py' to another name, that is, the name of my file conflicts with the package name, it can work now. Thanks for your quick response and detailed answer.

**Comment by ceesroele** [comment]
Thanks, this was a helpful find! Lacking inspiration I called a little scripting file in my working directory 'code.py' and ran into the same problem. Renaming solved it.

**Comment by tikik** [comment]
Hi, Im using linux and when I import ClassificationModels from simpletransformers, it always said too many arguements, can you help?
