### ISSUE TITLE
Sliding window CUBLAS error 

### ISSUE THREAD

**Issue by andrewlaikh** [ThilinaRajapakse/simpletransformers#549]
**Describe the bug**
Tried running the follow classifier with the following parameters: 
model = ClassificationModel('bert', 'bert-base-uncased', num_labels=20, args = {'fp16': False, 'reprocess_input_data': True, 'sliding_window:': True,'max_seq_length':1024, "train_batch_size": 2, "evaluate_during_training": True, "evaluate_during_training_verbose": True}) 

When i train the model using the following command: 
model.train_model(df_train, eval_df = df_val, output_dir = 'bert_base')
I get the following error: 
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-6ab7d33a6581> in <module>
      1 # eval see if you can go further
----> 2 model.train_model(df_train, eval_df = df_val, output_dir = 'bert_base')

~/anaconda3/envs/NLPLaw/lib/python3.6/site-packages/simpletransformers/classification/classification_model.py in train_model(self, train_df, multi_label, output_dir, show_running_loss, args, eval_df, verbose, **kwargs)
    289             eval_df=eval_df,
    290             verbose=verbose,
--> 291             **kwargs,
    292         )
    293 

~/anaconda3/envs/NLPLaw/lib/python3.6/site-packages/simpletransformers/classification/classification_model.py in train(self, train_dataloader, output_dir, multi_label, show_running_loss, eval_df, verbose, **kwargs)
    407 
    408                 inputs = self._get_inputs_dict(batch)
--> 409                 outputs = model(**inputs)
    410                 # model outputs are always tuple in pytorch-transformers (see doc)
    411                 loss = outputs[0]

~/anaconda3/envs/NLPLaw/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

~/anaconda3/envs/NLPLaw/lib/python3.6/site-packages/simpletransformers/classification/transformer_models/bert_model.py in forward(self, input_ids, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, labels)
     60             token_type_ids=token_type_ids,
     61             position_ids=position_ids,
---> 62             head_mask=head_mask,
     63         )
     64         # Complains if input_embeds is kept

~/anaconda3/envs/NLPLaw/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

~/anaconda3/envs/NLPLaw/lib/python3.6/site-packages/transformers/modeling_bert.py in forward(self, input_ids, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, encoder_hidden_states, encoder_attention_mask, output_attentions, output_hidden_states)
    760             encoder_attention_mask=encoder_extended_attention_mask,
    761             output_attentions=output_attentions,
--> 762             output_hidden_states=output_hidden_states,
    763         )
    764         sequence_output = encoder_outputs[0]

~/anaconda3/envs/NLPLaw/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

~/anaconda3/envs/NLPLaw/lib/python3.6/site-packages/transformers/modeling_bert.py in forward(self, hidden_states, attention_mask, head_mask, encoder_hidden_states, encoder_attention_mask, output_attentions, output_hidden_states)
    437                     encoder_hidden_states,
    438                     encoder_attention_mask,
--> 439                     output_attentions,
    440                 )
    441             hidden_states = layer_outputs[0]

~/anaconda3/envs/NLPLaw/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

~/anaconda3/envs/NLPLaw/lib/python3.6/site-packages/transformers/modeling_bert.py in forward(self, hidden_states, attention_mask, head_mask, encoder_hidden_states, encoder_attention_mask, output_attentions)
    369     ):
    370         self_attention_outputs = self.attention(
--> 371             hidden_states, attention_mask, head_mask, output_attentions=output_attentions,
    372         )
    373         attention_output = self_attention_outputs[0]

~/anaconda3/envs/NLPLaw/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

~/anaconda3/envs/NLPLaw/lib/python3.6/site-packages/transformers/modeling_bert.py in forward(self, hidden_states, attention_mask, head_mask, encoder_hidden_states, encoder_attention_mask, output_attentions)
    313     ):
    314         self_outputs = self.self(
--> 315             hidden_states, attention_mask, head_mask, encoder_hidden_states, encoder_attention_mask, output_attentions,
    316         )
    317         attention_output = self.output(self_outputs[0], hidden_states)

~/anaconda3/envs/NLPLaw/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

~/anaconda3/envs/NLPLaw/lib/python3.6/site-packages/transformers/modeling_bert.py in forward(self, hidden_states, attention_mask, head_mask, encoder_hidden_states, encoder_attention_mask, output_attentions)
    219         output_attentions=False,
    220     ):
--> 221         mixed_query_layer = self.query(hidden_states)
    222 
    223         # If this is instantiated as a cross-attention module, the keys

~/anaconda3/envs/NLPLaw/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

~/anaconda3/envs/NLPLaw/lib/python3.6/site-packages/torch/nn/modules/linear.py in forward(self, input)
     85 
     86     def forward(self, input):
---> 87         return F.linear(input, self.weight, self.bias)
     88 
     89     def extra_repr(self):

~/anaconda3/envs/NLPLaw/lib/python3.6/site-packages/torch/nn/functional.py in linear(input, weight, bias)
   1610         ret = torch.addmm(bias, input, weight.t())
   1611     else:
-> 1612         output = input.matmul(weight.t())
   1613         if bias is not None:
   1614             output += bias

RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`

**To Reproduce**
This is run on GCloud with a Tesla T4. Transformers version is 0.41.0. Happy to furnish more information if needed. thanks.

**Expected behavior**
Should run as expected, I'm not sure what the cublas issue is about? I am quite sure this has to do with sliding windows because I have tried running with the other parameters but sliding windows with a token size larger than bert's 512 generates this error.

**Comment by ThilinaRajapakse** [comment]
You have to keep the maximum length at 512 (or below) even when using the sliding window. The `max_seq_length` is the length of the final input to the model. When using a sliding window, any sequences longer than the max length will be split into windows in order to keep the maximum length of any individual sequence below the 512 length limit. This ensures that BERT is happy with the inputs while simultaneously preventing the sequence from being chopped off at the length limit. The library keeps track of which windows are part of the same sequence so that you will get a single prediction for a single sequence when evaluating/predicting.

**Comment by andrewlaikh** [comment]
Got it, thanks!
