### ISSUE TITLE
Problem while trying to load saved models

### ISSUE THREAD

**Issue by manueltonneau** [ThilinaRajapakse/simpletransformers#55]
I get this error (RuntimeError: Error(s) in loading state_dict for BertForSequenceClassification:
	size mismatch for classifier.weight: copying a param with shape torch.Size([3, 768]) from checkpoint, the shape in current model is torch.Size([2, 768]).
	size mismatch for classifier.bias: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([2]).) after trying to load the classification models through:
`model = ClassificationModel('bert', 'outputs/', use_cuda=False)`

I'm doing multi-class classification with BERT base uncased (3 classes).

**Comment by ThilinaRajapakse** [comment]
You need to specify the number of labels when you load the model as well.

> model = ClassificationModel('bert', 'outputs/', num_labels=3, use_cuda=False)

**Comment by manueltonneau** [comment]
Very nice, it works, thanks for the swift reply :)

**Comment by ThilinaRajapakse** [comment]
No problem!
