### ISSUE TITLE
RuntimeError: DataLoader worker (pid 32597) is killed by signal: Aborted.

### ISSUE THREAD

**Issue by daiyongya** [ThilinaRajapakse/simpletransformers#552]
**Describe the bug**
after the training, this error is posted. Is the dataset is too big? What I need to do?
**Screenshots**
![image](https://user-images.githubusercontent.com/8669262/86586409-6b1b6080-bfba-11ea-8dd4-b791ebc69eee.png)

**Comment by ThilinaRajapakse** [comment]
Try turning off multiprocessing. E.g. `model_args = ClassificationArgs(use_multiprocessing=False)`

Unfortunately, the latest updates to transformers and tokenizers libraries seem to have messed up some things.

**Comment by daiyongya** [comment]
> Try turning off multiprocessing. E.g. `model_args = ClassificationArgs(use_multiprocessing=False)`
> 
> Unfortunately, the latest updates to transformers and tokenizers libraries seem to have messed up some things.

thanks. I have tried, it's the same, is there parameter I can set 'data_loader=0' ? I suppose this may be works

**Comment by daiyongya** [comment]
I have split the dataset into small parts, but the code still posed the same error. 
Then, I moved my code to another machine, it becomes all right now. I have checked the free memory, they are nearly the same. It's too weird or something I didn't know. Maybe it's not the memory problem, and maybe there are some conflicts.
Thanks again.
