### ISSUE TITLE
'LanguageModelingArgs' object is not subscriptable

### ISSUE THREAD

**Issue by rushabh7cr** [ThilinaRajapakse/simpletransformers#554]
Trying to finetune.
 model = LanguageModelingModel(
    "electra",
    **'electra',    -->   (when this is none it works but throws the  type error in title when I add electra here)**
    generator_name = 'google/electra-small-generator',
    discriminator_name = 'google/electra-small-discriminator',
    args=train_args
)

in __init__
    "tie_generator_and_discriminator_embeddings"
TypeError: 'LanguageModelingArgs' object is not subscriptable

**Comment by ThilinaRajapakse** [comment]
I pushed a fix for this. Can you try it again with v0.43.3?

**Comment by rushabh7cr** [comment]
It works !!!!
