### ISSUE TITLE
I am getting (ImportError: cannot import name 'BartForQuestionAnswering')

### ISSUE THREAD

**Issue by salateeq** [ThilinaRajapakse/simpletransformers#559]
**Describe the bug**
A clear and concise description of what the bug is. Please specify the class causing the issue.
When I try to (from simpletransformers.question_answering import QuestionAnsweringModel) it is working fine. Suddenly when I installed (SentenceTransformer https://github.com/UKPLab/sentence-transformers) because I need to work on both of these libraries. I am getting an error in importing (simpletransformers)
**To Reproduce**
1- installing simpletransformers
2- then installing sentence-transformers

**Expected behavior**
ImportError: cannot import name 'BartForQuestionAnswering' from 'transformers' (C:\Users\DELL\Anaconda3\envs\towardsdatascience4\lib\site-packages\transformers\__init__.py)

**Screenshots**
![image](https://user-images.githubusercontent.com/19849656/86982165-820baf80-c180-11ea-80cc-ee4c04c2da0f.png)

Desktop
 - OS , Windows 10

**Comment by gitfabianmeyer** [comment]
Which version of transformers do have installed? Run
`import transformers`
`print(transformers.__version__)`

Make sure it's a least 2.6 ( where Bart is introduced). Or simply run 
`pip install transformers --upgrade` to upgrade the version of the transformers package. Maybe that helps.

**Comment by salateeq** [comment]
> Which version of transformers do have installed? Run
> `import transformers`
> `print(transformers.__version__)`
> 
> Make sure it's a least 2.6 ( where Bart is introduced). Or simply run
> `pip install transformers --upgrade` to upgrade the version of the transformers package. Maybe that helps.

Worked fine. Thank you
