### ISSUE TITLE
Electra Warning message while fine tuning

### ISSUE THREAD

**Issue by rushabh7cr** [ThilinaRajapakse/simpletransformers#560]
**Describe the bug**
WARNING:transformers.modeling_utils:Some weights of the model checkpoint at google/electra-base-discriminator were not used when initializing ElectraForPreTraining: ['electra.embeddings_project.weight', 'electra.embeddings_project.bias']
- This IS expected if you are initializing ElectraForPreTraining from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing ElectraForPreTraining from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
**To Reproduce**

Fine tuning using :
model = LanguageModelingModel(
    "electra",
    'electra',
    generator_name = 'google/electra-base-generator',
    discriminator_name = 'google/electra-base-discriminator',
    args=train_args
)

**Comment by ThilinaRajapakse** [comment]
It's expected here.
