### ISSUE TITLE
[QUESTION] How to do I generate a complete article with GPT-2 that contains a coherent an ending as well?

### ISSUE THREAD

**Issue by atherfawaz** [ThilinaRajapakse/simpletransformers#561]
I have been doing language generation using GPT-2. However, the pre-trained model rarely generates a full, self-contained article with a coherent ending. Mostly, it either ends the generated text mid-way through a sentence if not very abruptly. 

Any ideas on how I might fix this? Any parameters that I could pass to the model?

**Comment by ThilinaRajapakse** [comment]
I can't remember anything about this off the top of my head, I'm afraid. This probably won't be helpful, but you could trim any text not ending with a period to prevent text ending mid-way through sentences.

I can't recall running into this issue when I wrote [this article](https://medium.com/swlh/learning-to-write-language-generation-with-gpt-2-2a13fa249024?source=friends_link&sk=97192355cd3d8ba6cfd8b782d7380d86) though.
