### ISSUE TITLE
sliding window for Multi-Label classification

### ISSUE THREAD

**Issue by jonas-nothnagel** [ThilinaRajapakse/simpletransformers#562]
Are there plans to implement the sliding_window function for multi-label classification as well? 
It would be great to be able to work with larger documents as well here!

**Comment by ThilinaRajapakse** [comment]
I'm afraid I don't have immediate plans to extend it to multi-label classification at the moment. But, I will add this to feature requests and see if I can do something about it.

**Comment by null-id** [comment]
Hi @ThilinaRajapakse , I wonder why this feature is moved from TODO to DONE, but I still cannot use it?

**Comment by jonas-nothnagel** [comment]
I would also still love to have this!

**Comment by null-id** [comment]
@jonas-nothnagel It already has.

**Comment by jonas-nothnagel** [comment]
@null-id and @ThilinaRajapakse  this is great to hear! Thank you for keep improving this library!

I just tried to enable sliding window in the `MultiLabelClassificationArgs()` but always ran into following error during evaluation:

`TypeError: zip argument #2 must support iteration`

Anything to keep in mind?

**Comment by ThilinaRajapakse** [comment]
Unfortunately, it's not done yet. The bot marked it as done, not me. 😅

**Comment by null-id** [comment]
Ah... But Why I just used it normally for MultiLabelClassification?😂 @ThilinaRajapakse

**Comment by ThilinaRajapakse** [comment]
You can set it, but I don't think it will be used. Unless I added the feature but have absolutely no memory of doing so. 😆

**Comment by null-id** [comment]
Emm... However, It seems the result makes sense... The trained model can predict long text and return a list of predictions (the length is the number of segmentation for this piece of text).

**Comment by jonas-nothnagel** [comment]
@null-id  How do you use the trained model for evaluation? 

You can set and also run `model.train_model()` with sliding-window, however it always fails for me in the evaluation step.

@ThilinaRajapakse perhaps save us from speculating and implement :) ?

**Comment by null-id** [comment]
@jonas-nothnagel What error you met during evaluation?

**Comment by ThilinaRajapakse** [comment]
Well, damn lol. Either of you guys interested in taking a look and seeing if you can get it to work with evaluation so that we can add it officially? 😉

**Comment by null-id** [comment]
I can try to mean the list of segments to get the result to evaluate. But is this an acceptable version to merge?

**Comment by ThilinaRajapakse** [comment]
Yes. That is how it is implemented in `ClassificationModel` as well. You should be able to just follow that spec I think.

**Comment by jonas-nothnagel** [comment]
Wow is it done now?

**Comment by ThilinaRajapakse** [comment]
I'm afraid not. Apparently, it does work with training and prediction though (no guarantees).
