### ISSUE TITLE
Can't import ClassificationModel in Kaggle

### ISSUE THREAD

**Issue by vin2015-edem** [ThilinaRajapakse/simpletransformers#563]
Can't import ClassificationModel in the private notebook in Kaggle (Python 3.7).
I start:

`!pip install simpletransformers`
`import torch`
`from simpletransformers.classification import ClassificationModel`

 and get the error on the last command:

> ImportError: cannot import name 'MobileBertConfig' from 'transformers' (/opt/conda/lib/python3.7/site-packages/transformers/__init__.py)

I tried changing parameter "Environment" = "original environment (2020-07-06)" or "latest environment" - no difference

How to fix it?

**Comment by ThilinaRajapakse** [comment]
The `transformers` version may be out of date.

`!pip install --upgrade transformers`

**Comment by vin2015-edem** [comment]
Thanks, but that did not help me. Displayed the same error

**Comment by ThilinaRajapakse** [comment]
What is the version of `transformers`?

**Comment by ma-ji** [comment]
The same issue here. After removing `MobileBertConfig` and related `MobileBert` lines, it worked.

**Comment by vin2015-edem** [comment]
transformers-3.0.2, tokenizers-0.8.1rc1, simpletransformers-0.43.5
...
The error has disappeared, thanks! 
Now another appeared:

> OSError: [Errno 28] No space left on device

But this is another problem. 
I think my question is closed.

**Comment by vin2015-edem** [comment]
I solved the problem with a lack of space by switching from model "BERT" to "DistilBERT". And this gave a very good result even in 1 or 2 epochs. I made public my notebook - you can see: https://www.kaggle.com/vbmokin/nlp-with-dt-simple-transformers-research
This is not a prize contest - this is a contest to test new NLP technologies - https://www.kaggle.com/c/nlp-getting-started
Thank you for your amazing library and for your help in using it! Your advice "upgrade transformers" helped me.

**Comment by ThilinaRajapakse** [comment]
> The same issue here. After removing `MobileBertConfig` and related `MobileBert` lines, it worked.

It shouldn't be necessary to remove them if your `transformers` version is up to date.
