### ISSUE TITLE
ImportError: cannot import name 'add_code_sample_docstrings' from 'transformers.file_utils'

### ISSUE THREAD

**Issue by jasontweet** [ThilinaRajapakse/simpletransformers#567]
I am following the tutorial on Medium: 
**Simple Transformers — Multi-Class Text Classification with BERT, RoBERTa, XLNet, XLM, and DistilBERT**
[Tutorial on Medium](https://medium.com/swlh/simple-transformers-multi-class-text-classification-with-bert-roberta-xlnet-xlm-and-8b585000ce3a)

- After setting up the environment as per instructions, I open a new notebook with a kernel of the new *transformers* environment (created as per instructions) in a Jupyter notebook.   
- I import some data.   
- Then I wanted to load the model as shown in the second cell block in the tutorial (except for 2 labels, not 4):

`from simpletransformers.classification import ClassificationModel`    
`model = ClassificationModel('roberta', 'roberta-base', num_labels=2)`

**Error**
ImportError: cannot import name 'add_code_sample_docstrings' from 'transformers.file_utils' (..\.conda\envs\SimpleTransformers\lib\site-packages\transformers\file_utils.py)

**Expected behavior**
I had expected to model to load as suggested by the tutorial. Transformers itself works fine with other code to train models such as BERT.

**My System Set-up**
- Windows 10
- NVidia RTX 2080 ti
- Cuda 10.0 installed
- Python 3.7
- Anaconda

**Virtual Environment Packages Installed:**
Package            Version
attrs              19.3.0
backcall           0.2.0
bleach             3.1.5
certifi            2020.6.20
cffi               1.14.0
chardet            3.0.4
click              7.1.2
colorama           0.4.3
decorator          4.4.2
defusedxml         0.6.0
entrypoints        0.3
filelock           3.0.12
h5py               2.10.0
idna               2.10
importlib-metadata 1.7.0
ipykernel          5.3.0
ipython            7.16.1
ipython-genutils   0.2.0
ipywidgets         7.5.1
jedi               0.17.1
Jinja2             2.11.2
joblib             0.16.0
jsonschema         3.2.0
jupyter            1.0.0
jupyter-client     6.1.5
jupyter-console    6.1.0
jupyter-core       4.6.3
Keras              2.4.3
MarkupSafe         1.1.1
mistune            0.8.4
mkl-fft            1.1.0
mkl-random         1.1.1
mkl-service        2.3.0
nbconvert          5.6.1
nbformat           5.0.7
notebook           6.0.3
numpy              1.18.5
packaging          20.4
pandas             1.0.5
pandocfilters      1.4.2
parso              0.7.0
pickleshare        0.7.5
pip                20.1.1
prometheus-client  0.8.0
prompt-toolkit     3.0.5
protobuf           3.12.2
pycparser          2.20
Pygments           2.6.1
pyparsing          2.4.7
pyrsistent         0.16.0
python-dateutil    2.8.1
pytz               2020.1
pywin32            227
pywinpty           0.5.7
PyYAML             5.3.1
pyzmq              19.0.1
qtconsole          4.7.5
QtPy               1.9.0
regex              2020.6.8
requests           2.24.0
sacremoses         0.0.43
scikit-learn       0.23.1
scipy              1.5.0
Send2Trash         1.5.0
sentencepiece      0.1.91
seqeval            0.0.12
setuptools         47.3.1.post20200622
simpletransformers 0.43.5
sip                4.19.13
six                1.15.0
tensorboardX       2.1
terminado          0.8.3
testpath           0.4.4
threadpoolctl      2.1.0
tokenizers         0.8.1rc1
torch              1.4.0
tornado            6.0.4
tqdm               4.47.0
traitlets          4.3.3
transformers       3.0.2
urllib3            1.25.9
wcwidth            0.2.5
webencodings       0.5.1
wheel              0.34.2
widgetsnbextension 3.5.1
wincertstore       0.2
zipp               3.1.0

**Full Error**

ImportError                               Traceback (most recent call last)
<ipython-input-3-0ff8e6f62f64> in <module>
----> 1 from simpletransformers.classification import ClassificationModel
      2 # Create a ClassificationModel
      3 model = ClassificationModel('roberta', 'roberta-base', num_labels=2)

~\.conda\envs\SimpleTransformers\lib\site-packages\simpletransformers\classification\__init__.py in <module>
----> 1 from simpletransformers.classification.classification_model import ClassificationModel
      2 from simpletransformers.classification.multi_label_classification_model import MultiLabelClassificationModel
      3 from simpletransformers.classification.multi_modal_classification_model import MultiModalClassificationModel
      4 from simpletransformers.config.model_args import ClassificationArgs
      5 from simpletransformers.config.model_args import MultiLabelClassificationArgs

~\.conda\envs\SimpleTransformers\lib\site-packages\simpletransformers\classification\classification_model.py in <module>
     28 import torch
     29 from simpletransformers.classification.classification_utils import InputExample, convert_examples_to_features
---> 30 from simpletransformers.classification.transformer_models.albert_model import AlbertForSequenceClassification
     31 from simpletransformers.classification.transformer_models.bert_model import BertForSequenceClassification
     32 from simpletransformers.classification.transformer_models.camembert_model import CamembertForSequenceClassification

~\.conda\envs\SimpleTransformers\lib\site-packages\simpletransformers\classification\transformer_models\albert_model.py in <module>
      2 import torch.nn as nn
      3 from torch.nn import CrossEntropyLoss, MSELoss
----> 4 from transformers.modeling_albert import AlbertConfig, AlbertModel, AlbertPreTrainedModel
      5 
      6 

~\.conda\envs\SimpleTransformers\lib\site-packages\transformers\modeling_albert.py in <module>
     25 
     26 from .configuration_albert import AlbertConfig
---> 27 from .file_utils import add_code_sample_docstrings, add_start_docstrings, add_start_docstrings_to_callable
     28 from .modeling_bert import ACT2FN, BertEmbeddings, BertSelfAttention, prune_linear_layer
     29 from .modeling_utils import PreTrainedModel, find_pruneable_heads_and_indices

ImportError: cannot import name 'add_code_sample_docstrings' from 'transformers.file_utils' (..\.conda\envs\SimpleTransformers\lib\site-packages\transformers\file_utils.py)

**Comment by jasontweet** [comment]
Resolved problem by setting/up a new environment with python 3.7, TF 2.0 and pytorch for cuda 10.0

**Comment by ThilinaRajapakse** [comment]
You may have been using the wrong environment.

```bash
ImportError: cannot import name 'add_code_sample_docstrings' from 'transformers.file_utils' (...conda\envs\SimpleTransformers\lib\site-packages\transformers\file_utils.py)
```

The environment name is SimpleTransformers here (you mentioned that the environment was created with the name `transformers`)
