### ISSUE TITLE
Warning: "Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels."

### ISSUE THREAD

**Issue by vin2015-edem** [ThilinaRajapakse/simpletransformers#568]
I have a training data as DataFrame (Python 3.7) in Kaggle (see my public notebook https://www.kaggle.com/vbmokin/nlp-with-dt-simple-transformers-research) with such features:
- "text" with text for example (type "object") 'Forest fire near La Ronge Sask. Canada'
- "target" with 0 or 1 only (type "int64")
I start training model in according to instructions. All works but outputs warning:

`/opt/conda/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py:277: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  "Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels."` 

Why? I just have column 0 as text and column 1 as labels.
I worry. Maybe something is working incorrectly?

**Comment by ThilinaRajapakse** [comment]
I think your labels column is named `label` rather than `labels`, which is why you get the warning. Renaming the column to `labels` should remove the warning.

Even if you don't, it's fine as the dataframe columns are in the expected order.

**Comment by vin2015-edem** [comment]
Thanks for your answer.
