### ISSUE TITLE
Can't get embeddings

### ISSUE THREAD

**Issue by vin2015-edem** [ThilinaRajapakse/simpletransformers#569]
The documentation contains advice:

> If config: {"output_hidden_states": True}, two additional values will be returned.
> - all_embedding_outputs: Numpy array of shape (batch_size, sequence_length, hidden_size)

I set 

`model_args =  {'output_hidden_states': True}`
`model = ClassificationModel(model_type, model_name, args=model_args)`
`model.train_model(train_data)`
`pred_train, _, all_embedding_outputs, _ = model.predict(train_data['text'])`

and get the error:

> ValueError: not enough values to unpack (expected 4, got 2)

What am I doing wrong?

**Comment by ThilinaRajapakse** [comment]
Try:

```python
model_args = {'config': {'output_hidden_states': True}}
```

**Comment by vin2015-edem** [comment]
It works, thanks!
The only pity is that there is not enough memory. Only started for 'max_seq_length' = 20 and not for 128 and even 40. 
It would be better if there was a parameter returning the aggregating or last embedding (batch_size, sequence_length) only.

**Comment by ThilinaRajapakse** [comment]
How much memory do you have on the system? I don't think getting the embedding should make _that_ much of a difference to memory consumption. Not unless you need to keep all the embeddings saved in memory or something like that.

**Comment by vin2015-edem** [comment]
I use Kaggle free editor (Jupyter Notebook, Python 3.7): https://www.kaggle.com/docs/notebooks

* CPU Specifications
4 CPU cores, 16 Gigabytes of RAM
* GPU Specifications
2 CPU cores, 13 Gigabytes of RAM

Dataset: https://www.kaggle.com/c/nlp-getting-started/data

But really, when working with one notebook, apparently, not everything is available. Also, it all depends on the dataset. And I am running not only your library. EDA, cleaning data, visualization data etc.
Obviously there are problems with your settings. I have to work only with the most economical models and their parameters.
