### ISSUE TITLE
Unable to import Xlnet DistilBERT models for NER training

### ISSUE THREAD

**Issue by miteshyadav** [ThilinaRajapakse/simpletransformers#57]
Throws a key error when trying to import either XLnet or DistilBert. Runs fine with any BERT (case/uncased) model

#Code
model = NERModel('xlnet', 'xlnet-large-cased',use_cuda=True)
model = NERModel('distilbert', 'distilbert-base-uncased-distilled-squad',use_cuda=True)

Ran on Google Collab

**Comment by ThilinaRajapakse** [comment]
Bert is the only available model for NER atm (Same on the Transformers library).

**Comment by miteshyadav** [comment]
Thank you for your response. Any plans to add more models in the future?

**Comment by ThilinaRajapakse** [comment]
Yeah, I am continuously adding new models but how long it takes depends on how much free time I get!

**Comment by miteshyadav** [comment]
Awesome. Thanks so much. It's a really awesome library and does a good job abstracting lower level features. Also, Huggingface recently added a new DistilBERT model for TokenClassification, named DistilBertForTokenClassification, which can be helpful if you plan to embed that feature in Simpletransfomers. Thanks.

**Comment by ThilinaRajapakse** [comment]
Thank you!
Yeah, I can add that soon
