### ISSUE TITLE
Use electra with `from_pretrained` in transformers library

### ISSUE THREAD

**Issue by Zhylkaaa** [ThilinaRajapakse/simpletransformers#571]
**Is your feature request related to a problem? Please describe.**
We trained `ElectraForSequenceClassification`, but we tried to use this pertained model with transformers `ElectraForSequenceClassification` using `.from_pretrained` method which provided us with following warnings 
```
Some weights of the model checkpoint at models/electra-base-generator-final were not used when initializing ElectraForSequenceClassification: ['pooler.dense.weight', 'pooler.dense.bias', 'classifier.weight', 'classifier.bias']
- This IS expected if you are initializing ElectraForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing ElectraForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of ElectraForSequenceClassification were not initialized from the model checkpoint at models/electra-base-generator-final and are newly initialized: ['classifier.dense.weight', 'classifier.dense.bias', 'classifier.out_proj.weight', 'classifier.out_proj.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
```

**Describe the solution you'd like**
is there any way to convert this model without running training again? 

**Describe alternatives you've considered**
Can you provide some script or some hints on how it can be implemented?

**Additional context**

**Comment by ThilinaRajapakse** [comment]
You should be able to use it without retraining the model.

The warning is issued because the model weights are initialized directly through Pytorch instead of through the `from_pretrained()` method.

**Comment by Zhylkaaa** [comment]
Sorry, I was not very concise about what's wrong. So, we trained `ElectraForSequenceClassification` with `simpletransformers` and than I tried to use HuggingFace `transformers` library to serve the model, and due to different implementation I am getting this warning 
`transformers` use this as forward: 
```
discriminator_hidden_states = self.electra(
            input_ids,
            attention_mask,
            token_type_ids,
            position_ids,
            head_mask,
            inputs_embeds,
            output_attentions,
            output_hidden_states,
        )

        sequence_output = discriminator_hidden_states[0]
        logits = self.classifier(sequence_output)

        outputs = (logits,) + discriminator_hidden_states[1:]
```

while `simpletransformers` use:
```
outputs = self.electra(input_ids, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds)
        sequence_output = outputs[0]
        pooled_output = self.pooler(sequence_output)
        pooled_output = self.dropout(pooled_output)
        logits = self.classifier(pooled_output)

        outputs = (logits,) + outputs[2:]
```

**Comment by ThilinaRajapakse** [comment]
There was another issue about this which I can't seem to find. I could change the implementation to just use the `transformers` version, which should prevent this problem. But, that will probably mean that any ELECTRA classification models trained before the change will no longer work in ST. 🤔

**Comment by Zhylkaaa** [comment]
I was thinking to prepare PR with this change but was worried about backward compatibility, so do you want to do it?

**Comment by ThilinaRajapakse** [comment]
I am decidedly undecided. :sweat_smile:

But, I am leaning towards making the change. Having this incompatibility between the two libraries might be an even bigger headache down the line.

**Comment by WeberJulian** [comment]
Hi is there some news on this topic ? I trained a model with `simpletransformers` but my inference code is with the `transformers` library.
