### ISSUE TITLE
Evaluation issue (sentence pair regression with BERT)

### ISSUE THREAD

**Issue by carolscarton** [ThilinaRajapakse/simpletransformers#573]
Hi,

I am using this toolkit for sentence pair regression, fine-tuning BERT with multilingual BERT model. 

I have managed to train and evaluate the models in a single step, but when I reload the model and try to perform evaluation (in the same development set as before) I get the following error:

Traceback (most recent call last):
  File "qe_simpletrans_eval.py", line 65, in <module>
    result, model_outputs, wrong_predictions = model.eval_model(eval_df, pearson_corr=pearson_corr, spearman_corr=spearman_corr, mae=mae, frank=frank)
  File "/srv/Documents/anaconda3/envs/simpletrans/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py", line 704, in eval_model
    eval_df, output_dir, multi_label=multi_label, verbose=verbose, silent=silent, wandb_log=wandb_log, **kwargs
  File "/srv/Documents/anaconda3/envs/simpletrans/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py", line 760, in evaluate
    eval_examples, evaluate=True, verbose=verbose, silent=silent
  File "/srv/Documents/anaconda3/envs/simpletrans/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py", line 912, in load_and_cache_examples
    example.label = self.args.labels_map[example.label]
KeyError: 0.09997

I have used exactly the same args to reload the model and I have also double checked I was using the same why to create the development data pandas dataframe. 

For reference, the pandas dataframe looks like this: 

                                                text_a                                             text_b    labels
0    text text text text text text text text text...  text text text text text text text text text...   0.09997
1    text text text text text text text text text...  text text text text text text text text text...  0.8525
2    text text text text text text text text text...        text text text text text text text text text...  -1.3323

Any ideas on why this happens? 

thanks!

**Comment by ThilinaRajapakse** [comment]
There was a bug in a previous version that would have caused this error. Can you check whether you are on the latest version, please?

**Comment by carolscarton** [comment]
Hi! Many thanks for your reply! I indeed was using an older version simpletransformers 0.43.4.

I have now upgraded to simpletransformers-0.43.6 (following the instructions here: https://simpletransformers.ai/docs/upgrading/)

However, I am still getting the same error.

**Comment by khituras** [comment]
I am a newbie myself, but did you set the `num_labels` argument to `1` when creating the classifier? Because it looks to me as if the error happens where the label string is mapped to the encoding label integer what is done for a classification setup. But this should not happen in the case of regression.
