### ISSUE TITLE
Epoch counter starts at 0

### ISSUE THREAD

**Issue by gitfabianmeyer** [ThilinaRajapakse/simpletransformers#575]
Training for N epochs, the training starts at epoch 0/N and ends after N-1/N.
If this behaviour is not needed inside, it could be an idea to start at 1 and end at N.
Great work btw, I really like this project!

**Comment by ThilinaRajapakse** [comment]
It's only cosmetic, so it can be changed without causing issues. I wasn't sure about which behaviour to use, but I decided to go with the Python way of defining ranges. Looking back, I must admit that the behaviour you suggest may be more intuitive. :thinking:
