### ISSUE TITLE
Weight doesn't work in the ClassificationModel in binary classification

### ISSUE THREAD

**Issue by vin2015-edem** [ThilinaRajapakse/simpletransformers#576]
Attempting to add parameter "weight" in the ClassificationModel in binary classification 

`model = ClassificationModel(model_type, model_name, args=model_args, weight=weight)`

results in an error:

`NameError: name 'weight' is not defined`

In the same time the documentation:

> "weight (optional): A list of length num_labels containing the weights to assign to each label for loss calculation."

I have labels = [0,1] and set 

`weight = [0.6, 0.4]`

Why isn't it working or what am I doing wrong?

**Comment by gitfabianmeyer** [comment]
`NameError: name 'weight' is not defined` means your variable `weight` is not known. Therefor you didn't set `weight = [0.6, 0.4]` before calling the variable.
Try
`model = ClassificationModel(model_type, model_name, args=model_args, weight=[0.6, 0.4])`

**Comment by vin2015-edem** [comment]
Strange, that's how it was for me ... But then I started the cells in a different sequence. Apparently, I mixed something up. Everything is working now. Thanks.
