### ISSUE TITLE
MultiLabel-ClassificationModel : shape is invalid for input of size 

### ISSUE THREAD

**Issue by HYC0311** [ThilinaRajapakse/simpletransformers#58]
I'm trying to repeat the example "Toxic Comments Dataset - Multilabel Classification"
And an error occurs while model.train_model(train_df_0)

Note:
model = MultiLabelClassificationModel('roberta', 'roberta-base', num_labels=6, args={'train_batch_size':2, 'gradient_accumulation_steps':16, 'learning_rate': 3e-5, 'num_train_epochs': 3, 'max_seq_length': 512, 'reprocess_input_data': True})

train_df_0.shape = (127656, 7)

Here is the message:
Converting to features started.
HBox(children=(IntProgress(value=0, max=127656), HTML(value='')))
HBox(children=(IntProgress(value=0, description='Epoch', max=3, style=ProgressStyle(description_width='initial…
HBox(children=(IntProgress(value=0, description='Current iteration', max=63828, style=ProgressStyle(descriptio…
Traceback (most recent call last):
  File "C:\Users\GPU\Anaconda3\envs\tf2_simple\lib\site-packages\simpletransformers\custom_models\models.py", line 114, in forward
    loss = loss_fct(logits.view(-1, self.num_labels), labels.view(-1, self.num_labels))

RuntimeError: shape '[-1, 6]' is invalid for input of size 2

**Comment by HYC0311** [comment]
I found the answer.

# Train and Evaluation data needs to be in a Pandas Dataframe containing at least two columns, a 'text' and a 'labels' column. The `labels` column should contain multi-hot encoded lists.
train_data = [['Example sentence 1 for multilabel classification.', [1, 1, 1, 1, 0, 1]]] + [['This is another example sentence. ', [0, 1, 1, 0, 0, 0]]]
train_df = pd.DataFrame(train_data, columns=['text', 'labels'])
train_df = pd.DataFrame(train_data)

**Comment by ThilinaRajapakse** [comment]
Great!
