### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by Sreelakshmi-k** [ThilinaRajapakse/simpletransformers#583]
When i load the saved models and try to load them i am getting assertion error. Could you please tell why this is occurring

**Comment by ThilinaRajapakse** [comment]
Please show your code and the error you get.

**Comment by Sreelakshmi-k** [comment]
[image: image.png]
Thank you for your response.
Above is the image of the error message and my code.
Regards,
Sreelakshmi

**Comment by Sreelakshmi-k** [comment]
Could you pleases help me with a solution for this error

**Comment by ThilinaRajapakse** [comment]
The image can't be opened. Please copy the error as text.

Make sure that you are using the latest version of the library.

**Comment by Sreelakshmi-k** [comment]
AssertionError                            Traceback (most recent call last)
<ipython-input-19-cf6066880caa> in <module>()
      1 from simpletransformers.classification import ClassificationModel
      2 # Create a TransformerModel
----> 3 model = ClassificationModel('bert', 'checkpoint-282-epoch-1/',use_cuda=False,num_labels=2, args={'num_train_epochs':1, 'learning_rate': 3e-5,'max_seq_length': 300,'train_batch_size': 32,'eval_batch_size': 32,'overwrite_output_dir':True,'save_steps':4000,'use_multiprocessing':False})
      4 # Train the model
      5 model.train_model(train)

/usr/local/lib/python3.6/dist-packages/simpletransformers/classification/classification_model.py in __init__(self, model_type, model_name, num_labels, weight, args, use_cuda, cuda_device, **kwargs)
    143                 assert num_labels == len(self.args.labels_list)
    144             if self.args.labels_map:
--> 145                 assert list(self.args.labels_map.keys()) == self.args.labels_list
    146             else:
    147                 self.args.labels_map = {label: i for i, label in enumerate(self.args.labels_list)}

AssertionError:

**Comment by Sreelakshmi-k** [comment]
I have done !pip install simpletransformers so i think it is using the latest version of the library.

**Comment by ThilinaRajapakse** [comment]
What was the `num_labels` in the saved model? Can you add the contents of the `model_args.json` file (should be there in the model directory)?

**Comment by tsing90** [comment]
I got the same issue. the reason is simple, in `model_args.json`, they are: 
`"labels_list": [0, 1, 2, 3], "labels_map": {"0": 0, "1": 1, "2": 2, "3": 3}`
as can be seen obviously, the issue comes from the initialization code in `classification_model.py` (line 147)

**Comment by ThilinaRajapakse** [comment]
You are right. The issue is that JSON converts the integer keys to strings. I pushed a fix for this in `0.45.5`. Please let me know if the problem persists.

**Comment by Sreelakshmi-k** [comment]
Thank you for your reply sir.

I still have that issue. I ran for 3 epochs continuously and then loaded the 3rd epoch checkpoint and trained for 4th epoch which worked. Now the saved 4th epoch checkpoint has "labels_list": [0, 1], "labels_map": {"0": 0, "1": 1} in model_args.json and when this checkpoint is loaded and trained i get the error. 

This time the error has a different name 

/usr/local/lib/python3.6/dist-packages/simpletransformers/classification/classification_model.py in load_and_cache_examples(self, examples, evaluate, no_cache, multi_label, verbose, silent)
    914                         example.label = [self.args.labels_map[label] for label in example.label]
    915                     else:
--> 916                         example.label = self.args.labels_map[example.label]
    917 
    918             features = convert_examples_to_features(

KeyError: 0

**Comment by ThilinaRajapakse** [comment]
Can you share the Colab notebook?

**Comment by Sreelakshmi-k** [comment]
Please find the attached colab notebook
Regards,
Sreelakshmi

**Comment by ThilinaRajapakse** [comment]
Sorry, I don't see the attachment. Can you share it through a link?

**Comment by Sreelakshmi-k** [comment]
Sorry for the inconvenience.
Below is the link to the notebook

https://colab.research.google.com/drive/145tl0nOLe0NX9swodHCNsBPasMx0-wqz?usp=sharing

Regards,
Sreelakshmi

**Comment by ThilinaRajapakse** [comment]
Thanks.

You should be able to install the latest version (`0.46.6`) on Colab now. Can you check whether you still have these issues with that version?

**Comment by Sreelakshmi-k** [comment]
Thank you sir. Will doing pip install simpletransformer install the new
version?

**Comment by ThilinaRajapakse** [comment]
It should. If not, `pip install simpletransformers==0.46.6` should work now.

**Comment by Sreelakshmi-k** [comment]
Thank you sir.
