### ISSUE TITLE
Required transformers version over 3.0 because of MobileBert

### ISSUE THREAD

**Issue by kwanhong66** [ThilinaRajapakse/simpletransformers#584]
**Describe the bug**

I wanted to customize this repo code and import it for loading Korean model.
I cloned this library code for manipulation and installed requirements. When I install requirements, I fixed transformers version with 2.11.0, because I saw `install_requires` with `transformers>=2.11.0` in `setup.py`.
Then, I got ImportError becuase `ner_model.py` import `MobileBert...` from transformers which was released in over version 3.0.0.
I think `simpletransformers` has to require transformers over 3.0.0.

**To Reproduce**

1. Clone this repo
2. Install requirements with transformers version 2.11.0 fixed especially
3. Run debug NER minimal start code
4. Got `ImportError: cannot import name 'MobileBertConfig'`

**Expected behavior**
Successful import `NERModel`

**Screenshots**

**Desktop (please complete the following information):**
 - Ubuntu 16.04

**Additional context**

**Comment by ThilinaRajapakse** [comment]
`transformers>=2.11.0` is _greater than or equal_ not `equal to`. The version requirement hasn't been bumped yet because there were some issues in transformers 3.0, but it should be safe to bump it now.

**Comment by kwanhong66** [comment]
I already knew that `transformers>=2.11.0` means `greater than or equal`. 
I just tried to figure out whether this library could run on the 2.11.0 version when importing this library code not `pip install` because of major changes between 2 and 3.

Thanks for your response 😄

**Comment by ThilinaRajapakse** [comment]
Clearly.
