### ISSUE TITLE
How do I use a finetuned classification model to generate token embeddings?

### ISSUE THREAD

**Issue by ayanchandra** [ThilinaRajapakse/simpletransformers#586]
I have already finetuned the bert-base-uncased with a custom dataset using text classifier/ClassificationModel. Now I want to use the saved model for generating token embeddings for the tokens of a given text. 
How to do that? 
In other way, can the saved instance of ClassificationModel be converted into the corresponding huggingface transformer model?
Thanks.

**Comment by ThilinaRajapakse** [comment]
You can get the hidden states from each layer by setting `config: {"output_hidden_states": True}`. E.g.:

```python
from simpletransformers.classification import ClassificationArgs


model_args = ClassificationArgs()
model_args.config = {"output_hidden_states": True}
```

**Comment by OanaIgnat** [comment]
I added "output_hidden_states": True in the args of my classification model, but when I run model.predict() I still don't see all_layer_hidden_states and all_embedding_outputs.

Could you give a more detail example?
