### ISSUE TITLE
Distributed training issue in language_modeling_model.py

### ISSUE THREAD

**Issue by abhik1505040** [ThilinaRajapakse/simpletransformers#588]
[https://github.com/ThilinaRajapakse/simpletransformers/blob/master/simpletransformers/language_modeling/language_modeling_model.py#L149-L166](https://github.com/ThilinaRajapakse/simpletransformers/blob/master/simpletransformers/language_modeling/language_modeling_model.py#L149-L166)

Shouln't this block be inside the `train_model` function? In a distributed setting, the tokenizer would be trained unnecessarily for multiple times.

**Comment by ThilinaRajapakse** [comment]
Yeah, this is causing the tokenizer to be trained multiple times.
