### ISSUE TITLE
lazy_text_a_column argument in description reads "For single sentence datasets" in Documentation

### ISSUE THREAD

**Issue by aakashdusane** [ThilinaRajapakse/simpletransformers#589]
"Configuring the classification model" section needs a small correction. 
For the arguments **lazy_text_a_column, lazy_text_b_column**, the description should read "for lazy loading sentence pair datasets" instead of "single sentence datasets".

![image](https://user-images.githubusercontent.com/40353160/88256409-e5492600-ccd8-11ea-8c24-ad36b25a0a8d.png)

**Comment by ThilinaRajapakse** [comment]
Thanks! I'll fix it.

**Comment by ThilinaRajapakse** [comment]
Fixed.
