### ISSUE TITLE
Possible values for early_stopping_metric

### ISSUE THREAD

**Issue by fatotoro** [ThilinaRajapakse/simpletransformers#591]
I am sorry if I am missing anything - I have been reading through the documentation to find possible values for "early_stopping_metric" in addition to the default value ("eval_loss"), but have no luck finding it. Could anyone please point me to where this information resides? Thank you so much!

**Comment by fatotoro** [comment]
Just found a way round by manually adding metrics as provided in the docs - wonder if there are other preset metrics but manually adding definitely works though!

**Comment by xiang994271774** [comment]
HI,fatotoro,I have the same problem with you. How did you solve it at last?
