### ISSUE TITLE
NER labels assignment for tokens

### ISSUE THREAD

**Issue by Pradhy729** [ThilinaRajapakse/simpletransformers#592]
Why are the labels for all but the 1st token of a work annotated with the the pad label? Doesn't it make more sense for all the tokens of a word to have the same label of the named entity?

https://github.com/ThilinaRajapakse/simpletransformers/blob/3e9836132495b28ace613ca61d245575ca3f8abc/simpletransformers/ner/ner_utils.py#L115-L120

If you agree - I can push a PR.

**Comment by ThilinaRajapakse** [comment]
I am not sure why, but that's how it seems to be implemented for NER. It's the same in Hugging Face as well (unless I missed a change).
