### ISSUE TITLE
Bug in classification Model

### ISSUE THREAD

**Issue by Jashjeet** [ThilinaRajapakse/simpletransformers#593]
AttributeError: 'NoneType' object has no attribute 'dataloader_num_workers'

   sampler=train_sampler,
    286             batch_size=self.args.train_batch_size,
--> 287             num_workers=args.dataloader_num_workers,
    288         )

**Comment by wanng-ide** [comment]
Me too

**Comment by MDTech-us-MAN** [comment]
Same here. Looks to be a typo at line 287. `args.dataloader_num_workers` probably should be `self.args.dataloader_num_workers`. After manually fixing that, everythign started working.

**Comment by Jashjeet** [comment]
> 
> 
> Same here. Looks to be a typo at line 287. `args.dataloader_num_workers` probably should be `self.args.dataloader_num_workers`. After manually fixing that, everything started working.

Yep even I was thinking the same

**Comment by ThilinaRajapakse** [comment]
Yeah, you guys are right. I'll push a fix soon.

**Comment by FahriBilici** [comment]
I have same error
