### ISSUE TITLE
Add custom tokens

### ISSUE THREAD

**Issue by DebanjanaKar** [ThilinaRajapakse/simpletransformers#594]
**Is your feature request related to a problem? Please describe.**
I want to add customized tokens to the pre-trained models while finetuning.  Reading through the issues, I believe this option is still not available.

**Describe the solution you'd like**
To be able to add customized tokens through this API as it can be done in huggingface and to be able to view the tokenized input before feeding into the model.

**Describe alternatives you've considered**
The alternative is to use huggingface 😅 

**Additional context**
If there is a workaround for this that already exists in simpletransformers that would be awesome! Thanks.

**Comment by ThilinaRajapakse** [comment]
This is something I need as well, so it should be added soon. 😅 

In the meantime, you should be able to use the huggingface function itself to add custom tokens. You can access the Transformer model itself through `model.model` where the first model is the ST model and _its_ model is either a Hugging Face model or a subclassed HF model.
