### ISSUE TITLE
Training with lazy loading throws AttributeError

### ISSUE THREAD

**Issue by aakashdusane** [ThilinaRajapakse/simpletransformers#597]
I'm getting the following error:
 "AttributeError: 'LazyClassificationDataset' object has no attribute 'text_a_column'", even when i'm specifying lazy_labels_column, lazy_text_column=0

Here's what I'm doing:

```
model = ClassificationModel("roberta", "roberta-base", use_cuda=True)

model_args = dict(output_dir=path_to_op, lazy_loading=True, lazy_labels_column=1, lazy_text_column=0)

# train
model.train_model("train.txt", args=model_args)

# Evaluate
result, model_outputs, wrong_predictions = model.eval_model("eval.txt")

```

I'm using Google Colab to run the code. Here's a snapshot of the full error message.

![image](https://user-images.githubusercontent.com/40353160/88539154-59affc00-d02e-11ea-9807-d5015fa1a37a.png)

**Comment by ThilinaRajapakse** [comment]
I pushed a fix to this now. Should be good in `0.45.4`.
