### ISSUE TITLE
Add support for Bio-BERT

### ISSUE THREAD

**Issue by tramya28** [ThilinaRajapakse/simpletransformers#599]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tramya28** [comment]
I started using this for my research and Simple Transformers is amazing. It's like everything in a box. Is there a way you can add Bio-BERT to the list of pre-trained models so i can directly use it with Simple Transformers??

**Comment by ThilinaRajapakse** [comment]
I am delighted to hear that!

All pre-trained models in Simple Transformers are made available through the Hugging Face model hub. If it is available there, then they can be used directly. They have some Bio-BERT models in the hub [here](https://huggingface.co/models?search=biobert).

**Comment by tramya28** [comment]
I do not find Bio-Bert on the supported models list here - https://simpletransformers.ai/docs/classification-specifics/ 
Will this work?
model =ClassificationModel('biobert_v1.1_pubmed', 'biobert_v1.1_pubmed-base-cased')

**Comment by ThilinaRajapakse** [comment]
Bio-BERT is a BERT model and therefore, it should work. That list contains the supported model _types_.

Since BioBERT is a BERT model, this should work.

```python
model = ClassificationModel("bert", "monologg/biobert_v1.1_pubmed")
```

**Comment by tramya28** [comment]
This works! Thank you so much!
