### ISSUE TITLE
Allow parameters to be passed to tokenizers

### ISSUE THREAD

**Issue by khituras** [ThilinaRajapakse/simpletransformers#600]
**Is your feature request related to a problem? Please describe.**
The transformer tokenizers have some parameters associated with truncation (longest first, only first, ...). It is sometimes useful or even necessary to manipulate this setting (when one has long inputs).

**Describe the solution you'd like**
Let the model classes accept parameters to be set to the tokenizers.

**Comment by ThilinaRajapakse** [comment]
I agree this should be added.
