### ISSUE TITLE
Transfer Learning

### ISSUE THREAD

**Issue by thiagosantos1** [ThilinaRajapakse/simpletransformers#602]
A transfer learning feature would be welcome.

It would be nice to have the option to train a classification model over a larger dataset with N number of labels, and then fine tune over a smaller dataset with M number of labels.

**Comment by ThilinaRajapakse** [comment]
I'll have to look into it. The problem is that the mismatched shapes in the classification layer will lead to an error when trying to load a model trained for N number of labels as a model for M number of labels.
