### ISSUE TITLE
ImportError: cannot import name 'get_linear_schedule_with_warmup'

### ISSUE THREAD

**Issue by tzhxs** [ThilinaRajapakse/simpletransformers#61]
**Describe the bug**
A clear and concise description of what the bug is. Please specify the class causing the issue.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS

**Additional context**

**Comment by ThilinaRajapakse** [comment]
Update the transformers library to 2.2.

**Comment by tzhxs** [comment]
thanks

**Comment by tzhxs** [comment]
how can i change the epoch used in model.train_model(train), please

**Comment by ThilinaRajapakse** [comment]
That, and many other hyperparameters, can be passed as a dictionary to either the model or to the train_model method. Please check the readme or the examples given.

**Comment by tzhxs** [comment]
thanks so much

**Comment by tzhxs** [comment]
where can i download the  bert/xlnet/roberta model pre-trained using pytorch, please

**Comment by ThilinaRajapakse** [comment]
They will be automatically downloaded when you use them.

**Comment by tzhxs** [comment]
thanks, it seems like using more gpu resource compared to use Zihang Dai's  code in my project, is this normal

**Comment by ThilinaRajapakse** [comment]
I'm not familiar with that code so I can't really tell. However, the model is never removed from memory while training and evaluation is running with this setup.

**Comment by tzhxs** [comment]
thanks, how can I release it in my project? could you give some suggestion

**Comment by ThilinaRajapakse** [comment]
Please open a new issue for a new topic. I've moved this here. #65
