### ISSUE TITLE
Unreachable conditional block when masking for ELECTRA

### ISSUE THREAD

**Issue by yusufrahadika** [ThilinaRajapakse/simpletransformers#611]
https://github.com/ThilinaRajapakse/simpletransformers/blob/708347d66471fbe9adbbe394b406d7ddb4e2f25e/simpletransformers/language_modeling/language_modeling_utils.py#L160
I'm just not sure what's the meaning of that conditional block. Is that block is meant to be unreachable? (operator "and" with False always returning False, right?) Or that block is not ready? Please give me explanation or clarify.
Thank you very much.

**Comment by ThilinaRajapakse** [comment]
That seems to be a bug. I think it probably sneaked in by accident when I was adding the special case logic for Electra.

Good catch!

_Fixed in 0.46.3_

**Comment by yusufrahadika** [comment]
Thanks for your quick response. I am closing this issue.
