### ISSUE TITLE
I want to separate input and outputs while finetuning gpt2 model

### ISSUE THREAD

**Issue by Krish-Nerkar** [ThilinaRajapakse/simpletransformers#613]
For example i have a training data full of essays but each essay has an topic, so i wanna correlate the title to the essay so the model learns the relation between them and when a new prompt is given it can generate the result accordingly. What should i do to acheive this !?

**Comment by ThilinaRajapakse** [comment]
This is just an idea, but you could probably concatenate the titles and essays for the training. Then, for inference, you can use the title as the prompt with `LanguageGenerationModel`.

**Comment by Krish-Nerkar** [comment]
@ThilinaRajapakse 

So should I like add tokens to separate the titles and the essays in the data set or should I just keep spaces. In which scenario can the model more effectively identify the relationship between title and content

**Comment by ThilinaRajapakse** [comment]
I think spaces will be fine. But, if it doesn't work out, you can try adding a special token.

**Comment by Krish-Nerkar** [comment]
@ThilinaRajapakse 

Okay sure will try it out, but one final thing, where exactly while fine-tuning should I code the model to identify the special token cause as far as I know, it dosent support it, does it?
