### ISSUE TITLE
New version not install-able on Colab

### ISSUE THREAD

**Issue by PrithaBhattacharya09** [ThilinaRajapakse/simpletransformers#614]
I tried installing the latest 0.46.2 version on Colab by typing the command:
```
!pip install simpletransformers==0.46.2
```
but this results in the following error message:
>ERROR: Could not find a version that satisfies the requirement simpletransformers==0.46.2 (from versions: 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.2.10, 0.2.11, 0.2.12, 0.2.13, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.13, 0.7.0, 0.7.5, 0.7.6, 0.7.7, 0.7.8, 0.7.9, 0.7.10, 0.7.11, 0.7.12, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.10.1, 0.10.2, 0.10.4, 0.10.5, 0.10.6, 0.10.7, 0.10.8, 0.11.0, 0.11.1, 0.11.2, 0.12.0, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.14.0, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.15.4, 0.15.5, 0.15.6, 0.15.7, 0.16.0, 0.16.1, 0.16.2, 0.16.4, 0.16.5, 0.16.6, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.18.2, 0.18.3, 0.18.4, 0.18.5, 0.18.6, 0.18.7, 0.18.8, 0.18.9, 0.18.10, 0.18.11, 0.18.12, 0.19.0, 0.19.1, 0.19.2, 0.19.3, 0.19.4, 0.19.5, 0.19.6, 0.19.7, 0.19.8, 0.19.9, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.21.2, 0.21.3, 0.21.4, 0.21.5, 0.22.0, 0.22.1, 0.23.2, 0.23.3, 0.24.0, 0.24.1, 0.24.2, 0.24.3, 0.24.4, 0.24.5, 0.24.6, 0.24.7, 0.24.8, 0.24.9, 0.25.0, 0.26.0, 0.27.0, 0.27.1, 0.27.2, 0.27.3, 0.27.4, 0.28.0, 0.28.1, 0.28.2, 0.28.3, 0.28.4, 0.28.5, 0.28.6, 0.28.7, 0.28.8, 0.28.9, 0.28.10, 0.28.12, 0.29.0, 0.29.1, 0.30.0, 0.31.0, 0.32.0, 0.32.1, 0.32.2, 0.32.3, 0.33.0, 0.33.1, 0.33.2, 0.34.0, 0.34.1, 0.34.2, 0.34.4, 0.40.0, 0.40.1, 0.40.2, 0.41.0, 0.41.1, 0.41.2, 0.42.0, 0.43.0, 0.43.1, 0.43.2, 0.43.3, 0.43.4, 0.43.5, 0.43.6, 0.44.0, 0.45.0, 0.45.1, 0.45.2, 0.45.3, 0.45.4, 0.45.5)
>ERROR: No matching distribution found for simpletransformers==0.46.2

So the latest version available for installation on Colab is 0.45.5
The 0.46.2 version is, however, easily installed on my local computer. 
I need to work on Colab though, is there a way I can access the newest version there?

**Comment by ThilinaRajapakse** [comment]
That's probably because colab has an older version of Pytorch installed by default. Uninstalling it and installing PyTorch 1.6 should fix it.

**Comment by Krish-Nerkar** [comment]
I used
`!pip install simpletransformers`
and it worked fine for me and even finetuned the models w/o any error

**Comment by PrithaBhattacharya09** [comment]
Well, I tried to install the now latest version, 0.46.3 using the .whl file
It gave me the following error:
>ERROR: Package 'simpletransformers' requires a different Python: 3.6.9 not in '>=3.7'
So, turns out that Colab uses python 3.6.9 and the library requires a 3.7 or higher version. I'm not sure why this should be an issue given that python is backward compatible. Do you think this is fixable?

- I did google how to update the python in Colab but I guess the only way to do that is to run on a local runtime, which isn't very useful in my case.

**Comment by Krish-Nerkar** [comment]
Just use the 0.45.5 (atleast for now), it is compatible with python 3.6.9. Is there any specific feature you need in the latest version or some kind of error in the older version? Cause its working fine with me

**Comment by PrithaBhattacharya09** [comment]
> Just use the 0.45.5 (atleast for now), it is compatible with python 3.6.9. Is there any specific feature you need in the latest version or some kind of error in the older version? Cause its working fine with me

Yes, I need to use the 0.46.1 version at least to get my work done
