### ISSUE TITLE
Want to decrease the size of my finetuned GPT-2 model

### ISSUE THREAD

**Issue by Krish-Nerkar** [ThilinaRajapakse/simpletransformers#615]
I have finetuned a gpt2 model using LanguageModelingModel class and then generated results with that finetuned model using LanguageGenerationModel class, when i create a object of the LanguageGenerationModel class with the following line -

`model = LanguageGenerationModel("gpt2", "outputs/", args={"max_length": 200})`

and then save it and compress it using pickel 

`with bz2.BZ2File( "model_final.pbz2", "w") as f: 
   cPickle.dump(model, f)`

and when i see the file size it is over 450mb and since i want to deploy it on heroku, where the max limit is 500mb, i am failing as the depedencies along with the model take upto 580 mb

this is what i get while pushing it to the master branch and deploying it-

`remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote:
remote: -----> Compressing...
remote:  !     Compiled slug size: 581.6M is too large (max is 500M).
remote:  !     See: http://devcenter.heroku.com/articles/slug-size
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to lyrics-generatoe.
remote:
To https://git.heroku.com/lyrics-generatoe.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/lyrics-generatoe.git'
`

How should i solve this!?!?

**Comment by manueltonneau** [comment]
[Quantization](https://pytorch.org/blog/introduction-to-quantization-on-pytorch/) could be an idea. In my experience, dynamic quantization could reduce the model size by up to 4x with speed gains of up to 2x. 

Another approach could be [to train a distilled version of your model](https://github.com/huggingface/transformers/tree/master/examples/distillation), using your current model as teacher, for reduced model size and inference speedup. 

You could also look into [ONNX](https://medium.com/microsoftazure/accelerate-your-nlp-pipelines-using-hugging-face-transformers-and-onnx-runtime-2443578f4333) though I'm not sure to what extent the model size is reduced.

**Comment by Krish-Nerkar** [comment]
Thanks !
