### ISSUE TITLE
Use classes other than RepresentationModel for sentence vector generation

### ISSUE THREAD

**Issue by crispin-nosidam** [ThilinaRajapakse/simpletransformers#618]
Thanks for the library - it's just simplify the task greatly!

Just wonder why we need a separate RepresentationModel.
I am doing some training with ClassificationModel and then there are some need to create a vector for sentences.
When I look at your code, the encode_sentence() generally work just fine with other models like ClassificationModel.
To avoid creating a separate model, I ended up just calling model.model.bert or model.model.roberta, etc. directly.
It would be nice if this can be ported to other classes whereever it makes sense - thanks!

**Comment by pablonm3** [comment]
excuse me but I don't understand your question, can u please clarify what's the issue?

**Comment by pablonm3** [comment]
If I understand correctly You are suggesting that `encode_sentence` method should be included in other models like classificationModel, can u provide more detail of your usecase, why would you need to generate vectors from a classificationModel?
