### ISSUE TITLE
Setting evaluation metric for NER 

### ISSUE THREAD

**Issue by andrewlaikh** [ThilinaRajapakse/simpletransformers#621]
Hi, i have the following issue when trying to set a custom evaluation metric for NER: 

```

train_args={
    'fp16': False,
    'max_seq_length': 512, 
    'num_train_epochs': 15,
    'reprocess_input_data': True,
    'overwrite_output_dir': True,
    'evaluate_during_training': True,
    'save_model_every_epoch' : True
    # 'evaluate_during_training_verbose': True,
#     'logging_steps': 5,
#     'stride': 0.8,
}
labels=["Legislation", "Provision", "Others"]
# Create a NERModel with the requisite tags 
model = NERModel('roberta', 'roberta-base', args=train_args, use_cuda = True, labels = labels)

# Train the model
model.train_model(train_df, eval_df = val_df, acc=sklearn.metrics.accuracy_score ,output_dir = 'roberta-base-15')

```

I get the following error. 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-27ca190fb5be> in <module>()
     22 
     23 # Train the model
---> 24 model.train_model(train_df, eval_df = val_df, acc=sklearn.metrics.accuracy_score ,output_dir = 'roberta-base-15')

6 frames
/usr/local/lib/python3.6/dist-packages/simpletransformers/ner/ner_model.py in train_model(self, train_data, output_dir, show_running_loss, args, eval_data, verbose, **kwargs)
    245 
    246         global_step, tr_loss = self.train(
--> 247             train_dataset, output_dir, show_running_loss=show_running_loss, eval_data=eval_data, **kwargs
    248         )
    249 

/usr/local/lib/python3.6/dist-packages/simpletransformers/ner/ner_model.py in train(self, train_dataset, output_dir, show_running_loss, eval_data, verbose, **kwargs)
    558             if args.evaluate_during_training:
    559                 results, _, _ = self.eval_model(
--> 560                     eval_data, verbose=verbose and args.evaluate_during_training_verbose, wandb_log=False, **kwargs
    561                 )
    562 

/usr/local/lib/python3.6/dist-packages/simpletransformers/ner/ner_model.py in eval_model(self, eval_data, output_dir, verbose, silent, wandb_log, **kwargs)
    648 
    649         result, model_outputs, preds_list = self.evaluate(
--> 650             eval_dataset, output_dir, verbose=verbose, silent=silent, wandb_log=wandb_log, **kwargs
    651         )
    652         self.results.update(result)

/usr/local/lib/python3.6/dist-packages/simpletransformers/ner/ner_model.py in evaluate(self, eval_dataset, output_dir, verbose, silent, wandb_log, **kwargs)
    739         extra_metrics = {}
    740         for metric, func in kwargs.items():
--> 741             extra_metrics[metric] = func(out_label_list, preds_list)
    742 
    743         result = {

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py in accuracy_score(y_true, y_pred, normalize, sample_weight)
    183 
    184     # Compute accuracy for each possible representation
--> 185     y_type, y_true, y_pred = _check_targets(y_true, y_pred)
    186     check_consistent_length(y_true, y_pred, sample_weight)
    187     if y_type.startswith('multilabel'):

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py in _check_targets(y_true, y_pred)
     79     """
     80     check_consistent_length(y_true, y_pred)
---> 81     type_true = type_of_target(y_true)
     82     type_pred = type_of_target(y_pred)
     83 

/usr/local/lib/python3.6/dist-packages/sklearn/utils/multiclass.py in type_of_target(y)
    258         if (not hasattr(y[0], '__array__') and isinstance(y[0], Sequence)
    259                 and not isinstance(y[0], str)):
--> 260             raise ValueError('You appear to be using a legacy multi-label data'
    261                              ' representation. Sequence of sequences are no'
    262                              ' longer supported; use a binary array or sparse'

ValueError: You appear to be using a legacy multi-label data representation. Sequence of sequences are no longer supported; use a binary array or sparse matrix instead - the MultiLabelBinarizer transformer can convert to this format.

Just wondering if it is at all possible to set an evaluation metric for NER and if so,what am i doing wrong? Thanks. 
`

**Comment by soleares** [comment]
`sklearn.metrics.accuracy_score` doesn't support NER formatted data (sequence of sequences). Try seqeval https://github.com/chakki-works/seqeval. seqeval.metrics.accuracy_score or seqeval.metrics.f1_score should work.
