### ISSUE TITLE
Uploading Fine-Tuned Model to Huggingface Transformers Library

### ISSUE THREAD

**Issue by abedkhooli** [ThilinaRajapakse/simpletransformers#622]
Say I fine-tuned a community GPT2 model on a specialized dataset and would like to share the model back on Huggigface. The fine-tuned model is in outputs/fine-tuned/ which has 9 files. 
Do I just upload the fine-tuned directory? A brief how to would be a great addition to a great library.
Edit: I uploaded the directory (probably with a few extra files) and can call the model from code. However, HF interface complains about the config file.

**Comment by ThilinaRajapakse** [comment]
What does it say? I've never tried to upload a model to HF, but the model files should be compatible (as long as extra files don't cause issues)

**Comment by abedkhooli** [comment]
> 
> 
> What does it say? I've never tried to upload a model to HF, but the model files should be compatible (as long as extra files don't cause issues)
it says "Can't load config for [model], make sure the directory has config.json file". 
I filed an issue at HF (https://github.com/huggingface/transformers/issues/6226) - it may be their API. 
For Simple Transformers, the only thing I can think of is a formatting issue of the config.json file in trained model directory (I tried to re-write it but did not make a difference). 
Here's less command reading the ST generated file (notice the strange char): 
![image](https://user-images.githubusercontent.com/11407254/89308346-d1a7a300-d67a-11ea-9beb-643fe5350f2e.png)

**Comment by ThilinaRajapakse** [comment]
Is the JSON file corrupted? That is not intentional as far as I can tell.

**Comment by abedkhooli** [comment]
> 
> 
> Is the JSON file corrupted? That is not intentional as far as I can tell.
Not sure if that hidden char causes a problem - I re-wrote the file before uploading to HF. Apparently, HF API also has an issue - they said they are working on it.

**Comment by ThilinaRajapakse** [comment]
All good then?

**Comment by abedkhooli** [comment]
Closing, but did not try with ST generated config.json (uploaded file was re-written:
```
with open('../input/st-ar-poetry2/outputs/fine-tuned/config.json') as json_file:
    data = json.load(json_file)
with open('config.json', 'w', encoding='utf-8') as f:
    json.dump(data, f)
```
