### ISSUE TITLE
ValueError: arrays must all be same length

### ISSUE THREAD

**Issue by sarapapi** [ThilinaRajapakse/simpletransformers#627]
**Description**
When running `T5Model.train_model` the error: `ValueError: arrays must all be same length` arises.

**Details**
I'm trying to use an additional metric, in particular sacreBLEU, to select the checkpoint during T5 model training and, afterward, for early stopping.
I've tried sacreBLEU library as well as nlp library from Hugging Face and it doesn't work.
Then I've tried to use the example case with mcc in your docs, I don't know if I've done it correctly (there are any example codes of using additional metrics to select the checkpoints?).
This is my simple code:
```
import pandas as pd 
from simpletransformers.t5 import T5Model
import sklearn

############################################################## DATA loading
train_df = pd.read_csv("/mypath", sep="\t", usecols=["prefix","input_text","target_text"]).astype(str)
eval_df = pd.read_csv("/mypath", sep="\t", usecols=["prefix","input_text","target_text"]).astype(str)

model_args = {
    "reprocess_input_data": True,
    "overwrite_output_dir": True,
    "max_seq_length": 512, 
    'sliding_window': False,
    "max_length": 107, 
    "train_batch_size": 2,
    "num_train_epochs": 1,
    "save_eval_checkpoints": False,
    "save_steps": -1, # -1 don't save
    "save_model_every_epoch": False,
    "use_multiprocessing": False,
    "evaluate_during_training": True,
    "evaluate_during_training_steps": 100, 
    "evaluate_during_training_verbose": True,
    "use_early_stopping" : True,
    #"early_stopping_delta" : 0.01,
    "early_stopping_metric" : "mcc",
    "early_stopping_metric_minimize" : False,
    "early_stopping_patience" : 3,
    "fp16": False,
}

model = T5Model("t5-small", args=model_args)

model.train_model(train_df, eval_data=eval_df, mcc=sklearn.metrics.matthews_corrcoef)
```

**Full Error**

> Traceback (most recent call last):
>   File "/kaggle/src/script.py", line 54, in <module>
>     model.train_model(train_df, eval_data=eval_df, mcc=sklearn.metrics.matthews_corrcoef) #, **kwargs
>   File "/opt/conda/lib/python3.7/site-packages/simpletransformers/t5/t5_model.py", line 165, in train_model
>     **kwargs,
>   File "/opt/conda/lib/python3.7/site-packages/simpletransformers/t5/t5_model.py", line 425, in train
>     report = pd.DataFrame(training_progress_scores)
>   File "/opt/conda/lib/python3.7/site-packages/pandas/core/frame.py", line 435, in __init__
>     mgr = init_dict(data, index, columns, dtype=dtype)
>   File "/opt/conda/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 254, in init_dict
>     return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
>   File "/opt/conda/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 64, in arrays_to_mgr
>     index = extract_index(arrays)
>   File "/opt/conda/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 365, in extract_index
>     raise ValueError("arrays must all be same length")
> ValueError: arrays must all be same length

**Comment by ThilinaRajapakse** [comment]
You can use additional metrics, but there are some caveats.

You need to set `"evaluate_generated_text": True`. Otherwise, the text is not generated and the metric is not calculated (leading to this error). However, you still won't be able to use MCC as the generated text is going to be a string. You'll need to use a metric that works with strings.
For example, `compute_exact` and `compute_f1` from `transformers.data.metrics.squad_metrics`.

**Comment by sarapapi** [comment]
Thanks for your reply!
My original aim was to use sacreBLEU to select the best checkpoint, to do this `evaluate_genereted_text: True` is sufficient? Or it computes the metric obtained by the final model only?

Moreover, I've tried to use the sacreBLEU metric of the nlp library by hugging face:
```
import nlp
sacrebleu = nlp.load_metric("sacrebleu")

def sacreBLEU(ref, pred):
    return sacrebleu.compute(pred,ref)

model_args = {
    "reprocess_input_data": True,
    "overwrite_output_dir": True,
    "max_seq_length": 512, 
    'sliding_window': False,
    "max_length": 107, #107+1 
    "train_batch_size": 2,
    "num_train_epochs": 1,
    "save_eval_checkpoints": False,
    "save_steps": -1, # -1 don't save
    "save_model_every_epoch": False,
    "use_multiprocessing": False, 
    "evaluate_during_training": True,
    "evaluate_during_training_steps": 100, 
    "evaluate_during_training_verbose": True,
    "evaluate_generated_text": True,
    "use_early_stopping": True,
    #"early_stopping_delta" : 0.01,
    "early_stopping_metric" : sacreBLEU, 
    "early_stopping_metric_minimize" : False,
    "early_stopping_patience" : 3,
    "fp16": False, # issues for T5
}

model = T5Model("t5-small", args=model_args) 

model.train_model(train_df, eval_data=eval_df, BLEU=sacreBLEU) 
```
But the error remains.
