### ISSUE TITLE
Decrease in F-Score when evaluate_during_training_steps is used and it's visualization in wandb

### ISSUE THREAD

**Issue by DebanjanaKar** [ThilinaRajapakse/simpletransformers#628]
I am training an NER model, and I face a weird error. If I set evaluate_during_training = True, the performance of the model decreases than when trained without this option. Further elaborating with examples: 1. If I don't set this arg, F-Score = 77, 2. If set to True, F-Score = 76, and 3. If I further add evaluate_during_training_steps = 7, the F-Score= 49. Any idea why this may be happening?

Also wandb scores and seqeval scores produced by the model are different slightly.

When visualizing it on wandb, I am having difficulty associating the steps given there with the steps I am training for. For each epoch, the number of steps = 88, so I believe in the graph it should be having 88*7 steps, given 7 is the number of epochs I have trained my model for. But the graph shows a total of 106 steps in the graph. Any shedding of light on this matter will also be extremely helpful.

**Comment by ThilinaRajapakse** [comment]
> I am training an NER model, and I face a weird error. If I set evaluate_during_training = True, the performance of the model decreases than when trained without this option. Further elaborating with examples: 1. If I don't set this arg, F-Score = 77, 2. If set to True, F-Score = 76, and 3. If I further add evaluate_during_training_steps = 7, the F-Score= 49. Any idea why this may be happening?

Is this the final score for the trained model?

The total steps on wandb are the number of times values were logged to wandb. The `global_step` corresponds to the actual training.

**Comment by DebanjanaKar** [comment]
Yes the final seqeval F-Score obtained from ST.

How can I change the x-axis from steps to epochs?

**Comment by ThilinaRajapakse** [comment]
Probably late, sorry. But, you can change it by clicking the X icon.

![image](https://user-images.githubusercontent.com/17320131/90043991-98121000-dcea-11ea-916f-afb2e195906e.png)
