### ISSUE TITLE
Seq2Seq Minimal Start for BART doesn't work

### ISSUE THREAD

**Issue by KerenzaDoxolodeo** [ThilinaRajapakse/simpletransformers#629]
**Describe the bug**
The code manages to train the model and predicts, but fail in the part of demonstrating that models can be saved and reloaded for future usage.

It produces this error.

```
OSError: file outputs/config.json not found

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/transformers/configuration_utils.py in get_config_dict(cls, pretrained_model_name_or_path, **kwargs)
    249                 f"- or '{pretrained_model_name_or_path}' is the correct path to a directory containing a {CONFIG_NAME} file\n\n"
    250             )
--> 251             raise EnvironmentError(msg)
    252 
    253         except json.JSONDecodeError:

OSError: Can't load config for 'outputs'. Make sure that:

- 'outputs' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'outputs' is the correct path to a directory containing a config.json file
```

**To Reproduce**
Run the code from https://simpletransformers.ai/docs/seq2seq-minimal-start/ in Google Colabs

**Expected behavior**
The program terminates successfully.

**Desktop (please complete the following information):**
 - OS 
Ubuntu 18.04.3

**Comment by katreparitosh** [comment]
Hello @KerenzaDoxolodeo,

Did you manage to find a solution to this issue? I am facing the same issue.

It would be great if you might have solved it.

Regards,
Paritosh

**Comment by ThilinaRajapakse** [comment]
This was because of the `no_save` arg being set to True. I've updated the docs to fix it.

**Comment by DebanjanaKar** [comment]
Still got the error for general seq2seq models, will try with the above-mentioned fix.

**Comment by DebanjanaKar** [comment]
Fix didn't work unfortunately. :(

**Comment by katreparitosh** [comment]
Hi @DebanjanaKar,

I read that HuggingFace recently moved all models behind SSL. Hence, people are facing this issue as your system might also be behind a firewall. 

Try installing transformers==4.6.1 Read somewhere that this resolved the problem in some cases.
