### ISSUE TITLE
Start evaluation after first epoch

### ISSUE THREAD

**Issue by manueltonneau** [ThilinaRajapakse/simpletransformers#630]
Hi again :) 

Thanks again for the help on [this issue](https://github.com/ThilinaRajapakse/simpletransformers/issues/620). 

The problem I am now facing when evaluating several times (10 in my case) per epoch is that the best evaluation loss is always found before the end of the first epoch. That's problematic in my case because it means that my `best_model` hasn't seen all of the training data.

Is there a way to start evaluating every `evaluate_during_training_steps` steps starting from the end of the first epoch, as a way to ensure that my `best_model` has at least seen all of the training data?

**Comment by ThilinaRajapakse** [comment]
There isn't a direct solution to this issue right now, unfortunately. The workaround would be to manually choose a checkpoint saved after the first epoch has already completed.

**Comment by manueltonneau** [comment]
Thanks for your reply :) 

For anyone interested, I wrote [code](https://github.com/spfraib/twitter/blob/f8130fd52ccb33c062bd91a1bbedc2a15041ece3/code/2-twitter_labor/2-model_training/bert_models/train_bert.py#L224) to find the best_model in terms of evaluation loss at or after the first epoch. 

Closing this now as my problem is solved!
