### ISSUE TITLE
Error in multi modal classifier while training 

### ISSUE THREAD

**Issue by AshishGogo** [ThilinaRajapakse/simpletransformers#631]
Getting 
**ValueError: only one element tensors can be converted to Python scalars error on training multi modal classifier.** 
It was working fine yesterday

**To Reproduce**
Can send notebook link in pvt mail

**Expected behavior**
model should have trained without fail

ERROR:

      2 from sklearn.metrics import roc_auc_score
----> 3 model.train_model(image_path='/content/train/data/',train_data=train_df,args={'auc':roc_auc_score})

1 frames
/usr/local/lib/python3.6/dist-packages/simpletransformers/classification/multi_modal_classification_model.py in train(self, train_dataset, output_dir, files_list, image_path, text_label, labels_label, images_label, image_type_extension, data_type_extension, show_running_loss, eval_data, verbose, **kwargs)
    485                     loss = loss.mean()  # mean() to average on multi-gpu parallel training
    486 
--> 487                 current_loss = loss.item()
    488 
    489                 if show_running_loss:

ValueError: only one element tensors can be converted to Python scalars

**Comment by mohamadhabash** [comment]
@AshishGogo Have you found a solution for this?
