### ISSUE TITLE
More data in wandb config

### ISSUE THREAD

**Issue by djstrong** [ThilinaRajapakse/simpletransformers#632]
Now, there is no way to include more information in config for wandb, like path to data or model_name.
Earlier, model args was a dict and it was possible assign anything, now dataclass prevents it.

**Comment by ThilinaRajapakse** [comment]
We could solve this by adding another attribute (dict) to model_args, right? For example, we could have a `model_notes` dict where the user can add pretty much anything.

**Comment by djstrong** [comment]
Yes, I think so. I am usually adding arguments from ArgumentParser.

**Comment by ThilinaRajapakse** [comment]
Great. I'll add this then.
