### ISSUE TITLE
Is it possible to return the attention heads learned when using longformer classificaitons.

### ISSUE THREAD

**Issue by codeninja** [ThilinaRajapakse/simpletransformers#633]
I am attempting to use the new longformer model and I am missing how I can configure the system to return the attentions when making a prediction.

Please point me in the right direction. Thanks.

**Comment by DebanjanaKar** [comment]
I want to know the same thing with regard to NER Models.

**Comment by rhamnett** [comment]
This would be extremely useful @ThilinaRajapakse

**Comment by DebanjanaKar** [comment]
I did a workaround and I am posting it here hoping it might help others as well : 

In the predict function, find the line where the output is getting returned. Usually it is stored in a variable `outputs` . After that line add : 

`if self.config.output_attentions:
     attn = outputs[-1]`

After that skip to the line containing the return statement and right before the return statement add : 
`if self.config.output_attentions:
     return preds, model_outputs, attn`

This would return the attention weights of your model.

**Comment by DebanjanaKar** [comment]
@ThilinaRajapakse : if you want I could raise a PR for this so that all the modules can return the attention scores as well. Let me know your thoughts on it. :)

**Comment by codeninja** [comment]
> @ThilinaRajapakse : if you want I could raise a PR for this so that all the modules can return the attention weights as well. Let me know your thoughts on it. :)

This would be extremely helpful! BERT et. al. would benefit from this.

**Comment by codeninja** [comment]
UPDATE: It appears as though `output_hidden_states` also returns attentions.
![image](https://user-images.githubusercontent.com/14914/89663739-9f28c080-d89b-11ea-960f-691856ab0e72.png)

From `o[3]` we have access to all attention heads!

@DebanjanaKar I don't feel like a PR is necessary at this point.

This issue may be closed, however I think the documentation should be updated to reflect this.

**Comment by ThilinaRajapakse** [comment]
`output_hidden_states` is currently only implemented for Classification tasks. I believe @DebanjanaKar was suggesting a PR for the other tasks as well. I think it may be useful to have it for the other tasks too.
