### ISSUE TITLE
Convert The model to tensorflow.js

### ISSUE THREAD

**Issue by Krish-Nerkar** [ThilinaRajapakse/simpletransformers#635]
I trained a model using the LanguageModellingClass. How should i convert the model to tensorflow.js. or is there any function like 
`model.save()` to save the model to the device?

**Comment by ThilinaRajapakse** [comment]
The model gets saved to `ouput_dir` as a Pytorch model. If you need it in another format, you'll have to convert it from there.

**Comment by Krish-Nerkar** [comment]
@ThilinaRajapakse 

Are you talking abt the pytorch_model.bin file!?

**Comment by ThilinaRajapakse** [comment]
Yeah.

**Comment by Krish-Nerkar** [comment]
Okayy thanks, will try it out
