### ISSUE TITLE
Multi input for multi label classification task

### ISSUE THREAD

**Issue by siyanew** [ThilinaRajapakse/simpletransformers#639]
Hi,

I have two text columns and some labels, one of text columns contains some sentences and another one contains just some arbitrary words (it doesn't have any specific order). 

How can I provide these two columns as separated embedding input to multi label classification task?

**Comment by ThilinaRajapakse** [comment]
You could probably use the sentence-pair [format](https://simpletransformers.ai/docs/sentence-pair-classification/). Will that work?

**Comment by siyanew** [comment]
I read the doc, I think sentence-pair task get some sentences and after that classify whether they are related or not. but in my problem i have two `text` ( `text_a` and `text_b` ) and some labels (`labels_a` and `labels_b` and `labels_c`) I just want a way to input two different text for multi label classification task. After My description is it still ok to use sentence pair? 

for clarifying this is one of my data row example:

| text_a  | text_b  |  label_a |  label_b | label_c  |
|---|---|---|---|---|
|  I am a student and I study at MIT. | city honor document  | 0  |  1 |  1 |

**Comment by siyanew** [comment]
I tested the text_a and text_b way and the result didn't have significant change. one of my input is sentence in english language but another one doesn't have sequential order, it is just some words like file and folders name. do you have any idea? does split them into text_a and text_b will change the result? 

In traditional classifier like TFIDF + LinearRegression I split my dataset into two section and I got better result, how can i achieve this in simple transformer? 

 Thank you in advance.

**Comment by ThilinaRajapakse** [comment]
The idea behind using the sentence-pair approach is to give a better idea to the model about the fact that the two sequences are distinct (it adds a separator in between the two sequences).

Another possibility would be to try using the T5 model. With an input like below, for example.

`"sentence: I am a student and I study at MIT. keywords: city, honor, document"`.

Then the target sequence would be:

`0,1,1`

How many labels do you have?

**Comment by siyanew** [comment]
Thank you for your clear response. I have 220 labels.

**Comment by ThilinaRajapakse** [comment]
Transformer models seem to struggle at tasks with a high number of labels. It's possible that this issue is due to the same reason.

**Comment by siyanew** [comment]
this is so interesting! can you please refer me to some sources/evidence on this?

**Comment by malihizadi** [comment]
Hi,
I also want to use two types of text for multi-label classification. I was thinking maybe we can modify the classification layer, to add a vector containing the embeddings of text_2. that is, at first feed the transformer with only text_1 and then in the multi-label classification layer, concat a tf-idf vector of my text_2 with the output of network (before the last layer which does the prediction). Do you think it is possible? if yes, can you point me where should I change the code?

**Comment by ThilinaRajapakse** [comment]
@siyanew Take a look at Amazon's [paper](https://www.amazon.science/publications/x-bert-extreme-multi-label-text-classification-using-bidirectional-encoder-representations-from-transformers).

@malihizadi It should theoretically be possible. You'll need to edit the relevant model implementation (e.g. [here](https://github.com/ThilinaRajapakse/simpletransformers/blob/aa8e6a6337938aa9b8e5e8c8427b1e5b90aed8ef/simpletransformers/classification/transformer_models/bert_model.py#L7)). You'll also need to edit the `load_and_cache_examples()` process to handle the extra inputs.
