### ISSUE TITLE
Passing in epoch number to wandb. 

### ISSUE THREAD

**Issue by andrewlaikh** [ThilinaRajapakse/simpletransformers#640]
Hi, not a bug but just a quick question--Is there a way to pass in the epoch number into wandb so i can review which epoch the evaluation results are for? Many thanks.

**Comment by ThilinaRajapakse** [comment]
I don't think that information is passed to wandb atm. You can still calculate it from the if you know the size of the training data though.

**Comment by andrewlaikh** [comment]
Noted, thanks!
