### ISSUE TITLE
TypeError: GPT2LMHeadModel object argument after ** must be a mapping, not Tensor

### ISSUE THREAD

**Issue by reobroqn** [ThilinaRajapakse/simpletransformers#646]
**Describe the bug**
TypeError: GPT2LMHeadModel object argument after ** must be a mapping, not Tensor
But when i set use_cuda=False it run normally on colab. Cuda's curse perhaps :v 

**To Reproduce**
I just run exactly as in fine-tune gpt2 document.

**Expected behavior**
Normal running

**Screenshots**
![image](https://user-images.githubusercontent.com/52645376/90003374-2f14a300-dcbe-11ea-8745-b441cafb5a9b.png)

**Desktop (please complete the following information):**
 - Colab, ubuntu server

**Comment by ThilinaRajapakse** [comment]
I think it's a bug, probably introduced when switching to amp from Apex. Can you try running it without `fp16`?

**Comment by reobroqn** [comment]
Okay, I tried to set fp16 = False and it works. Thanks!

**Comment by WeberJulian** [comment]
> I think it's a bug, probably introduced when switching to amp from Apex. Can you try running it without `fp16`?

Hi, I'm having the same issue with ELECTRA, when do you think mixed precision will be available again ?

**Comment by ThilinaRajapakse** [comment]
Should be resolved in `v0.48.13`
