### ISSUE TITLE
training loss in classificationmodel

### ISSUE THREAD

**Issue by Jashjeet** [ThilinaRajapakse/simpletransformers#648]
Is there a way to get the training loss as output after training. At present, it is not set to return anything.

![image](https://user-images.githubusercontent.com/53444766/90066636-fe336e80-dcbb-11ea-8965-e3fed2f0bd01.png)

**Comment by Jashjeet** [comment]
![image](https://user-images.githubusercontent.com/53444766/90424232-c3e71a00-e08b-11ea-98a4-22b15d580cd2.png)
I think I can get the value by just making the following changes.

**Comment by ThilinaRajapakse** [comment]
Training loss is logged to wandb/tensorboard if you are using them. You can also find it in `training_progress_scores.csv` file in your model outputs.

**Comment by moh-yani** [comment]
Dear @ThilinaRajapakse 
I have installed wand. However, I didn't found the training_progress_scores.csv file in our model outputs. What does it happened?

**Comment by moh-yani** [comment]
> Training loss is logged to wandb/tensorboard if you are using them. You can also find it in `training_progress_scores.csv` file in your model outputs.

Dear @ThilinaRajapakse
I have installed wand. However, I didn't found the training_progress_scores.csv file in our model outputs. What does it happened?

**Comment by ThilinaRajapakse** [comment]
Are you using the latest version of the library?
