### ISSUE TITLE
Regarding GPU usage

### ISSUE THREAD

**Issue by ThilinaRajapakse** [ThilinaRajapakse/simpletransformers#65]
thanks, it seems like using more gpu resource compared to use Zihang Dai's  code in my project, is this normal

_Originally posted by @tzhxs in https://github.com/ThilinaRajapakse/simpletransformers/issues/61#issuecomment-559955617_

**Comment by ThilinaRajapakse** [comment]
If you are only running a single model, I really wouldn't bother. But if you are running multiple models, even consecutively, I recommend writing a python script to run one experiment, and then run that python script as needed through a bash/shell script.

Even deleting the model doesn't seem to release CUDA memory until the python script itself exits.

**Comment by tzhxs** [comment]
thanks, I will try it
