### ISSUE TITLE
Using prediction of regression is slow

### ISSUE THREAD

**Issue by telunyang** [ThilinaRajapakse/simpletransformers#651]
Hi, I have something to consult you about the prediction of regression.

```
from simpletransformers.classification import ClassificationModel, ClassificationArgs
import torch

def run():
    cuda_available = torch.cuda.is_available()
    print('GPU is available: {}'.format(cuda_available))

    '''ModelArgs'''
    model_args = ClassificationArgs()
    model_args.train_batch_size = 8
    model_args.num_train_epochs = 1
    model_args.overwrite_output_dir = True
    model_args.reprocess_input_data = True
    model_args.use_multiprocessing = True
    model_args.regression = True
    model_args.output_dir = "outputs/distilbert_regression_epochs_1/"

    ''Loading model'''
    model_cls = ClassificationModel('distilbert', "outputs/distilbert_regression_epochs_1/", use_cuda=True, cuda_device=0, num_labels=1, args=model_args)

    #Try to predict
    predictions, raw_outputs = model_cls.predict( [ [ '謝謝你的幫忙', '不客氣' ] ] )
    print(predictions)
    predictions, raw_outputs = model_cls.predict( [ [ '謝謝你的幫忙', '不客氣' ] ] )
    print(predictions)
    predictions, raw_outputs = model_cls.predict( [ [ '謝謝你的幫忙', '不客氣' ] ] )
    print(predictions)

if __name__ == '__main__':
    run()
```

(Sentences in prediction are Traditional Chinese.)

I ran my code as above, why did it predict that slow?

A prediction would cost 3 to 5 seconds.

I inspected detailed information of CPU and GPU when I ran my code, CPU usage will be 100% and GPU is getting the high temperature, but the GPU seems not to work for prediction of regression.

Could anyone answer me, please?

Thanks in advance.

**Comment by ThilinaRajapakse** [comment]
The time taken for a prediction depends on the GPU used, but for a relatively high-end GPU with a distilbert model, it probably shouldn't take 3-5 seconds (unless this includes the time taken to load the model, i.e. run time from start to finish for the script).

Does it take the same amount of time for English? You could try the minimal example to test it.

**Comment by telunyang** [comment]
> The time taken for a prediction depends on the GPU used, but for a relatively high-end GPU with a distilbert model, it probably shouldn't take 3-5 seconds (unless this includes the time taken to load the model, i.e. run time from start to finish for the script).
> 
> Does it take the same amount of time for English? You could try the minimal example to test it.

Thanks for your reply, I tried to run my code on different servers, I found that server I've tried before has something wrong with its environment.

Thanks a lot indeeds.
