### ISSUE TITLE
Multiple inputs for seq2seq

### ISSUE THREAD

**Issue by felipeboffnunes** [ThilinaRajapakse/simpletransformers#652]
Is it possible to add multiple inputs to a seq2seq model? I haven't found a way to do it, I believe it may be a nice addition to the project.

**Comment by ThilinaRajapakse** [comment]
Do you mean multiple sequences? You can simply concatenate the sequences together and use a delimiter in between the sequences if necessary.

**Comment by felipeboffnunes** [comment]
Yes, I did that. I guess that's true, being able to just put a delimiter means there is no true reason to implement the whole separate input feature. Thanks for confirming it!
