### ISSUE TITLE
Using Longformer for Text Representation

### ISSUE THREAD

**Issue by FeryET** [ThilinaRajapakse/simpletransformers#653]
**Is your feature request related to a problem? Please describe.**

I'm trying to get text representations of long documents using LongFormer, and this is still not supported in this library. The classification models and language models include LongFormer as a supported model but the representation model does not.

**Describe the solution you'd like**
Supporting it.

**Describe alternatives you've considered**
I've tried using HuggingFace's transformers library, but it's still really confusing for me. This library really simplifies many of the confusing (atm) huggingface API.

**Comment by rhamnett** [comment]
```from simpletransformers.classification import ClassificationModel

import pandas as pd
import logging
import torch

logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.WARNING)

train_data = [['aaaaaaa', 1], ['bbbbbbb', 0], ['cccccc' 2]]
train_df = pd.DataFrame(train_data)

eval_data = ['xxx', 1], ['yyy', 0], ['zzz', 2]
eval_df = pd.DataFrame(eval_data)


# Create a ClassificationModel
train_args ={"reprocess_input_data": True,
             "do_lower_case" : False,
             "max_seq_length" : 256,
             "attention_window": 20,
             "train_batch_size" : 8}


cuda_available = torch.cuda.is_available()

model = ClassificationModel('longformer', 'allenai/longformer-large-4096', num_labels=3, use_cuda=cuda_available, 
                            args=train_args)```

**Comment by FeryET** [comment]
@rhamnett Hi. thanks for your reply, but you are training a classification model. I want to use LongFormer as a text representation model, to embed long documents to high quality document vectors. Is this possible with this approach?

**Comment by rhamnett** [comment]
Ah sorry it was late and I hadn't read the issue properly, my bad
