### ISSUE TITLE
Trained model is not saved to `output_dir` parameter directory.

### ISSUE THREAD

**Issue by jnishi** [ThilinaRajapakse/simpletransformers#657]
**Describe the bug**
The trained model of ClassificationModel is saved to the directory  where the `output_dir` parameter of `ClassificationModel.train_model` function. However, a part of trained model (e.g. config.json, pytorch_model.bin, etc.) is saved to the directory which is specified by `args.output_dir` even if  `output_dir` parameter of  `train_model` is specified.

**Expected behavior**
All of trained model is saved to the directory which is specified by `output_dir` parameter.

**Desktop (please complete the following information):**
 - OS:  Ubuntu 16.04.6 LTS

**Additional context**
This may be because `_save_model` which is called in `train_model` does not use `output_dir` variable in `train_model`.
https://github.com/ThilinaRajapakse/simpletransformers/blob/v0.47.2/simpletransformers/classification/classification_model.py#L313

**Comment by ThilinaRajapakse** [comment]
Yeah, I must have missed it because I never pass `output_dir` directly to `train_model()`. I'll push a fix for this. As a workaround, you can set the output directory through the `model_args`.
