### ISSUE TITLE
Q&A modeling: Possible to provide pre-generated context to prediction

### ISSUE THREAD

**Issue by lazarillo** [ThilinaRajapakse/simpletransformers#658]
**Is your feature request related to a problem? Please describe.**

The "problem" I have is that I have to predict an answer relatively quickly (seconds), but `model.predict` for the Q&A modeling is very slow (minutes) *because most of the time is being dominated by ingesting a fairly large context and generating features from it, even though the context does not change*.

**Describe the solution you'd like**

I would like to call `model.predict` with a context that has already been mapped, so that all that is needed is to perform the actual prediction (and the tokenization on the question, which is far smaller than the context).

In other words, I would like for the `to_predict` object to look like this:

```python
to_predict = [
    "qas": [
        {
            "question": "How many licks does it take to get to the center of a Tootsie pop?",
            "id": "0",
        }
    ],
]
```

instead of this:

```python
to_predict = [
  {
    "context": my_very_large_but_always_consistent_context_object,
        "qas": [
            {
            "question": "How many licks does it take to get to the center of a Tootsie pop?",
                "id": "0",
            }
        ],
  }
]
```

**Describe alternatives you've considered**

I am looking to see how hard it is to just implement what simpletransformers is doing "under the hood", for instance writing all the layers in PyTorch, etc.  But I am new to NLP (not deep learning, just NLP) and I do not think I can convert your otherwise great library into PyTorch code quickly enough to meet an expected deadline.

**Additional context**

Thanks for all the great work!!  👍

**Comment by ThilinaRajapakse** [comment]
While I agree that it would certainly be useful to be able to do this, I don't think it will be trivial to implement. It's probably going to be most complicated in the same case where it is most useful - when there is a large context.

If your context is the same and if you know all your questions beforehand, I think it will be faster if you put all the questions in the same `qas` list.
