### ISSUE TITLE
Reading Bert model using ClassificationModel is failing with utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by thunderhemu** [ThilinaRajapakse/simpletransformers#659]
**Describe the bug**
A clear and concise description of what the bug is. Please specify the class causing the issue.

So I saved the classification  model as a pickle file and I am trying to read it back it's failing with the following error

'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
this is because the it was read using `r` mode in  model_args.py  line number 96 if read it using `rb` this should fix the problem 

**To Reproduce**
Save a classification model and try read it back

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS
  databrics cluster

**Additional context**

**Comment by NaRuecker** [comment]
Following

**Comment by ThilinaRajapakse** [comment]
This is not an issue when using the built-in save/load functionality, right?

Is there a use-case where pickle must be used instead?

**Comment by thunderhemu** [comment]
so we are saving the model and trying to reload, we tried using pickle and json,  both the cases it's the same error. could please point me how do I use built in save function to save the model, on more thing 

with the following functionality in model_args.py we are expecting always the model should be saved as model_args.json

   def load(self, input_dir):
        if input_dir:
            model_args_file = os.path.join(input_dir, "model_args.json")
            if os.path.isfile(model_args_file):
                with open(model_args_file, "r") as f:
                    model_args = json.load(f)

                self.update_from_dict(model_args)

**Comment by ThilinaRajapakse** [comment]
The saved model consists of _all_ the files in the output directory. As the documentation says, it should be the path to the directory itself and not a particular file.

The [example](https://simpletransformers.ai/docs/usage/#loading-a-local-save) from the docs.

You don't need to manually save the model. It gets saved during training according to the [parameters](https://simpletransformers.ai/docs/usage/#configuring-a-simple-transformers-model) you set (e.g. `save_steps`, `save_model_every_epoch`). 

If your model  files are in `/dbfs/FileStore/tables/`, then you would load them like so.

```python
model = ClassificationModel("roberta", "/dbfs/FileStore/tables/")
```

**Comment by chris-aeviator** [comment]
I can confirm this only happens when you add the (misleading in the docs) `/path/to/model/pytorch_model.bin` instead of `/path/to/model`.

**Comment by ThilinaRajapakse** [comment]
_model_name specifies the exact architecture and trained weights to use. This may be a Hugging Face Transformers compatible pre-trained model, a community model, or the path to a directory containing model files._

It clearly says path to a _directory_

**Comment by chris-aeviator** [comment]
@ThilinaRajapakse it also clearly mentions `pytorch_model.bin`

```
model_name: model_name: Default Transformer model name or path to Transformer model file (pytorch_model.bin).
```

**Comment by ThilinaRajapakse** [comment]
Okay, that is misleading. Can you give me the link to where this description is?
