### ISSUE TITLE
AttributeError: 'MultiLabelClassificationModel' object has no attribute 'sliding_window'

### ISSUE THREAD

**Issue by QAQOAO** [ThilinaRajapakse/simpletransformers#66]
**Describe the bug**
A clear and concise description of what the bug is. Please specify the class causing the issue.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS

**Additional context**

This error emerges when executing my MultiLabelClassificationModel, seems to be a bug from the update of experimental features.

----> model.train_model(train_df)

    481                 silent=args['silent'],
    482                 use_multiprocessing=args['use_multiprocessing'],
--> 483                 sliding_window=self.sliding_window,
    484                 stride=self.args['stride']
    485             )

AttributeError: 'MultiLabelClassificationModel' object has no attribute 'sliding_window'

**Comment by ThilinaRajapakse** [comment]
Oh yeah. I'll add a workaround until it gets implemented for MultiLabelClassificationModel.

**Comment by ThilinaRajapakse** [comment]
Fixed! 0.9.1

**Comment by lirabenjamin** [comment]
Hi I'm getting the same error for attribute regression:

AttributeError: 'MultiLabelClassificationArgs' object has no attribute 'regression'

Thanks!!

**Comment by ChristopherMarais** [comment]
I am also getting this issue:

"AttributeError("'MultiLabelClassificationArgs' object has no attribute 'regression'")"

**Comment by tsavage6001** [comment]
did anyone find a work around?

**Comment by tsavage6001** [comment]
To the regression issue above *
