### ISSUE TITLE
Truncation warning even with truncation=True

### ISSUE THREAD

**Issue by felipeboffnunes** [ThilinaRajapakse/simpletransformers#662]
Hi!
I receive this Warning from the script:

WARNING:transformers.tokenization_utils_base:Truncation was not explicitely activated but max_length is provided a specific value, please use truncation=True to explicitely truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to truncation.

It may seem obvious to just put truncation=True on the model_args, but it is not changing the outcome, I still receive the Warning.

I have max_lenght set to a specific size, yes. But, I also have truncation set to True.

I'm running on Ubuntu.

**Comment by ThilinaRajapakse** [comment]
The warning is being generated from Huggingface. As far as I can tell, it's safe to ignore.
