### ISSUE TITLE
Ability to call BertTokenizer instead of RobertaTokenizer.

### ISSUE THREAD

**Issue by net2cn** [ThilinaRajapakse/simpletransformers#664]
Hi,
Thank you for creating this fascinating repo. I've been playing around with this repo for a while. Everything works so smooth until I tried to use the model "clue/roberta_chinese_base", which gives me an error:
`OSError: Model name 'clue/roberta_chinese_base' was not found in tokenizers model name list (roberta-base, roberta-large, roberta-large-mnli, distilroberta-base, roberta-base-openai-detector, roberta-large-openai-detector). We assumed 'clue/roberta_chinese_base' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.json', 'merges.txt'] but couldn't find such vocabulary files at this path or url.`
After digging around I noticed that I should use `BertTokenizer` instead of `RobertaTokenizer` in [its description](https://huggingface.co/clue/roberta_chinese_base). Unfortunately, I didn't find a proper way to do so. How can I call `BertTokenizer` instead of `RobertaTokenizer`?
Thanks.

**Comment by ThilinaRajapakse** [comment]
There is no way to do that directly as of now. However, you can change your local simpletransformers library as a temporary workaround.

https://github.com/ThilinaRajapakse/simpletransformers/blob/6a6ae049242d0c9cff9e597fc3639e4d5e7e63e2/simpletransformers/classification/classification_model.py#L119-L119

You should be able to just change `RobertaTokenizer` to `BertTokenizer` here.

**Comment by seyonechithrananda** [comment]
@ThilinaRajapakse  I tried this, but it still initializes a RobertaTokenizer and throws an error in Colab
