### ISSUE TITLE
how to load save model in sentence pair classification 

### ISSUE THREAD

**Issue by mayankpathaklumiq** [ThilinaRajapakse/simpletransformers#669]
**Describe the bug**
A clear and concise description of what the bug is. Please specify the class causing the issue.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS

**Additional context**

**Comment by estaub** [comment]
I haven't tried it, but I think you replace the model name (e.g. `roberta-base`) with the path to the saved model.
