### ISSUE TITLE
[question] token level classification handling

### ISSUE THREAD

**Issue by antgr** [ThilinaRajapakse/simpletransformers#67]
Hi,
bert has its own vocabulary, which means that, we have to use bert tokenizer before feeding a sentence to bert. But for a sequence labeling task (token level classification) bert will cut some words further and the alignment between lenght of words and length of labels will break.
The Question: How this issue is handled by the library?

**Comment by ThilinaRajapakse** [comment]
You can use the tokenizer to handle that part. Take a look at the ner_utils.py file. Specifically,

```
    tokens = []
    label_ids = []
    for word, label in zip(example.words, example.labels):
        word_tokens = tokenizer.tokenize(word)
        tokens.extend(word_tokens)
        # Use the real label id for the first token of the word, and padding ids for the remaining tokens
        label_ids.extend([label_map[label]] + [pad_token_label_id] * (len(word_tokens) - 1))
```

**Comment by antgr** [comment]
aha! Thank you..

**Comment by ThilinaRajapakse** [comment]
No problem!
