### ISSUE TITLE
XLNET for NER in Readme 

### ISSUE THREAD

**Issue by andrewlaikh** [ThilinaRajapakse/simpletransformers#670]
Hi, I note that both the github readme and the simpletransformers ai readme states that XLNet can be used for NER in simpletransformers. However, looking at the implementation for NER in the repo at the moment, XLNet does not seem to be implemented.  I'm curious is there's any future plans to support this? Thanks!

**Comment by ThilinaRajapakse** [comment]
Unfortunately, this is a mistake in the docs. There are no immediate plans to add XLNet for NER atm.
