### ISSUE TITLE
`best_model_dir` not working

### ISSUE THREAD

**Issue by ma-ji** [ThilinaRajapakse/simpletransformers#671]
`model.train_model(train_df=train_df, eval_df=eval_df, output_dir='model_outputs/', show_running_loss=True, best_model_dir='best_model/', evaluate_during_training=True)`

The above code cannot create a `best_model` directory, and still puts the best model (I guess) under `outputs`.

**Comment by ThilinaRajapakse** [comment]
Those options need to be passed in as a dictionary to the `args` parameter. E.g. :

```python
model.train_model(train_df=train_df, eval_df=eval_df, args={"best_model_dir": "best_model"})
```

**Comment by ma-ji** [comment]
It works now as you suggested. Is it possible to raise an error to suggest this?

**Comment by ThilinaRajapakse** [comment]
I don't think it's necessary (or advisable). There are valid `kwargs` that you can pass, just not these ones. Also, the correct way to pass these arguments are documented.
