### ISSUE TITLE
language_modeling_model.py

### ISSUE THREAD

**Issue by asharma567** [ThilinaRajapakse/simpletransformers#673]
outputs = model(**inputs)

throws an error: can't unpack tensors

**To Reproduce**
fine-tune using distilroberta

**Comment by jubrowon** [comment]
I have the same issue as well. 
https://github.com/ThilinaRajapakse/simpletransformers/blob/master/simpletransformers/language_modeling/language_modeling_model.py

![image](https://user-images.githubusercontent.com/26244917/91674679-ab3f2f80-eb74-11ea-804b-9309337f6c46.png)

It seems that inputs are tensor after mask_tokens but it seems that model(**inputs) expects kwargs.
