### ISSUE TITLE
`Seq2SeqModel` can't read saved model 

### ISSUE THREAD

**Issue by Zhylkaaa** [ThilinaRajapakse/simpletransformers#676]
**Describe the bug**
A clear and concise description of what the bug is. Please specify the class causing the issue.
I have trained `Seq2SeqModel` with 2 Berts as encoder and decoder and then tried to evaluate model using `Seq2SeqModel(encoder_type='bert', encoder_decoder_name='path/to/save/model')` and got `AssertionError: If you want to use `BertForMaskedLM` make sure `config.is_decoder=False` for bi-directional self-attention.` 

**To Reproduce**
- save `Seq2SeqModel` (e.g `Seq2SeqModel(encoder_type='bert', encoder_name='bert-base-multilingual-cased', decoder_name='bert-base-multilingual-cased')`
- read model with `Seq2SeqModel(encoder_type='bert', encoder_decoder_name='path/to/save/model')`

**Expected behavior**
This should read the model 😄 

**Desktop (please complete the following information):**
 - OS: Linux (CentOS)
 - python: 3.7

**Additional context**
I believe that this could be fixed with changing `directionality` in `config.json`, or is it something else? I need some help, 'cause a can't figure how to fix it for now

Work around is to just use `Seq2SeqModel(encoder_type='bert', encoder_name='path/to/save/model/encoder', decoder_name='path/to/save/model/decoder')`

**Comment by ThilinaRajapakse** [comment]
The workaround is actually the correct way to load the model. `encoder_decoder_name` is for BART models, if I remember correctly.
