### ISSUE TITLE
Multi-task learning

### ISSUE THREAD

**Issue by djstrong** [ThilinaRajapakse/simpletransformers#677]
It should allow for many datasets, each with separate heads (one or more). So, e.g. I can combine NER with text classification on the same or different datasets. It could be sentiment analysis on whole text and detecting positive and negatives phrases (using NER approach), and it could be supported by other sentiment dataset using different annotation.

**Comment by ThilinaRajapakse** [comment]
Since there are infinite combinations of such systems, it's not possible to support it directly in the library. You could probably use the library models as the building blocks to build such a system though.

**Comment by djstrong** [comment]
There is FARM (https://github.com/deepset-ai/FARM/) which supports multi head learning (the same dataset annotated on different levels) or jiant (https://github.com/jiant-dev/jiant) which supports multi dataset scenarios.
