### ISSUE TITLE
Logging to file

### ISSUE THREAD

**Issue by juliovillena** [ThilinaRajapakse/simpletransformers#678]
Any suggestion to send the messages of the training process to a log file? 
"silent=True" argument removes all output, and I would like to have some progress indication.
I have tried with python logging, stderr redirection, etc. without success. 
Thanks a lot!
  Julio

**Comment by ThilinaRajapakse** [comment]
All the messages are generated with the python logging module. So, you can use any functionality from the module.

E.g.:

```python
logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.WARNING)

fh = logging.FileHandler('file.log')
fh.setLevel(logging.INFO)
st_logger = logging.getLogger()
st_logger.addHandler(fh)
```

**Comment by juliovillena** [comment]
Thanks a lot, Thilina! I had tried that, but doesn't seem to work (or I am doing something wrong). I want to send everything from the standard/error output to a file, even the progress bars:

Epochs 0/1. Running Loss:    0.6933: 100%|████████| 1/1 [00:00<00:00,  5.71it/s]
Epoch 1 of 1: 100%|███████████████████████████████| 1/1 [00:00<00:00,  5.66it/s]

**Comment by juliovillena** [comment]
I finally got it. The default output from tqdm is sys.stderr, so redirecting it to a file worked. Well, in addition to passing {"silent": None} in args -instead of True or False- (corresponds to "disable" argument in tqdm: "If set to None, disable on non-TTY"). 
If would be even better to pass the "leave" tqdm's argument to True, but this is not possible with simpletransformers interface.
Thanks!!
