### ISSUE TITLE
map_location from GPU to CPU in LanguageModelingModel

### ISSUE THREAD

**Issue by hetryn** [ThilinaRajapakse/simpletransformers#681]
**Describe the bug**
When running 

```
from simpletransformers.language_modeling import LanguageModelingModel

test_file="./test.txt" # path to file 
model_path="./path_to_model" # path to fine-tuned language model
generator_path="./path_to_model/generator_model" # path to fine-tuned generator model
discriminator_path="./path_to_model/discriminator_model # path to fine-tuned discriminator model

    model = LanguageModelingModel(
        model_type="electra",
        model_name=model_path,
        generator_name=generator_path,
        discriminator_name=discriminator_path,
        use_cuda=torch.cuda.is_available(),
    )

test_results = model.eval_model(test_file)
```

`RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU. `

Following error occured when instantiating LanguageModelingModel on cpu device, using a path to the model (in this case, I was using a fine-tuned electra generator model. Model was trained on a GPU device. However not all the time, we would want to do inference/evaluation on the same device.

**To reproduce**
Train a model on GPU and save the model. Reload the model on CPU device.

**Expected behavior**
To be able to load our saved models that was pretrained on GPU to load onto CPU.

**Comment by ThilinaRajapakse** [comment]
I can't reproduce this error (a model trained on GPU successfully loads when using the CPU as well). Can you provide a minimal script to reproduce this?
