### ISSUE TITLE
Predict not working in docker in AWS (Timing out)

### ISSUE THREAD

**Issue by aamin21** [ThilinaRajapakse/simpletransformers#682]
**Describe the bug**
I wish I could be more detailed but honestly I don't even have much. I created a Flask api contained in a Docker container, and deployed to AWS. The endpoint is working and the model is being loaded properly. But when it comes predicting, it just idles and the endpoint times out. When I run the API locally, everything works fine.

I am attaching screen shots.

![image](https://user-images.githubusercontent.com/38225633/91581035-f0b4f000-e91b-11ea-9072-88501f3db0ec.png)

**To Reproduce**
Steps to reproduce the behavior: This is very specific to my use case, so it's very hard to reproduce.

**Expected behavior**
The prediction should be returned
![image](https://user-images.githubusercontent.com/38225633/91581162-19d58080-e91c-11ea-8361-7202d782fd36.png)

**Desktop (please complete the following information):**
 - OS: Linux EC2 instance
 - Docker

**Comment by ThilinaRajapakse** [comment]
Could it be possible that the EC2 instance is running out of resources?

**Comment by aamin21** [comment]
> 
> 
> Could it be possible that the EC2 instance is running out of resources?

I thought about it. The instance has 30gb of memory and the docker container has 8gb reserved. Might bump it up to 16gb but honestly, I thought 8gb would have been enough. Very clueless about this at this point.

**Comment by aamin21** [comment]
Bumping up to 16gb did not help. I am so lost at this point....

**Comment by g-laz77** [comment]
Switch `use_multiprocesssing` to false

**Comment by aamin21** [comment]
> 
> 
> Switch `use_multiprocessing` to false

Tried that, didn't work unfortunately.

**Comment by g-laz77** [comment]
Does the flask api when hosted locally, not respond to requests?

**Comment by aamin21** [comment]
> 
> 
> Does the flask api when hosted locally, not respond to requests?

It works perfectly locally! That's why this is more frustrating! Locally, I see the request being processed and predicted terms being spit out. In AWS, I can see the request being processed and the model prediction "start" but then idles immediately (refer to the first screenshot and red markers). AWS waits for 1 min and then times out.

**Comment by aamin21** [comment]
Update 1: I have been able to reproduce this issue **locally** by running a docker image (with gunicorn as the server).
 
**Dockerfile:**
![image](https://user-images.githubusercontent.com/38225633/92025024-f308b700-ed2c-11ea-9694-358ec8c6b272.png)

**Requirements.txt:**

psutil==5.7.2
numpy==1.19.1
joblib==0.13.2
boto3==1.14.47 
Flask==1.0.3
pytest==3.8.1
pytest-cov==2.7.1
jsons==1.0.0
scikit-learn==0.21.3
scikit-multilearn==0.2.0
Flask-Cors==3.0.8
tqdm==4.47.0
tokenizers==0.8.1.rc1
-f https://download.pytorch.org/whl/torch_stable.html 
torch==1.4.0+cpu 
-f https://download.pytorch.org/whl/torch_stable.html
torchvision==0.5.0+cpu
transformers==3.0.2
simpletransformers==0.47.3
python-dotenv==0.14.0

**Comment by aamin21** [comment]
SOLUTION: This is caused by a mem leak when running using Gunicorn (as mentioned in this issue: https://github.com/ThilinaRajapakse/simpletransformers/issues/330) . Basically, make sure use_multiprocessing is FALSE and SILENT is TRUE. @g-laz77 You were right!
