### ISSUE TITLE
How can I use it to do regression? Please

### ISSUE THREAD

**Issue by tzhxs** [ThilinaRajapakse/simpletransformers#69]
**Describe the bug**
A clear and concise description of what the bug is. Please specify the class causing the issue.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS

**Additional context**

**Comment by ThilinaRajapakse** [comment]
Regression is not yet implemented.

**Comment by ThilinaRajapakse** [comment]
Regression is now supported.
