### ISSUE TITLE
mBART model for Seq2Seq ?

### ISSUE THREAD

**Issue by Neuronys** [ThilinaRajapakse/simpletransformers#692]
Hello
Thanks for this great lib. 
Can we use mBART model with your Seq2Seq instead of BART ?
https://github.com/ThilinaRajapakse/simpletransformers#sequence-to-sequence-models
I want to finuetune in the French language. 
Cheers 
Philippe

**Comment by ThilinaRajapakse** [comment]
mBART was added to transformers quite recently, so I haven't had the time to add it here yet. But it's definitely something I need as well so I'm hoping to add it as soon as possible.

**Comment by Neuronys** [comment]
Thanks @ThilinaRajapakse 
I will be impatient to test it 😏
Cheers

**Comment by abedkhooli** [comment]
Until this is done (more convenient, especially with TPU support), I used HF's [examples section](https://github.com/huggingface/transformers/tree/master/examples) on GPU.

**Comment by Zhylkaaa** [comment]
see #767 I guess this is ready to use model
