### ISSUE TITLE
Can we upload ELECTRA discriminator + generator to HuggingFace's model hub?

### ISSUE THREAD

**Issue by seyonechithrananda** [ThilinaRajapakse/simpletransformers#693]
Hi, @ThilinaRajapakse,

Thanks for adding ELECTRA pre-training support. Your documentation is excellently written! 
[Electra training](https://simpletransformers.ai/docs/lm-specifics/) allows us to save the model after pre-training is complete on a custom corpus. After pre-training, does the simple-transformers format allow us to upload the model files back to HuggingFace's model hub? 

Thanks!

**Comment by ThilinaRajapakse** [comment]
I am not sure about this. Getting ELECTRA models to save and load properly was painful, to say the least. The HF loading functions didn't load the weights properly at the time ELECTRA pre-training was added here so it's possible that there are differences.

I'd say go ahead and give it a shot. 😀

**Comment by seyonechithrananda** [comment]
Thanks for the response!

I believe they've resolved most of the problems with the `save_` methods (looking at the PR's to address them in June-July), I remember dealing with a bunch of errors there with tokenizers, saving models, etc. as well! 

I was curious about how the file structure for ELECTRA models works in simple transformers and was guessing that since the library builds on the HuggingFace equivalent for the language-modelling, we could possibly still upload back to the S3 on HuggingFace.

I was hoping we could use a similar flow to this to upload the model:

```
from transformers import AutoModelWithLMHead, AutoTokenizer, BertTokenizer
import os


directory = "/path/to/model"
tokenizer_directory = "/path/to/tokenizer"

model = AutoModelWithLMHead.from_pretrained(directory)
tokenizer = BertTokenizer.from_pretrained(tokenizer_directory)
out = "ChemBERTa"
os.makedirs(out, exist_ok=True)
model.save_pretrained(out)
tokenizer.save_pretrained(out)

!transformers-cli upload /content/ChemBERTa
```
