### ISSUE TITLE
After last update in ConvAIModel, getting AttributeError: 'ConvAIModel' object has no attribute 'model' while loading pre-trained

### ISSUE THREAD

**Issue by anindyasdas** [ThilinaRajapakse/simpletransformers#696]
**Describe the bug**
While loading the pre-trained model  getting error "AttributeError: 'ConvAIModel' object has no attribute 'model'"

This error appears appears after the recent changes made.

**To Reproduce**

`model = ConvAIModel("gpt",model_path, use_cuda=True, args=train_args)`

**Expected behavior**
This error was not there before the update. It seems like it refers self.model before assigning self.model 

**Screenshots**
`AttributeError                            Traceback (most recent call last)
<ipython-input-53-1daa579c40bc> in <module>()
----> 1 model = ConvAIModel("gpt",model_path, use_cuda=True, args=train_args)

/usr/local/lib/python3.6/dist-packages/simpletransformers/conv_ai/conv_ai_model.py in __init__(self, model_type, model_name, args, use_cuda, cuda_device, **kwargs)
    117         self.__dict__.update(kwargs)
    118         self.tokenizer = tokenizer_class.from_pretrained(model_name, **kwargs)
--> **119         self.add_special_tokens_(self.model, self.tokenizer)**
    120 
    121         if not self.args.quantized_model:

AttributeError: 'ConvAIModel' object has no attribute 'model`

@ThilinaRajapakse

**Comment by ThilinaRajapakse** [comment]
Should be fixed now.
