### ISSUE TITLE
The new Dynamic Quantize support is increasing inference time

### ISSUE THREAD

**Issue by g-laz77** [ThilinaRajapakse/simpletransformers#698]
I am using a MultiLabelClassificationModel fine-tuned on distilbert. 

I am observing that the inference time has almost increased by 80% when I use the `dynamic_quantize:true` than when I don't use this flag.

Any reason for this increased inference time?

Also, does `thread_count` help improve inference time ?

**Comment by ThilinaRajapakse** [comment]
Using `dynamic_quantize` will quantize the model before running inference (Load model --> quantize model --> inference). This process will likely take longer than just doing inference directly. It's better to load the model with `dynamic_quantize` and save the model once and then load the quantized model directly for inference. This should be slightly faster than not using quantization.

Unfortunately, dynamic quantization doesn't seem to significantly improve the inference time. Its main advantage is that it cuts down the model size by almost half.

No, `thread_count` would generally be used to limit the number of threads used (typically in an environment with constrained resources).

**Comment by g-laz77** [comment]
Understood. Exporting the model to ONNX, optimising the ONNX model using onnxruntime and then quantising the p[timized ONNX model helped improve inference time by a margin.
Should definitely consider adding ONNX export support once training is completed.
