### ISSUE TITLE
why is the word in vocab.json of bart model so weird

### ISSUE THREAD

**Issue by zhangshouleibupt** [ThilinaRajapakse/simpletransformers#701]
hi many thans your build this awesome project. it really help me in some seq2seq task.
recently i want to do some experiment in cnn daily(it's text summarition corpus)，i use the facebook/bart-base model step by step your instruction in tutorials.  and i use the rouge_l score as metrics.  but the result is so terrible as the model completely random prediction and learned nothing.
here are my hyparemeters: 
batch_size:8
max_sen_length:128
max_length:128
beam_size:3
epochs:4
i wander whether i use the model in wrong way, so i check the data fromat and check the model outputs including saved config and vocab.
i find a weird thing in vocab.json. **words all start with G(G with a dot in it's head).** is it your special  processing or i use the model in wrong way.

**Comment by ThilinaRajapakse** [comment]
That's how the vocabulary is saved for BERT based models. It's normal. Also, the vocab will not be changed when you fine-tune a model.

Can you show some example outputs from your model?

**Comment by Ricardokevins** [comment]
> hi many thans your build this awesome project. it really help me in some seq2seq task. recently i want to do some experiment in cnn daily(it's text summarition corpus)，i use the facebook/bart-base model step by step your instruction in tutorials. and i use the rouge_l score as metrics. but the result is so terrible as the model completely random prediction and learned nothing. here are my hyparemeters: batch_size:8 max_sen_length:128 max_length:128 beam_size:3 epochs:4 i wander whether i use the model in wrong way, so i check the data fromat and check the model outputs including saved config and vocab. i find a weird thing in vocab.json. **words all start with G(G with a dot in it's head).** is it your special processing or i use the model in wrong way.

thats maybe the bart use GPT2-bpe tokenizer. G is just the binary charactor( which is not english charactor G)
