### ISSUE TITLE
model.predict() sends SIGTERM signal

### ISSUE THREAD

**Issue by mossadhelalitalentbait** [ThilinaRajapakse/simpletransformers#705]
Hey, thanks for the awesome work you have doing!

**Describe the bug**
I ran into an issue when trying to deploying A BERT model to a [Cortex](https://www.cortex.dev/) API. The issue stems from the predict method sending a SIGTERM while still doing the prediction. This causes the API server to crash while making predictions.

I have documented the issue in more details [here](https://github.com/cortexlabs/cortex/issues/1346). You can also find the response from Cortex developers.

**To Reproduce**
1. Create a classification model (via loading or training/fine-tuning)
2. Call `model.predict([<sample>])`

**Expected behavior**
The model should predict the sample without sending a SIGTERM signal.

**Code Used**
I implemented a wrapper around the SimpleTransformers model.
Here is How I initialize the model:

```
    def load_saved_model(self, path_to_model_directory='outputs'):
        self.train_args['thread_count'] = 1
        self.model = ClassificationModel('bert', path_to_model_directory, 
                                         args=self.train_args, use_cuda=self.use_cuda)
```

And here is how I predict:
```
    def predict_categories(self, job_descriptions):
        predicted_category_ids, _ = self.model.predict(job_descriptions)
```

**Configuration**

```
python: 3.8.3
simpletransformers: 0.47.3
torch: 1.6.0
numpy: 1.19.1
```

**Comment by ThilinaRajapakse** [comment]
I'm not sure why the `predict()` method would send a SIGTERM signal. It's just a function that returns a value.

It's possible that the issue is related to how multiprocessing is handled on servers. You need to turn off multiprocessing to use the models with a Flask API, for example.

`train_args.use_multiprocessing = False`

**Comment by mossadhelalitalentbait** [comment]
Thank you for your response @ThilinaRajapakse. I can confirm that using `train_args.use_multiprocessing = False` has solved the problem for me. I will close this issue.

**Comment by meeDeepakOfficial** [comment]
what if we have to `use_multiprocessing` and `sigterm` at the same time? any idea
