### ISSUE TITLE
multi-label classification / paperswithcode dataset

### ISSUE THREAD

**Issue by x0rzkov** [ThilinaRajapakse/simpletransformers#710]
Hi guys,

Hope you are all well !

I was wondering if **simpletransformers** can handle multi-label classification with 1560 labels.

More precisely, I would like to apply it to paperswithcode dataset where `labels` are called `tasks`.

Refs:
- [Repository](https://github.com/paperswithcode/paperswithcode-data) 
- [Dataset](https://paperswithcode.com/media/about/papers-with-abstracts.json.gz)

Thanks for any insights or inputs on that.

Cheers,
X

**Comment by ThilinaRajapakse** [comment]
It can handle 1560 labels in the sense that it shouldn't throw any errors but I'm not sure whether you'll be able to get good results. A lot will depend on the label balance (or rather the imbalance).
