### ISSUE TITLE
Training T5 on new language from scratch

### ISSUE THREAD

**Issue by parthplc** [ThilinaRajapakse/simpletransformers#716]
Hey, @ThilinaRajapakse saw your post on Training ELECTRA from scratch. Will the same method applies to T5 text to text transformer for another language?

**Comment by ThilinaRajapakse** [comment]
The training process is different. T5 is an encoder-decoder model whereas ELECTRA is, well, ELECTRA (generator + discriminator scheme).

Also, T5 is _extremely_ resource-intensive to train, both in terms of compute and data. In other words, you need Google-level resources to train a T5 model from scratch.

**Comment by parthplc** [comment]
Will it work if I want to train t5-small?  Like the one here https://github.com/huseinzol05/Malaya/tree/master/pretrained-model/t5
@ThilinaRajapakse ?

**Comment by ThilinaRajapakse** [comment]
I haven't tried so I can't say for sure. The current `LanguageModeling` task in Simple Transformers doesn't support T5 though.
