### ISSUE TITLE
Sentence pair classification model 

### ISSUE THREAD

**Issue by 53X** [ThilinaRajapakse/simpletransformers#720]
**Describe the bug**
I am trying to train as aspect level sentence classifcation model using the sentence pair classifcation framework on own private data. I ensured to follow the minimal start for sentence pair classifcation. But I get the folowing error:

AttributeError: 'InputExample' object has no attribute 'tokens_b'

Please find the screenshot here :

![image](https://user-images.githubusercontent.com/36399781/93574390-fac78d00-f9b5-11ea-9be3-2cd069b8c7a4.png)

This is on a p3.8x large AWS instance

**Comment by 53X** [comment]
The text_b column in my particular case is mostly one single word ( or very very short phrase , maybe like 2-3 words at max )

**Comment by ThilinaRajapakse** [comment]
Does the minimal start itself work, or does it throw the same error?

**Comment by 53X** [comment]
The minimal itself throws an error

**Comment by 53X** [comment]
I rechecked for errors from my end as I thought that this might be happening because of rows having empty string in the desired columns .... but i couldnt find any

**Comment by 53X** [comment]
Was able to solve the issue , some way the` classification_utils.py` file got changed at` line 117 ` .

Hence closing this
