### ISSUE TITLE
NER eval_loss unexpected

### ISSUE THREAD

**Issue by moritzblum** [ThilinaRajapakse/simpletransformers#721]
training_progress_scores.csv show unexpected values. When the `eval_loss` starts to increase again, `precision`, `recall` and `f1_score` continue getting better. This should not happen, since both seem to be evaluated on the same evaluation data. The result in the end looks good, so I guess there is an issue concerning the computation of the `eval_loss`.

The `"roberta"` model was just trained using data following the BIO schema. 

<img width="895" alt="Screen Shot 2020-09-18 at 12 01 56 PM" src="https://user-images.githubusercontent.com/31183934/93585212-c1d3ec00-f9a6-11ea-9104-44a7d8d34eac.png">

**Comment by ThilinaRajapakse** [comment]
Could this be related to #714 ?

**Comment by moritzblum** [comment]
Possibly, but because of #714 precision/recall/f1 should actually be less than it is. But I looked at the predictions, and they seem to match the reached precision/recall/f1. 

Probably the eval_loss is calculated differently than the train_loss?

**Comment by ThilinaRajapakse** [comment]
The loss is computed the same way for both train and eval, although there might have been a difference in how they were recorded. Is this issue still present? I switched around a few things which may have helped.

**Comment by moritzblum** [comment]
Thank you for your help. Your code definitely looks correct, I checked it as well. Now I switched to my own implementations with `huggingface transformers` and experience the same effect among multiple tasks. Unfortunately I have not yet found the reason why.
