### ISSUE TITLE
ImportError: Cannot import BertForPreTrained

### ISSUE THREAD

**Issue by seyonechithrananda** [ThilinaRajapakse/simpletransformers#727]
I just wanted to notify the author of this library (@ThilinaRajapakse) regarding a bug I came across in importing ClassificationModel from a Google Colab instance. When using the newset version of transformers (3.2.0) and simpletransformers (0.48.3), it throws an import error when the following import is run:

`from simpletransformers.classification import ClassificationModel` 

This issue is resolved when I move back to v3.10 of transformers and v0.48.1 of simpletransformers (for good measure, just to go back to my older version in my previous Colab notebooks). It may be worth checking out what changes were made in the v3.2.0 release of transformers to fix this bug to allow for supporting the newest version of transformers in this library.

Thanks!

**Comment by wenqinglim** [comment]
@seyonechithrananda thank you, I was facing this problem and your comment helped. Here is what I ran in colab:

**Comment by epcpu** [comment]
I'm struggling with the same issue. Unfortunately, moving back to transformers==3.1.0 and simpletransformers=0.48.1 does not solve my problem. any help will be appreciated.

**Comment by ThilinaRajapakse** [comment]
Should be fixed in `0.48.4`. Please let me know if any other incompatibilities pop up.

**Comment by seyonechithrananda** [comment]
Sounds good, I'll test the 0.48.4 version and let you know
