### ISSUE TITLE
XLNet's warnings. Some weights of the model checkpoint at xlnet-base-cased were not used when initializing XLNetForQuestionAnswering: [‘lm_loss.weight’, ‘lm_loss.bias’]

### ISSUE THREAD

**Issue by nxnixin** [ThilinaRajapakse/simpletransformers#729]
**Describe the bug**
A clear and concise description of what the bug is. Please specify the class causing the issue.

Hi, Thanks for your amazing library first. I got a warning as follows:

> Some weights of the model checkpoint at xlnet-base-cased were not used when initializing XLNetForQuestionAnswering: [‘lm_loss.weight’, ‘lm_loss.bias’]
> 
> This IS expected if you are initializing XLNetForQuestionAnswering from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
> This IS NOT expected if you are initializing XLNetForQuestionAnswering from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
> Some weights of XLNetForQuestionAnswering were not initialized from the model checkpoint at xlnet-base-cased and are newly initialized: [‘start_logits.dense.weight’, ‘start_logits.dense.bias’, ‘end_logits.dense_0.weight’, ‘end_logits.dense_0.bias’, ‘end_logits.LayerNorm.weight’, ‘end_logits.LayerNorm.bias’, ‘end_logits.dense_1.weight’, ‘end_logits.dense_1.bias’, ‘answer_class.dense_0.weight’, ‘answer_class.dense_0.bias’, ‘answer_class.dense_1.weight’]
> You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

I got this warning for XLNet’s QuestionsAnsweringModel when I use the pretrained xlnet-base-cased model. It was working well probably 2 months ago and I didn’t change anything.

When I ignore this warning, the training loss will be too huge in each epoch.

I want to know are there any solutions or reasons now? I am appreciate anyone's possible help or suggestions.

**To Reproduce**

1. load the model before training:

```
from simpletransformers.question_answering import QuestionAnsweringModel
import torch

train_args = {
‘learning_rate’: 3e-5,
‘num_train_epochs’: 3, ###
‘max_seq_length’: 384,
‘doc_stride’: 384,
‘max_query_length’: 64,
‘max_answer_length’:100,
‘n_best_size’:3,
‘early_stopping_consider_epochs’: True,
‘overwrite_output_dir’: False, #####
‘reprocess_input_data’: False,
‘gradient_accumulation_steps’: 8,
‘use_early_stopping’: True,
‘evaluate_during_traing’: True,
‘save_eval_checkpoints’ : True,
‘save_model_every_epoch’: True,
‘save_steps’: 2000,
‘n_gpu’: 2, ###
‘train_batch_size’: 4,
‘dataloader_num_worker’: 8, ###
‘use_early_stopping’: True,
‘early_stopping_delta’: 0.01,
‘early_stopping_metric’: ‘eval_loss’,
‘early_stopping_metric_minimize’: True,
‘early_stopping_patience’: 3,
‘evaluate_during_training_steps’: 1000,
‘mem_len’: 1024, ### Xlnet

}

cuda_available = torch.cuda.is_available()

model = QuestionAnsweringModel(‘xlnet’, ‘xlnet-base-cased’, args=train_args, use_cuda=cuda_available)
```

After this, I got that warnings.

2. the code to save the model after training:
`model.train_model(train_data, output_dir="/media/bizon/DATA/QA/model_saved")`

3. the code using to load the saved model:
`model = QuestionAnsweringModel(‘xlnet’, ‘/content/drive/MyDrive/transformers/apex/outputs/checkpoint-24435-epoch-3’)`

It is from my previous working code, due to the current XLNet doesn’t work.

**Desktop (please complete the following information):**

-The environment I am using:

Ubuntu 18.04.3 LTS

-The libraries I used are:
Name: transformers
Version: 3.1.0

Name: simpletransformers
Version: 0.48.3

Name: torch
Version: 1.5.0

**Comment by nxnixin** [comment]
I got an answer for the similar issue someone had

> Okay, so after some digging:
> 
> This is expected behavior
> When you run load_model you re-load the original pretrained bert-base-uncased because you reinitialize the model. This line is run again: BertForSequenceClassification.from_pretrained(‘bert-base-uncased’
> The message that you get is because “bert-base-uncased” contains the weights for BertForPretraining, which has the following submodules:

[https://github.com/huggingface/transformers/blob/28cf873036d078b47fb9dd38ac3421a7c874da44/src/transformers/modeling_bert.py#L858-L865](url)
```
class BertForPreTraining(BertPreTrainedModel):
    def __init__(self, config):
        super().__init__(config)

        self.bert = BertModel(config)
        self.cls = BertPreTrainingHeads(config)

        self.init_weights()
```

> The warning that you get tells you that the original model has weights (heads) that BertForSequenceClassification does not have. The final classifier layer in BertForSequenceClassification is randomly initialized and does not get the weights from the pretrained modelùs seq_relationship. As said, this warning will return every time you use BertForSequenceClassification.from_pretrained("bert-base-uncased").
> 
> The correct way, and most pythonic, is to subclass the PreTrainedModel and use the save_pretrained and load_pretrained methods directly.

Could someone explain how to do it using simpletransformers? Appreciate any possible suggestions.

**Comment by ThilinaRajapakse** [comment]
Getting the warning when loading the pre-trained model (`xlnet-base-cased`) is expected. The warning started appearing recently because it was only added recently. The underlying behaviour didn't change.

If the warning is given even when you load a fine-tuned model (e.g. `model = QuestionAnsweringModel("xlnet", "outputs")), then something is going wrong. Does this happen too?

**Comment by nxnixin** [comment]
> Getting the warning when loading the pre-trained model (`xlnet-base-cased`) is expected. The warning started appearing recently because it was only added recently. The underlying behaviour didn't change.
> 
> If the warning is given even when you load a fine-tuned model (e.g. `model = QuestionAnsweringModel("xlnet", "outputs")`), then something is going wrong. Does this happen too?

Thanks for your reply first.

Firstly, the same code works well (especially without huge running loss) on (even fine-tuned model):

Ubuntu 18.04.3 LTS
Name: transformers
Version: 2.9.1

Name: simpletransformers
Version: 0.28.8

Name: torch
Version: 1.5.0
+++++++++++++++++
When:
1. Ubuntu 18.04.3 LTS
Name: transformers
Version: 3.2.0 or 3.1.0

Name: simpletransformers
Version: 0.48.6 or 0.48.3

Name: torch
Version: 1.5.0

I got the error:
```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-11-5033bf56d940> in <module>
----> 1 model.train_model(train_data, output_dir= "/media/bizon/DATA/QA/model_saved")

~/anaconda3/lib/python3.8/site-packages/simpletransformers/question_answering/question_answering_model.py in train_model(self, train_data, output_dir, show_running_loss, args, eval_data, verbose, **kwargs)
    318                 train_examples = train_data
    319 
--> 320             train_dataset = self.load_and_cache_examples(train_examples)
    321 
    322         os.makedirs(output_dir, exist_ok=True)

~/anaconda3/lib/python3.8/site-packages/simpletransformers/question_answering/question_answering_model.py in load_and_cache_examples(self, examples, evaluate, no_cache, output_examples)
    262         if output_examples:
    263             return dataset, examples, features
--> 264         return dataset
    265 
    266     def train_model(

UnboundLocalError: local variable 'dataset' referenced before assignment
```
I have no idea why this new error happened.

2. I have to move to Googlecolab
Name: transformers
Version: 3.2.0

Name: simpletransformers
Version: 0.48.6

train a new model or continue with a fine-tuned model:
I got the same issue as before, the running loss becomes huge. But it didn't happen in the transformer (2.9.1) and simpletransformers (0.28.8).

![image](https://user-images.githubusercontent.com/42440514/94420133-00765d00-0184-11eb-8ca6-5e62f11c3ee8.png)

I don't know the reason. But there isn't that warning on the fine-tuned model.

Thanks for your further help in advance.

**Comment by ThilinaRajapakse** [comment]
I am not sure what's going on either. It doesn't seem to affect `ClassificationModel` which is even weirder. Did you manage to find anything else on this issue?

**Comment by nxnixin** [comment]
Unfortunately, have not found any new solutions or reasons yet. Hopefully, you could provide some solutions or suggestions.

**Comment by ShivamSharma1997** [comment]
@ThilinaRajapakse @nxnixin Hey, did you find the reason for this. I am facing the same warnings when I am predicting using MultiLabelClassification model

**Comment by ThilinaRajapakse** [comment]
I haven't. 😞

**Comment by abdurrahmanazami** [comment]
H
![Screenshot 2023-08-01 105550](https://github.com/ThilinaRajapakse/simpletransformers/assets/49465416/62f1323e-28f7-404f-b5f6-946c948e355c)
ow to solve these issues.
