### ISSUE TITLE
Checkpoint averaging

### ISSUE THREAD

**Issue by sarapapi** [ThilinaRajapakse/simpletransformers#730]
**Is your feature request related to a problem? Please describe.**
Is it possible to add checkpoint weight averaging to the library?
It was described by Attention Is All You Need paper in which the authors use a checkpoint averaging for the 5-20 last checkpoints. 

**Describe the solution you'd like**
Add this functionality to the generation (prediction) step, specifying checkpoint_averaging True/False, how many checkpoints or which one maybe.

**Describe alternatives you've considered**
I think that fairseq implements something similar.

**Comment by ThilinaRajapakse** [comment]
I'll add this as a feature request but I don't think I will be implementing this in the near future. It doesn't seem to be used in the more recent models (going off the top of my head).

**Comment by sarapapi** [comment]
> I'll add this as a feature request but I don't think I will be implementing this in the near future. It doesn't seem to be used in the more recent models (going off the top of my head).

Thank you in any case!

**Comment by ThilinaRajapakse** [comment]
If anyone would like to submit a PR, I'm more than happy to take a look though. 😄
