### ISSUE TITLE
Extract Embeddings from LanguageModelingModel

### ISSUE THREAD

**Issue by BlagaVic** [ThilinaRajapakse/simpletransformers#731]
Is there any way to extract embeddings from a `LanguageModelingModel` like there is for a `ClassificationModel`?

I have trained an `ELECTRA`-based `LanguageModelingModel` and would like to extract embeddings for my data. Is there an equivalent to the `ClassificationModel`'s `predict` function with the `LanguageRepresentationModel`?

**Comment by ThilinaRajapakse** [comment]
You can load the trained model as a `ClassificationModel` directly. Any model trained with `LanguageModelingModel` can be loaded into any other type of model provided the `model_type` is supported.

**Comment by BlagaVic** [comment]
Works, thank you!
