### ISSUE TITLE
Use ONXX

### ISSUE THREAD

**Issue by balajib5497** [ThilinaRajapakse/simpletransformers#732]
I'm using 'bert' MultilabelClassfication. I'd like to try out ONNX. Could you please provide some information on how to migrate the saved model into onnx format.

**Comment by manueltonneau** [comment]
I found the two blog posts they published with Microsoft on both how to [convert/optimize your BERT model to ONNX ](https://medium.com/microsoftazure/accelerate-your-nlp-pipelines-using-hugging-face-transformers-and-onnx-runtime-2443578f4333) and [how to include quantization in the process](https://medium.com/microsoftazure/faster-and-smaller-quantized-nlp-with-hugging-face-and-onnx-runtime-ec5525473bb7) helpful.

**Comment by manueltonneau** [comment]
Unfortunately, you won't be able to use simpletransformers (as of now, in my understanding) to do inference with onnx models. I wrote [this code](https://github.com/spfraib/twitter/blob/master/code/2-twitter_labor/4-inference_200M/bert_models/onnx_model_conversion.py) to convert, optimize and quantize BERT models (based on the blog posts) and then [this one](https://github.com/spfraib/twitter/blob/master/code/2-twitter_labor/4-inference_200M/bert_models/inference_ONNX_bert_100M_random.py) for inference. Not production code at all but maybe it can help.

**Comment by manueltonneau** [comment]
You will find more information in [the documentation ](https://simpletransformers.ai/docs/tips-and-tricks/#onnx-support-beta). FYI, ONNX seems to be in beta version for now.
