### ISSUE TITLE
Does this library support building models using plain vanilla transformers?

### ISSUE THREAD

**Issue by zeeshansayyed** [ThilinaRajapakse/simpletransformers#734]
Does it support sequence tagging using standard non-pretrained transformer encoders? I want to create a quick baseline before using the bigger models.

**Comment by ThilinaRajapakse** [comment]
You can use the `LanguageModeling` model for that ([docs](https://simpletransformers.ai/docs/lm-model/#language-model-training-from-scratch)).

You can create the architecture you want and then use the `save_model()` method to save it. You can then load the model as a NER model.

```python
from simpletransformers.language_modeling import (
    LanguageModelingModel,
)
from simpletransformers.ner import NERModel


model = LanguageModelingModel(
    "bert", None
)

model.save_model(model=model, output_dir="outputs")

model = NERModel("bert", "outputs")
```
