### ISSUE TITLE
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

### ISSUE THREAD

**Issue by MrRace** [ThilinaRajapakse/simpletransformers#737]
I follow the example in `https://github.com/ThilinaRajapakse/simpletransformers/blob/master/examples/hyperparameter%20tuning/sweeps.py`

When use wandb's sweep to do hyperparameter searching. I specify one GPU with `CUDA_VISIBLE_DEVICES=0` to run script.
Comes the error：
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/wandb/wandb_agent.py", line 64, in _start
    function()
  File "hyperparameter_simpletransformers.py", line 272, in train
    sweep_config=wandb.config,
  File "/opt/conda/lib/python3.7/site-packages/simpletransformers/classification/multi_label_classification_model.py", line 146, in __init__
    model_name, config=self.config, pos_weight=torch.Tensor(self.pos_weight).to(self.device), **kwargs
  File "/opt/conda/lib/python3.7/site-packages/torch/cuda/__init__.py", line 185, in _lazy_init
    "Cannot re-initialize CUDA in forked subprocess. " + msg)
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

```
Then I add `torch.multiprocessing.set_start_method('spawn')` to my script，it can run ,however it keep the same frame for such long time, no any new response：
```
opt/conda/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 15 leaked semaphores to clean up at shutdown?, ?it/s]
  len(cache))

```
![image](https://user-images.githubusercontent.com/10300313/94361789-85f8ff00-00e9-11eb-8eab-c431949f7fce.png)

Therefore I guess there must be something wrong.  What  can I do next? It seems been stuck somewhere. and  not occupy GPU.

**Comment by MrRace** [comment]
I am confused with the problem for a few days~~~~

**Comment by ThilinaRajapakse** [comment]
Unfortunately, this is a W&B issue ([link](https://docs.wandb.com/sweeps/python-api#wandb-agent)). Right now, the workaround is to use the configuration file method ([link](https://docs.wandb.com/sweeps/quickstart#2-sweep-config)).
