### ISSUE TITLE
Assistance with code for accessing the encoder and the decoder? 

### ISSUE THREAD

**Issue by Hellisotherpeople** [ThilinaRajapakse/simpletransformers#745]
I'm trying to train an auto-encoder using this library and pre-trained transformers for the encoder and decoder. 

So far, I am successfully able to access the encoder and the decoder models separately and independently, but I have not figured out how to manually encode a sentence with the encoder, and pass that output directly to the decoder for decoding. I can manually encode my sentence, but passing that output to the decoder gave me weird shape errors which I did not know how to resolve. 

I need to do this manually (rather than run the .generate command) because I plan to project the encoded sentences using PCA/UMAP, and I plan to use the inverse transform method to take a (user provided) UMAP/PCA coordinates and turn them into an encoded vector, which I would then decode to generate a non-existant document. Examples of doing exactly this exist for images (within UMAPs documentation on inverse transformers) and even in the sklearn documentation (the eigenfaces examples), so I know it's super easy to do with images. It should be similarly easy with text... 

Can someone post a code snippet of 
1. Manually encoding a sentence using just the encoder portion of an encoder/decoder model 
2. Taking the encoding produced by the encoder and decoding them using the decoder

**Comment by Hellisotherpeople** [comment]
Code I have right now, I can get a list of my encoded vectors - how do I get these properly into the decoder? 

```python

my_debate_data = pd.read_csv("/home/lain/lain/CX_DB8/card_data/debateall.csv")


debate_document = my_debate_data["Full-Document"][0:N_F]
inputs = pd.DataFrame(debate_document)
inputs.columns = ['input_text']
inputs["target_text"] = inputs['input_text']
print(inputs)

model.train_model(inputs)


encoder = model.model.encoder
tokenizer = model.encoder_tokenizer

def get_vector_from_trained_model(sentence):
    input_ids = torch.tensor(tokenizer.encode(sentence)).unsqueeze(0).to(device='cuda')
    outputs = encoder(input_ids) ##Gets all hidden states, outputs [0] is the final head
    return outputs[0].to("cpu").data.numpy()


list_of_doc_vectors = []
for doc in inputs["input_text"]:
    encoded_doc = get_vector_from_trained_model(doc[0:200])
    list_of_doc_vectors.append(encoded_doc)

print(list_of_doc_vectors)

```

**Comment by ThilinaRajapakse** [comment]
Getting the tensors into the right shape will be painful but maybe looking at the [generate()](https://github.com/huggingface/transformers/blob/2f34bcf3e7b7f53181367faf7f492905612d205e/src/transformers/generation_utils.py#L111) method might help?
