### ISSUE TITLE
Mismatch between dataset labels and classification labels in ClassificationModel

### ISSUE THREAD

**Issue by Zeraphil** [ThilinaRajapakse/simpletransformers#748]
**Describe the bug**
Hi there, first off, thank you for this excellent wrapper, it has made it very easy for me to get a few experiments started and running without having to dive deep into HuggingFace architectures. I'm currently having a bit of an issue training a bert based classification model with my dataset. I have about 430k entries, evenly distributed amongst 23 classes. I'm having an issue in both CUDA and non cuda torch where the nll_loss function raises an error (in cuda, it's a device side assert), in CPU, it's 

` File "C:\Users\zerap\anaconda3\envs\nlu-nocuda\lib\site-packages\torch\nn\functional.py", line 2218, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
IndexError: Target 13 is out of bounds.`

I understand this to mean that the output tensor is being set to a size (batch_sz, 12), and that there are additional labels out of bounds. I'm not sure why this could be, but I can assert that I've tried another dataset with 40 some classes and I get the exact same error, stating Target 32 is out of bounds.

My current testing environment has pytorch 1.6, cpu only. 

I have set the number of labels manually with model_args.num_labels = number of labels in dataframe, as well as hardcoding them, to no success. The way I have it setup is below 

    num_labels = len(train_df['labels'].unique())

    model_args = ClassificationArgs()
    model_args.eval_batch_size = 32
    model_args.evaluate_during_training = True
    model_args.evaluate_during_training_silent = False
    model_args.evaluate_during_training_steps = -1
    model_args.save_eval_checkpoints = False
    model_args.save_model_every_epoch = False
    model_args.learning_rate = 1e-5
    model_args.manual_seed = 4
    model_args.max_seq_length = 256
    model_args.multiprocessing_chunksize = 3125
    model_args.no_cache = True
    model_args.num_train_epochs = 6
    model_args.overwrite_output_dir = True
    model_args.reprocess_input_data = True
    model_args.train_batch_size = 16
    model_args.gradient_accumulation_steps = 2
    model_args.output_dir = "output"
    model_args.best_model_dir = "output/best_model"
    model_args.use_cached_eval_features = True
    model_args.num_labels = num_labels
    model_args.fp16 = False
    
    model = ClassificationModel("bert", "bert-base-multilingual-cased", use_cuda=False, args=model_args)

Is there something I'm missing?

**Desktop (please complete the following information):**
 - Windows 10
- Ryzen 3950X

**Comment by ThilinaRajapakse** [comment]
The `num_labels` parameter has to be provided to the `ClassificationModel` itself. ([docs](https://simpletransformers.ai/docs/classification-models/#specifying-the-number-of-classeslabels)

E.g.:

```python
model = ClassificationModel("bert", "bert-base-multilingual-cased", num_labels=40, args=model_args)
```

**Comment by Zeraphil** [comment]
woops! Thanks, this worked!
