### ISSUE TITLE
error using multilingual xlm models and xlmroberta

### ISSUE THREAD

**Issue by stefdam** [ThilinaRajapakse/simpletransformers#749]
Hello , 

I am not sure if this is a bug or just these models are not yet supported. 

I tried binary classification using class ClassificationModel and I encoutered  the following errors:

1) keyerror using 'xlmroberta' as model type 

2) unexpected keyword using xlm multilingual models like xlm-mlm-xnli15-1024 

"__init__() got an unexpected keyword argument 'sliding_window' "

**Comment by ThilinaRajapakse** [comment]
`xlmroberta` is supported for Classification. `sliding_window` is a model `args`, which is why you get that error.

```python
model_args = ClassificationArgs()
model_args.sliding_window = True
```
