### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by QAQOAO** [ThilinaRajapakse/simpletransformers#75]
When I tried to load any large model like 'roberta-large' using google colab , it always showed this error.

I don't know how to debug this error and wonder whether it's the problem of code or the environment.

If it's not caused by code, what environment should I have to run these "large" models? Maybe use google cloud platform?

**Comment by penatbater** [comment]
How much memory was used/left over? This happens to me whenever I train one model, and I don't restart my VM and train another model. I'm not sure how much memory is required as I'm also using GCP. Do note that Roberta already has significantly more parameters than bert-base. 

If google colab notes that you're oom, sometimes it lets you start a new instance with more memory (from 12gb default to about 25gb).

**Comment by ThilinaRajapakse** [comment]
Yeah, the 11 gigs on Google Colab probably isn't enough to run the larger models. It's an issue with the environment, unfortunately. Penatbater is also right to note that reusing the model without restarting the instance tends to increase the VRAM usage. The model being overwritten or deleted doesn't seem to release the memory, at least not quickly enough to matter.

I can check how much memory is consumed when using the roberta-large model later and let you know. You can definitely run them on Google cloud if you get one of the bigger GPUs.

**Comment by QAQOAO** [comment]
I somehow manage to make colab RAM double to 25.51GB and reset all runtimes before running "large" model. However, this error still emerges. So is RAM really the issue? Also, what environment (like GPU, RAM ...) should I use to run large on google could?

**Comment by ThilinaRajapakse** [comment]
Colab will increase RAM if you run out of RAM. But, more RAM only helps you load bigger _datasets_. CUDA memory is the amount of VRAM on the GPU. That is what you need to run bigger models. I don't think Colab increases that.

I'm not too familiar with the different cloud offerings but you'll want one with more GPU VRAM. Make sure that it's the memory on the GPU and not the system RAM.

**Comment by tsavinho** [comment]
Is there any possibility to remove the model from memory after a successful evaluation / prediction? It would make it easier to compare the different models (like BERT, XLNet, XLM etc.) against each other.

**Comment by ThilinaRajapakse** [comment]
As far as I can tell, this is a Python/Pytorch issue. Nothing short of terminating the python session seems to resolve the issue. The workaround that I use is to start the Python script from a bash script.

**Comment by penatbater** [comment]
Consider using
del model_name
Or sth like that.

And/Or
Import gc
gc.collect()

Maybe that can help remove the model from memory.

**Comment by ThilinaRajapakse** [comment]
Doesn't seem to work. Neither does clearing CUDA cache.

**Comment by mabu-dev** [comment]
I'm hoping there is a fix for this?

**Comment by ThilinaRajapakse** [comment]
Nope, as this isn't something that can be fixed on my end. I'm still using bash scripts to sequentially execute python scripts (with command line arguments if necessary) when I need to train a bunch of models one after the other.

**Comment by ZahraAbbasiantaeb** [comment]
Hi, I have the same problem while I did not receive this Error on Colab about 2 weeks ago and It used to work well, but now even when I try to load the base models of BART and T5 I receive this error. 

`RuntimeError: CUDA out of memory. Tried to allocate 96.00 MiB (GPU 0; 11.17 GiB total capacity; 10.61 GiB already allocated; 3.81 MiB free; 10.72 GiB reserved in total by PyTorch)`

Is there any problem with the version of the libraries on Colab, as I think the version of some libraries has been changed on Colab?

**Comment by ThilinaRajapakse** [comment]
Might be a Colab issue if you get this even on your first training run with a T5 model. By first training run, I mean when you instantiate a model and run `train_model()` for the first time.

Locally, `t5-base` uses about 3 GB of GPU VRAM.
