### ISSUE TITLE
max_seq_length in model args might not work

### ISSUE THREAD

**Issue by BaoshengHeTR** [ThilinaRajapakse/simpletransformers#752]
**max_seq_length in model args is not assigned to model.tokenizer**
`max_seq_length` used in defining a model by `ClassificationModel(model_type, model_name, args = {'max_seq_length':128})` seems not restrict the input length.

**for example**
`model = ClassificationModel('roberta', 'roberta-base', use_cuda=False, args={'max_seq_length':128})`
Expected to see:
`model.tokenizer.model_max_length = 128`
Actually we see:
```
>>> model.tokenizer.model_max_length
512

```
Is this a supposed behavior?

**Comment by ThilinaRajapakse** [comment]
The inputs are truncated internally to `max_seq_length`. You can double-check this by looking at the GPU memory consumption at different lengths.

**Comment by BaoshengHeTR** [comment]
> The inputs are truncated internally to `max_seq_length`. You can double-check this by looking at the GPU memory consumption at different lengths.

Great. Thanks for your response. Just feel keeping the consistency might be more intuitive.

**Comment by ThilinaRajapakse** [comment]
I agree. However, this wasn't present in the Hugging Face library at the time (the truncation done here is essentially the original implementation by Hugging Face). Unless something breaks compatibility or results in different behaviour, I simply don't have the time to update all the Hugging Face changes.
