### ISSUE TITLE
[Debate] Using simpletransformers at work

### ISSUE THREAD

**Issue by pablonm3** [ThilinaRajapakse/simpletransformers#755]
I just used simpletransformers on a project for a client, the usecase is a script that makes text classification by batch. The results are great, I could reach a very high accuracy in no time! But wonder wether I could trust the library for production usecases and not just for research.
Are you guys using simpletransformers at work? would love to hear your usecases and opinions!

**Comment by ThilinaRajapakse** [comment]
I do, but my case is obviously going to be unique. Broadly speaking, if you are getting the results you expect and are happy with it, you can use it in production. But, it might be safer to fix the library versions for simple transformers, transformers, and tokenizers to make sure that things don't break with future updates.

Also, the speed of updates and support I can provide will vary with how busy I am as I am only one guy!

**Comment by rrajp** [comment]
I am using this for production specially in multi-processing env where high throughput is 1st priority along with accuracy. But I face issue with inference speed, I use larger inference batch so my service runs like driving on bumpy road, not so smooth. @ThilinaRajapakse  Can I change the batch size in model args post training to improve on speed? I haven't tried it yet.

**Comment by ThilinaRajapakse** [comment]
You can change the batch size after training the model. It'll use whatever value you set when you load the model.
