### ISSUE TITLE
Bug: Running loss for ALBERT with multiple GPUs throws error

### ISSUE THREAD

**Issue by CorwinTanner** [ThilinaRajapakse/simpletransformers#76]
First off, thank you. I really appreciate the work you've put into this library.

**Describe the bug**
Classification with ALBERT on multiple GPUs causes the follow error when running loss is enabled:
```
~/anaconda3/envs/transformers/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py in train(self, train_dataset, output_dir, show_running_loss, eval_df)
    261                 loss = outputs[0]
    262                 if show_running_loss:
--> 263                     print("\rRunning loss: %f" % loss, end="")
    264 
    265                 if args['n_gpu'] > 1:

ValueError: only one element tensors can be converted to Python scalars
```

**To Reproduce**
```python
model = ClassificationModel('albert', 'albert-xxlarge-v1', args={'n_gpu': 8)
model.train_model(train_df)
```

**Workaround**
Disabling running loss works as expected:
```python
model.train_model(train_df, show_running_loss=False)
```

**Comment by ThilinaRajapakse** [comment]
Can you try it now? I think the issue was because the print statement came before averaging the losses. But I'm not sure if the tensor needs to be taken off the GPU first, and I don't have multi-GPUs to test atm.

#68

**Comment by CorwinTanner** [comment]
That seems to have resolved the issue. Thanks!

**Comment by ThilinaRajapakse** [comment]
Great! No problem and thank you for the detailed bug report!
