### ISSUE TITLE
training model with mixed input

### ISSUE THREAD

**Issue by CiTRuS93** [ThilinaRajapakse/simpletransformers#766]
hi everyone!

I have data with both text and integers, and I want to build a model that relies on all the data not just the text.
How should I do it with simpletransformers?

thanks in advance!

**Comment by guy-mor** [comment]
As far as I know it is not possible using the base model classes that simpletransformers uses. You need to write a custom model that incorporates the huggingface transformer with the other data and decide on the logic of the combination yourself. I just did something similar for categorical data.
