### ISSUE TITLE
Adding ElectraForTextRepresentation

### ISSUE THREAD

**Issue by WeberJulian** [ThilinaRajapakse/simpletransformers#768]
Hi,
Is there a technical reason why there is no support for Electra in the RepresentationModel or anything other than GPT2, BERT and ROBERTA for that matter ? thanks

**Comment by Zhylkaaa** [comment]
Hi, I believe there is no reason for it, because electra is more about pre-training method not new architecture, but maybe I am wrong 🤷‍♂️. 
I guess somebody just must add this. (btw. if you would like to do this you can consider fixing this issue #571 as well)
