### ISSUE TITLE
File error in MultiLabelClassificationModel when save options are toggled

### ISSUE THREAD

**Issue by abhinavg97** [ThilinaRajapakse/simpletransformers#773]
**Describe the bug**
A clear and concise description of what the bug is. Please specify the class causing the issue.

When all the available intermediate saving is toggled off, the model throws a File handling error. 

**To Reproduce**

model = MultiLabelClassificationModel('distilbert', 'distilbert-base-uncased-distilled-squad',
                                      use_cuda=False, num_labels=num_classes,
                                      args={'n_gpu': 0,
                                            'no_cache': True,
                                            # 'no_save': True,
                                            'save_eval_checkpoints': False,
                                            # 'save_model_every_epoch': False,
                                            'save_optimizer_and_scheduler': False,
                                            'reprocess_input_data': True,
                                            'overwrite_output_dir': True,
                                            'evaluate_during_training': True,
                                            'evaluate_during_training_verbose': True,
                                            'evaluate_each_epoch': True,
                                            'use_early_stopping': True,
                                            'early_stopping_consider_epochs': True,
                                            'tensorboard_dir': 'lightning_logs/baseline'})

Uncomment the above line and run the model.

**Expected behavior**

The model runs and exits gracefully.

**Screenshots**

![Screenshot from 2020-10-16 16-27-59](https://user-images.githubusercontent.com/26171694/96226016-f00c1200-0fcc-11eb-89b8-964c00d669fd.png)

**Desktop (please complete the following information):**
 - OS
 - simpletransformers version:   0.48.14
**Additional context**

**Comment by null-id** [comment]
I also face with a similar issue to run multilabelclassificationmodel, but not exactly same:

```bash
OSError: [Errno 24] Too many open files
```

**Comment by ThilinaRajapakse** [comment]
The provided code runs without any error for me in the latest version. Is this specific to `0.48.14`?

**Comment by null-id** [comment]
Yeah, I find the default cpu process number is too many (default is cpu core number minus 2, but I have a server that has tens of cpus), I decreased the number and it works ok now. @ThilinaRajapakse
