### ISSUE TITLE
Error loading roberta-base-openai-detector for multiclass with num_labels argument

### ISSUE THREAD

**Issue by kskarakostas** [ThilinaRajapakse/simpletransformers#779]
**Describe the bug**
When trying to load the roberta-base-openai-detector flavor of roberta with num_labels argument RunTimeError raises

**To Reproduce**
```
from simpletransformers.classification import ClassificationModel
model = ClassificationModel(
    "roberta", "roberta-base-openai-detector",
    num_labels=12
)
```

Error:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-9-d660a9c45c91> in <module>()
     32 model = ClassificationModel(
     33     "roberta", "roberta-base-openai-detector",
---> 34     num_labels=12
     35 )

1 frames
/usr/local/lib/python3.6/dist-packages/transformers/modeling_utils.py in from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
   1045                 raise RuntimeError(
   1046                     "Error(s) in loading state_dict for {}:\n\t{}".format(
-> 1047                         model.__class__.__name__, "\n\t".join(error_msgs)
   1048                     )
   1049                 )

RuntimeError: Error(s) in loading state_dict for RobertaForSequenceClassification:
	size mismatch for classifier.out_proj.weight: copying a param with shape torch.Size([2, 768]) from checkpoint, the shape in current model is torch.Size([12, 768]).
	size mismatch for classifier.out_proj.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([12]).
```

**Desktop (please complete the following information):**
 Google Colab with GPU support

**Comment by ThilinaRajapakse** [comment]
If it's a model fine-tuned for a 2 label task, then it cannot be loaded for a different number of labels (i.e. the output shape can't change after the model is fine-tuned).

**Comment by roboserg** [comment]
> If it's a model fine-tuned for a 2 label task, then it cannot be loaded for a different number of labels (i.e. the output shape can't change after the model is fine-tuned).

I have the same problem as OP. Does simpletransformers allow for an easy way to remove the last layers of the pre-trained model and finetune it? I would think it should do it automatically when using pre-trained models.

**Comment by ThilinaRajapakse** [comment]
It will do it automatically with pre-trained models. But, that doesn't work for models with task-specific heads.

**Comment by roboserg** [comment]
> It will do it automatically with pre-trained models. But, that doesn't work for models with task-specific heads.

How do I know which models have a "task-specific head"? Also, what do you mean by a "task-specific head"? Something like NER, summarization etc? For example, I am using xlm-roberta-large-finetuned-conll03-german that is a NER model to do my own NER 
 fine-tuning for  my 3x  custom labels. But I get the error, the output shape is 9, but I am giving it 3 labels, instead of 9. But shouldn't simpletransformer remove the last layer and create a layer with 3 outputs? I am very confused.

**Comment by ThilinaRajapakse** [comment]
Yes, a model with a task-specific head is one that has been fine-tuned on a task like NER. For example, `xlm-roberta-large-finetuned-conll03-german` has been fine-tuned on (I assume) a German CoNLL dataset. As that task has 9 labels, you can't load that fine-tuned model for a task with a different number of labels. Simple Transformers will not change the last layer as it has already been trained.

It will automatically add a final layer with 3 output neurons if you start from `xlm-roberta-large`, as that model has not been fine-tuned on a specific task.
