### ISSUE TITLE
Save model for tensorflow serving

### ISSUE THREAD

**Issue by elixium** [ThilinaRajapakse/simpletransformers#78]
Hello,
Thanks for the library. I tried your Multi label classification. I trained it with my data. It worked very accurate and fast. Now i want to use this model with tensorflow. I am new on pytorch and i looked some tutorials. As i understand i need to save model then convert to Onnx then to tensorflow. So I tried to save model first but it gave me this error;
```
AttributeError                            Traceback (most recent call last)
<ipython-input-10-4f1e1257e6e8> in <module>()
      1 
----> 2 torch.save(model.state_dict(), 'output/multilabel.pth')

AttributeError: 'MultiLabelClassificationModel' object has no attribute 'state_dict'
```

How can i save the model and export to onnx?

**Comment by ThilinaRajapakse** [comment]
I haven't tried exporting to onnx, but to save the state_dict you can use `torch.save(model.model.state_dict())`.

**Comment by vidhig** [comment]
@elixium were you able to use tensorflow serving?
