### ISSUE TITLE
Fine-tuning with Language Modeling

### ISSUE THREAD

**Issue by ChenTao98** [ThilinaRajapakse/simpletransformers#780]
I trained the model with Language Modeling(bert) by the code in [doc](https://simpletransformers.ai/docs/lm-minimal-start/).
If train with 1w samples, it will work well. However, if I train with 1000w samples, it will crash.
Anyone know how to train with a lot of samples?

**Comment by ThilinaRajapakse** [comment]
I'm not sure what "1w" and "1000w" are.

What is the error that you get when it crashes?

**Comment by ChenTao98** [comment]
> I'm not sure what "1w" and "1000w" are.
> 
> What is the error that you get when it crashes?

Sorry. I mean that If train with 10000 samples, it will work well. However, if I train with 10million samples, it will crash and the server will reboot. I I guess if there is too much data causing out of memory.

> I'm not sure what "1w" and "1000w" are.
> 
> What is the error that you get when it crashes?

**Comment by ChenTao98** [comment]
Sorry. I mean that If train with 10000 samples, it will work well. However, if I train with 10million samples, it will crash and the server will reboot. I I guess if there is too much data causing out of memory.

**Comment by ThilinaRajapakse** [comment]
I would guess so!

**Comment by ChenTao98** [comment]
Do you plan to provide a function that like the fit_generator in keras, which may be useful to train with large amounts of data
