### ISSUE TITLE
Using t5 for tuning a language model

### ISSUE THREAD

**Issue by marley1** [ThilinaRajapakse/simpletransformers#781]
Hi, 

Does the `language_modeling.LanguageModelingModel` class support the t5 model?

For example:
`LanguageModelingModel(model_type='t5', 
                      model_name='t5-base',
		      args={...})`

I'm looking to tune this on my training text before training downstream tasks.

Also, am I correct to assume `t5-base` is NOT uncased?

Apologies if my question is documented - I wasn't able to find anything in the docs.

Cheers

**Comment by ThilinaRajapakse** [comment]
T5 is not supported for language modeling atm ([supported models](https://simpletransformers.ai/docs/lm-specifics/#supported-model-types)). 

You are right! `t5-base` is not uncased (it's _cased_).

**Comment by marley1** [comment]
Great, thanks again.
