### ISSUE TITLE
Continue training problem

### ISSUE THREAD

**Issue by zl930216** [ThilinaRajapakse/simpletransformers#783]
1) I set num_train_epochs 10 , save_model_every_epoch false, when training process stops for instance after 6 epochs, there is no model saved at all because model and model_args.json under 'outputs/' only appear after 10 epochs.
Is there a way that can save model of the latest epoch? save_model_every_epoch occupy too much storage.
2) save_model_every_epoch or evaluate_during_training will make sure some model is saved even train process does not finished.
Is it possible to continue training until it reach num_train_epochs set at the first begining? i tried several times but it seems those saved models can not know how many epochs already passed and try to train another 10 epochs according to model_args.json
Waiting for ur response. Thanks a lot!

**Comment by ThilinaRajapakse** [comment]
You should be able to use `save_steps` to save the model at a specified number of training steps.

`number_of_steps_per_epoch = num_samples / train_batch_size`
