### ISSUE TITLE
Start and end postion in question answering task

### ISSUE THREAD

**Issue by nishchay47b** [ThilinaRajapakse/simpletransformers#786]
Hi,
Is there any way to get start and end position of returned answers in question answering task. In [get_best_predictions_extended](https://github.com/ThilinaRajapakse/simpletransformers/blob/bb46cde3643b99b45b335d88f0cdacb85b2a2407/simpletransformers/question_answering/question_answering_utils.py#L1424)  method the start and end index are being used but the predict method does not return these.

**Comment by ThilinaRajapakse** [comment]
Yeah, the `predict()` function doesn't return the indexes. If you need the indexes, maybe you could do a string search for the answer in the context?
