### ISSUE TITLE
Multiprocessing Errors when Training for Multiple Epochs

### ISSUE THREAD

**Issue by thymian-crypto** [ThilinaRajapakse/simpletransformers#789]
**Bug Description**
When training RoBERTa for a text regression task for more than 1 epoch, I get an `OSError` and `ValueError` related to the multiprocessing package (see details below).

**Reproduction Info**
The error persists even when using the exact same code as presented in the [simpletransformers docu](https://simpletransformers.ai/docs/regression/), except for `model_args.num_train_epochs = 4` (and other values `> 0`). I also tried fixing `model_args.process_count` and afterwards `model_args.use_multiprocessing = False`, both to no success. Code runs with no errors when `model_args.num_train_epochs = 1`.

**Setup Details**
- Debian Linux 10
- GTX 1080 Ti / RTX 2080 Ti with CUDA 11
- Python 3.7, PyTorch 1.7.0, simpletransformers 0.48.14.

**Full Error Message**
```
Exception in thread QueueFeederThread:
Traceback (most recent call last):
  File ".../anaconda3/lib/python3.7/multiprocessing/queues.py", line 232, in _feed
    close()
  File ".../anaconda3/lib/python3.7/multiprocessing/connection.py", line 177, in close
    self._close()
  File ".../anaconda3/lib/python3.7/multiprocessing/connection.py", line 361, in _close
    _close(self._handle)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File ".../anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File ".../anaconda3/lib/python3.7/multiprocessing/queues.py", line 263, in _feed
    queue_sem.release()
ValueError: semaphore or lock released too many times
```

Edit: Added GPU, PyTorch, and CUDA specs.

**Comment by Damien-IR** [comment]
Are you using RTX 3000 series graphic cards?
Recently I 've changed my graphic card to RTX 3080, and used pytorch=1.7, cudatoolkit=11.0 version.
When I use ClassificationModel class on Windows 10, although I used very small (few MB) dataset, it forks almost 30 child processes and used 120GB of virtual memory.
Also I tested in Ubuntu 18.04 (WSL and pure ubuntu), same errors that you wrote raised.

**Comment by thymian-crypto** [comment]
Thanks for your reply! I'm operating on a GTX 1080 Ti with Pytorch 1.7.0 and Cuda 11.0. I also have access to a machine with an RTX 2080 Ti and will report back what happens there.

**Comment by Damien-IR** [comment]
I've add "dataloader_num_workers" to 1, then no errors raised on WSL and pure Ubuntu 18.04, 20.04 both.
In windows 10, still uses huge memories.
Don't have any ideas why these errors raised only in torch 1.7 upper version..

**Comment by Junshan233** [comment]
I have another bug.
```
Exception ignored in: <bound method _MultiProcessingDataLoaderIter.__del__ of <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f64aed47358>>                                                                                    
Traceback (most recent call last):
  File "/opt/conda/envs/st/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1203, in __del__
    self._shutdown_workers()
  File "/opt/conda/envs/st/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1177, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/opt/conda/envs/st/lib/python3.6/multiprocessing/process.py", line 122, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
```
But my program continues to run.
I have added `"process_count": 1, "use_multiprocessing": False, "dataloader_num_workers": 1` on model args.

**Comment by thymian-crypto** [comment]
My model also keeps training but the results become nonsensical (correlations close to zero or even negative between predicted labels and ground truth).

**Comment by ThilinaRajapakse** [comment]
This seems to be a Pytorch issue. With `"process_count": 1, "use_multiprocessing": False, "dataloader_num_workers": 1`, Simple Transformers shouldn't even be using Multiprocessing.

> My model also keeps training but the results become nonsensical (correlations close to zero or even negative between predicted labels and ground truth).

Fine-tuning a Transformer model for a high number of steps will lead to this issue. However, it shouldn't happen with like 4 or 5 training epochs.

**Comment by thymian-crypto** [comment]
Thanks for your reply and your work on the library, @ThilinaRajapakse!

> Fine-tuning a Transformer model for a high number of steps will lead to this issue. However, it shouldn't happen with like 4 or 5 training epochs.

 I observe this behavior even when fine-tuning for 2 epochs.

**Comment by ThilinaRajapakse** [comment]
What is the size of the training dataset? Does it happen only for this particular dataset?

**Comment by thymian-crypto** [comment]
Sorry, the error seemed to be partly on my side, @ThilinaRajapakse. Setting `"process_count": 1`, `"use_multiprocessing": False`, **and** `"dataloader_num_workers": 1` did the trick. Simply forgot to set the last argument.

It would be nice to update the docu with this work-around, as (even though not rooted in the simpletransformers lib) the multiprocessing issue seems to concern many users. Thanks again for your awesome work!

**Comment by artificial-cassiano** [comment]
hi,
I'm getting an issue that might be similar to this issue of multiprocessing, when running the [seq2seq minimal start](https://simpletransformers.ai/docs/seq2seq-minimal-start/) 
```sh
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 266, in _feed
    queue_sem.release()
ValueError: semaphore or lock released too many times
```

hardware: RTX3080
torch: 1.7
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.32.00    Driver Version: 455.32.00    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3080    Off  | 00000000:07:00.0 Off |                  N/A |
| 47%   64C    P2    98W / 320W |   9467MiB / 10018MiB |     12%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     32546      C   python3                          9465MiB |
+-----------------------------------------------------------------------------+
```

Any solutions?

**Comment by ThilinaRajapakse** [comment]
> Setting "process_count": 1, "use_multiprocessing": False, and "dataloader_num_workers": 1 did the trick.
Did you try this?

**Comment by chenweilong915** [comment]
Try to set "dataloader_num_workers": 0,
It solved my problem.

**Comment by niclaswue** [comment]
I experienced the same issue with the seq2seq example. Only ```"dataloader_num_workers": 0``` seems to work. When setting ```"dataloader_num_workers": 1``` it takes a bit longer, but I still get the 

> AssertionError: can only join a child process

Hope someone can localize and fix the problem.

**Comment by ThilinaRajapakse** [comment]
`"dataloader_num_workers": 0 ` seems to be the solution to this. It seems to be a Pytorch multiprocessing issue. I'm setting the default value of `dataloader_num_workers` to `0` from the next version.
