### ISSUE TITLE
Is there a way to extract just the model? 

### ISSUE THREAD

**Issue by penatbater** [ThilinaRajapakse/simpletransformers#79]
I'm looking into using this with SHAP for some model interpretability. However I get the error 'ClassificationModel is not subscriptable' (iirc. I'm on mobile now so I can't remember the exact word but it's similar to this), when I use the model object directly with shap. 

Is this possible?

**Comment by ThilinaRajapakse** [comment]
I've never tried it myself, but you should try using `model.model` rather than the ClassificationModel object directly. ClassificationModel is not the transformer model itself. Rather, the transformer model is contained in the `ClassificationModel.model` attribute. Worth a shot!

**Comment by djstrong** [comment]
@penatbater Did you integrate it with SHAP?
