### ISSUE TITLE
Missing cache file in project dir with custom bert model

### ISSUE THREAD

**Issue by ptamas88** [ThilinaRajapakse/simpletransformers#794]
**Describe the bug**
Hi,
I am trying to reproduce the Seq2seq tutorial with a custom hungarian bert based model from huggingface as both for encoder and decoder.
I can create the model variable in jupyter but during the train it looks for some file in the cache_dir (created during model definition)
First I tried the base example with roberta and bert-base and it created a file named:
`roberta-base-bert-base-cased_cached_1282`
But for the custom bert model it is looking for an other file which is not in the cache_dir folder.
Here is the complete traceback:

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-24-966c73571a72> in <module>
----> 1 model.train_model(qa_train, eval_data=qa_eval)

/WD/s2s/venv/lib/python3.8/site-packages/simpletransformers/seq2seq/seq2seq_model.py in train_model(self, train_data, output_dir, show_running_loss, args, eval_data, verbose, **kwargs)
    286         self._move_model_to_device()
    287 
--> 288         train_dataset = self.load_and_cache_examples(train_data, verbose=verbose)
    289 
    290         os.makedirs(output_dir, exist_ok=True)

/WD/s2s/venv/lib/python3.8/site-packages/simpletransformers/seq2seq/seq2seq_model.py in load_and_cache_examples(self, data, evaluate, no_cache, verbose, silent)
    969                 return SimpleSummarizationDataset(encoder_tokenizer, self.args, data, mode)
    970             else:
--> 971                 return Seq2SeqDataset(encoder_tokenizer, decoder_tokenizer, self.args, data, mode,)
    972 
    973     def _create_training_progress_scores(self, **kwargs):

/WD/s2s/venv/lib/python3.8/site-packages/simpletransformers/seq2seq/seq2seq_utils.py in __init__(self, encoder_tokenizer, decoder_tokenizer, args, data, mode)
     63 
     64             logger.info(" Saving features into cached file %s", cached_features_file)
---> 65             with open(cached_features_file, "wb") as handle:
     66                 pickle.dump(self.examples, handle, protocol=pickle.HIGHEST_PROTOCOL)
     67 

FileNotFoundError: [Errno 2] No such file or directory: 'cache_dir/SZTAKI-HLT/hubert-base-cc-SZTAKI-HLT/hubert-base-cc_cached_12872820'
```
My first guess is that the slash sign in the name of the custom huggingface model produces the error, but if I am right, how to solve it?
Thanks in advance

**To Reproduce**
model = Seq2SeqModel(
    "bert",
    "SZTAKI-HLT/hubert-base-cc",
    "SZTAKI-HLT/hubert-base-cc",
    args=model_args,
    use_cuda=False,
)
model.train_model(train_df, eval_data=eval_df)

**Expected behavior**
Start training

**Desktop (please complete the following information):**
Ubuntu 18.04
simpletransformers     0.48.15
torch                  1.7.0+cpu
transformers           3.4.0

**Comment by ThilinaRajapakse** [comment]
You could try setting `use_cache=False` in the `model_args` as a workaround. I'm inclined to agree that the backslash is the likely culprit here.
