### ISSUE TITLE
Error seeing model with `dataset_class` argument 

### ISSUE THREAD

**Issue by Zhylkaaa** [ThilinaRajapakse/simpletransformers#795]
**Describe the bug**
Error while `self.args.save` when using `dataset_class` argument. Default JSONEncoder can't serialise Dataset object.

**To Reproduce**
Try using `dataset_class` argument for example in seq2seq_model.

**Expected behavior**
Save the model_args.json correctly.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.2

**Additional context**
Actually this error is present in `wandb` but as mentioned in this [issue](https://github.com/wandb/client/issues/1375) this will be fixed in next versions.

Commenting definition of `dataset_class` in `Seq2SeqArgs` helps, but its a bit ugly solution

**Comment by ThilinaRajapakse** [comment]
I changed the `Seq2SeqArgs` class to save the `dataset_class` as the name of the class rather than the class itself. But this means that the `dataset_class` must be provided when loading the model (a warning is raised when loading a model with a custom dataset class).

**Comment by Zhylkaaa** [comment]
I been thinking about something like this and it seems to be the only solution for now.

Thank you!
