### ISSUE TITLE
Prediction function and Multi-threading

### ISSUE THREAD

**Issue by ns-hxue** [ThilinaRajapakse/simpletransformers#798]
I have a question regarding the prediction functions in general. Does the prediction function run in multithreading by default? Any way to limite the threads only for prediction

**Comment by ThilinaRajapakse** [comment]
The data preprocessing (tokenization) part of the prediction function uses multiprocessing by default. You can't turn it off just for the predictions, but you can turn it off after the model is trained by setting `use_multiprocessing=False`. Pytorch will also use multithreading by default both for the actual forward pass (if using the CPU) or for loading data into memory (if using the GPU).
