### ISSUE TITLE
Training DistilBERT language model from scratch not working

### ISSUE THREAD

**Issue by Subh1m** [ThilinaRajapakse/simpletransformers#799]
**Describe the bug**
Unable to train a DistilBERT language model from scratch. I keep getting the underlying error.

CodeLine: 
`model = LanguageModelingModel('distilbert', None, args=train_args, train_files='data/train.txt')`
This code taken from [Language Model From Scratch](https://github.com/ThilinaRajapakse/simpletransformers#minimal-example-for-language-model-training-from-scratch)
 
ERROR:

`OSError: Model name 'outputs/' was not found in tokenizers model name list (distilbert-base-uncased, distilbert-base-uncased-distilled-squad, distilbert-base-cased, distilbert-base-cased-distilled-squad, distilbert-base-german-cased, distilbert-base-multilingual-cased). We assumed 'outputs/' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.txt'] but couldn't find such vocabulary files at this path or url.`

**To Reproduce**
Replace the 'roberta' to 'distilbert' in [Language Model From Scratch](https://github.com/ThilinaRajapakse/simpletransformers#minimal-example-for-language-model-training-from-scratch)

**Desktop (please complete the following information):**
 - OS: CentOS 6

**Additional context**
Thanks for the library...really helps understanding transformers pretty well.

**Comment by manueltonneau** [comment]
Hi @Subh1m, 

I don't think `distilbert` is intended to be trained from scratch. The architecture is based on model distillation which implies having a teacher model to learn from. This might explain the error. If you really want a distilBERT trained on your data, you could pre-train a BERT model on your data and then distil it (code [here](https://github.com/huggingface/transformers/tree/master/examples/distillation) for distillation part).

**Comment by Subh1m** [comment]
Actually, I was able to solve this by just running gpt2 first and then running distilbert. I have yet to check why that happened.


model = LanguageModelingModel('gpt2', None, args=train_args, train_files='data/train.txt')
followed by:
model = LanguageModelingModel('distilbert', None, args=train_args, train_files='data/train.txt')

Now, I am able to train it, but another problem appeared. It seems to be pretty slow compared to huggingface implementation for distilbert. I am using 4 GPUs but still it takes nearly 3 times slower. Is there any parameter other than batch size and n_gpu that helps in speeding up?
