### ISSUE TITLE
Asking for multi-label classification function

### ISSUE THREAD

**Issue by wshuyi** [ThilinaRajapakse/simpletransformers#8]
Great job! Thanks a lot for making it so easy! When will you support multi-label classification?

**Comment by ThilinaRajapakse** [comment]
I can't say for sure. I've been a bit busy but I'll take a look at it when I have the time.

**Comment by ThilinaRajapakse** [comment]
Happy to say this went smoother than expected! Multiclass classification is now supported.

**Comment by wshuyi** [comment]
Can I reopen this issue?

**Comment by ThilinaRajapakse** [comment]
Yeah, let's do that.

**Comment by wshuyi** [comment]
Terrific!

**Comment by emtropyml** [comment]
Does it support only Multi-class or Multi-label classification also?

**Comment by ThilinaRajapakse** [comment]
At the moment, only multiclass. But multilabel will be added shortly (when I verify that the implementation is working correctly.)

**Comment by ThilinaRajapakse** [comment]
Multilabel classification is now implemented.

**Comment by wshuyi** [comment]
Thanks a lot! Great job!

**Comment by mxzahid** [comment]
For multi-label classification, what do the predictions (huge array that contains more entries than the number of labels) and raw_outputs (as an array of arrays) entail?
