### ISSUE TITLE
simple-viewer not working in notebook

### ISSUE THREAD

**Issue by jonas-nothnagel** [ThilinaRajapakse/simpletransformers#802]
Hi Thilina,

thank you for this great library! 
I was wondering if  there is any additional documentation how to use the simple-viewer build with streamlit?
I am running my experiments in a Paperspace notebook for GPU support and did not figure out how to properly run and make the simple-viewer working after training a classification model.

I am importing and running it as follows:
`from simpletransformers.streamlit.simple_view import streamlit_runner`
`streamlit_runner()`

The function loads forever and finally gets stuck.

**Comment by ThilinaRajapakse** [comment]
I'm not sure how you can run it in something like Paperspace. Locally, the easiest way to run it is to use the bash command `simple-viewer`. Can you use the terminal in Paperspace?

**Comment by jonas-nothnagel** [comment]
In other words: Is there a way to run the simple-viewer in a Jupyter notebook environment? 

I think otherwise I may use GPU driven notebooks (such as Paperspace) to train my models and then simply download the outputs, store them locally and run the simple-viewer from my terminal as a bash command.

**Comment by ThilinaRajapakse** [comment]
You can run it by opening a terminal in the Jupyter environment. That works locally but I am not sure whether it will through Paperspace. I'm sorry if this doesn't help, but I haven't used Paperspace so I can't say for sure.
