### ISSUE TITLE
Multi-Label classification for long documents

### ISSUE THREAD

**Issue by jonas-nothnagel** [ThilinaRajapakse/simpletransformers#803]
Hello Thilina, 

I was wondering if there are any plans to support Multi-Label classification for long documents in the near future? 
Personally, I think this would be a great contribution to this library and enable tackling a lot of real-world use cases. 

Would you consider to enable either:
i) Sliding Window for multi-label classification or 
ii) longformer support for multi-label classification?

Thank you!

**Comment by manueltonneau** [comment]
Hi @jonas-nothnagel, I added longformer support for multi-label classification in the PR above. Feel free to test and let me know if things work fine :)

**Comment by jonas-nothnagel** [comment]
Hi @manueltonneau, wow that is great news! I am ready to try and give feedback!

Unfortunately, I still receive the error: 
`KeyError: 'longformer'`

when trying to import the model. Is your commit already merged with the official simpletransformer library? I installed the latest update - but still can not import the model.

Thank you!

**Comment by jonas-nothnagel** [comment]
It seems the commit has been merged and I can now import the longformer model for Multi-Label classification. 
Thanks again!

**Comment by manueltonneau** [comment]
You're welcome. Happy hacking :)

**Comment by jonas-nothnagel** [comment]
@manueltonneau perhaps you can quickly help me out with additional information:
Is the default max_seq_length of the longformer 4096 automatically? Or do I need to specify it in the model arguments manually?

**Comment by ThilinaRajapakse** [comment]
You need to specify it manually. The default values are taken from the default values for the task (`config/model_args.py`) and not the model itself.
