### ISSUE TITLE
Wandb not logging eval data during training when running sweep

### ISSUE THREAD

**Issue by ohstopityou** [ThilinaRajapakse/simpletransformers#817]
Wandb does not log model eval data during training when running sweep. 
Because arg wandb_project cannot be set without causing issues during sweep.

If I add wandb project to model args, the model tries to reinit wandb, which causes previous wandb run to finish. 
This leads to Program failed with code 1... Exception('The wandb backend process has shutdown',)

Edit:
 If wandb project is set in args:
 wandb: WARNING Ignored wandb.init() arg project when running a sweep
 Finishing last run (ID:459ak22l) before initializing another...
 Data is logged to the run this way, but wandb progress either stops, or gpu runs out of ram.
 I assume it keeps the wandb progress running in the background, as it is never finished by the model or agent. This causes the model to stay allocated to GPU ram, which results in CUDA out-of-memory when running several runs from agent.

Can probably be easily solved by adding if statements in classification_model.py which requires args.wandb_project OR sweep_config kwarg to log. Ex line 614
 
**To Reproduce**
Setup is same as sweep example by Thilina, with addition to enabling eval during training.
Training function logs to wandb as expected when wandb_project is set and not run by sweep agent.
If sweep and no project arg, wandb only shows run system info and sweep config. Sweep runs without errors. 

Im using Google Colab.

**Comment by ohstopityou** [comment]
Temporarily solved by manually logging train_progress to wandb at end of run.
But this makes the hyperband early stopping method useless because wandb updates is not live.

**Comment by Yannik1337** [comment]
Have you tried passing "reinit=False" to the wandb_kwargs dict? Does that help?

**Comment by ohstopityou** [comment]
When adding wandb_project and setting kwarg reinit=False, it does log to wandb. Only one 
Does not really help the issue, as it results in UnboundLocalError("local variable 'run' referenced before assignment",) and the model is still kept in RAM.
