### ISSUE TITLE
We meet a low performance when trying multi class_classification.py for our dataset.

### ISSUE THREAD

**Issue by moh-yani** [ThilinaRajapakse/simpletransformers#818]
Dear,

I tried to use https://github.com/ThilinaRajapakse/simpletransformers/blob/master/examples/text_classification/multiclass_classification.py for a dataset containing 20k data with 120 classes. However, the eval result showed that the performance of this model is not good such as below:
<img width="241" alt="Screen Shot 2020-11-16 at 05 30 22" src="https://user-images.githubusercontent.com/55953151/99198519-b7c64200-27cb-11eb-91b2-e75a4f515643.png">

FYI, We have set the num_labels with 120 (num_labels=120) in the model.
<img width="818" alt="Screen Shot 2020-11-16 at 05 32 17" src="https://user-images.githubusercontent.com/55953151/99198577-2e633f80-27cc-11eb-83d8-5a04c3ceaec2.png">

We want to know if there is something wrong with what I did?

Thank you for your attention.

Sincerely,

MY

**Comment by ThilinaRajapakse** [comment]
Transformer models do seem to have issues learning when there is a very high number of labels (such as in this case). I would say an MCC score of 0.62 for 120 classes is actually pretty good.

**Comment by moh-yani** [comment]
I see. However, maybe you know how many classes that Transformer can obtain a good performance?

**Comment by ThilinaRajapakse** [comment]
I'm not aware of a specific number. I've gone up to like 20 or 30 without much trouble though.
