### ISSUE TITLE
NoneType error while training a small sample to test multilingual BERT

### ISSUE THREAD

**Issue by fredshu** [ThilinaRajapakse/simpletransformers#82]
I am trying to train the question answering multilingual BERT with only three sentences (in Portuguese) with the below code. I am quite novice with BERT, Python, PyTorch etc. Got the following issues:

(a) Most important error: the below code is producing an "AttributeError: 'NoneType' object has no attribute 'next_functions' "

(b) Sometimes I get "ZeroDivisionError: float division by zero", especially with batch size > 1

(c) I could not make it run with Google Colab TPU and my 6 Gb GPU Nvidia 1060 runs OOM

I use Ubuntu 18.04 and Spyder.

train_args = {
    'learning_rate': 3e-5,
    'num_train_epochs': 2,
    'max_seq_length': 500,
    'doc_stride': 128,
    'overwrite_output_dir': True,
    'reprocess_input_data': False,
    'train_batch_size': 1,
    'gradient_accumulation_steps': 8,
}

model = QuestionAnsweringModel('bert', 'bert-base-multilingual-cased', args = train_args, use_cuda = False)

train_data = [
    {
        'context': "cento e trinta mil, seiscentos e cinquenta e cinco reais e \
sessenta centavos) um aumento, portanto, de R$ 70.000.000,00 (setenta milhões de \
reais), mediante a emissão de 70.000.000 (setenta milhões) de novas ações ordinárias, \
nominativas e sem valor nominal, com preço de emissão total de R$ 1,00 (um real), \
fixado conforme art. 170",
        'qas': [
            {
                'id': "00001",
                'is_impossible': False,
                'question': "Quantas ações foram emitidas?",
                'answers': [
                    {
                        'text': "70.000.000 (setenta milhões) de novas ações ordinárias",
                        'answer_start': 170
                    }
                ]
            }
        ]
    },
    {
        'context': "para R$ 6.969.409,75 (seis milhões, novecentos e sessenta e nove mil e quatrocentos e \
nove reais e setenta e cinco centavos), mediante a emissão privada de 1.726.371 (um milhão, \
setecentas e vinte e seis mil e trezentas e setenta e uma) ações ordinárias, todas nominativas, \
sem valor nominal, pelo preço de R$ 0,2317 por ação, fixado com base nos parâmetros do §1o do \
artigo 170 da Lei no 6.404/76",
        'qas': [
            {
                'id': "00002",
                'is_impossible': False,
                'question': "Quantas ações foram emitidas?",
                'answers': [
                    {
                        'text': "1.726.371 (um milhão, setecentas e vinte e seis mil e trezentas e setenta e uma) ações ordinárias",
                        'answer_start': 156
                    }
                ]
            }
        ]
    },
    {
        'context': "A substituição de investimentos da INCORPORADORA na INCORPORADA \
pelos elementos ativos e passivos constantes do Balanço Patrimonial da \
INCORPORADA não implicará em alteração no valor do patrimônio líquido e do \
capital social da INCORPORADORA, nem a emissão de novas ações ou \
qualquer modificação aos direitos de voto, dividendos ou quaisquer outros \
direitos políticos ou patrimoniais conferidos aos atuais acionistas da \
INCORPORADORA.",
        'qas': [
            {
                'id': "00003",
                'is_impossible': False,
                'question': "Quantas ações foram emitidas?",
                'answers': [
                    {
                        'text': "não implicará em alteração no valor do patrimônio líquido e do \
capital social da INCORPORADORA, nem a emissão de novas ações",
                        'answer_start': 147
                    }
                ]
            }
        ]
    }
]

model.train_model(train_data)

**Comment by ThilinaRajapakse** [comment]
I ran your code but didn't get the error mentioned in _a_.

The error in _b_ is due to using gradient accumulation of 8 when you only have 3 samples. This means that you are essentially not completing a single training step.

I think a 1060 should be enough to run the bert-base models with small batch sizes. I'm not sure why you got an OOM error with a batch size of 1. I haven't tried using the TPUs, but the library does work with the Colab GPU.

**Comment by fredshu** [comment]
Thank you very much. Gradient accumulation of 1 made it work on Colab.
Needs 15 epochs of training to achieve good performance in one test
sentence. I will play with more data and other configurations. Thanks.

Em dom., 8 de dez. de 2019 às 05:31, Thilina Rajapakse <
notifications@github.com> escreveu:

**Comment by ThilinaRajapakse** [comment]
You will probably be able to get better performance with a lower number of training epochs if you increased the size of the training dataset!

**Comment by fredshu** [comment]
Thanks again! Are there any early stopping and model checkpoint modules to
use with a validation set?

Em dom., 8 de dez. de 2019 às 08:09, Thilina Rajapakse <
notifications@github.com> escreveu:

**Comment by ThilinaRajapakse** [comment]
You can set `evaluate_during_training: True` to perform evaluation at checkpoints. Early stopping is planned but has not been implemented yet.

**Comment by fredshu** [comment]
Thank you!

Em dom., 8 de dez. de 2019 às 08:38, Thilina Rajapakse <
notifications@github.com> escreveu:
