### ISSUE TITLE
Adding custom tokens

### ISSUE THREAD

**Issue by overlookcurl** [ThilinaRajapakse/simpletransformers#824]
Hi, 

Thank you for the wonderful library. Can I know how to add custom tokens when performing language modeling from a pretrained model like bert? 

I am sorry if it is straightforward, but could not find any documentation regarding that

**Comment by ThilinaRajapakse** [comment]
Hugging Face [tokenizers](https://huggingface.co/transformers/master/main_classes/tokenizer.html#) have a method to add tokens. You should be able to do something like this:

```python
model = LanguageModelingModel(
    "bert",
    "bert-base-cased",
)

model.tokenizer.add_tokens(["New token 1", "New token 2"])
```

**Comment by overlookcurl** [comment]
Thank you. It works!!
