### ISSUE TITLE
nn.dataparallel

### ISSUE THREAD

**Issue by nickcoch** [ThilinaRajapakse/simpletransformers#826]
I know that there is documentation out there on how to get pytorch to work on multiple gpu's, but is there anyway you could include a section regarding setup of this.  As simple Transformers is easy to use and a great tool, but combining Cuda on cloud environments is beyond myself and I'm sure many others.  With transformer models getting larger and larger, it's hard to run large models with high batch sizes (on higher sequence lengths), if you could include this that would be awesome.  If there was easy way to run large models on the multi-gpu cloud instances that would be awesome!  Thank you

**Comment by sarapapi** [comment]
Actually the library includes Pytorch Dataparallel, you can simply set up the number of GPUs by [n_gpu](https://github.com/ThilinaRajapakse/simpletransformers#n_gpu-int) and the GPUs will be used and handled automatically.
