### ISSUE TITLE
Getting a KeyError:0 when trying to predict

### ISSUE THREAD

**Issue by YatharthVats** [ThilinaRajapakse/simpletransformers#828]
Hi! I have been trying to use the ClassificationModel for multiclass classification and have trained a bert model for this. While trying to predict info using this model I am geting a KeyError:0. 

Can someone comment on what I am doing wrong or is it a bug?

Screenshots of the code and error :

![code](https://user-images.githubusercontent.com/37652883/99658201-2aae1200-2a85-11eb-9f3e-411977014518.png)
![err1](https://user-images.githubusercontent.com/37652883/99658224-326db680-2a85-11eb-93ef-b6bb95612ba8.png)
![err2](https://user-images.githubusercontent.com/37652883/99658233-3699d400-2a85-11eb-9fbe-a8643b412054.png)

**Comment by sarapapi** [comment]
I think that you have to transform your pandas DataFrame `predict_df` into a list for the predict method.

**Comment by ThilinaRajapakse** [comment]
@all-contributors add @sarapapi for question

**Comment by YatharthVats** [comment]
Hey @sarapapi thanks for that help! I was able to get an output using that. I have just one more question. 
Currently, I am classifying between 4 different labels. Here is the output that I am getting:
![ques](https://user-images.githubusercontent.com/37652883/99725175-b900b300-2ada-11eb-9aaa-202a3b182baf.png)
Could you please help me understand why I am getting an array of [2,2]?  Shouldn't I be getting a single label as the output on giving the headline and article body?

**Comment by kwanhong66** [comment]
As you can see in [multi-class-classification minimal example](https://simpletransformers.ai/docs/multi-class-classification/), `model.predict` returns `predictions` and `raw_outputs`.

[2, 2] result means your batch input is predicted as a label 2 for the first input(headline) and a label 2 for the second input(bodies).
As you can see the probability for each class in `raw_outputs`, the third one (index 2) is the highest probability for both of them.

**Comment by YatharthVats** [comment]
Thanks everyone! I was able to understand why this was happening. Turns out I just had to use the sentence pair format instead. As the issue is over I'll close this now

**Comment by ThilinaRajapakse** [comment]
@all-contributors add @kwanhong66 for question
