### ISSUE TITLE
TypeError: special token bos_token has to be either str or AddedToken but got: <class 'dict'>

### ISSUE THREAD

**Issue by Shivanandroy** [ThilinaRajapakse/simpletransformers#833]
**Describe the bug**
Getting this error
`TypeError: special token bos_token has to be either str or AddedToken but got: <class 'dict'>` when loading a `Seq2Seq` model (trained on GPU) on CPU for inferencing

**To Reproduce**
1. Train a model on GPU, and save the model in `./outputs` directory
```python
# setting up Seq2Seq model parameters
model_args = {
    "output_dir": 'outputs',
    "reprocess_input_data": True,
    "overwrite_output_dir": True,
    "max_seq_length": 50,
    "train_batch_size": 16,
    "num_train_epochs": 10,
    "save_eval_checkpoints": False,
    "save_model_every_epoch": False,
    "evaluate_generated_text": True,
    "evaluate_during_training_verbose": True,
    "use_multiprocessing": False,
    "max_length": 15,
    "manual_seed": 4,
    "num_return_sequences":5,
    "do_sample": True,
    "n_beams":20
}

encoder_type = "roberta"

# model building
model = Seq2SeqModel(
    encoder_type,
    "roberta-base",
    "bert-base-cased",
    args=model_args,
    use_cuda=True,
)

# model training
model.train_model(train_df)

# model evaluation
results = model.eval_model(eval_df)

```

2. load the model on CPU machine for inferencing
```python
model_reloaded = Seq2SeqModel(
    "roberta",
    encoder_decoder_name="outputs",
    args=model_args, use_cuda=False
)
```

**Expected behavior**
A model trained on GPU should load on a CPU machine

**Desktop (please complete the following information):**
 - macOS

**Comment by ThilinaRajapakse** [comment]
The same code is working for me without any issues. Is it possible that the model was trained with an earlier version of the library which is incompatible with the latest?

**Comment by Shivanandroy** [comment]
@ThilinaRajapakse I'm closing this issue, as the code works on colab, it's weird it gives me the error on my local machine.
