### ISSUE TITLE
How to train several datasets

### ISSUE THREAD

**Issue by polodealvarado** [ThilinaRajapakse/simpletransformers#838]
Hi everyone!

I would like to train my spanish BERT model for entity recognition. However, for the training I have a dataset for each document with the required dataset format (sentence_id,token,entity):
- Document 1 => dataset_1.hd5
- Document 2 => dataset_2.hd5
... etc

Should I join the data sets into one or do continuous learning?

If I have to join all the datasets, how should I set the "sentence_id" column?

**Comment by ThilinaRajapakse** [comment]
You should probably just join them into one. You can use the document number or document id as the `sentence_id`. The `sentence_id` is essentially what separates the sequences. All the rows with a particular sentence_id will be considered a single sequence.

**Comment by polodealvarado** [comment]
Great, I will try it.
