### ISSUE TITLE
Adjust ClassificationModel for Multi-Input

### ISSUE THREAD

**Issue by thymian-crypto** [ThilinaRajapakse/simpletransformers#846]
I'd like to fine-tune BERT for a text regression task with multimodal input features. For example, apart from text data, I'd like to encode the identity of the author via one-hot-encoding as suggested [here](https://ai.stackexchange.com/questions/21928/how-to-use-speakers-information-as-well-as-text-for-fine-tuning-bert). To this end, for each document one would have to concatenate the BERT [CLS] output to the one-hot-encoded author ID and feed that into a final dense layer performing the prediction. 

Would that be possible with the simpletransformers `ClassificationModel` (and if so, how?) or would I have to fall back to huggingface? Thank you!

**Comment by ThilinaRajapakse** [comment]
Unfortunately, it's not possible without modifying the code/logic in Simple Transformers. I'm not sure whether it will be easier to do that or to just do it from scratch with hugging face! 😅

**Comment by tyomik-mnemonic** [comment]
Hi, @ThilinaRajapakse ! Thanks u and other contributers for this tool. But I have to know, situation is change or not? The one hot output for classification task was added ?

**Comment by ThilinaRajapakse** [comment]
I'm afraid not. There aren't any plans to add it currently either.
