### ISSUE TITLE
SpanBERT support

### ISSUE THREAD

**Issue by mirzakhalov** [ThilinaRajapakse/simpletransformers#847]
Any plans on integrating SpanBERT into the library? Link: https://huggingface.co/SpanBERT/spanbert-large-cased#how-to-use

**Comment by ThilinaRajapakse** [comment]
You should be able to use it with tasks like classification, NER, QA, etc. already. E.g.:

`model = QuestionAnsweringModel("bert", "SpanBERT/spanbert-base-cased"`

I don't have immediate plans to add it for pre-training though. There's so much to do but not enough time, sadly. 😞
