### ISSUE TITLE
ModuleNotFoundError: No module named 'simpletransformers'

### ISSUE THREAD

**Issue by moh-yani** [ThilinaRajapakse/simpletransformers#848]
Dear,

I have installed simpletransformers on my 'simpletransformers' environment. However, when I import from simpletransformers.classification import ClassificationModel on Jupiter Notebook, I have an error message like this:

<img width="1068" alt="Screen Shot 2020-11-24 at 05 55 48" src="https://user-images.githubusercontent.com/55953151/100024261-03569c80-2e19-11eb-8e6f-dd471f40efc8.png">

FYI, I have imported this library on terminal mode, and it run well. However, for one reason, I want to run it using Jupyter Notebook. Why does it happened?

**Comment by moh-yani** [comment]
I also have checked if the simpletransformers is already installed with !pip list

<img width="875" alt="Screen Shot 2020-11-24 at 06 00 47" src="https://user-images.githubusercontent.com/55953151/100024406-444eb100-2e19-11eb-8336-5b924ca34cd9.png">

**Comment by moh-yani** [comment]
I found this issue again, but I couldn't solve it even I added the simpletransformers library on my env.

**Comment by ThilinaRajapakse** [comment]
It looks like the jupyter environment is not using the virtual environment which has simple transformers installed. I'm not sure why that would happen though.

Also, those simple transformers and transformers versions are quite old.

**Comment by moh-yani** [comment]
Thanks @ThilinaRajapakse.
