### ISSUE TITLE
ValueError: 'use_cuda' set to True when cuda is unavailable. Make sure CUDA is available or set use_cuda=False.

### ISSUE THREAD

**Issue by moh-yani** [ThilinaRajapakse/simpletransformers#849]
Dear,

I want to run your script 'multiclass_classification.py' using GPU on Jupyter Notebook. I have checked if I am in correct correct environment I created, namely 'st' by typing '!which pip'. I also have checked if my cuda is available by typing '!nvidia-smi'

<img width="763" alt="Screen Shot 2020-11-24 at 08 52 29" src="https://user-images.githubusercontent.com/55953151/100035620-3a38ac80-2e31-11eb-9db8-d671b4a75e18.png">

FYI, I also have installed 'simpletransformers' on the 'st' environment by typing 'pip install simpletransformers'. 
<img width="723" alt="Screen Shot 2020-11-24 at 08 54 07" src="https://user-images.githubusercontent.com/55953151/100035777-82f06580-2e31-11eb-8837-d66d9355c218.png">

However, when I want to run these scripts, I got the error message such as follows:

<img width="1038" alt="Screen Shot 2020-11-24 at 08 56 01" src="https://user-images.githubusercontent.com/55953151/100035883-b4693100-2e31-11eb-9e19-e8678e228854.png">

Any idea for this?

**Comment by gaganmanku96** [comment]
You can try a few things
1. Check whether CUDA is available or not
import torch
print(torch.cuda.is_available())

2. Try updating drivers
You seem to be using quite an old version of drivers. I'm currently using 460.20

**Comment by moh-yani** [comment]
@gaganmanku96 thank you for your advise. I have tried your script:
import torch
print(torch.cuda.is_available())

and returned False

<img width="505" alt="Screen Shot 2020-11-24 at 16 25 47" src="https://user-images.githubusercontent.com/55953151/100073797-87883e80-2e70-11eb-886e-31493bcf7818.png">


I actually have not cleared if cudatoolkit installed in Conda environment is same with cuda in Jupiter notebook or not.

Anyone could give a suggestion?

**Comment by gaganmanku96** [comment]
Yes, looks like PyTorch is not detecting your GPU.

You need 3 things to work with GPU in PyTorch
1. PyTorch (GPU version)
2. Nvidia Drivers
3. Cudatoolkit

This is the link to install Pytorch
https://pytorch.org/get-started/locally/
Select the appropriate PyTorch version along with cudatoolkit version.
You'll also have to update Nvidia Drivers. You can check the following compatibility chart.

This is the compatibility chart. 
![image](https://user-images.githubusercontent.com/20324385/100076804-9b7b7280-2e67-11eb-8019-ce7823aa9470.png)
