### ISSUE TITLE
shape '[-1, 22]' is invalid for input of size 2

### ISSUE THREAD

**Issue by samarthsarin** [ThilinaRajapakse/simpletransformers#85]
I am training a bert model on Multi Label classification problem with 22 classes. After using the default parameters 
model = MultiLabelClassificationModel('bert', 'bert-base-uncased', num_labels=22, args={'train_batch_size':2, 'gradient_accumulation_steps':16, 'learning_rate': 3e-5, 'num_train_epochs': 3, 'max_seq_length': 512})

model.train_model(train_df)

RuntimeError: shape '[-1, 22]' is invalid for input of size 2

**Comment by ThilinaRajapakse** [comment]
Please show `train_df.head()`.

**Comment by samarthsarin** [comment]
![image](https://user-images.githubusercontent.com/40137295/70393292-6683cf00-1a0e-11ea-827a-c393ed34eaeb.png)

**Comment by samarthsarin** [comment]
Also, I wanted to know how is the model determining which column name is the text data and which column name is the label data? Do we have to provide the data in any specific column name format?

**Comment by ThilinaRajapakse** [comment]
That is not the correct format for multilabel classification atm.

Please refer to the [docs](https://github.com/ThilinaRajapakse/simpletransformers#minimal-start-for-multilabel-classification).

**Comment by samarthsarin** [comment]
Got it
Thanks
