### ISSUE TITLE
M-T5 NEEDS TO BE PUT OUT THERE.

### ISSUE THREAD

**Issue by vyommartin** [ThilinaRajapakse/simpletransformers#858]
I have been using the SimpleTransformers Library for a decent amount of time now, but I really want to use the M-T5. Unfortunately the HuggingFace or transformers libraries for a fact don't have it yet even thought they have the T5 variants in there.

This is so dumb but could you find a way to 

I have tried using their notebooks which are terribly coded, see if you could help. Cheers mate I love your stuff its gold.

**Comment by manueltonneau** [comment]
FYI it has been released in transformers v4.0.0 (see [here](https://huggingface.co/google/mt5-base) for instance).

**Comment by abedkhooli** [comment]
I tried the latest (0.50) and it accepted `google/mt5-base` as pretrained model but there seems an issue with t5_utils (also with t5-base):
```
simpletransformers/t5/t5_utils.py", line 33, in preprocess_data
    target_text + " </s>"
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

**Comment by ThilinaRajapakse** [comment]
Added here too. Forgot to mention it here!
