### ISSUE TITLE
what 'answer_start' means in question answering model

### ISSUE THREAD

**Issue by moh-yani** [ThilinaRajapakse/simpletransformers#859]
Dear @ThilinaRajapakse 

I have not understood what 'answer_start' means in QA model. For example:
<img width="514" alt="Screen Shot 2020-11-28 at 05 13 25" src="https://user-images.githubusercontent.com/55953151/100486671-7c1a6900-3137-11eb-9502-b4af5ed17b3c.png">

Could you give us the brief explanation for this?

**Comment by ThilinaRajapakse** [comment]
It's the starting index of the answer in the question. In your example, it would be `"Which context is this?".index("the first")`. ([docs](https://simpletransformers.ai/docs/qa-data-formats/#input-structure))

**Comment by moh-yani** [comment]
Oh I see, thanks sir.
