### ISSUE TITLE
About the input

### ISSUE THREAD

**Issue by tzhxs** [ThilinaRajapakse/simpletransformers#86]
When I use the original code of bert, the input should include some special token like 'cls', and  the roberta also have same requirement, should I do the same thing when i use the simpletransformers? and why not?

**Comment by ThilinaRajapakse** [comment]
No, you shouldn't. The special tokens are added automatically in the `convert_example_to_feature` method.

**Comment by tzhxs** [comment]
That is great! and how can i get the embedding of the special token if i want use it to train my fully connect nn instead of use the default one?

**Comment by ThilinaRajapakse** [comment]
You'll have to create a new ClassificationModel (e.g. BertForSequenceClassification) which uses your own linear layer. The default one looks like this.
```
def forward(self, input_ids=None, attention_mask=None, token_type_ids=None,
                position_ids=None, head_mask=None, inputs_embeds=None, labels=None):

        outputs = self.bert(input_ids,
                            attention_mask=attention_mask,
                            token_type_ids=token_type_ids,
                            position_ids=position_ids,
                            head_mask=head_mask)

        pooled_output = outputs[1]

        pooled_output = self.dropout(pooled_output)
        logits = self.classifier(pooled_output)
```
Here, `self.classifier` is the fully connected layer. You can replace it with a custom layer.
```
self.classifier = nn.Linear(config.hidden_size, self.config.num_labels)
```

**Comment by tzhxs** [comment]
Thanks, and donyou know why here use output[1]? When i use bert the embedding of 'cls' is output[1][0], where the output[1] means all the embedding of the input and the output[1][0] means the embedding of 'cls'

**Comment by tzhxs** [comment]
Which special token is used to do predict in roberta? I konw it is cls in bert, but when it come to roberta, I dont clear abot it, can you tell me? please

**Comment by ThilinaRajapakse** [comment]
It's `<s>` and `</s>` if I remember correctly.

**Comment by tzhxs** [comment]
thanks, you are so friendly, so is it using the embeddig of <s> to predict the score? Can i get the embedding of the <s>?

**Comment by tzhxs** [comment]
I could not find the token "<s>" in the classification_utils?  Is it wrong?

**Comment by ThilinaRajapakse** [comment]
Yes, the embedding of the token is what gets sent to the classifier. 

You'll have to trace it through several layers of inheritance if you want to find the actual token from the place where it gets added during conversion.

**Comment by tzhxs** [comment]
Thanks. I mean I could not find the code which add the `s` to my input in your project, Is there something wrong?

**Comment by ThilinaRajapakse** [comment]
`tokens = [cls_token] + tokens`

From the `convert_example_to_feature` function.

**Comment by tzhxs** [comment]
I read the code and find it.  Maybe use the token s will be better?

**Comment by ThilinaRajapakse** [comment]
It is `s` when using Roberta. But the special tokens are different for different models so it's not hard coded into the conversion code.

**Comment by tzhxs** [comment]
Thanks！
