### ISSUE TITLE
Always stop when evaluation for classification_model.py

### ISSUE THREAD

**Issue by moh-yani** [ThilinaRajapakse/simpletransformers#860]
I have tried for more than five times to run 'classification_model.py' in different datasets. For all the time, the progress evaluation is always stopped (not terminated).

The screenshoot:
<img width="1151" alt="Screen Shot 2020-11-28 at 18 41 00" src="https://user-images.githubusercontent.com/55953151/100514592-a6f0d580-31a8-11eb-98ce-e37adc61186d.png">

The evaluation process did not progress until I type CTRL+C to quit.

Any information about that?

Thank you.

**Comment by ThilinaRajapakse** [comment]
Hard to say just by looking at this. Can you try running it without multiprocessing. `model_args.use_multiprocessing = False`

**Comment by AhmedIdr** [comment]
Im having the same Problem, removing `model_args.use_multiprocessing = False` didnt seem to fix it.

**Comment by chenweilong915** [comment]
Try to set "dataloader_num_workers": 0,
It solved my problem.

**Comment by AhmedIdr** [comment]
That's seem to solve the problem, thank you

**Comment by moh-yani** [comment]
> Try to set "dataloader_num_workers": 0,
> It solved my problem.

Is it set in args? like:
args={'dataloader_num_workers': 0}

**Comment by chenweilong915** [comment]
> > Try to set "dataloader_num_workers": 0,
> > It solved my problem.
> 
> Is it set in args? like:
> args={'dataloader_num_workers': 0}

yes

**Comment by moh-yani** [comment]
> > > Try to set "dataloader_num_workers": 0,
> > > It solved my problem.
> > 
> > 
> > Is it set in args? like:
> > args={'dataloader_num_workers': 0}
> 
> yes

I see, thank a lot for your advise.
