### ISSUE TITLE
How to load model for predicting a class using classification_model.py

### ISSUE THREAD

**Issue by moh-yani** [ThilinaRajapakse/simpletransformers#861]
Dear,

Excuse me if I often ask about simpletransformers. I used classification library for our dataset (in terms of multi classes). I have trained our data (I named the file with 'train_eval.py'):
<img width="1155" alt="train_eval" src="https://user-images.githubusercontent.com/55953151/100518772-440e3700-31c6-11eb-8fa4-f424cff0f680.png">

Now, I want to create another file ('pred.py') I will use to predict a given sentence. 
<img width="1150" alt="pred" src="https://user-images.githubusercontent.com/55953151/100518781-4c667200-31c6-11eb-8bca-f4dd52b09f1b.png">

When I did a prediction in 'train_eval.py', I can obtain the correct prediction. However, when I did a prediction using 'pred.py', I got the wrong prediction. It looks like because I did not load my model trained before correctly. Honestly, I have no idea how to load my model before in order to the prediction outputs the correct prediction. 

Anyone could help?

Thank you

**Comment by LianaN** [comment]
Hey, you should load your trained model in `pred.py`:

```
model_path =<MODEL_DIR>
model = ClassificationModel(model_type="bert", tokenizer_name="bert-base-cased", model_name=model_path)
```

**Comment by moh-yani** [comment]
@LianaN 

Oh I see. Thanks for your advise.
