### ISSUE TITLE
make save_steps arg more powerful

### ISSUE THREAD

**Issue by pablonm3** [ThilinaRajapakse/simpletransformers#862]
from the doc: "save_steps: int
Save a model checkpoint at every specified number of steps"

## What's the problem?
When I train big deep learning models for a high number of ephocs sometimes I don't want to save checkpoints since they take a lot of disk space or sometimes I would like to save checkpoints every N number of ephocs, with N>1. The current save_steps arg IMO has 2 problems: 1) there is no way to turn it off so that it saves no checkpoints 2)The biggest time it can stay without saving checkpoints is 1 ephoc, even if I set save_steps to a huge number it always saves a checkpoint after every ephoc.

## My suggested solution:
when save_steps=None don't save any checkpoints
when save_steps>steps it will continue in the next ephoc, eg: if save_steps=4 and every ephoc takes 2 steps then at the end of ephoc 2 the first checkpoint will be saved.

I'm willing to implement this feature and open a PR but want to get some feedback on my approach before coding.

**Comment by ThilinaRajapakse** [comment]
As described [here](https://simpletransformers.ai/docs/usage/#using-the-dataclass):

1) You can set `save_steps` to `-1` to turn it off. (This wasn't specified in the docs previously, but I've updated it now)
2) You can disable epoch saving with `save_model_every_epoch = False`

Do these options cover all bases?

**Comment by pablonm3** [comment]
It covers all my usecases, than you @ThilinaRajapakse !
I opened a PR with examples for how to use this feature: https://github.com/ThilinaRajapakse/simpletransformers/pull/863/files
