### ISSUE TITLE
Error while importing ClassificationModel

### ISSUE THREAD

**Issue by SimonVilliod** [ThilinaRajapakse/simpletransformers#865]
Hello, 

Since the new update of files i have an error that appears when i try to import ClassificationModel: 

ModuleNotFoundError: No module named 'transformers.modeling_albert'

**Comment by Mathufnn** [comment]
Same happened to me @pop-ketle .

The Transformers library just updated to 4.0.0 today and introduced some breaking changes. So I tried downgrading to the previous version (3.5.1) and it worked. This is a compatibility issue.

**Comment by SimonVilliod** [comment]
Thanks a lot!

**Comment by MutazYounes** [comment]
Thanks @Mathufnn worked.
`pip install transformers==3.5.1`

**Comment by tvkpz** [comment]
for ```from simpletransformers.classification import ClassificationModel, ClassificationArgs```  I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./lib/simpletransformers/classification/__init__.py", line 1, in <module>
    from simpletransformers.classification.classification_model import ClassificationModel
  File "./lib/simpletransformers/classification/classification_model.py", line 81, in <module>
    from simpletransformers.classification.transformer_models.albert_model import AlbertForSequenceClassification
  File "./lib/simpletransformers/classification/transformer_models/albert_model.py", line 4, in <module>
    from transformers.models.albert.modeling_albert import AlbertConfig, AlbertModel, AlbertPreTrainedModel
ModuleNotFoundError: No module named 'transformers.models'
```
I am using transformers 3.5.1 and the latest simpletransformers available through pip install. What could be the reason?
