### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'lm_labels' (while trying to run T5 model)

### ISSUE THREAD

**Issue by msakthi19** [ThilinaRajapakse/simpletransformers#866]
Hey,
Following #531 , 
I am trying to train a T5 model on Colab and I still get this error.

Code:

from simpletransformers.t5 import T5Model

model = T5Model("t5-small", args=model_args)
model.train_model(train_df, eval_data=eval_df)

Error: 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-8459c368865d> in <module>()
     23 model = T5Model("t5-small", args=model_args)
     24 
---> 25 model.train_model(train_df, eval_data=eval_df)

2 frames
/usr/local/lib/python3.6/dist-packages/simpletransformers/t5/t5_model.py in train_model(self, train_data, output_dir, show_running_loss, args, eval_data, verbose, **kwargs)
    181             eval_data=eval_data,
    182             verbose=verbose,
--> 183             **kwargs,
    184         )
    185 

/usr/local/lib/python3.6/dist-packages/simpletransformers/t5/t5_model.py in train(self, train_dataset, output_dir, show_running_loss, eval_data, verbose, **kwargs)
    364                         loss = outputs[0]
    365                 else:
--> 366                     outputs = model(**inputs)
    367                     # model outputs are always tuple in pytorch-transformers (see doc)
    368                     loss = outputs[0]

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

TypeError: forward() got an unexpected keyword argument 'lm_labels'

Version:
torch                         1.7.0+cu101
transformers                  4.0.0          
simpletransformers            0.49.7         
sentencepiece                 0.1.94         

PS:
Tried running the same script on Kaggle kernel and it ran perfectly fine. Noted down some of the library versions if that would help.
Kaggle Library versions:
torch                              1.6.0
transformers                       3.4.0
simpletransformers                 0.49.7
sentencepiece                      0.1.94

Thanks in advance!
![Screenshot 2020-12-01 at 9 56 17 AM](https://user-images.githubusercontent.com/47854670/100697258-82b91280-33bb-11eb-8242-3630dc86f034.png)

**Comment by vyommartin** [comment]
Same error!

**Comment by vyommartin** [comment]
@msakthi19 I tried to update the transformers and simple transformers libary using

![image](https://user-images.githubusercontent.com/63099980/100882071-be93cb00-34d4-11eb-835c-dc9f4f43b1fe.png)

It did seem to have worked since the model was training but another snag hit and the training gets stuck.

**Comment by msakthi19** [comment]
@vyommartin try using the below mentioned library versions. It seemed to fix the issue for me.
torch 1.6.0
transformers 3.4.0
simpletransformers 0.49.7
sentencepiece 0.1.94

**Comment by msakthi19** [comment]
Closing the issue :)
