### ISSUE TITLE
Error while importing MultiLabelClassificationModel

### ISSUE THREAD

**Issue by krannnn** [ThilinaRajapakse/simpletransformers#867]
**Describe the bug**
I have a problem importing MultiLabelClassificationModel for a multilabel classification task, and this since the last update of transformers to 4.0.0 .
However I tried to downgrade both libraries to before the update and I still have this problem on the jupyter notebook, and on the REPL it's working just fine.
I checked that I have the same python version and kernel is running on both REPL and Jupyter Notebook

**To Reproduce**
`from simpletransformers.classification import MultiLabelClassificationModel`

**Expected behavior**
Will load forerver in jupyter notebook

**Screenshots**

**Desktop (please complete the following information):**
 - Linux

**Additional context**
- simpletransformers version: 0.49.3
- transformers version: 3.5.1
- No Compatibility update was done to the multi_label_classification_model.py file under simpletransforemrs/classification

**Comment by ThilinaRajapakse** [comment]
Is this still an issue with the latest versions of Simple Transformers and Transformers?
