### ISSUE TITLE
Unpickle a GPU Trained Classification Model On a None CPU Machine

### ISSUE THREAD

**Issue by gokhangerdan** [ThilinaRajapakse/simpletransformers#874]
I trained a Classification Model using gpu and pickled it. Than I tried to unpickle it on a cpu only machine but this throwed an error.

`Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device(\'cpu\') to map your storages to the CPU.`

**Comment by ThilinaRajapakse** [comment]
The error message tells you what is happening. You'll have to handle that if you want to pickle and unpickle models. But, if you just want to save the model and load it somewhere else, you just need to copy over the `outputs` directory. Then, you can load a model like [this](https://simpletransformers.ai/docs/usage/#loading-a-local-save).

**Comment by gokhangerdan** [comment]
@ThilinaRajapakse I am trying to upload and register the model on Azure ML. I need to serialize the model using pickle or joblib for that. Do you have any recommendations?

**Comment by ThilinaRajapakse** [comment]
In that case, I assume you are working directly with the Pytorch model (`ClassificationModel.model`). If so, you need to specify the map location when you load the model on a different device with `map_location=torch.device('cpu')` (this is normal Pytorch behaviour).
