### ISSUE TITLE
Hyperparameter search / tuning / optimization

### ISSUE THREAD

**Issue by kommerzienrat** [ThilinaRajapakse/simpletransformers#876]
Will there be a feature for the automatic tuning of hyperparameters? So far it is not implemented afaik.
The transformers library of huggingface[ just got implemented a way](https://huggingface.co/transformers/main_classes/trainer.html#transformers.Trainer.hyperparameter_search) using ray and wandb among others.
Many thanks for this great library (and also thanks in advance for your reply).

**Comment by ThilinaRajapakse** [comment]
It's been implemented for ages. [Docs](https://simpletransformers.ai/docs/tips-and-tricks/#hyperparameter-optimization)

**Comment by kommerzienrat** [comment]
Will serve well. Thanks.
