### ISSUE TITLE
ValueError: multiclass-multioutput format is not supported

### ISSUE THREAD

**Issue by samarthsarin** [ThilinaRajapakse/simpletransformers#88]
Unable to perform model. evaluation on the eval_df. I am getting the following error

ValueError: multiclass-multioutput format is not supported

**Comment by ThilinaRajapakse** [comment]
Are you trying to use a metric function from sklearn?

**Comment by samarthsarin** [comment]
No, I am just following the medium tutorial for multilabel classification.
After training the model I am performing the model.eval step

**Comment by ThilinaRajapakse** [comment]
I am not getting this error. Which version of simpletransformers are you using?

**Comment by samarthsarin** [comment]
The latest verison only

**Comment by ThilinaRajapakse** [comment]
Do you get the same error with the minimal example on the readme?

**Comment by samarthsarin** [comment]
simpletransformers-0.10.4 This is the version i am using
Also I am following the exact same steps are mentioned in the medium article for the multilabel classification problem. I am done with training for the model. When I perform the evaluation of the model step using model.eval I am getting the following issue of ValueError: multiclass-multioutput format is not supported.

**Comment by samarthsarin** [comment]
Any update?

**Comment by samarthsarin** [comment]
![image](https://user-images.githubusercontent.com/40137295/70592786-ed989900-1c00-11ea-99c4-10854d6fe4c4.png)

**Comment by samarthsarin** [comment]
![image](https://user-images.githubusercontent.com/40137295/70592816-fe490f00-1c00-11ea-90a7-cd348478a19b.png)

**Comment by samarthsarin** [comment]
![image](https://user-images.githubusercontent.com/40137295/70592840-0f921b80-1c01-11ea-8c67-a43ec81fc500.png)

**Comment by samarthsarin** [comment]
Solved

**Comment by Younday** [comment]
I'm running into the same issue. Could you indicate how you solved it?

**Comment by ThilinaRajapakse** [comment]
Are you using the latest version of the library?

**Comment by brentbiseda** [comment]
Still encountering this error with the minimal example on your github:

simpletransformers == 0.34.4
pandas == 1.0.5
sklearn == 0.23.1

eval_data = list(zip(eval_df['text'].tolist(), eval_df['labels'].tolist()))
test = pd.DataFrame(eval_data)
result, model_outputs, wrong_predictions = model.eval_model(test)

ValueError: multiclass-multioutput format is not supported

**Comment by aaronbriel** [comment]
I ran into this same issue and found out that sklearn/metrics/_ranking.py line 878, y_type was 'multiclass-multioutput' vs 'multilabel-indicator' causing the error to be thrown. As I researched how these y_types were determined in sklearn metrics, I found out that it was due to my y_true not being entirely binary - there were indeed some rouge non-binary values in the dataset. After cleaning the data and rerunning the issue was resolved. Hopefully this helps @brentbiseda and @Younday.

**Comment by muzaluisa** [comment]
Thanks @aaronbriel , it helped me to resolve my problem as well!

**Comment by DrRaja** [comment]
Hi, 
I'm facing the same error while trying to run the  multilabel example from the examples folder. Can anyone please help me on this?

**Comment by aaronbriel** [comment]
@DrRaja did you try my workaround?

> I ran into this same issue and found out that sklearn/metrics/_ranking.py line 878, y_type was 'multiclass-multioutput' vs 'multilabel-indicator' causing the error to be thrown. As I researched how these y_types were determined in sklearn metrics, I found out that it was due to my y_true not being entirely binary - there were indeed some rouge non-binary values in the dataset. After cleaning the data and rerunning the issue was resolved.

**Comment by DrRaja** [comment]
@aaronbriel , thank you for your reply. As I mentioned that I'm only following the toy example and the eval_df looks like this: 
```
eval_data = [
    ["Example eval sentence for multilabel classification.", [1, 1, 1, 1, 0, 1]],
    ["Example eval senntence belonging to class 2", [0, 1, 1, 0, 0, 0]],
]
```
there are no non-binary values here

**Comment by aaronbriel** [comment]
Which example are you following?

**Comment by zelekemarew** [comment]
Dears, For me also the same error...
please Support me..
<img width="773" alt="image" src="https://github.com/ThilinaRajapakse/simpletransformers/assets/92783749/bcf49742-40af-4fa6-b6bf-41f075068b5b">
