### ISSUE TITLE
XLNet sentencepiece dependency

### ISSUE THREAD

**Issue by nhsmith85** [ThilinaRajapakse/simpletransformers#880]
**Describe the bug**
It appears that even after pip installing sentencepiece to my system, I continue to get an error from transformers coming from transformers/utils/dummy_sentencepiece_objects.py script where it checks for sentencpiece being available. 

**To Reproduce**
model = MultiLabelClassificationModel(model_type = 'xlnet', 
                                      model_name = model_name, 
                                      num_labels=9,
                                      args=model_args)

**Expected behavior**
No error on sentencepiece dependency

**Screenshots**
![image](https://user-images.githubusercontent.com/9698634/101300009-177ba000-3802-11eb-982b-711bcded21cb.png)

**Desktop (please complete the following information):**
Google colab (linux)
Pytorch version: 1.7.0+cu101
tranformers version: 4.0.0
datasets version:  1.0.2
wandb version:  0.10.12
Python 3.6.9
simpletransformers 0.50.0

**Additional context**

**Comment by ThilinaRajapakse** [comment]
XLNet is working for me. Can you try again in a fresh environment?

**Comment by nhsmith85** [comment]
Tried it again after loading a new Colab environment with same configuration - still doesn't work even after pip installing sentencepiece and importing it. Same error as above when loading the model. It seems something about that script from file_utils.py is not finding sentencepiece despite it being installed on my system.
