### ISSUE TITLE
BERTWEET giving error in Classification Model

### ISSUE THREAD

**Issue by ShivamSharma1997** [ThilinaRajapakse/simpletransformers#885]
Getting the following error when trying to get BERTWEET model for multi-label classification model

In directory: /home/s/ss4354/workspace/2020B
Starting on: Tue Dec 8 10:10:52 EST 2020
Traceback (most recent call last):
  File "./scripts/TASK1/Text_Augmentation/Information_Type/cross_validation.py", line 49, in <module>
    args=args)
  File "/home/s/ss4354/.local/lib/python3.7/site-packages/simpletransformers/classification/multi_label_classification_model.py", line 132, in __init__
    config_class, model_class, tokenizer_class = MODEL_CLASSES[model_type]
KeyError: 'bertweet'
INFO:wandb.sdk.internal.internal:Internal process exited

Also, can you help with this wandb issue?

**Comment by ThilinaRajapakse** [comment]
Bertweet is not implemented for multilabel classification (updated docs to reflect this).

The wandb message is not an issue. It's just reporting that the script was terminated.

**Comment by ShivamSharma1997** [comment]
@ThilinaRajapakse Thanks!

**Comment by ShivamSharma1997** [comment]
@ThilinaRajapakse Also, by what time can we expect to get the BERTweet model for multilabel classification?

**Comment by ThilinaRajapakse** [comment]
I'm not sure. I don't have any concrete plans for that yet, I'm afraid.

**Comment by manueltonneau** [comment]
@ShivamSharma1997 I'll see if I can find some time to do it in the coming days.

**Comment by ShivamSharma1997** [comment]
@manueltonneau Thanks, would appreciate it!

**Comment by manueltonneau** [comment]
The [PR](https://github.com/ThilinaRajapakse/simpletransformers/pull/898) is open :)

**Comment by manueltonneau** [comment]
Should work now @ShivamSharma1997

**Comment by ShivamSharma1997** [comment]
@manueltonneau Thanks a lot!

**Comment by manueltonneau** [comment]
You're welcome @ShivamSharma1997 :) If it works, could you please close this issue?
