### ISSUE TITLE
Saving & Loading T5 Model

### ISSUE THREAD

**Issue by safakkbilici** [ThilinaRajapakse/simpletransformers#886]
I have trained a T5 model and now I have some files:
- config.json
- eval_results.txt
- model_args.json
- pytorch_model.bin
- spiece.model
- training_args.bin

How can I load those files into T5 model. Okay I trained it, but I can't find any document about loading trained parameters for T5. 
I don't want to train every time then use. Thanks...

**Comment by eneSadi** [comment]
I am also faced this problem, answer would be nice...

**Comment by ThilinaRajapakse** [comment]
[Docs](https://simpletransformers.ai/docs/usage/#loading-a-local-save), guys. You load a T5 model the same way you load any other model.

**Comment by safakkbilici** [comment]
Thanks for answering Thilina. For people who cannot load the T5 model, this script would be helpful, I think.

model = T5Model("test_outputs_large/best_model", args=model_args)

I am closing this issue as solved.

**Comment by ThilinaRajapakse** [comment]
> Thanks for answering Thilina. For people who cannot load the T5 model, this script would be helpful, I think.
> 
> model = T5Model("test_outputs_large/best_model", args=model_args)
> 
> I am closing this issue as solved.

As of the latest version, `T5Model` requires the `model_type` argument as well. E.g.

`model = T5Model("t5", "test_outputs_large/best_model", args=model_args)`
