### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by srijiths** [ThilinaRajapakse/simpletransformers#89]
**Describe the bug**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/centos/anaconda3/envs/transformers/lib/python3.7/site-packages/simpletransformers/classification/__init__.py", line 1, in <module>
    from simpletransformers.classification.classification_model import ClassificationModel
  File "/home/centos/anaconda3/envs/transformers/lib/python3.7/site-packages/simpletransformers/classification/classification_model.py", line 31, in <module>
    from transformers import AdamW, get_linear_schedule_with_warmup
  File "/home/centos/srijith/KTC/transformers.py", line 11, in <module>
    model = simpletransformers.classification.ClassificationModel('roberta', 'roberta-base', num_labels=4)
AttributeError: module 'simpletransformers' has no attribute 'classification'

**To Reproduce**
python : 3.7.5
torch : 1.1.0
cuda: 9.0

**Expected behavior**
Is it supports pytorch 1.1.0 version and cuda 9.0 ?
**Screenshots**

**Desktop (please complete the following information):**
 - Linux

**Additional context**

**Comment by namrathaurs** [comment]
Did you try using the import statement as `from simpletransformers.classification import Classification_Model` instead of `from simpletransformers.classification.classification_model import Classification_Model`?

**Comment by namrathaurs** [comment]
@srijiths , did you try using the import statement as from `simpletransformers.classification import Classification_Model` instead of `from simpletransformers.classification.classification_model import Classification_Model`?

**Comment by ThilinaRajapakse** [comment]
I haven't tested this on CUDA 9.0 but even if it were incompatible, it still shouldn't throw an error on the import. Try reinstalling the library, just to see whether something went wrong with pip.

**Comment by srijiths** [comment]
Thank you @ThilinaRajapakse for making transformers further simple. Import issue is fixed by cleaning the conda caches. Some conflicts. I have tried it with cuda 9.0 but its not supported i guess, bacause based on cudatoolkit as 9.0 pytorch version is getting downgraded. 
cuda 9.0 getting a segmentaion fault(core dumped).

**Comment by ThilinaRajapakse** [comment]
Then I guess it's a good time to upgrade to CUDA 10. 😉

**Comment by savethebeesandseeds** [comment]
This post solved for me: https://github.com/huggingface/transformers/issues/5359
----
Here was how i solved my case:

>>> import simpletransformers ---> works
>>> from simpletransformers.classification import ClassificationModel ---> (ERROR): segmentation fault (core dumped) 

To solve I went into ../lib/python3.6/site-packages/simpletransformers/classification/classification_model.py

Tried each one of the imports.
...
An error rised when: >>> import transformers
witch it self had a dependency on "import sentencepiece"

so the problem was solved for me when I downgraded such package to 0.1.91.
$ pip install sentencepiece==0.1.91
