### ISSUE TITLE
Getting error "TypeError: must be str, not float" when i try to train T5 model.

### ISSUE THREAD

**Issue by adithyaan-creator** [ThilinaRajapakse/simpletransformers#891]
The dataset has 3 columns - prefix, input_text and target_text, all are strings. @ThilinaRajapakse Could be a very small issue, and would appreciate the help. 
Thanks.
![image](https://user-images.githubusercontent.com/54103522/101753920-2d86aa80-3af9-11eb-8b2d-7d8c69c7ed53.png)

**Comment by sarapapi** [comment]
Could you post your code? I think that you're passing a number instead of a string in input_text and/or prefix columns. 
Maybe, when you load the tsv, you have to specify `astype(str)`.

**Comment by ThilinaRajapakse** [comment]
> Could you post your code? I think that you're passing a number instead of a string in input_text and/or prefix columns.
> Maybe, when you load the tsv, you have to specify `astype(str)`.

Yes, it's generally a good idea to do `astype(str)` with T5 unless you are _absolutely_ sure there are no numeric strings in your data.
