### ISSUE TITLE
SimpleDataset stops while creating features from dataset file

### ISSUE THREAD

**Issue by mattivi** [ThilinaRajapakse/simpletransformers#894]
**Describe the bug**
I am training an Electra model from scratch with a dataset of about 30M rows (each line is a sentence). Dataset type is 'simple'. The process stop at around 9.9M sample (see screenshots below) with  TOKENIZERS_PARALLELISM True and also with False. 
Any idea where is the problem and how to solve it? 

**To Reproduce**
1. Have a dataset with more than 20M rows
2. Run electra model as 
```
model = LanguageModelingModel(
    "electra",
    None,
    args=model_args,
    train_files=train_files[0]
)
```
3. Process will be stuck at about 10M rows. It should be in class SimpleDataset.

**Expected behavior**
Not crash and provide error.

**Screenshots**
[00:11:55] Reading files (1985 Mo)              █████████████████████████                 100
[00:00:00] Tokenize words                           █████████████████████████ 61025    /    61025
[00:01:21] Count pairs                                   █████████████████████████ 61025    /    61025
[00:00:00] Compute merges                        █████████████████████████ 29920    /    29920

INFO:simpletransformers.language_modeling.language_modeling_model: Training of None tokenizer complete. Saved to /my-model/.
INFO:simpletransformers.language_modeling.language_modeling_model: Training language model from scratch
INFO:simpletransformers.language_modeling.language_modeling_utils: Creating features from dataset file at /my-model/cache
 34%|█████████▌                                                                                                           | 9918001/29458218 [58:40<1:58:06, 2757.56it/s]

**Additional context**
`simpletransformers` version: 0.51.3
`tokenizers` version: 0.9.4
`transformers` version: 4.1.0.dev0
Python version: Python 3.7.9 (default, Aug 31 2020, 12:42:55)
[GCC 7.3.0] :: Anaconda, Inc. on linux
PyTorch version: 1.7.1

**Comment by ThilinaRajapakse** [comment]
Is it possible that you are running out of memory? If you are using multiprocessing, can you try it with `use_multiprocessing` set to False?

**Comment by mattivi** [comment]
Yes, it runs out of memory. I opened a feature request to support HuggingFace Datasets that would solve the problem.
Thanks for looking into this!
