### ISSUE TITLE
Error during loading T5 model

### ISSUE THREAD

**Issue by safakkbilici** [ThilinaRajapakse/simpletransformers#897]
Hi again. I trained my T5 model and saved the config files and weights. The scripts is

```python
from simpletransformers.t5 import T5Model
model_args = {
    "reprocess_input_data": True,
    "overwrite_output_dir": True,
    "max_seq_length": 256,
    "eval_batch_size": 128,
    "num_train_epochs": 1,
    "save_eval_checkpoints": False,
    "use_multiprocessing": False,
    "num_beams": None,
    "do_sample": True,
    "max_length": 50,
    "top_k": 50,
    "top_p": 0.95,
    "num_return_sequences": 3,
}
model = T5Model("t5","/content/drive/My Drive/outputs/best_model", args=model_args)
```

And the files are:

![files](https://user-images.githubusercontent.com/44443472/102100821-ec650200-3e3a-11eb-8e92-480df8c42be9.png)

But when I load the model, this error happens:

![error](https://user-images.githubusercontent.com/44443472/102100859-f850c400-3e3a-11eb-9d32-284468732c1c.png)

What am I missing..?

**Comment by sarapapi** [comment]
`model = T5Model("t5","/content/drive/My Drive/outputs/best_model", args=model_args)`
I think that you have to specify which version of t5 you want, like `t5-base` instead of only `t5`

**Comment by safakkbilici** [comment]
> `model = T5Model("t5","/content/drive/My Drive/outputs/best_model", args=model_args)`
> I think that you have to specify which version of t5 you want, like `t5-base` instead of only `t5`

No, it is "t5". "t5-base" would be a KeyError. There is something that I cannot solve. I will start to think that my checkpoints are somehow corrupted. But it shouldn't be.

**Comment by sarapapi** [comment]
> > `model = T5Model("t5","/content/drive/My Drive/outputs/best_model", args=model_args)`
> > I think that you have to specify which version of t5 you want, like `t5-base` instead of only `t5`
> 
> No, it is "t5". "t5-base" would be a KeyError. There is something that I cannot solve. I will start to think that my checkpoints are somehow corrupted. But it shouldn't be.

For me, it works perfectly specifying the model. Could you post your full code?

**Comment by safakkbilici** [comment]
> > > `model = T5Model("t5","/content/drive/My Drive/outputs/best_model", args=model_args)`
> > > I think that you have to specify which version of t5 you want, like `t5-base` instead of only `t5`
> > 
> > 
> > No, it is "t5". "t5-base" would be a KeyError. There is something that I cannot solve. I will start to think that my checkpoints are somehow corrupted. But it shouldn't be.
> 
> For me, it works perfectly specifying the model. Could you post your full code?

Sure:

```python
df = pd.read_csv('../data/df_to_model.csv')
eval_df = df.sample(frac=0.2, random_state=101)
train_df = df.drop(eval_df.index)
train_df['prefix'] = "summarize"
eval_df['prefix'] = "summarize"

model_args = {
    "reprocess_input_data": True,
    "overwrite_output_dir": True,
    "max_seq_length": 256,
    "train_batch_size": 8,
    "num_train_epochs": 1,
    "save_eval_checkpoints": True,
    "save_steps": -1,
    "use_multiprocessing": False,
    "evaluate_during_training": True,
    "evaluate_during_training_steps": 15000,
    "evaluate_during_training_verbose": True,
    "fp16": False,
    "wandb_project": "Summarization with T5",
}
#train
model = T5Model("t5", "t5-base", args=model_args)
model.train_model(train_df, eval_data=eval_df)

#load
model_args = {
    "reprocess_input_data": True,
    "overwrite_output_dir": True,
    "max_seq_length": 256,
    "eval_batch_size": 128,
    "num_train_epochs": 1,
    "save_eval_checkpoints": False,
    "use_multiprocessing": False,
    "num_beams": None,
    "do_sample": True,
    "max_length": 50,
    "top_k": 50,
    "top_p": 0.95,
    "num_return_sequences": 3,
}
model = T5Model("t5","outputs/best_model", args=model_args)
```

**Comment by safakkbilici** [comment]
[SOLVED]: 
Changing output_dir and best_model_dir with "/content/drive/My Drive/outputs" and "/content/drive/My Drive/outputs/best_model" int model_args is enough.

The checkpoints are corrupted when you download and again load it into drive.
