### ISSUE TITLE
Multi-task learning

### ISSUE THREAD

**Issue by manueltonneau** [ThilinaRajapakse/simpletransformers#902]
Hi @ThilinaRajapakse :)

I found several closed issues (#49 and #677) on support for multi-task learning and was wondering whether we could look into implementing it in simpletransformers.

As mentioned in #677, it is already supported by two other packages built on top of transformers:

> There is FARM (https://github.com/deepset-ai/FARM/) which supports multi head learning (the same dataset annotated on different levels) or jiant (https://github.com/jiant-dev/jiant) which supports multi dataset scenarios.

 Let me know if you would be down for it and how I could help.

**Comment by ThilinaRajapakse** [comment]
Do you have anything specific in mind to be implemented? I haven't really given this much thought.

**Comment by manueltonneau** [comment]
I'm no expert at all in multi-task learning but I was thinking a first nice-to-have would be the possibility to have multiple heads on top of a BERT-type encoder and to fine-tune them at the same time on one dataset. 

Say for instance that you have a dataset that is labelled for text classification but also NER, you could have both Classification and a NER head on top. 

We could have a new class called `MultiTaskModel` that takes as input the data path and then a `heads` argument where the user would define the number and type of heads (for instance, `heads = [ 'ClassificationHead', 'NERHead']`. This `MultiTaskModel` class would look a lot like the `ClassificationModel` class, just need to add the possibility to have more heads. Does that make sense?

**Comment by ayan-vitraya** [comment]
> Do you have anything specific in mind to be implemented? I haven't really given this much thought.

For now, I would look into MT-DNN. That's an excellent resource to start with.

**Comment by ThilinaRajapakse** [comment]
> I'm no expert at all in multi-task learning but I was thinking a first nice-to-have would be the possibility to have multiple heads on top of a BERT-type encoder and to fine-tune them at the same time on one dataset.
> 
> Say for instance that you have a dataset that is labelled for text classification but also NER, you could have both Classification and a NER head on top.
> 
> We could have a new class called `MultiTaskModel` that takes as input the data path and then a `heads` argument where the user would define the number and type of heads (for instance, `heads = [ 'ClassificationHead', 'NERHead']`. This `MultiTaskModel` class would look a lot like the `ClassificationModel` class, just need to add the possibility to have more heads. Does that make sense?

Yes, that makes sense. I'll give it some thought (when I have some free time) and see what I can come up with.
