### ISSUE TITLE
Broken link on supported models

### ISSUE THREAD

**Issue by Sphinxs** [ThilinaRajapakse/simpletransformers#903]
On [MultiLabelClassificationModelPermalink](https://simpletransformers.ai/docs/classification-models/#multilabelclassificationmodel) the [link](https://simpletransformers.ai/docs/intro-classification/) to the 'supported models' is broken:

![image](https://user-images.githubusercontent.com/19755014/102351344-0c084180-3f85-11eb-89f0-62b9f18a231b.png)

![image](https://user-images.githubusercontent.com/19755014/102351356-11fe2280-3f85-11eb-91eb-6e228e99624d.png)

I think it needs to be replaced by 'Supported Model Types' [link](https://simpletransformers.ai/docs/classification-specifics/#supported-model-types) and also add the 'Pretrained Models' from [Hugging Face](https://huggingface.co/transformers/pretrained_models.html) and 'Summary' from [Hugging Face](https://huggingface.co/transformers/summary.html)

**Comment by ThilinaRajapakse** [comment]
Thanks for the heads up. The link will be updated in the next version.
