### ISSUE TITLE
Support for HuggingFace Datasets

### ISSUE THREAD

**Issue by mattivi** [ThilinaRajapakse/simpletransformers#905]
**Is your feature request related to a problem? Please describe.**
I am dealing with huge dataset of 100M+ lines. With the current approach the dataset does not fit into memory and thus can't train an Electra model with all data available, but only with a tiny subset (around 5M).

**Describe the solution you'd like**
[HuggingFace datasets](https://github.com/huggingface/datasets) would solve the problem by minimising the memory footprint (Apache Arrow) and allow smart caching.

**Comment by Pacman1984** [comment]
Have you tried lazyloading?

https://simpletransformers.ai/docs/classification-specifics/#lazy-loading-data

**Comment by mattivi** [comment]
Is see that lazy loading is available as LazyClassificationDataset, LazyNERDataset and LazyQuestionAnsweringDataset. 
I need to pre-train a Language Model for LM tasks, any idea how to adapt?

**Comment by ThilinaRajapakse** [comment]
Lazy loading isn't implemented yet for LM tasks, unfortunately. It would be nice to have Datasets integration and it's something I want to add. It didn't look quite ready when I last checked it (a long time ago tbh) but I'll see if I can find some time to look into it.

**Comment by mattivi** [comment]
Thanks!
