### ISSUE TITLE
onnx exports for bert-based models raise ValueError

### ISSUE THREAD

**Issue by guydepauw** [ThilinaRajapakse/simpletransformers#906]
**Describe the bug**

Exporting a bert-based model to onnx, loading it and using it for inference raises an error

`ValueError: Model requires 3 inputs. Input Feed contains 2`

**To Reproduce**

These steps:
[https://simpletransformers.ai/docs/tips-and-tricks/#converting-a-simple-transformers-model-to-the-onnx-format](https://simpletransformers.ai/docs/tips-and-tricks/#converting-a-simple-transformers-model-to-the-onnx-format)

but with 

```
model = ClassificationModel(
    "bert",
    "bert-base-uncased",
    args=model_args,
)
```

**Expected behavior**

Exports can be used for inference

**Desktop (please complete the following information):**
 - OS UBUNTU

**Comment by ThilinaRajapakse** [comment]
The code example in the docs works for me without any errors.

**Comment by guydepauw** [comment]
It does for roberta. Doet is work for you for bert as well? Full code below produces the error I mentioned.

```
from time import time

from simpletransformers.classification import (
    ClassificationModel,
    ClassificationArgs,
)


model_args = ClassificationArgs()
model_args.overwrite_output_dir = True


# Create a TransformerModel
model = ClassificationModel(
    "bert",
    "bert-base-uncased",
    use_cuda=False,
    args=model_args,
)

start = time()
print(model.predict(["test " * 450]))
end = time()
print(f"Pytorch CPU: {end - start}")

model.convert_to_onnx("onnx_outputs")

model_args.dynamic_quantize = True

model = ClassificationModel(
    "bert",
    "onnx_outputs",
    args=model_args,
)

start = time()
print(model.predict(["test " * 450]))
end = time()
print(f"ONNX CPU (Cold): {end - start}")

start = time()
print(model.predict(["test " * 450]))
end = time()
print(f"ONNX CPU (Warm): {end - start}")
```

**Comment by ThilinaRajapakse** [comment]
Ah, I missed that the issue was with BERT. I'm getting the same error. Unfortunately, it seems to be coming from the Huggingface BERT implementation.

**Comment by FahriBilici** [comment]
I have same problem. is there any solution?

**Comment by Nikita-Sherstnev** [comment]
I faced the same problem. Any news?

**Comment by forrestfaraday** [comment]
I have  the same issue, is there any solution?

I converted to model to onnx by using optimum. When I tried to load onnx model to st, I faced error.
