### ISSUE TITLE
Add sampler as a model argument 

### ISSUE THREAD

**Issue by alaverghett** [ThilinaRajapakse/simpletransformers#908]
For classification, would it be possible to add the sampler we want to use for the train set as an argument? That way, if for instance, we wanted to use the SequentialSampler rather than the RandomSampler, we could specify this when initializing the ClassificationModel?

**Comment by ThilinaRajapakse** [comment]
I'm not sure this is a common enough requirement to warrant adding an extra argument. Why do you need the training sampler to be sequential?

**Comment by alaverghett** [comment]
Recently I worked on a project involving curriculum learning, where basically the optimal order for the training set was determined by a separate model. In this case, using the random sampler would have invalidated the results we were trying to achieve, so I needed to change the code to use the sequential sampler.

I agree though that in most cases the random sampler is appropriate.

**Comment by ThilinaRajapakse** [comment]
Interesting!

But, I think we don't need to add a feature for it considering that the random sampler will be used in most cases.
