### ISSUE TITLE
ValueError: too many dimensions 'str'

### ISSUE THREAD

**Issue by giandrickdabian** [ThilinaRajapakse/simpletransformers#909]
Hi , I keep getting this error and I do not know how to solve it. Any tips or suggestions would be appreciated it.

This is the link to my notebook that shows my entire code and issue.

https://colab.research.google.com/drive/1ikol2D8mmiIPKhNHbcFlTfVpuU_Gf9BZ?usp=sharing

**Comment by ThilinaRajapakse** [comment]
This is usually caused by incorrect input formats. Please describe what you are trying to do and provide _minimal_ code examples to illustrate the issue.
