### ISSUE TITLE
Is it possible to use miniLM or other models using simpletransformers.classification models

### ISSUE THREAD

**Issue by adithyaan-creator** [ThilinaRajapakse/simpletransformers#912]
Hi @ThilinaRajapakse ,
is it possible to train miniLM or other models[xlm] using the classification[simpletransformers.classification] training in simpleTransformers?
If not, any direction is appreciated.
Thanks.

**Comment by ThilinaRajapakse** [comment]
MiniLM isn't supported atm. You can find all supported models for classification [here](early_stopping_metric_minimize).
