### ISSUE TITLE
While training custom convAI model the model is asking us to pass lm_labels

### ISSUE THREAD

**Issue by techthiyanes** [ThilinaRajapakse/simpletransformers#914]
**Describe the bug**
While training custom convAI model the model is asking us to pass lm_labels.
**To Reproduce**
The below error trace is getting displayed.
TypeError                                 Traceback (most recent call last)
<ipython-input-12-c760493476b4> in <module>()
----> 1 model.train_model("/content/drive/MyDrive/Colab Notebooks/d.json",lm_labels=["t","t2"])

2 frames
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

**TypeError: forward() got an unexpected keyword argument 'lm_labels'**
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS

**Additional context**

**Comment by nikirg** [comment]
I had an error like this when I set the "model_type" argument (ConvAIModel) to the "gpt", while I used the GPT2 as a pre-train model (model_name argument in ConvAIModel)
