### ISSUE TITLE
When using eval_df for MultiLabelClassificationModel, there is 'TypeError: 'bool' object is not callable'

### ISSUE THREAD

**Issue by Adel-Memariani** [ThilinaRajapakse/simpletransformers#915]
Whenever I add my evaluation dataset to the **MultiLabelClassificationModel**, there is the following error:

```
/usr/local/lib/python3.6/dist-packages/simpletransformers/classification/classification_model.py in compute_metrics(self, preds, labels, eval_examples, multi_label, **kwargs)
   1241         extra_metrics = {}
   1242         for metric, func in kwargs.items():
-> 1243             extra_metrics[metric] = func(labels, preds)
   1244 
   1245         if multi_label:

TypeError: 'bool' object is not callable
```

Here is my code:

```
from simpletransformers.classification import MultiLabelClassificationModel, MultiLabelClassificationArgs

MODEL_ARGs = MultiLabelClassificationArgs(
    reprocess_input_data=True,
    overwrite_output_dir=True,
    num_train_epochs=1,
    train_batch_size=16,
    evaluate_during_training=True,
    evaluate_during_training_verbose=True,
    )

model = MultiLabelClassificationModel('roberta', 'path_to_my_pretrained_model',
                                              num_labels=NUM_LABELS,
                                              args=MODEL_ARGs,
                                      )

model.train_model(train_df=train_data, eval_df=validation_data, output_dir='my_output_dir')
```

If I remove the eval_df and evaluate_during_training=True, then the model will work. However, I want the evaluation during  training. I appreciate any help!

**Comment by ThilinaRajapakse** [comment]
I'm not getting this error. Do you get it with the minimal example as well?

**Comment by Adel-Memariani** [comment]
I don't get it when I use this as a minimal example:

`model.train_model(train_df=train_data, eval_df=validation_data)`

It is good and we can close this issue. However, I really want to add f1, recall and precision metrics to the evaluation during training (for multi-label classification), so it would be great if we could solve the issues with additional metrics/parameters. Because monitoring the f1 score during training is so important for multi-label classification.
