### ISSUE TITLE
Issue in T5 model 

### ISSUE THREAD

**Issue by ayan-vitraya** [ThilinaRajapakse/simpletransformers#919]
**Describe the bug**
When I am trying to load the model with some arguments, the error is observed. This error was not observed earlier. But I observed it today only. 

**To Reproduce**
I am using Google colab. I have the apex installed and the simpletransformers package installed. 
from simpletransformers.t5 import T5Model

model = T5Model("t5","t5-base",args={'num_train_epochs': 10, 'preprocess_inputs': True, 'overwrite_output_dir': True, 'save_model_every_epoch' : False},use_cuda=True, )
model.train_model(train_df,output_dir =model_path)
preds = model.predict(to_predict)

**Error **
TqdmDeprecationWarning: Please use `tqdm.gui.tqdm(...)` instead of `tqdm(..., gui=True)`
---------------------------------------------------------------------------
TqdmDeprecationWarning                    Traceback (most recent call last)
<ipython-input-28-128169f1f19d> in <module>()
      1 from simpletransformers.t5 import T5Model
      2 
----> 3 model = T5Model("t5","t5-base",args={'num_train_epochs': 10, 'preprocess_inputs': True, 'overwrite_output_dir': True, 'save_model_every_epoch' : False},use_cuda=True, )
      4 model.train_model(train_df,output_dir ='/content/drive/My Drive/experiments/t5_model/')
      5 

6 frames
/usr/local/lib/python3.6/dist-packages/tqdm/std.py in update(self, n)
   1203         if n < 0:
   1204             self.last_print_n += n  # for auto-refresh logic to work
-> 1205         self.n += n
   1206 
   1207         # check counter first to reduce calls to time()

TqdmDeprecationWarning: Please use `tqdm.gui.tqdm(...)` instead of `tqdm(..., gui=True)`

**Comment by ThilinaRajapakse** [comment]
Looks like something changed in the Colab environment. Can you try updating `tqdm`? If that doesn't work, try using an earlier version of `tqdm`.

**Comment by EduardoRodriguesMorais** [comment]
Thanks for the tip @ThilinaRajapakse. I had the same problem with the tqdm library when instantiating `NERModel`. Here it worked in version `tqdm==4.47.0`

**Comment by saurabh502** [comment]
Hi, 
Facing similar issue because of tqdm.  @ThilinaRajapakse  could you please specify exact version we need to install for tqdm?

Thanks

**Comment by saurabh502** [comment]
Before installing simpletransformers, install tqdm

`!pip install tqdm==4.47.0 `

This worked for me
