### ISSUE TITLE
eval_model() versus predict()

### ISSUE THREAD

**Issue by namrathaurs** [ThilinaRajapakse/simpletransformers#92]
I noticed that there are two methods available with the `simpletransformers` library for `ClassificationModel`, **eval_model( )** and **predict( )** methods. Except for the difference that **predict( )** returns predictions made by the model, is there any other difference between their functionalities that I may have overlooked but helps determine which of the two needs to be used in a given situation?

Hoping to get this clarified. Thanks in advance!

**Comment by ThilinaRajapakse** [comment]
The difference is that `eval_model()` needs the ground truth labels while `predict()` does not. Use `eval_model()` when you want to test the performance of the model, and `predict()` when you want to use the model for making predictions on unseen data. The `predict()` function can be used for real-time inference as well, by wrapping it inside a for loop for example.

**Comment by namrathaurs** [comment]
Thanks for the clarification. And, thanks for sharing your library to get started on using transformer-based models written in Hugging Face. Closing this issue. Cheers!
