### ISSUE TITLE
model.eval_model() returns a 'local variable dataset referenced before assignment error'

### ISSUE THREAD

**Issue by Walid-Rahman2** [ThilinaRajapakse/simpletransformers#925]
**Describe the bug**
Whenever I try to evaluate the model on my test set, I get the following error: 

/usr/local/lib/python3.6/dist-packages/simpletransformers/question_answering/question_answering_model.py in load_and_cache_examples(self, examples, evaluate, no_cache, output_examples)
    249 
    250         if output_examples:
--> 251             return dataset, examples, features
    252         return dataset
    253 

UnboundLocalError: local variable 'dataset' referenced before assignment

**To Reproduce**

After training the model, I send in a list of qa data structured like SQuAD. 

result, text = model.eval_model(all_qa_data[5500:])

I have also sent in a josn file path, but the issue persists

**Expected behavior**
I expected an output like this: {'correct': 248, 'similar': 276, 'incorrect': 170, 'eval_loss': -9.224048132183908}

**Desktop (please complete the following information):**
 - Google colab, so Linux

**Additional context**
This is finetuning distilbert for question answering.

**Comment by ThilinaRajapakse** [comment]
This will be fixed in the next update. A temporary workaround is to set `model_args.reprocess_input_data = True`.

**Comment by Walid-Rahman2** [comment]
Awesome. Thank you!!
________________________________

**Comment by Tdrinker** [comment]
> I have the same problem, is there another solution ?? ![Capture](https://user-images.githubusercontent.com/46635239/137812324-3e576509-88a9-4329-bf41-dca33a44af85.PNG)

Hello I am facing the same issue. Do you have a solution for this?
