### ISSUE TITLE
Support for Custom Tokenizers based on tokenizers.Tokenizer class

### ISSUE THREAD

**Issue by gstranger** [ThilinaRajapakse/simpletransformers#929]
**Is your feature request related to a problem? Please describe.**
While the provided tokenizer models from huggingface are useful, they do not work well on a non-language based corpus.  In these cases we can manually train a tokenizer based on our custom dataset. However, `simpletransformers` leverages the `PretrainedTokenizer` class which isn't compatible with the `tokenizers.Tokenizer` class. For my particular case I've trained a `WordLevel` model similar to the walkthrough huggingface has described [here](https://huggingface.co/docs/tokenizers/python/master/quicktour.html). If this feature were implemented it would make solving sequence generation problems that can be modeled as language modeling problems much easier. 

**Describe the solution you'd like**
Allow a user to instantiate a custom tokenizer based on the `tokenizers.Tokenizer` class for LanguageModeling purposes. 

**Describe alternatives you've considered**
I've attempted to train and customize a tokenizer based on one of the included models, however the vocabulary ends up "bloated" in such a way that the data becomes "corrupted" when they are encoded by the tokenizer. 

**Additional context**
[LanguageModel utils](https://github.com/ThilinaRajapakse/simpletransformers/blob/master/simpletransformers/language_modeling/language_modeling_utils.py)

**Also wanted to say thanks for creating this library and all the work put into it, it has made my life much easier when it comes to solving nlp based problems.**

**Comment by ThilinaRajapakse** [comment]
The `PretrainedTokenizer` functionality is quite integral to Simple Transformers. Unfortunately, I'm not sure whether we can easily support a tokenizer if it isn't compatible with `PretrainedTokenizer`.

**Comment by ty5491003** [comment]
> The `PretrainedTokenizer` functionality is quite integral to Simple Transformers. Unfortunately, I'm not sure whether we can easily support a tokenizer if it isn't compatible with `PretrainedTokenizer`.

@ThilinaRajapakse So do you consider adding a custom tokenizer function only in the case of training model from scratch? I think it's a good idea.

**Comment by ThilinaRajapakse** [comment]
I would recommend creating your own tokenizer by subclassing the PretrainedTokenizer class. I don't think it's a good idea to allow any arbitrary tokenizer to be used because that would make it impossible to ensure that the rest of the code works as expected (e.g. saving and loading would break).
