### ISSUE TITLE
question_answering models evaluation does not handle the impossible answers correctly

### ISSUE THREAD

**Issue by Tahsin-Mayeesha** [ThilinaRajapakse/simpletransformers#93]
Here in this function : 
https://github.com/ThilinaRajapakse/simpletransformers/blob/134cbf85f7c4ee0cb3ae92d0bd9d6996ba100470/simpletransformers/question_answering/question_answering_model.py#L579

It seems to assume there is always an answer available,  when its building the truth_dictionary but squad 2.0 has many impossible questions.

![image](https://user-images.githubusercontent.com/17886829/70748828-fbf7c980-1d54-11ea-963c-ad063586540d.png)

A typical impossible question looks like this : 

![image](https://user-images.githubusercontent.com/17886829/70748928-39f4ed80-1d55-11ea-8bef-ae0c842af6c9.png)

Where the answer is an empty list and it does not have a single dictionary element with the text value represent. So sending in Squad like datasets is giving errors. I'll do a random split of Squad train and train a model on it to reproduce the issue fully. 

Note, feel free to correct me if I'm wrong. This is the error I'm getting when sending in data:

![image](https://user-images.githubusercontent.com/17886829/70756465-d4116180-1d66-11ea-82c9-4f0995938d25.png)

**Comment by Tahsin-Mayeesha** [comment]
Here's a notebook trying to reproduce the error with dummy data.
How should we handle this situation?


https://colab.research.google.com/drive/1czcyELTJKm1TgFAFJ4T9W03JyhhzuCe3

**Comment by Tahsin-Mayeesha** [comment]
Also, how we should be formatting impossible questions then? If I do include a correct answer to the imposible question , what should be the answer_start token? @ThilinaRajapakse  , really sorry for bothering but we are doing a class project  with the library on QA and don't want to switch.

**Comment by ThilinaRajapakse** [comment]
This should be fixed now. Let me know if the issue persists.

Thank you for the detailed bug report. Much easier to provide a fix when I don't have to play the detective in my own crime!

**Comment by Tahsin-Mayeesha** [comment]
@ThilinaRajapakse I'll test again and inform! Really sorry for late reply. I was super busy. Also can you add support for the QA Evaluation metrics please? :)

**Comment by Tahsin-Mayeesha** [comment]
I think

**Comment by Tahsin-Mayeesha** [comment]
It works now.
