### ISSUE TITLE
wandb sweeps accumulates GPU memory

### ISSUE THREAD

**Issue by nhsmith85** [ThilinaRajapakse/simpletransformers#932]
**Describe the bug**
When running a GPU sweep using any NERModel() or ClassificationModel() such as bert, distilbert, roberta, etc. the sweep retains some amount of GPU memory on every run. I tried to add a statement in my run functions passed to the agent to clear gpu cache but it did not work. 

**To Reproduce**
```

sweep_config = {
    
    'name' : 'batch-16',
    'method': 'bayes', #grid, random, bayes
    'metric': {
      'name': 'f1_score',
      'goal': 'maximize'
      },

    'parameters': {
        
        'learning_rate': {'min': 0, 'max': 4e-4},
        'num_train_epochs': {'min': 1, 'max': 10},
        #'train_batch_size': {'values': [16, 32]},
        'weight_decay': {'min': 0, 'max': 0.1 } # {'values': [0, 0.01, 0.03]}

        },

   'early_terminate': {'type': 'hyperband', 'min_iter': 1}
}


sweep_id = wandb.sweep(sweep_config, project=wandb_project)


import gc

def run_training():

    # Initialize a new wandb run
    wandb.init()

    # Create a TransformerModel
    model = NERModel(
    model_type = model_type,
    model_name = model_name,
    args = model_args,
    sweep_config = wandb.config
    )

    # Train the model
    model.train_model(train_data = train, 
                      eval_data = val)
    
    
    # Sync wandb
    wandb.join()

    # clear gpu and cpu ram
    gc.collect()
    torch.cuda.empty_cache()

```

**Expected behavior**
Cleared GPU and CPU ram on every run of sweep. As we can see below there is an incremental increase in GPU memory allocated for every run in a sweep. 

**Screenshots**
![image](https://user-images.githubusercontent.com/9698634/103464702-b44b3380-4d03-11eb-8c92-a2b91bb80da3.png)

**Desktop (please complete the following information):**
 - OS

**Additional context**

**Comment by ThilinaRajapakse** [comment]
I'm not observing the same behaviour, i.e the GPU memory usage remains constant.
![W B Chart 1_5_2021, 12_42_09 AM](https://user-images.githubusercontent.com/17320131/103570509-38adda00-4eef-11eb-91e7-5bc7d49631be.png)

**Comment by nhsmith85** [comment]
I wonder if it has anything to do with running in wandb in Google colab or with notebooks? I tried the example code you have on the hyperparam [example](https://towardsdatascience.com/hyperparameter-optimization-for-optimum-transformer-models-b95a32b70949) but again seeing this same issue with the GPU memory usage accumulating each run. Below is the gpu memory allocation from running the tutorial code. This same issue occurs if I run from a .py file in Google Colab as opposed to executing it line-by-line in a Colab notebook.

**Comment by ThilinaRajapakse** [comment]
In that case, it likely is an issue with Colab. You'd probably have to run the sweep "manually" according to the instructions from W&B.

**Comment by akrahdan** [comment]
Hi @ThilinaRajapakse I am getting the same memory allocation errors for in colab, kaggle, and on-premise servers. Is there anything you can do to help?

**Comment by ThilinaRajapakse** [comment]
Unfortunately, I don't think I can. In my experience, it's nearly impossible to get notebook environments to release GPU memory properly.

**Comment by aryopg** [comment]
I recently encountered this error using a script (not a notebook). Is there a way to release the GPU memory properly after a sweep run?
