### ISSUE TITLE
Error on multi_label_classification->train_model with eval_df

### ISSUE THREAD

**Issue by aucan** [ThilinaRajapakse/simpletransformers#94]
Although I give eval_df as an argument when calling the train_model function (MultiLabelClassification ), I get the following error.
ValueError: evaluate_during_training is enabled but eval_df is not specified. Pass eval_df to model.train_model() if using evaluate_during_training.

https://github.com/ThilinaRajapakse/simpletransformers/blob/master/simpletransformers/classification/multi_label_classification_model.py#L114

![image](https://user-images.githubusercontent.com/1591145/70783635-ebb60d80-1d99-11ea-9e99-4f0339a3ff10.png)

**Comment by ThilinaRajapakse** [comment]
This should be fixed now. Thanks for pointing out the bug and the cause of the bug!

**Comment by josh-cooper** [comment]
Still getting this error.

**Comment by ThilinaRajapakse** [comment]
Which version of the library are you using?

**Comment by josh-cooper** [comment]
The latest. I've also tried installing from github.
https://github.com/ThilinaRajapakse/simpletransformers/blob/master/simpletransformers/classification/multi_label_classification_model.py#L114
Still seems to show the original cause that aucan pointed out.

**Comment by ThilinaRajapakse** [comment]
Yeah, I just noticed that some changes are missing. Something must have gone wrong with a git push as I had to reinsy my OS recently.

**Comment by josh-cooper** [comment]
Yeah I just realised I can install an older version (0.7.12) and it works.

**Comment by ThilinaRajapakse** [comment]
This should be fixed now with 0.11.2.
