### ISSUE TITLE
TypeError: special token bos_token has to be either str or AddedToken but got: <class 'dict'>

### ISSUE THREAD

**Issue by eashan2798** [ThilinaRajapakse/simpletransformers#942]
I have fine-tuned the Multi classification model on ATIS dataset and trained the model with the same input.But when I am trying to load the checkpoint it is giving me this Type Error
![Screenshot from 2021-01-08 17-58-49](https://user-images.githubusercontent.com/68741106/104015821-3394a780-51db-11eb-8d88-00e1980b324a.png)

**Comment by ThilinaRajapakse** [comment]
Can you please share **minimal** examples of your training code and your model loading code?
