### ISSUE TITLE
Reducing latency on inference

### ISSUE THREAD

**Issue by ricknichols84** [ThilinaRajapakse/simpletransformers#95]
Hi Thilina,
I'm looking to reduce latency when i execute model.predict. Are there any methods in the code I can execute/filter in order to reduce inference time? I know I can always add more compute but i'm looking to see if the code can be optimized further.

Thank you and great repo!

**Comment by kinoute** [comment]
What model are you using? It seems really model-dependent. The bigger the model, the slower the predictions will be.

**Comment by ThilinaRajapakse** [comment]
Indeed. While the predict function probably could be optimized further by trimming away anything that is not needed in your use case, we are talking about almost negligible gains.

**Comment by ricknichols84** [comment]
__> What model are you using? It seems really model-dependent. The bigger the model, the slower the predictions will be._

I'm using Roberta for multi-class sequence classification. 

Inference is not just dependent on model size, but also input and output text is also a factor (in addition to compute). Which is why a single sentence inference taking several seconds came as a surprise to me, thought it would be faster.

**Comment by ThilinaRajapakse** [comment]
It's not _solely_ dependent on the model size, but it is still the dominant factor. Another significant factor is the maximum sequence length.

A single sentence inference shouldn't take several seconds unless you are doing it on a CPU. Although the time taken to load the model into GPU memory might have an impact if it has to be done for each prediction, for example from a script.
Also, the prediction code is designed for a list of inputs so there is some overhead from that. The single sentence is still loaded into a Dataloader before being sent to the GPU.

**Comment by ricknichols84** [comment]
regarding maximum sequence length: are you referring to the sequence length assigned during training?

**Comment by ThilinaRajapakse** [comment]
I was. `max_seq_length`, to be concrete. Now that I think about it, I can say for sure that a bigger `max_seq_length` results in longer training times, but I can't say I've tested its effect on inference. Logically, it makes sense that inference would take longer as well though.

**Comment by ricknichols84** [comment]
Thank You

**Comment by ThilinaRajapakse** [comment]
You are welcome! Please feel free to reopen if you need more info.

**Comment by g-laz77** [comment]
`max_seq_len` is definitely leading to longer training times, however I don't see it affecting the inference time. This is because in the saved model files, the `tokeniser_config.json` has `max_len: 512`. Will reducing this to a smaller number speed inference time?

**Comment by ThilinaRajapakse** [comment]
Possibly, yes. There was a recent contribution which prevents padding to max length for single predictions which seems to speed up prediction for classification models.
