### ISSUE TITLE
VersionConflict Error

### ISSUE THREAD

**Issue by azizcu** [ThilinaRajapakse/simpletransformers#950]
![error](https://user-images.githubusercontent.com/63375421/104560254-d16ef300-566f-11eb-9324-c28c3d314501.png)
Please have a look i got this error for last couple of days .
I try to solve this error many time to reinstall and upgrade simpletransformer,transformer but i am not able to solve it .

**Comment by eashan2798** [comment]
@azizcu  I am having the same issue.Were you able to resolve it?

**Comment by eashan2798** [comment]
IT WAS WORKING FINE TILL YESTERDAY

**Comment by ThilinaRajapakse** [comment]
Workaround:
Install `tokenizers==0.9.4` before install simpletransformers

In Colab for example;
```
!pip install tokenizers==0.9.4
!pip install simpletransformers
```

**Comment by eashan2798** [comment]
Yeah thanks it worked

**Comment by azizcu** [comment]
Thank You it worked perfectly

**Comment by azizcu** [comment]
`def model_train(model_name,model_type,arguments):
  # Create a ClassificationModel
  model = ClassificationModel(model_name, 
                              model_type,
                              num_labels=1, 
                              use_cuda=True, cuda_device=0, args=arguments)
  # Train the model
  model.train_model(train_df,eval_df=eval_df,)

from simpletransformers.classification import ClassificationModel
#First for Bert
model_train('bert','bert-base-uncased',train_args1)`

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-5b72818696e5> in <module>()
      1 from simpletransformers.classification import ClassificationModel
      2 #First for Bert
----> 3 model_train('bert','bert-base-uncased',train_args1)

2 frames
/usr/local/lib/python3.6/dist-packages/torch/utils/data/sampler.py in __init__(self, data_source, replacement, num_samples, generator)
    102         if not isinstance(self.num_samples, int) or self.num_samples <= 0:
    103             raise ValueError("num_samples should be a positive integer "
--> 104                              "value, but got num_samples={}".format(self.num_samples))
    105 
    106     @property

ValueError: num_samples should be a positive integer value, but got num_samples=0



after solve that issue , i got another one . i want to try sentence pair regression .can you tell me why i got the error ?
