### ISSUE TITLE
best_model_dir not working

### ISSUE THREAD

**Issue by eashan2798** [ThilinaRajapakse/simpletransformers#953]
**Describe the bug**
I have passed the best_model_dir in args dictionary for Multilabel classification model as mentioned in the documents but it is still not working as model checkpoints are stored in an output folder for all the epochs

Can you please explain how to save the best checkpoint directly ?

**Screenshots**

**Desktop (please complete the following information):**
 - OS LINUX UBUNTU 18.04

**Additional context**

**Comment by ThilinaRajapakse** [comment]
Changing the best_model_dir will mean that the best model (lowest eval_loss by default) will get saved to your directory. Other checkpoints will still be saved to `outputs`. You also need to have `eval_during_training` enabled in order for Simple Transformers to figure out what the "best model" is.

**Comment by askintution** [comment]
same problem, even add "evaluate_during_training:True"
