### ISSUE TITLE
Electra language model fintuning

### ISSUE THREAD

**Issue by AhmedIdr** [ThilinaRajapakse/simpletransformers#954]
I was just wondering how to go about finetuning an electra model where only one model is available and it is not separated into a generator and discriminator as shown in the example.

**Comment by ThilinaRajapakse** [comment]
If you want to finetune it on a specific task (e.g. classification, ner), you can use it like any other model.

```python
model = ClassificationModel("electra", "electra-base")
```

If you want to finetune the language model itself, you need both the generator and the discriminator.
