### ISSUE TITLE
Unable to add class weights for Longformer model

### ISSUE THREAD

**Issue by Timliuzhaolu** [ThilinaRajapakse/simpletransformers#959]
Hi

I was trying to set class weights in a classification model. However I can only do so using the sample code which uses roberta. 
![image](https://user-images.githubusercontent.com/74063834/104943471-bb359f80-59ad-11eb-96ce-5d9011061123.png)
When I try to implement the same code using my fine-tuned longformer it says TypeError: init() got an unexpected keyword argument 'weight'. Is it because long former does not support this weight setting feature or am I doing something wrong? 

![image](https://user-images.githubusercontent.com/74063834/104942890-e4096500-59ac-11eb-9cb3-f546fe4198e1.jpeg)

I also tried with the model from HuggingFace longformer and it still does not work.
![image](https://user-images.githubusercontent.com/74063834/104943121-2d59b480-59ad-11eb-86c9-47493d6653c9.png)

I am using 
transformers: 4.2.1
simpletransformers: 0.51.13

Thank you!

Tim

**Comment by jonas-nothnagel** [comment]
Hi @Timliuzhaolu I just ran longformer multi-label classification with class weights. You may try to replace `weight` with `pos_weight`.

Here is a specification that worked for me:
```
model = MultiLabelClassificationModel('longformer', 
                                      'allenai/longformer-base-4096', 
                                      num_labels=10, 
                                      pos_weight = weights,
                                      args={'overwrite_output_dir': True, 'max_seq_length': 4096, "save_eval_checkpoints": False, "train_batch_size": 2, 
                                            "fp16": True, "num_train_epochs": 5})
```

**Comment by Timliuzhaolu** [comment]
@jonas-nothnagel It does work for Multilabel classification.
![image](https://user-images.githubusercontent.com/74063834/105056988-ad931f00-5a6c-11eb-8eca-97fdcda9635e.png)
However pos_weight is called weight in normal classification if you check the classification_model.py. I think there is probably something wrong with the original code.
![image](https://user-images.githubusercontent.com/74063834/105057570-41fd8180-5a6d-11eb-9bd9-ef10b5d79342.png)


Have you tried ClassificationModel using weight?

**Comment by ThilinaRajapakse** [comment]
The longformer model used in `ClassificationModel` is directly from Huggingface so it doesn't support class weights atm. The other model types have a slightly modified implementation to allow weights.
