### ISSUE TITLE
MT5 Tokenizer not defined in Multilabel Classification Model

### ISSUE THREAD

**Issue by NumberSpace** [ThilinaRajapakse/simpletransformers#963]
When attempting to import the Multilabel Classification Model I receive an error that the MT5 tokenizer is not defined. Similarly to another issue the following code also produces errors: 

from simpletransformers.t5 import T5Model
ImportError                               Traceback (most recent call last)
<ipython-input-63-ccaa022d2bdf> in <module>()
     15 get_ipython().system('pip install simpletransformers')
     16 import simpletransformers
---> 17 from simpletransformers.t5 import T5Model

1 frames
/usr/local/lib/python3.6/dist-packages/simpletransformers/t5/t5_model.py in <module>()
     18 from torch.utils.data.distributed import DistributedSampler
     19 from tqdm.auto import tqdm, trange
---> 20 from transformers.models.t5 import T5Config, T5ForConditionalGeneration, T5Tokenizer
     21 from transformers.optimization import (
     22     get_constant_schedule,

ImportError: cannot import name 'T5Tokenizer'

from simpletransformers.classification import(MultiLabelClassificationModel, MultiLabelClassificationArgs)

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-64-3bb1132b07c9> in <module>()
----> 1 from simpletransformers.classification import(MultiLabelClassificationModel, MultiLabelClassificationArgs)
      2 model = MultiLabelClassificationModel('xlnet', 'xlnet-large-cased', num_labels=20, args={'train_batch_size':2, 'gradient_accumulation_steps':8, 'learning_rate': 1e-5, 'num_train_epochs': 3, 'max_seq_length': 512})

6 frames
/usr/local/lib/python3.6/dist-packages/transformers/models/mt5/__init__.py in __getattr__(self, name)
     86         def __getattr__(self, name):
     87             if name == "MT5Tokenizer":
---> 88                 return MT5Tokenizer
     89             elif name == name == "MT5TokenizerFast":
     90                 return MT5TokenizerFast

NameError: name 'MT5Tokenizer' is not defined

**Comment by rjadr** [comment]
I ran into the same issue. Something must have been changed in the newer version of transformers. I fixed it for now by installing an older version:
`pip install transformers==3.5.1`

**Comment by ThilinaRajapakse** [comment]
Is this happening on the latest simple transformers version?

**Comment by NumberSpace** [comment]
Yes, this was the latest version, specifically in Colab

**Comment by ThilinaRajapakse** [comment]
I can't reproduce this. Make sure both simple transformers and transformers libraries are up to date.

**Comment by lenyabloko** [comment]
@rjadr I have the same error and tried older trasformers per your suggestion. I now get this error in Colab
...
ImportError: cannot import name 'SAVE_STATE_WARNING' from 'torch.optim.lr_scheduler' (/usr/local/lib/python3.7/dist-packages/torch/optim/lr_scheduler.py)
'''

**Comment by Broever101** [comment]
Same error. Tried importing pipeline lol.

**Comment by krmc-globality** [comment]
I had the same MT5Tokenizer issue using transformers 4.4.2, but uninstall/reinstall of both packages sorted it.

**Comment by filipmarkoski** [comment]
I still have this issue

Package versions:
```
simpletransformers  0.61.4
transformers        4.4.2
```

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-23-7a7ae47b0a23> in <module>
----> 1 from simpletransformers.classification import ClassificationModel, ClassificationArgs
      2 import pandas as pd
      3 import logging
      4 
      5 logging.basicConfig(level=logging.INFO)

~/scraping/.env/lib/python3.6/site-packages/simpletransformers/classification/__init__.py in <module>
----> 1 from simpletransformers.classification.classification_model import ClassificationModel
      2 from simpletransformers.classification.multi_label_classification_model import MultiLabelClassificationModel
      3 from simpletransformers.classification.multi_modal_classification_model import MultiModalClassificationModel
      4 from simpletransformers.config.model_args import (
      5     ClassificationArgs,

~/scraping/.env/lib/python3.6/site-packages/simpletransformers/classification/classification_model.py in <module>
     45 )
     46 from transformers.optimization import AdamW, Adafactor
---> 47 from transformers import (
     48     AlbertConfig,
     49     AlbertTokenizer,

/usr/lib/python3.6/importlib/_bootstrap.py in _handle_fromlist(module, fromlist, import_, recursive)

~/scraping/.env/lib/python3.6/site-packages/transformers/__init__.py in __getattr__(self, name)
   2308             if name == "__version__":
   2309                 return __version__
-> 2310             return super().__getattr__(name)
   2311 
   2312     sys.modules[__name__] = _LazyModule(__name__, _import_structure)

~/scraping/.env/lib/python3.6/site-packages/transformers/file_utils.py in __getattr__(self, name)
   1659         elif name in self._class_to_module.keys():
   1660             module = self._get_module(self._class_to_module[name])
-> 1661             value = getattr(module, name)
   1662         else:
   1663             raise AttributeError(f"module {self.__name__} has no attribute {name}")

~/scraping/.env/lib/python3.6/site-packages/transformers/file_utils.py in __getattr__(self, name)
   1658             value = self._get_module(name)
   1659         elif name in self._class_to_module.keys():
-> 1660             module = self._get_module(self._class_to_module[name])
   1661             value = getattr(module, name)
   1662         else:

~/scraping/.env/lib/python3.6/site-packages/transformers/models/auto/__init__.py in _get_module(self, module_name)
    158 
    159         def _get_module(self, module_name: str):
--> 160             return importlib.import_module("." + module_name, self.__name__)
    161 
    162     sys.modules[__name__] = _LazyModule(__name__, _import_structure)

/usr/lib/python3.6/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

~/scraping/.env/lib/python3.6/site-packages/transformers/models/auto/tokenization_auto.py in <module>
    118     from ..mbart.tokenization_mbart import MBartTokenizer
    119     from ..mbart.tokenization_mbart50 import MBart50Tokenizer
--> 120     from ..mt5 import MT5Tokenizer
    121     from ..pegasus.tokenization_pegasus import PegasusTokenizer
    122     from ..reformer.tokenization_reformer import ReformerTokenizer

/usr/lib/python3.6/importlib/_bootstrap.py in _handle_fromlist(module, fromlist, import_, recursive)

~/scraping/.env/lib/python3.6/site-packages/transformers/models/mt5/__init__.py in __getattr__(self, name)
     86         def __getattr__(self, name):
     87             if name == "MT5Tokenizer":
---> 88                 return MT5Tokenizer
     89             elif name == "MT5TokenizerFast":
     90                 return MT5TokenizerFast

NameError: name 'MT5Tokenizer' is not defined


```

**Comment by sahanpoornaka** [comment]
> @rjadr I have the same error and tried older trasformers per your suggestion. I now get this error in Colab
> 
> ```
> ImportError: cannot import name 'SAVE_STATE_WARNING' from 'torch.optim.lr_scheduler' (/usr/local/lib/python3.7/dist-packages/torch/optim/lr_scheduler.py)
> ```

Reinstalling torch Resolved the Issue for me

!pip install torch==1.4.0.
