### ISSUE TITLE
T5 for Seq2Seq tasks

### ISSUE THREAD

**Issue by yuchenlin** [ThilinaRajapakse/simpletransformers#964]
**Is your feature request related to a problem? Please describe.**

I would like to fine-tune T5 for seq2seq tasks in the Seq2Seq API (https://simpletransformers.ai/docs/seq2seq-minimal-start/), while it seems that the Seq2Seq models now only support BART, MBART, and etc. 

**Describe the solution you'd like**
I noticed that T5 is ready to use for other tasks in the framework but not for seq2seq tasks. Is it possible that we can use T5 just like BART? 

Thank you very much!

**Comment by ThilinaRajapakse** [comment]
T5 is essentially a sequence-to-sequence model. In fact, it's used for other tasks by framing the task as a sequence-to-sequence task.

This [article](https://towardsdatascience.com/how-to-train-an-mt5-model-for-translation-with-simple-transformers-30ba5fa66c5f?sk=31d91f9639bc5876ae465c340e1a026f) uses the mT5 model for machine translation (sequence-to-sequence). The approach would be identical for a T5 model.
