### ISSUE TITLE
cache_dir not working

### ISSUE THREAD

**Issue by miguelwon** [ThilinaRajapakse/simpletransformers#965]
**Describe the bug**
The parameter `cache_dir` is not working properly and the default cache_dir is used.

**To Reproduce**

Train with the particular defined local cache directory:

```
model = ClassificationModel(
    "bert","neuralmind/bert-base-portuguese-cased",args = {'cache_dir':"/home/mwon/data-mwon/paperChega/src_classificador/data/hugingface","local_files_only":True}
)
model.train_model(train_df)
```

It's using to use the default cache directory instead of the the custom one:

```
INFO:filelock:Lock 140580386371288 acquired on /home/mwon/.cache/huggingface/transformers/e716e2151985ba669e7197b64cdde2552acee146494d40ffaf0688a3f152e6ed.18a0b8b86f3ebd4c8a1d8d6199178feae9971ff5420f1d12f0ed8326ffdff716.lock
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 647/647 [00:00<00:00, 294kB/s]
INFO:filelock:Lock 140580386371288 released on /home/mwon/.cache/huggingface/transformers/e716e2151985ba669e7197b64cdde2552acee146494d40ffaf0688a3f152e6ed.18a0b8b86f3ebd4c8a1d8d6199178feae9971ff5420f1d12f0ed8326ffdff716.lock
INFO:filelock:Lock 140580386372912 acquired on /home/mwon/.cache/huggingface/transformers/1e42c907c340c902923496246dae63e33f64955c529720991b7ec5543a98e442.fa492fca6dcee85bef053cc60912a211feb1f7173129e4eb1a5164e817f2f5f2.lock
Downloading:   6%|███████▎                                                                                                                          | 24.6M/438M [00:02<00:36, 11.5MB/s]^CINFO:filelock:Lock 140580386372912 released on /home/mwon/.cache/huggingface/transformers/1e42c907c340c902923496246dae63e33f64955c529720991b7ec5543a98e442.fa492fca6dcee85bef053cc60912a211feb1f7173129e4eb1a5164e817f2f5f2.lock
```

**Desktop (please complete the following information):**

- `transformers` version: 4.2.1
- Platform: Linux-4.15.0-46-generic-x86_64-with-Ubuntu-16.04-xenial
- Python version: 3.6.7
- PyTorch version (GPU?): 1.6.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Additional context**

**Comment by ThilinaRajapakse** [comment]
The `cache_dir` parameter is for Simple Transformers only. Huggingface uses it's own cache to save models.

**Comment by philipperemy** [comment]
@ThilinaRajapakse 

```
INFO:simpletransformers.seq2seq.seq2seq_utils: Creating features from dataset file at cache_dir/
```

But after the creation of the features is completed, the cache_dir is still empty.

**Comment by ThilinaRajapakse** [comment]
Whether or not anything is written to the cache depends on the specific training arguments that are used. Also, some models don't use it.

**Comment by philipperemy** [comment]
Okay! Thanks for the reply.
