### ISSUE TITLE
Error when trying to extract word embeddings with RepresentationModel

### ISSUE THREAD

**Issue by Arousha** [ThilinaRajapakse/simpletransformers#967]
Hi

Thank you for this awesome work. I have been working with your library for my research and it really makes it much easier for conducting experiments. However, I am facing a bit of trouble when using **RepresentationModel** for extracting word embeddings for a downstream task. 

There is no problem when setting the combine-strategy to 'mean' but when I set the combine_strategy=None to extract the token embeddings I get the following error:

![image](https://user-images.githubusercontent.com/35211886/105968215-22e49c80-60ca-11eb-93f2-af13394a3b61.png)

I have varying text sizes in my data (from a minimum of 10 words to a maximum of 353 words) and I have set the max_seq_length=128. The problem stems when the text length is less than 128 I guess. Even though it is supposed to pad and truncate.    

Any ideas what is the problem? Is there something I am missing?

**Comment by ugm2** [comment]
Same error here 😔
