### ISSUE TITLE
AssertionError in convert_example_to_feature

### ISSUE THREAD

**Issue by igormis** [ThilinaRajapakse/simpletransformers#97]
I have 20 labels in a list, train and eval data as list
The train and eval frames are generates accordingly 
and I call:
`model = NERModel('bert', 'bert-base-cased', labels=labels,  args={'overwrite_output_dir': True, 'reprocess_input_data': True})`
But when I call:
`model.train_model(train_df)`
I have the following error:
```

AssertionError                            Traceback (most recent call last)

<ipython-input-40-44e3b58a00f8> in <module>()
----> 1 model.train_model(train_df)

3 frames

/usr/local/lib/python3.6/dist-packages/simpletransformers/ner/ner_utils.py in convert_example_to_feature(example_row)
    161     assert len(input_mask) == max_seq_length
    162     assert len(segment_ids) == max_seq_length
--> 163     assert len(label_ids) == max_seq_length
    164 
    165     return InputFeatures(
```

**Comment by ThilinaRajapakse** [comment]
Can you show `train_df.head()`?

**Comment by igormis** [comment]
Here is the output from train_df.head()

  | sentence_id | words | labels
-- | -- | -- | --
0 | this | B-TIME
0 | morning | I-TIME
0 | bitcoin | B-FIN_INSTR
0 | was | O
0 | down | B-PRICE_MOVEMENT


Here are my labels:
['I-PUBLICATION', 'B-AMOUNT_PRICE_TARGET', 'O', 'I-EVENT', 'B-GPE', 'I-HASHTAG', 'B-MEDIA_TYPE', 'I-TIME', 'I-ORGANIZATION', 'B-PUBLICATION', 'B-HASHTAG', 'I-EXCHANGE', 'I-SECTOR', 'B-QUANTITY', 'B-FIN_INSTR', 'I-AMOUNT_PRICE_TARGET', 'I-QUANTITY', 'B-MONEY', 'B-EVENT', 'B-TIME', 'I-FIN_INSTR', 'B-PRICE_MOVEMENT', 'B-ORGANIZATION', 'I-FINANCIAL_TOPIC', 'B-EXCHANGE', 'B-TICKER', 'I-PRODUCT', 'I-RATING_AGENCY', 'B-SECTOR', 'B-FINANCIAL_TOPIC', 'B-ANALYST', 'B-PERSON', 'I-PERCENT', 'I-PERSON', 'B-PRODUCT', 'I-ANALYST', 'I-PRICE_MOVEMENT', 'I-GPE', 'I-MONEY', 'I-TICKER', 'B-PERCENT', 'B-RATING_AGENCY']

**Comment by igormis** [comment]
or more rows are shown here:
	sentence_id	words	labels
0	0	this	B-TIME
1	0	morning	I-TIME
2	0	bitcoin	B-FIN_INSTR
3	0	was	O
4	0	down	B-PRICE_MOVEMENT
5	0	17	B-PERCENT
6	0	per	I-PERCENT
7	0	cent	I-PERCENT
8	0	ethereum	B-FIN_INSTR
9	0	was	O
10	0	down	B-PRICE_MOVEMENT
11	0	21	B-PERCENT
12	0	per	I-PERCENT
13	0	cent	I-PERCENT
14	0	litecoin	B-FIN_INSTR
15	0	had	O
16	0	dropped	B-PRICE_MOVEMENT
17	0	20	B-PERCENT
18	0	per	I-PERCENT
19	0	cent	I-PERCENT
20	0	and	O
21	0	ripple	B-FIN_INSTR
22	0	a	O
23	0	whopping	O
24	0	30	B-PERCENT
25	0	per	I-PERCENT
26	0	cent	I-PERCENT
27	0	.	O
28	1	apple	B-ORGANIZATION
29	1	is	O
30	1	upgraded	B-EVENT
31	1	by	O
32	1	goldman	B-RATING_AGENCY
33	1	sachs	I-RATING_AGENCY
34	2	forget	O
35	2	blockchain	B-SECTOR
36	2	:	O
37	2	invest	B-FINANCIAL_TOPIC
38	2	in	O
39	2	old-school	B-FINANCIAL_TOPIC

**Comment by igormis** [comment]
THe first column is the autogenerated Row ID, then the sentence_id, words and the labels.

**Comment by ThilinaRajapakse** [comment]
> Here is the output from train_df.head()
> 
>  	sentence_id	words	labels
> 0	this	B-TIME	
> 0	morning	I-TIME	
> 0	bitcoin	B-FIN_INSTR	
> 0	was	O	
> 0	down	B-PRICE_MOVEMENT	

Is it something weird with the formatting or are all columns shifted to the left? I'm seeing an empty `labels` column.

**Comment by igormis** [comment]
the sentence should be shifted to the left, wrong paste
![image](https://user-images.githubusercontent.com/6599037/71021346-6b2b4000-20fe-11ea-9958-485a42911cee.png)

**Comment by ThilinaRajapakse** [comment]
Can you give me a minimal script to reproduce this error?

**Comment by igormis** [comment]
Can I share colab with u?

**Comment by ThilinaRajapakse** [comment]
Yeah, that would be great.

**Comment by ThilinaRajapakse** [comment]
| sentence_id | words | labels
-- | -- | -- | --
080751| 4566 |  | O

This is the culprit. The empty word here is causing a mismatch between the length of the sentence and the length of the labels.

**Comment by igormis** [comment]
Tnx a lot :)

**Comment by ThilinaRajapakse** [comment]
No problem!

**Comment by igormis** [comment]
Still have the same error, even with the fix
`
train_df = train_df[train_df['words'] != '']`
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-37-44e3b58a00f8> in <module>()
----> 1 model.train_model(train_df)

3 frames
/usr/local/lib/python3.6/dist-packages/simpletransformers/ner/ner_utils.py in convert_example_to_feature(example_row)
    161     assert len(input_mask) == max_seq_length
    162     assert len(segment_ids) == max_seq_length
--> 163     assert len(label_ids) == max_seq_length
    164 
    165     return InputFeatures(

AssertionError:

**Comment by ThilinaRajapakse** [comment]
The colab notebook you shared is running perfectly for me with `train_df = train_df[train_df['words'] != '']`. Make sure this is called before calling train_model.

**Comment by igormis** [comment]
I tried before train_model, but I get the same error

**Comment by ThilinaRajapakse** [comment]
Looks like there are incompatible symbols in your data.

words | labels
-- | --
🤯 | O
 | O

I'm not sure if emojis are compatible.

**Comment by igormis** [comment]
Finally did it :)
Tnx

**Comment by ThilinaRajapakse** [comment]
Great! Did you find out why the blank cells weren't being filtered when checking for empty strings?

**Comment by igormis** [comment]
There was some special character inside, like /t or several tabs

**Comment by ThilinaRajapakse** [comment]
Aha!

**Comment by igormis** [comment]
If I want to train with DistilBERT
then the NerModel should be:
`model = NERModel('bert', 'distilbert', labels=labels)`
or with bert-multilingual
`model = NERModel('bert', 'bert-multilingual-cased', labels=labels)`

**Comment by ThilinaRajapakse** [comment]
`'bert', 'bert-base-multilingual-cased'` and `'distilbert', 'distilbert-base-uncased'`. 

You can check here.
https://github.com/ThilinaRajapakse/simpletransformers/blob/master/README.md#current-pretrained-models
