### ISSUE TITLE
HTTP error

### ISSUE THREAD

**Issue by mikaizhu** [ThilinaRajapakse/simpletransformers#975]
404 Client Error: Not Found for url: https://huggingface.co/robeerta-base/resolve/main/config.json

when i am using 

model_args = ClassificationArgs(num_train_epochs=1)

model = ClassificationModel('roberta', 'robeerta-base', args=model_args)

**Comment by ThilinaRajapakse** [comment]
You have a typo in the code. It should be `roberta-base`, not `robeerta-base`!

**Comment by Miki123-gif** [comment]
Then something was happend...
When I was training, the progress bar below did not change, but the program was running. What is going on?

--------
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
 0%|                                                                                       | 0/13809 [00:00<?, ?it/s]
--------

**Comment by Miki123-gif** [comment]
> You have a typo in the code. It should be `roberta-base`, not `robeerta-base`!
Then something was happend...
When I was training, the progress bar below did not change, but the program was running. What is going on?


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
0%|                                              | 0/13809[00:00<?, ?it/s]

**Comment by ZERO-SPACE-X** [comment]
@Miki123-gif hi，have you solved this question? I have meet the same question. I can`t download the file. 
Downloading:   6%|▌         | 52.2k/899k [01:20<12:54, 1.09kB/s]

**Comment by ThilinaRajapakse** [comment]
> > You have a typo in the code. It should be `roberta-base`, not `robeerta-base`!
> > Then something was happend...
> > When I was training, the progress bar below did not change, but the program was running. What is going on?
> 
> Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.weight', 'classifier.bias']
> You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
> 0%| | 0/13809[00:00<?, ?it/s]

That's not an error. It's expected.

**Comment by ZERO-SPACE-X** [comment]
@ThilinaRajapakse Thank you for your reply. I need to download this file when I am training in local, but I have been unable to download it.I found the location of this file, but did not find the corresponding download link.Could you please provide it? I will download it manually and put it in the corresponding folder. Thank you

**Comment by ThilinaRajapakse** [comment]
I'm not sure which file you are referring to, but, you should be able to find it [here](https://huggingface.co/models). That's where all the models and their files are hosted.

**Comment by ZERO-SPACE-X** [comment]
@ThilinaRajapakse  Thank you for your reply.
