### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by mikaizhu** [ThilinaRajapakse/simpletransformers#976]
When I was training, the progress bar below did not change, but the program was running. What is going on?

```
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
0%| | 0/13809[00:00<?, ?it/s]
```

**Comment by minegazioglu** [comment]
I have the same problem training the model. It is stuck on the same percentage for hours now

**Comment by ThilinaRajapakse** [comment]
This should be fixed in the latest version. Please let me know if the problem persists.

**Comment by azizcu** [comment]
![Screenshot from 2021-02-12 04-25-40](https://user-images.githubusercontent.com/63375421/107706392-6f46f380-6cea-11eb-8770-e04d0720aeae.png)

now i have found this error
TypeError: 'NoneType' object is not iterable
please solve it as early as possible. IMPORTANT!!!
Thank you for your co-operation.

**Comment by creatorrr** [comment]
@ThilinaRajapakse turning on `multiprocessing` options is causing a lot of such issues. Any thoughts on how to mitigate these?

For now, this has helped me:
```python
model_args = ClassificationArgs(
    use_multiprocessing=False,
    use_multiprocessing_for_evaluation=False,
)

os.environ["TOKENIZERS_PARALLELISM"] = "false"
```
