### ISSUE TITLE
Adding additional features to Binary Classification

### ISSUE THREAD

**Issue by pascca** [ThilinaRajapakse/simpletransformers#978]
Hello!

First of all thanks for simpletransformers, it works like a charm and helps to build stable prototypes fast. 

Now to my question: I'm training a simple Binary classification model utilizing BERT. I would like to add additional features to my classification Layer (e.g. 2 additional handcrafted numeric features). Is there an easy way to do this with your framework? If not, do you know how I could implement this?

A quick recap of the idea: Textual Input -> Bert Encoding + My Additional Features -> FFNN Layer -> Classification Output 

Thank you very much!

**Comment by ThilinaRajapakse** [comment]
You'll have to modify the library code itself to do that. Specifically, you'll need to implement a model class which can handle additional features, and you'll need to modify the dataloading logic to be able to handle the extra features as well.

It might be easier to do it directly with Huggingface Transformers.
