### ISSUE TITLE
What is the title of academic paper for this simple transformers?

### ISSUE THREAD

**Issue by moh-yani** [ThilinaRajapakse/simpletransformers#98]
Does this simple transformers have an academic paper published? If we refer your simple transformers, how to cite this?

**Comment by ThilinaRajapakse** [comment]
There is no academic paper published for this repo atm as this is based heavily on the [Transformers](https://github.com/huggingface/transformers) library. They do have a published paper that you can cite. In addition, you can cite Simple Transformers as a Github repo. An example bibtex would be something like this.

@misc{rajapakse2019simpletransformers,
  title={Simple Transformers},
  author={Rajapakse, T. C.},
  year={2019},
  howpublished={\url{https://github.com/ThilinaRajapakse/simpletransformers}},
}

**Comment by moh-yani** [comment]
Okay, thank you for the information.

Sel, 17 Des 2019 pukul 21.13 Thilina Rajapakse <notifications@github.com>
menulis:
