### ISSUE TITLE
RuntimeError: [enforce fail at CPUAllocator.cpp:65] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 93763584 bytes.

### ISSUE THREAD

**Issue by azizcu** [ThilinaRajapakse/simpletransformers#980]
RuntimeError                              Traceback (most recent call last)
<ipython-input-17-e0f766218a08> in <module>()
      5 # model_train('roberta','roberta-base',train_args2)
      6 # #third for roberta
----> 7 model_train('bert','bert-base-uncased',train_args1)

6 frames
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/sparse.py in __init__(self, num_embeddings, embedding_dim, padding_idx, max_norm, norm_type, scale_grad_by_freq, sparse, _weight)
    107         self.scale_grad_by_freq = scale_grad_by_freq
    108         if _weight is None:
--> 109             self.weight = Parameter(torch.Tensor(num_embeddings, embedding_dim))
    110             self.reset_parameters()
    111         else:

RuntimeError: [enforce fail at CPUAllocator.cpp:65] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 93763584 bytes. Error code 12 (Cannot allocate memory)

same code i use few days ago and worked perfectly but last couple of days i got this error( use gpu also set use_cuda=True)
can you explain please why i got the error?

**Comment by Akram1871** [comment]
I have faced the same problem also, but last week it was working fine.

**Comment by wassim-henia** [comment]
I'm facing the same problem

**Comment by mapmeld** [comment]
I think I contributed to this memory issue - we had a separate issue with labels being removed from the original features, so I added a line to create a copy of the feature:

https://github.com/ThilinaRajapakse/simpletransformers/commit/16fb3a14ea7d71f217d134652147725b430d9e20

Is there a better way to do this, or do we need to ```del``` features after it is used here?

**Comment by ThilinaRajapakse** [comment]
It doesn't seem to be related to the labels fix. I changed the logic so that features don't need to be copied every time, but this problem still persists. Also, it doesn't seem to be isolated to classification alone.

I'm not sure exactly what changed (could be Pytorch, Transformers, Tokenizers, or maybe even Simple Transformers) but the only reliable solution I found was to just turn off multiprocessing entirely. The tokenization is quite fast now, even without multiprocessing, so I don't think the speedup from multiprocessing is worth the hassle right now.

**Comment by azizcu** [comment]
yeah it worked but take more time than before like >8 minutes per epoch.

**Comment by ThilinaRajapakse** [comment]
Setting `use_cached_eval_features=True` might help with that. The training data is only tokenized once, so it shouldn't affect the training time of the epochs (it will take longer until the epoch starts, i.e. until the training data is tokenized). The slowdown is likely from the evaluation data being tokenized if you are using `evaluate_during_training`.

I'll look into implementing the multiprocessing without the instability. I have some ideas.

**Comment by ThilinaRajapakse** [comment]
I think I have resolved the issues with multiprocessing so I've turned it back on by default. Please let me know if the problems persist.

**Comment by azizcu** [comment]
![Screenshot from 2021-02-12 04-32-38](https://user-images.githubusercontent.com/63375421/107707191-b1bd0000-6ceb-11eb-9928-e902e5c33167.png)

Now i have found this error may be latest version problem .......

__TypeError: 'NoneType' object is not iterable__

please solve it as early as possible. IMPORTANT!!!
Thank you for your co-operation.

**Comment by ThilinaRajapakse** [comment]
How do I reproduce that error?

**Comment by azizcu** [comment]
train_args1={
    'reprocess_input_data': True,
    'overwrite_output_dir': True,
    'num_train_epochs': 10,
    'regression': True,
    "output_dir": "outputs_model/",
    "cache_dir": "cache/",
    "best_model_dir": "outputs_model/best_model/",
    "fp16": False,
    "max_seq_length": 128,
    "train_batch_size": 16,
    "eval_batch_size": 8,
    "gradient_accumulation_steps": 2,
    "learning_rate": 2.99e-5,
    "do_lower_case": True,
    "evaluate_during_training": True,
    "evaluate_during_training_steps": 90,
    "evaluate_during_training_verbose": True,
    "use_cached_eval_features": True,
    "save_eval_checkpoints": True,
    "no_cache": False,
    "save_model_every_epoch": True,
    "use_multiprocessing": True,
    "use_early_stopping": True,
    "early_stopping_patience": 3,
    "early_stopping_delta": 0.01,
    "early_stopping_metric": "eval_loss",
    "early_stopping_metric_minimize": True,
    "manual_seed": 1,
}

def model_train(model_name,model_type,arguments):
  # Create a ClassificationModel
  model = ClassificationModel(model_name, 
                              model_type,
                              num_labels=1, 
                              use_cuda=True, cuda_device=0, args=arguments)
  # Train the model
  model.train_model(train_df,eval_df=eval_df,)


from simpletransformers.classification import ClassificationModel
#First for Bert
model_train('bert','bert-base-uncased',train_args1)

To performe regression we we set num_labels=1 also train with a continuous label (regression score) 
# sentence pair dataset

**Comment by ThilinaRajapakse** [comment]
Got it. This should be fixed now in `0.60.8`.

**Comment by azizcu** [comment]
Thank you so much for your hard work . Now it is ok.
How can i cite this API in my paper?

**Comment by ThilinaRajapakse** [comment]
Awesome!

See [here](https://github.com/ThilinaRajapakse/simpletransformers/issues/98#issuecomment-566557659) for citation.

**Comment by krstp** [comment]
Either way, regardless of bug, lowering batch size should help with smaller available memory allocations.
