### ISSUE TITLE
T5 : Confidence/Prediction score for each generated sequences

### ISSUE THREAD

**Issue by Shivanandroy** [ThilinaRajapakse/simpletransformers#985]
I was wondering, is there any way, we can get the prediction or confidence score of generated sequences with T5.

Background: I'm using a T5 model in a production. Sometimes, (although very less) the generated sequences are not upto our standard. I was thinking, if each of generated sequences comes with a probability or confidence score, i can filter out suggestions (model prediction) or even control whether to consider any of the predictions/sequences generated by the model at all based on some threshold. 
Something like this
```python
model.predict(["convert : One"])
# output: ["1"] : score: 0.99
```

**Comment by ThilinaRajapakse** [comment]
There is no straightforward confidence score for T5 models like you would have with say a BERT classifier. This is because the generated sequence also depends on the decoding algorithm used and the hyperparameters chosen for the decoding algorithm.

**Comment by Shivanandroy** [comment]
So, playing with decoding parameters, says `top_p`, `top_k` and others is the only option. Is that correct?

**Comment by ThilinaRajapakse** [comment]
There's also `num_beams` if you are using beam search as the decoding algorithm.

**Comment by Shivanandroy** [comment]
Thank you! Closing the issue.
