### ISSUE TITLE
lazy_loading on .csv files (dataframes)

### ISSUE THREAD

**Issue by s-mostafa-a** [ThilinaRajapakse/simpletransformers#987]
Hi,
I think this can be common that people have preprocessed their data and want to train a model (in my case NER model).
I have preprocessed and tokenized my data, and the result is in a big .csv file that can be a big DatFrame. But, the problem is that the file is too big to be loaded in RAM. So, I need lazy loading on the .csv file during my train.
This `simpletransformers.ner.ner_utils.LazyNERDataset` just works on .txt files to be tokenized.

**Comment by ThilinaRajapakse** [comment]
Simple Transformers doesn't support pre-tokenized inputs atm. I'm afraid I don't have any immediate plans to add support for it.

**Comment by shyamalaspure** [comment]
@ThilinaRajapakse  I am using lazy_loading for text in NER giving following error:
```
TypeError: convert_example_to_feature() missing 14 required positional arguments: 'label_map', 'max_seq_length', 'tokenizer', 'cls_token_at_end', 'cls_token', 'cls_token_segment_id', 'sep_token', 'sep_token_extra', 'pad_on_left', 'pad_token', 'pad_token_segment_id', 'pad_token_label_id', 'sequence_a_segment_id', and 'mask_padding_with_zero'
```
