### ISSUE TITLE
Multi-lingual model support.

### ISSUE THREAD

**Issue by ssarode2597** [ThilinaRajapakse/simpletransformers#989]
Is there any way I can use simpletransformers for classifying multi-lingual texts?

**Comment by ThilinaRajapakse** [comment]
There are many different multi-lingual models supported in Simple Transformers (e.g. `xlm`, `xlm-roberta`, `mT5`)

**Comment by AlexandreDuperre** [comment]
Hi @ThilinaRajapakse!
Great job with the SimpleTransformers library! I see you currently support xlm, xlm-roberta and mT5 for classifying multi-lingual texts. Are you planning on adding xlm and mT5 support for NER in a near future? 

Thanks!
