### ISSUE TITLE
Kernal Restarting - The kernel appears to have died. It will restart automatically.

### ISSUE THREAD

**Issue by hammad26** [ThilinaRajapakse/simpletransformers#99]
I am running [Minimal Start for Binary Classification](https://github.com/ThilinaRajapakse/simpletransformers#minimal-start-for-binary-classification) code. At training model step I am getting following issue:

![image](https://user-images.githubusercontent.com/12643784/71002664-97948b80-2101-11ea-94fd-1836b83f23f1.png)

Can you guide in this regard?

Thanks

**Comment by ThilinaRajapakse** [comment]
Impossible to say based only on this. What are your system specs?

**Comment by hammad26** [comment]
Specs are as:
Python: 3.6.5
Operating System: CentOS Linux 7 (Core)
2 GPUs

**Comment by akupka** [comment]
Hello,

I had the same problem, in my case the cause seems to be the apex library. My solution is to change the  'fp16_opt_level' arg from 01 to 03

Best regards
Andree

**Comment by hammad26** [comment]
@akupka Thanks a lot. Now it is working perfectly fine.
