### ISSUE TITLE
Support for FB Wav2Vec2 Transformers

### ISSUE THREAD

**Issue by abedkhooli** [ThilinaRajapakse/simpletransformers#991]
I know this is pretty new on HF, but just asking if there is a plan to integrate wav2vec2 transformers - ex. https://huggingface.co/facebook/wav2vec2-large-960h for either fine-tuning or training from scratch.

**Comment by ThilinaRajapakse** [comment]
Yeah! I'm pretty curious to try this out. Hopefully, I'll have time to add this soon.
