### ISSUE TITLE
Additional prediction inputs (NERmodel)

### ISSUE THREAD

**Issue by jackragless** [ThilinaRajapakse/simpletransformers#992]
I've sent POS tags to the NERmodel during training. Is there any way to pass POS tags to the final model when performing predictions (rather than just providing the sentence)?

**Comment by ThilinaRajapakse** [comment]
I don't think so. The NERModel is not designed to take additional inputs. How did you pass POS tags during training? 🤔

**Comment by jackragless** [comment]
I added a POS tag column to my input dataframe and it didn't throw any errors. Do any other pipelines allow for additional inputs?

**Comment by ThilinaRajapakse** [comment]
Extra columns in your input won't throw any errors but they won't be used either (hence why it won't throw any errors). Simple Transformers doesn't currently support additional inputs.
