### ISSUE TITLE
How to cite the repo in a conference paper

### ISSUE THREAD

**Issue by Liu-Hy** [ThilinaRajapakse/simpletransformers#995]
This preject is excellent. I am using this repo and got some experimental result that I hope to present in an ACL workshop paper. Is there any instructions on how to cite this work? e.g. what to include in the citation, or the BibTex code if possible.

**Comment by ThilinaRajapakse** [comment]
You can use [this](https://github.com/ThilinaRajapakse/simpletransformers/issues/98#issuecomment-566557659). And good luck with your paper!

**Comment by Liu-Hy** [comment]
Thank you!
