### ISSUE TITLE
Question: can models be saved as ckpt

### ISSUE THREAD

**Issue by sersoage** [ThilinaRajapakse/simpletransformers#996]
Question for the community i trained a model and have the best_model folder with all the files, can i convert the model to ckpt for use with torch/transformers?
Thanks

**Comment by ThilinaRajapakse** [comment]
What do you mean by a ckpt file? The `pytorch_model.bin` file is just the state_dict saved with `torch.save()`. Internally, it uses the transformers `save_pretrained()` method, which in turn uses the PyTorch `torch.save()` method. You can load the `pytorch_model.bin` file directly to a PyTorch model without any conversion (provided you set up the class correctly). You can also load the best_model as a Huggingface model by giving the path to the directory to the `from_pretrained()` method. Essentially, an output model directory from Simple Transformers includes:
- The PyTorch model file
- Huggingface config files
- Simple Transformers config files

This means that you can use it with any of the 3.

**Comment by sersoage** [comment]
Sorry for the trouble I know this might be a silly question, but there is an API that load a ckpt trained using pytorch lightning, and I retrained the model using simpletransformers (great library BTW) and now would like to deploy that model with as few changes to the API as possible. And lightning uses the ckpt format
