### ISSUE TITLE
XLNet for Named Entity Recognition

### ISSUE THREAD

**Issue by codingnoobneedshelp** [ThilinaRajapakse/simpletransformers#998]
In some parts of the documentation, it is mentioned that XLNet is supported for NER. But under "Supported Model Types" for NER, it is not listed. So is XLNet currently not supported by simpletransformers for NER?

Thanks

**Comment by ThilinaRajapakse** [comment]
It wasn't available before but it looks like it can be added easily. So, I'll probably include it in the next update (which should be within the hour).

**Comment by codingnoobneedshelp** [comment]
Thank you for the great support.
