### ISSUE TITLE
Question - Text Representation from ClassificationModel

### ISSUE THREAD

**Issue by thiagosantos1** [ThilinaRajapakse/simpletransformers#999]
I am aware that we can use the  [RepresentationModel()](https://simpletransformers.ai/docs/text-rep-model/ ) to create Text Representation (Embeddings).

Is there a way to create such Representation using my fine-tuned model? 
Let's say I have my ClassificationModel fine-tuned and saved. Can I load it using the RepresentationModel() ?
Or, using the ClassificationModel() itself, can I already directly get the sentence representation(For each test data) ?

**Comment by letsGoBharat** [comment]
I have a similar query. Is it possible to extract text embedding produced by a 'MultiLabelClassificationModel' model from the training data? As you said, RepresntationModel() does that, but can we do it for other model types?
